apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:oOiLKpHjT6oGtbZMYIhvAkEqfK5MA5sjbkmj+HeD8slKB/8tC+5xXKPTWptndMM2k5rirx3Qr3wFrYqozf1kmd377M8tLeVtfIi5Zq2laqlK4IO7EIwHwrSp0U/7FnUze6h4z2xHwvGzuAzqPkEbAiZ/WSen0dxs1QI3FVoxF25WUZCZjKNaNsSJk4qvz8s78Z82psbYbcqrKGdm+caT+CSmqN9Zb0EmucFpK/cTuhIoVqfSDCpAv8XK5ZqXieynvITEMEozomCk8Mu70Z11Hw+SsJXkqfnrBwEjyrQ4tyRQm2hf8g3CPkNk0YeL9GI19JdzD2BxhMTaSFv9/77JfEc5nmJFOTqOyvfGOKR9KWaPWZ+6zlvwTMkwUXWLpKegzeiKfMzu0xh9sbqCmvnnSIo3yDfx1R35CTL81vZL3+mkmoneVPaWt3jGbcvvVgE3/kOS0opSa8/yysStuwms4xZyeF37iBLbhJ9mPcPPUQfjCgaNwX3AwlknkJhrj9541VMgWfQ2oeijpPj+Z2go7Q7GbJu8qfK+pY1VZNNrRm4C8s+/aQGzSNHhL4t61+AT6jWFJgBT+46G3L4WuAUvhIpBTyqlATesmLtnrsve5DZvvU5hAG1fNUC3q4oghwn4uBKZ+3gqpeVa0xaym/cWpuRh11p25HL7g0zGtNg5E30fClk2L34hYdPZ+N/R70H8DpRI+8BYRaC4Y7ZWeR9uIqh7BG30hubSV0x8TnAhSuSKPjhtR/MoYdOPDFKBp9WT8pE8v9qS8aRB2780r5v1xux1xqBPxWjuU19JIlYeuk6i+ljXEKu/zKuYRxocQWVxCDNOtMUrWiBqSRH3V9bATPg4mY/jfS4q/LkqwwB9Y+kXItLYaeEHjpMGDKYx6BZn03gpXxbUl4erfNJ2caflSXbohwn+pxTTuW8YmDDbMCeKAUOBrLsHVf9ma/LsftWQLVSEc//icCRnHHR+9yqdm1n/+mAKkggS7RfWy9EHQA7o63IEQM6EXdNSDe32Uig1y44VPGA3whSO41t5pHpB/d5VMiQU4RL7RcoL8ugZmM6LJztPdH2xTkq9DxqIIQhB7bXOPwdHRCz0vTQVPuDCTMJEPZg40eBRwHAQgjde3ICkQsblvvZGUuh2e47zdzMMsDcp3h3ub7Rx/eSoKdftikvkJZZgREt6n5+9KJNmSB66q8UBS+gRN/2w4eEhks/pkVX9LlX0yKsWNfDEcU0/bl8xRP+KIj9XyTRWH7gRiBr8nTpTnr/Bkz89il5NCVZK0pIJE3q4XlABzHhA23HLTm+UtCjoU5HkJGQ8DBP03yD3EtxeSabreVSy4N8T8D/JI5pc365Hf9I1U59vOYHTthYMSOlty6kDRKiMxCEp+5bjX+zYIqQK3edWkVqAQQ==,iv:4PGr6JJMjSzdnd/6oB0kY7lJA67svDjMrZaDWOf1epc=,tag:dhCmhwvsg6frCdRZlxnLqA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSjZZL1FvcmJISFRyWXJN
            ODBtaEpjUjJhVS9mZlg5K3dKK3A1QUk4b0NZCjlYOGlTWFpub0RPL0xZeDFkWkVt
            VmFteDdoWG5aOHVxOWZzajMyYklCMXcKLS0tIDZiUGlmNGRGdlp0UXE4RVNNb0lW
            bkd6VzRxZXZlVUN2cmJOa3Riei9NVFUKTMN6Bcq+s+wKk3J3O+34KUsRx6O+h7/s
            mP1JTkm+cd+mkZK0r5wTc0aeTrOY1TmHg2QHiFQWyHp0r1h29NRZNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRHJvazl4aXVjbytRTU0r
            K0ZWTUd4dGg3Q0ZXZDQrUmNzemJ5ajNuYmtjClJxZ04rYXo4bDVyTUlLS1FhbGxj
            YVhydWYxVnlQUFZqMFBFVHkvY2RmQXMKLS0tIGhBOTQ0U2VUT2JGY2UvekxLZmFF
            bmIyQXlJTEdsUHJrcGZaT1IwTDdqM00KF34P9sFhdGkJacvVCJYffw/3CBXMMsp7
            RGIukuJNRuUkN+b7ZcUK/tiWprPdFB1EnZJVhbs07PVRkzMN1tUzEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL0N2N0NzL042NnozTmNx
            NHRUWmtITHhNc00wT3grMk1hM1hZc21EL0JRCkNKSTlzTnNGM0F1eGY5MEw1MGQw
            aFhzQWl4TEozQ2lDL0dLNjloNlYvdUkKLS0tIE16dFd1UXF5UFZvcnJObUpkOXBD
            TCtYYmVYVVIzaEpKejdWbHh2TmsxajgKyO+Vatgx7vAIjvtdyMfa2UN+eaF0xfDM
            Q5tGftOAOCaeyIZXusitTI6f/0Ld4Idv3PL4qc37KFJ5ed5lTljreA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:57Z"
    mac: ENC[AES256_GCM,data:8DRLUD1M8NvCzGzdBATh3gmGf2urbADVGO791eFCQeEReLAWVZWdCTuKiCJG2sL+Zp7L+VEiwm5T/UQtucVSRxhz2MwWI2rbWGd3n2vCMOEHZSwlnsgdsjRyqceQrqfAQqEsb3YjE5E6kNi1KHF9q5JJd/HOG4KjqlMi/1Xd9kI=,iv:woAA2OEZ1Z2kvZ3zwW7O6ayywSE8+C7l2aZ1rLvfZGI=,tag:4pQviGCmu8SexjPwzis5IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:Nx+wPH/3OcPhRHmE/lJzOCqySKY=,iv:tF46/6KCEbPCk7ZezkySHpoDtnpdcHnYAXiE0Cq2Tb8=,tag:jCLZjnngTQ1P4pb7aWQbPA==,type:str]
    userKey: ENC[AES256_GCM,data:x6Gkxuzv/93q4evX/H2ovuDr02NH+6vNL2HQ5G30uAm2Gaax2ID9t8URvBx/f8xwycS3H3Szhbc=,iv:fPu9NhI6bwIDA8ZIFU25vUqfw/c9606X48bSRCI8Ir0=,tag:cYixN/2w7B/4iqrfConRRw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSjZZL1FvcmJISFRyWXJN
            ODBtaEpjUjJhVS9mZlg5K3dKK3A1QUk4b0NZCjlYOGlTWFpub0RPL0xZeDFkWkVt
            VmFteDdoWG5aOHVxOWZzajMyYklCMXcKLS0tIDZiUGlmNGRGdlp0UXE4RVNNb0lW
            bkd6VzRxZXZlVUN2cmJOa3Riei9NVFUKTMN6Bcq+s+wKk3J3O+34KUsRx6O+h7/s
            mP1JTkm+cd+mkZK0r5wTc0aeTrOY1TmHg2QHiFQWyHp0r1h29NRZNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRHJvazl4aXVjbytRTU0r
            K0ZWTUd4dGg3Q0ZXZDQrUmNzemJ5ajNuYmtjClJxZ04rYXo4bDVyTUlLS1FhbGxj
            YVhydWYxVnlQUFZqMFBFVHkvY2RmQXMKLS0tIGhBOTQ0U2VUT2JGY2UvekxLZmFF
            bmIyQXlJTEdsUHJrcGZaT1IwTDdqM00KF34P9sFhdGkJacvVCJYffw/3CBXMMsp7
            RGIukuJNRuUkN+b7ZcUK/tiWprPdFB1EnZJVhbs07PVRkzMN1tUzEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL0N2N0NzL042NnozTmNx
            NHRUWmtITHhNc00wT3grMk1hM1hZc21EL0JRCkNKSTlzTnNGM0F1eGY5MEw1MGQw
            aFhzQWl4TEozQ2lDL0dLNjloNlYvdUkKLS0tIE16dFd1UXF5UFZvcnJObUpkOXBD
            TCtYYmVYVVIzaEpKejdWbHh2TmsxajgKyO+Vatgx7vAIjvtdyMfa2UN+eaF0xfDM
            Q5tGftOAOCaeyIZXusitTI6f/0Ld4Idv3PL4qc37KFJ5ed5lTljreA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:57Z"
    mac: ENC[AES256_GCM,data:8DRLUD1M8NvCzGzdBATh3gmGf2urbADVGO791eFCQeEReLAWVZWdCTuKiCJG2sL+Zp7L+VEiwm5T/UQtucVSRxhz2MwWI2rbWGd3n2vCMOEHZSwlnsgdsjRyqceQrqfAQqEsb3YjE5E6kNi1KHF9q5JJd/HOG4KjqlMi/1Xd9kI=,iv:woAA2OEZ1Z2kvZ3zwW7O6ayywSE8+C7l2aZ1rLvfZGI=,tag:4pQviGCmu8SexjPwzis5IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
