apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:MeEm0f48BfbOHANKl3h8S1V5Zzlaq/GS1E59ywR8DLjRoqWokNePQew4Zyln37KLIpdEAyXfWXKphOfcv7kWPXMh783VmQ4rEEVXmjtY8mCwitqC+Sg3Aj+FVcDFao4rTur88urHbBNFaXc7u9VmscpYnNxBo19nyi9a251jT6Prgva6RgR5xfeN1iJeDk3F1IcYQG+Wzeh37asXFSFuSoIPZ0H9PH2eDYQ8487/0HHFBnbE5r+/ROazFB6QZFgDh5jWRB8vBq2aUwmqBb8qiE2lDiRex/ZkHqA2nIykZ/IH/HPSl2xyMhgrnIF9t6+rYEXxau47rpGb/mcRo/44oJyAYxEdvyLD1HTzZO0Khm32Z6m/0PYpVJ6qk3fTWgMSMlqwayUoledK92siagxJg5HKCgoTQ+xNKRQ5loFv3zp4BU1MNF0cMSCAnYRHu/siXXzrqjg1ctgbB/WsVWMqRqEseABbSs4nKN5wAPcqPVhLPCKfNtf0T1cRvABIXvSichGe+silG7EyKZakdbmtQWjFXOp8X+9jC93DGjIrD6GS5Hp4Z/pkpWTZDFgC7aGRHCw3xBpzTYnIJFeWSOlI0siaQX9IhCoOcwcUA7yelVBWA1ggEXv8PwrbS1Xq0ngrEeGfrob3aWAQKSR/C1guc9FGoeKntrHf1tpU0Jm+XSzGGwdYVgZhscTfrH9rGEE8Nchjc2x8odY7EVMUTtQVz8TYOve2+mBdaG3b9UWdOlt2Y5GQMhNkboLYvk7RYMM5TNc4nP75XNeazoYtR2J1uDPIS7aValDJI1mrXvoWzcsa7P0DSpE2oeqEl/FuMLnXq9cFdrnNWgy+S3Mz58JX7YhIOtQir4ZX0J3tjEyV4oZsG/KdJiKRujoIvfDcywr4XzuyRrHEuQqVTkVQUqAViejnanQE4LIDp0K3IfQEEFRmxSuBwCJBryP9lV0eCLyjJeoSnxDF2jlJPnWhaeayViD1pOC8eKuyVEtO9Q2aaShuPIiVRgvrvC3bh4pzHpbhxPMHOyzUQbnxWy+JsLggK/mh0oaJx2klRPraTLOUeVRJ0joETnGvBYFG9CSJ8eKt4EtqFC2aDslbxKIgXxSaenzbXe4HCzZ6fdkGTarcYZEp0GgydY/7Y+KXdyRtn1wvNuWdjL8yV9GmLlQwiVu49NYgbxHSWghhF0SEzh+BQdzANsrYN4qaVhpe45czZ5cyPGyGJJ/Z+1uM5rO3vbbG0TA42V9ec35Hwo1PZW6eI5Jpd/pa5mqRYn+GXjipQ9mi77G9mcmpOMPgo84QXbgGZ1LNF6jec45VBeW5S1ZOmjzNn/jQ4xMb6A5iomPkoqQwU++cKUl9VEFDX+sA9o1YWBeNBBAPE0qpO8Omz6c275Wah6zIL2BO/g87ZB/L9w==,iv:XRqje/uHaVKC5qvBv1XMmKDb4V4U3g25lng86SDy0kI=,tag:1loJHJF8wo5f3Mlqy3dCRw==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVStQNHQ3TXBuMFJNZFBS
            WU1PSExLVGhpRlFwaGU4MGUwNnJKU29tbVNRCmRnODZrOCtpUnRMOXI3aHFqblJG
            VU10d3pDMTZyOTdqWGswak50dWY4Z2cKLS0tIHlkWUJkeW5pWE03K2lCKytEcmJv
            SjlUNjk5d0EyM2tURk9hanNjOWFpcUkKiOKrC9YyRMp265nGPGlOoq9BUMSVJxz1
            DKxECyxTKDcIxo9tPsctYtVNVhuz0skPwJ5NUdqQ3NdG7FzwEOOkuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcEU3Q0cxTmhiZ1JyUHN0
            T1liYTdOREdmaFByYnRFOHNydVBnYnQ4dWhZClNsUlJZNGI3U2JWUGtvMGZiT3h5
            TWgvQUlvTjZFcDVXMW1VaTV3ZjdZdmsKLS0tIGNiRzNSRDVxVzVldVlxeDBXZkts
            Z3FWeGI3V3J0Y1Y2V1c3Mk42WEU1Nm8KggUERxVGgSeg1jYmKwOIMocvLRWzlKVc
            FKIA8yER9WWm3Y2OlQRfxIFrcBZpE2pQUkQpmKqBGkfddQpVmfQC/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbU5abENzeDN2eExWbFU0
            S1dJQ1pqcHN2ejJhU0RhMXN3V2NYTWpUTWhBCjVaUDc3NFZQNDBEQWtvc0ppNzMy
            ZzM5YnpwZGp0aFN0V3lCblIxWmF0bE0KLS0tIFhYVXkxa0YvVXZnRThXTHJQNWRm
            ZmRJaDZBZU9QUUZNREQ3a1dFQjhFQVEKRYdnt0RJ/4h2GaFGEixz+Y7p/F3WctF+
            2ooAgee7lZ0Mii1aB88FhMlkFt/HbvifEsYvhgt3nsL9dptNR4Zlcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:13:12Z"
    mac: ENC[AES256_GCM,data:nXb2VZ68kADUPp020AlgUA/qmLX4remupIGdIKDb53lLAzPOQvyroNbm7T/5ME+MJQ3lqyGAYOfVvER7B/i9/STmf2mA2C3MWEqFmr7RAvYKngze7ij3OPgM30bF07ixvJCeBkYrAgzrnWMEMUMJAqw048JjcgMtoU7Ezs+eg+k=,iv:9nDgpOoVPGavOPoygSxbUcKtlm3KXNmqM62G5jYcs/w=,tag:B/FslMa40sH+zo2WvMcUww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:mdxY2DwWxr78R9X/25yqBo3A6QQ=,iv:M54aLFh7uve0KUhQ9M+1IsT42zJGAp53UOuO0B6K5/o=,tag:fuhhA46ynZiAmqUmg5S2pw==,type:str]
    userKey: ENC[AES256_GCM,data:SEPAGR5fVfESG+xjJ4OwuvkR2BaCKwF7JA2Ms4yacJsEMKeggSaMRZXx+MYBaXCG1w71M+1lfwk=,iv:lD6t0dgEs12ACdWuEOxdj8g7koyGqO8FkpRlI6aRgz8=,tag:3E2BhBgJ2m3J/yy1rSZvlA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVStQNHQ3TXBuMFJNZFBS
            WU1PSExLVGhpRlFwaGU4MGUwNnJKU29tbVNRCmRnODZrOCtpUnRMOXI3aHFqblJG
            VU10d3pDMTZyOTdqWGswak50dWY4Z2cKLS0tIHlkWUJkeW5pWE03K2lCKytEcmJv
            SjlUNjk5d0EyM2tURk9hanNjOWFpcUkKiOKrC9YyRMp265nGPGlOoq9BUMSVJxz1
            DKxECyxTKDcIxo9tPsctYtVNVhuz0skPwJ5NUdqQ3NdG7FzwEOOkuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcEU3Q0cxTmhiZ1JyUHN0
            T1liYTdOREdmaFByYnRFOHNydVBnYnQ4dWhZClNsUlJZNGI3U2JWUGtvMGZiT3h5
            TWgvQUlvTjZFcDVXMW1VaTV3ZjdZdmsKLS0tIGNiRzNSRDVxVzVldVlxeDBXZkts
            Z3FWeGI3V3J0Y1Y2V1c3Mk42WEU1Nm8KggUERxVGgSeg1jYmKwOIMocvLRWzlKVc
            FKIA8yER9WWm3Y2OlQRfxIFrcBZpE2pQUkQpmKqBGkfddQpVmfQC/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlbU5abENzeDN2eExWbFU0
            S1dJQ1pqcHN2ejJhU0RhMXN3V2NYTWpUTWhBCjVaUDc3NFZQNDBEQWtvc0ppNzMy
            ZzM5YnpwZGp0aFN0V3lCblIxWmF0bE0KLS0tIFhYVXkxa0YvVXZnRThXTHJQNWRm
            ZmRJaDZBZU9QUUZNREQ3a1dFQjhFQVEKRYdnt0RJ/4h2GaFGEixz+Y7p/F3WctF+
            2ooAgee7lZ0Mii1aB88FhMlkFt/HbvifEsYvhgt3nsL9dptNR4Zlcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:13:12Z"
    mac: ENC[AES256_GCM,data:nXb2VZ68kADUPp020AlgUA/qmLX4remupIGdIKDb53lLAzPOQvyroNbm7T/5ME+MJQ3lqyGAYOfVvER7B/i9/STmf2mA2C3MWEqFmr7RAvYKngze7ij3OPgM30bF07ixvJCeBkYrAgzrnWMEMUMJAqw048JjcgMtoU7Ezs+eg+k=,iv:9nDgpOoVPGavOPoygSxbUcKtlm3KXNmqM62G5jYcs/w=,tag:B/FslMa40sH+zo2WvMcUww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
