apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:P8tYcPlciBIa16LQuDbl5FPWtzmtV91bdpMRziMOl68cE0uWHO730D+nU8mR4u0sylZ4d00zAbesW2EPGJZh5TYyJ7lFJPuj0OlYJ36QUAT218UnXDKfNR+Wbf+OBOyEiqhBHX4RGndFmR7nGcNwNHtTd+ZapCn6PkrXESnAlty8Tus9VMO8SM0GFVM/Df+uplI28OSdIpJSDpnIlNLDhlRUfqquL3Zfrw9Ckvq31r1LDmGNCIcb9N7WidNNyUbRjnJerbGCTuUHGG/+i3NAwOo2nZdDTmDz+4Whj1vCl45vdTo+6kOJpdUdZjYcMEg+VAtt8rzIXOLuYU2d3zplDOBCswCJdf3kGKU1SwfryuouhPda4EKz98urmFyjnfdhNvHK74Yhoue1PojoHF8dJ0O+AO6eDnBQAkZOpU1TzSQXK2z2XYoQ5TMKPTbuG19U70fkFm7x9Gfcl+P/GKoPWU6nKoBoZDQ45UpXl1xKHsmuqBqZTw0S0fx7f9rucBLYe0UF/O0Iid07uQ8ofQNwUyo8Z4SBWrPs0mTZ5Nj13XQHcB4/OMMMnZUgguSdTOCpn/FpcVfG/bBSuUotUZUGq96+Slusc2DlgmaibWY5b/f6BEUMsiO2drC/HcoEhn8CKsSqlXMjcqT+eZ6WNzVN0FTSofPwwOgZtUZy+LiuRDWhU3Wrh49UJi+WBdiKzwC9S/G1+B/HaKVTrxJj9wFjmyuaKovgGlgjZEs6FKsNF4mBPhW7FZJNP7WXRF+HFzATFYxOdIL5GuPCPYvSKSInCfCw9oscwEqL6/C+wm13w8px/m5HIg2CSN5JNWUuQItz+leOgbAdzMFTcofvOoOItmU5wYP8Ey1V2zgtncg5TlRZORqyHN/ysdynZi9DQ/4Qhs2xeRM0ZoEzLojKF5aJsZqZ5htC2G8Ew81cK+BAygK7AsvKotDanzefsXvFgZzBmyfpZFG8+6uihG9CE7bF3ma9cR768BM6jp7nMbJPepXsDrUkUeycI1M58ikxYcFC9dR2rCdHS7ObDFK7swdPQpbkSDI9AhDv9pqRSP9Vz/7qxq6ZwOXLuJK9a4Rudc3HDEtNh47PdMyYu8x7sSfDWEachkTS9MWikxuSStrUZNxxt19KZmNNaLJoVNDyNnu1iL4rwJ12dbp1jlvfWM4ptF/Pi6AIG84bznvvJbCCIF981CWnrYRHG3FyKYaURmwMi/dgCBAI+btpgKDHgHzP+YB1zYxYR+/EBcVXKrpOdl+sBp7yopWKaUJ+RPrzXg68q3BKLGv3ZKJzNjX/RhOoSg1TC1De6NBOx8aI2THW2Np/1ELA0/95hsQiJ/yWXPMl3kObQeSH30sY5knbEAOl6fy4jjD0j+i6OBVnv9B/Gif+TRJ9P/TcOklBTDJLkA==,iv:NFx6PZ+/qKbLdNS+Iqxp6JcSvyIgt9aGtaRMZkudhzE=,tag:Ku6dfvt3Jl07uM7WGykKLA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-smb-export-config
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVkZTOHJTUDdTTlc1aTdS
            Ti92YUFGZXRoUThPQWFZQ1pHRE9uZVdCZ1ZRCmFUc2YrejlIc1dBcjIyN0xNb1p5
            UXNhYjJyNWtFdDVLd0FXV05SQlZwRVUKLS0tIHRqTGJZYmt5YU5GWnNNaVR5MzJI
            MTkyR2U1VG52VDcxWUxxaThXWjNic28Kgt5aZVVteZMD+7EOxMIlYaHrhybCrQ9b
            NZBWFAEWwS8OwWV4LmKf/PqB6UOblYcdiCX3+am1Hd65VgwrCqrhTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MWVLNUE5alpSNE1LSkJ2
            TEtCek4yUDBoZHU2Y3Nwb0dJSjJPS2tNM0NrCngrcENVYllOWVEzY2RvNnZHWER2
            djk3c3lmT3hFejZSYzQySmFxaWVVZk0KLS0tIHBINi9wblRaTlJ4Tk5IbGE4RnpD
            SmRINXZXblY3VExOaTM0K1ZEMlg0TjQK2JQYjRor3+909krUWuU5Qyy1w+VV54u5
            G2/096zVQg6Fe2nLwEAXszu+OSzUeG346LCuNDllR41UtaCvqiOb0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOEhqOFE5SWYwMlhUclJU
            WkNVQW03NE90R3FvbjJ0ODViSEY1ZGhmb0RZCk1mdkFZaldpbTdabjA3VHRXM3lO
            Um5aNGxZTERWUlJOZ0lMWkhxaGV2VU0KLS0tIDJLb0p5U3JYekxWdTltWkNsRDly
            NTRJcnAwT2d5TFFkRzczdWV3R1NScW8KsEtT7Rd732TrpC9fmTq+MT/I2TtNjRi2
            ugikM8bhxjJ+iHzlO3mN/BfMNctkbIyrr/G73CT9JxhjddiZgIk8GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:25:01Z"
    mac: ENC[AES256_GCM,data:KOSkhgNEPGSDbFVnJzWdGsG70eFZmEDvNYadpzKOpMyH3DCvL4+tjenT8O/0uc5Io/ZMYJ9N574sRO6rbZvPHkneMs8ZyKN0SQu/meYA8E3llHajn3HRtjtMLLW+8V5h+2Ux+BzwIKGLGRN+J5nJFefliXbW4Obx0L/pF1ZeE/k=,iv:VGNzLY6YDTScgXd0vTFORvLJY3Dc2fZ13iV1hF2B0bI=,tag:98UunnRAFxtCyXee2tXcdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:HnVBVgyLAiUdOauUVROFtBFfBY4=,iv:3Rwg/jCMIuTx+q/jFqogYFaOtc4OjZ/VSgadz+BRbFE=,tag:uk2QJLOcy+8tAf7SquBUKA==,type:str]
    userKey: ENC[AES256_GCM,data:LwVDqXkCqp/MwOVtuzOExkr3+g/jB2B3wGZNB1dByibe0+s8vnq/rhmtoB8itlr8OERiWx8AKio=,iv:A8iCrBLMRkrgKy+NlnNb9vVh4YahimXT2X0wB8T6yHQ=,tag:NlPdN3eoE0onPoAfWr1MCQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: rook-ceph
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVkZTOHJTUDdTTlc1aTdS
            Ti92YUFGZXRoUThPQWFZQ1pHRE9uZVdCZ1ZRCmFUc2YrejlIc1dBcjIyN0xNb1p5
            UXNhYjJyNWtFdDVLd0FXV05SQlZwRVUKLS0tIHRqTGJZYmt5YU5GWnNNaVR5MzJI
            MTkyR2U1VG52VDcxWUxxaThXWjNic28Kgt5aZVVteZMD+7EOxMIlYaHrhybCrQ9b
            NZBWFAEWwS8OwWV4LmKf/PqB6UOblYcdiCX3+am1Hd65VgwrCqrhTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MWVLNUE5alpSNE1LSkJ2
            TEtCek4yUDBoZHU2Y3Nwb0dJSjJPS2tNM0NrCngrcENVYllOWVEzY2RvNnZHWER2
            djk3c3lmT3hFejZSYzQySmFxaWVVZk0KLS0tIHBINi9wblRaTlJ4Tk5IbGE4RnpD
            SmRINXZXblY3VExOaTM0K1ZEMlg0TjQK2JQYjRor3+909krUWuU5Qyy1w+VV54u5
            G2/096zVQg6Fe2nLwEAXszu+OSzUeG346LCuNDllR41UtaCvqiOb0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOEhqOFE5SWYwMlhUclJU
            WkNVQW03NE90R3FvbjJ0ODViSEY1ZGhmb0RZCk1mdkFZaldpbTdabjA3VHRXM3lO
            Um5aNGxZTERWUlJOZ0lMWkhxaGV2VU0KLS0tIDJLb0p5U3JYekxWdTltWkNsRDly
            NTRJcnAwT2d5TFFkRzczdWV3R1NScW8KsEtT7Rd732TrpC9fmTq+MT/I2TtNjRi2
            ugikM8bhxjJ+iHzlO3mN/BfMNctkbIyrr/G73CT9JxhjddiZgIk8GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:25:01Z"
    mac: ENC[AES256_GCM,data:KOSkhgNEPGSDbFVnJzWdGsG70eFZmEDvNYadpzKOpMyH3DCvL4+tjenT8O/0uc5Io/ZMYJ9N574sRO6rbZvPHkneMs8ZyKN0SQu/meYA8E3llHajn3HRtjtMLLW+8V5h+2Ux+BzwIKGLGRN+J5nJFefliXbW4Obx0L/pF1ZeE/k=,iv:VGNzLY6YDTScgXd0vTFORvLJY3Dc2fZ13iV1hF2B0bI=,tag:98UunnRAFxtCyXee2tXcdA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
