apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: df9170c5eb80e48cf2e50b4eacef0d986a3396cc
  name: cephfs-shared-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: cephfs-user-secret
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: ceph-filesystem
      rootPath: /volumes/nfs-exports/homelab-nfs/5a434804-52fc-4e58-b09f-592a37a16a97
      staticVolume: "true"
    volumeHandle: cephfs-shared-storage
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: df9170c5eb80e48cf2e50b4eacef0d986a3396cc
  name: cephfs-shared-storage
  namespace: rook-ceph
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: cephfs-shared-storage
