{{- range .Values.certificates.namespaces }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "wildcard-certificate"
  namespace: "{{ . }}"
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
spec:
  secretName: "wildcard-tls"
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - "{{ $.Values.domain }}"
    - "*.{{ $.Values.domain }}"
{{- end }}
