appVersion: 0.8.4
apiVersion: v2
kubeVersion: ">=1.23.0-0"
description: a simple glance dashboard helm chart
name: glance
sources:
- https://github.com/glanceapp/glance
- https://github.com/josevictorferreira/homelab
version: 0.1.0
