keys:
  - &josevictor age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
creation_rules:
  - path_regex: releases/services/.*/secrets\.enc\.ya?ml$
    age: *josevictor
  - path_regex: releases/monitoring/secrets\.enc\.ya?ml$
    age: *josevictor
  - path_regex: releases/infrastructure/.*/secrets\.enc\.ya?ml$
    age: *josevictor
