environments:
  homeserver:
    values:
      - environments/homeserver/values.yaml
    secrets:
      - environments/homeserver/secrets.enc.yaml

---

helmfiles:
  - path: releases/infrastructure/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: releases/monitoring/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: releases/services/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
