helmDefaults:
  kubeContext: homeserver
  wait: true
  timeout: 600
  recreatePods: false
  force: false

---

environments:
  homeserver:
    kubeContext: homeserver
    values:
      - environments/homeserver/values.yaml
      - environments/homeserver/common.yaml
      - environments/homeserver/versions.yaml
    secrets:
      - environments/homeserver/secrets.enc.yaml

---

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes

---

helmfiles:
  - path: releases/infrastructure/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: releases/monitoring/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
  - path: releases/services/helmfile.yaml
    values:
      - {{ toYaml .Values | nindent 8 }}
