apiVersion: ENC[AES256_GCM,data:KJo=,iv:pKDCD9GKnhUSeMXXWysTewM7YkIG83TqpcEvjvy1tNE=,tag:GJ/ebHx743CVkLOf08GJOg==,type:str]
kind: ENC[AES256_GCM,data:5s3sa4AE,iv:+8tF11FxIG9v4T6admYtQPcqNVBV3ob1UP1r4dfYMDc=,tag:xHxY1QK2ft/0z/t/0bPfAA==,type:str]
type: ENC[AES256_GCM,data:U4jWYvFV,iv:xvYLEMXkBj1x97cBwRwAOkDA9y8Y7wxKZlx3XhNyLhc=,tag:mdwTosWakOUY7FFXpI7TGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TUoaNTWevOOm/cbODig=,iv:rvBJ/H82si+hMVv1+krLXao9/NtGpq+g/yTABaAoolA=,tag:jvcIHhxapEdlhyqMoa0qBg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:/s26bpFNIA==,iv:2G5LCZ2mPoTZWJKnXBDUtPuTEGQRhELyQ25fpfINJwE=,tag:xI7BXw2DTSf0GMRwZ/0iuA==,type:str]
data:
    ADMIN_USER: ENC[AES256_GCM,data:jmm3vQY1PgsJB3CNN8Ncdg==,iv:PpBklYZqm5LJb9ZlLFVM3tNiFAmPfiHHe37VAjjhQ8Y=,tag:HYv2Wrii0Sea9BGHSpj5cw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:YtK8VnFPNwtkESB0O78bww==,iv:2uu/sRPV5MiVUvATrYsYZeqvx52v53Ml7svgqNWoxrU=,tag:vWAPzyCH5bLzJAyjTYMDWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd2NCa0JRTVlDUW5kTjgr
            aWF4WmRhV1kwQXBzRFFOTDhsVGVQc3ozVG5ZClVRRWV1T2xjR3BQaERaMHpYeUd4
            T0JmOUlyck5jU3h2Wmg2MVNIdFBNbTgKLS0tIDhJejZBdXl5bUJBQlhiU0toY1Ri
            YjJzWkdUL09JZ3N6REpsU09HRnhJSGsK/alTHbVfDxoceqMVI6IZmVlzc0ZtPVtr
            ZFpP5jIxxH8GYaRZ0Ha/WQ7GoQfU6kyV3pgOhNB2UikwbTJCYp/i2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T18:57:36Z"
    mac: ENC[AES256_GCM,data:LaJWxjmHcJH1SRD0LiyjD0WzoJSYWDDpIxymjBM7bzExCA0tdOuJXsbeDZGqunwe+ruRImKlOusJXoZosd6KHj+SEmfbFYbHQ9rkGoqIKmh93V/tK/Y+ExIErGRqMd8ajbMirouklN+HRjZ8NMrBsaNFRukDMUSZ6vP27H3MkcM=,iv:QVrRSRUB+7SZ32eVMT/P+mmspYF9LnBxMlqO4X0KDhU=,tag:APA0oQvkQ5NDJ/Fe5AkB6Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
