apiVersion: ENC[AES256_GCM,data:KJo=,iv:pKDCD9GKnhUSeMXXWysTewM7YkIG83TqpcEvjvy1tNE=,tag:GJ/ebHx743CVkLOf08GJOg==,type:str]
kind: ENC[AES256_GCM,data:5s3sa4AE,iv:+8tF11FxIG9v4T6admYtQPcqNVBV3ob1UP1r4dfYMDc=,tag:xHxY1QK2ft/0z/t/0bPfAA==,type:str]
type: ENC[AES256_GCM,data:U4jWYvFV,iv:xvYLEMXkBj1x97cBwRwAOkDA9y8Y7wxKZlx3XhNyLhc=,tag:mdwTosWakOUY7FFXpI7TGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:TUoaNTWevOOm/cbODig=,iv:rvBJ/H82si+hMVv1+krLXao9/NtGpq+g/yTABaAoolA=,tag:jvcIHhxapEdlhyqMoa0qBg==,type:str]
    namespace: ENC[AES256_GCM,data:5Of4zgPXk2rk/w==,iv:o7uW5eieZPTFpQFiyt6ihDJc53e7p2DudH+wgU1CixI=,tag:gLztpFS2+YZtsKp7j5JaHA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:/s26bpFNIA==,iv:2G5LCZ2mPoTZWJKnXBDUtPuTEGQRhELyQ25fpfINJwE=,tag:xI7BXw2DTSf0GMRwZ/0iuA==,type:str]
data:
    ADMIN_USER: ENC[AES256_GCM,data:NpXhbNv6PaR9fQ==,iv:GM4illH0BwcV83aSTIh020e+85MTwGXwvTQNvZvN/QA=,tag:hu71b5Aaz7264hm3cg5LxA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:VgV65V4mvDDsrg==,iv:A3+e8EnVnfT/Vr4NWaF7H1H4ae8tqdJWaaMoF8XJlLA=,tag:q3//eOqPYSJCIIpFbrBBhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd2NCa0JRTVlDUW5kTjgr
            aWF4WmRhV1kwQXBzRFFOTDhsVGVQc3ozVG5ZClVRRWV1T2xjR3BQaERaMHpYeUd4
            T0JmOUlyck5jU3h2Wmg2MVNIdFBNbTgKLS0tIDhJejZBdXl5bUJBQlhiU0toY1Ri
            YjJzWkdUL09JZ3N6REpsU09HRnhJSGsK/alTHbVfDxoceqMVI6IZmVlzc0ZtPVtr
            ZFpP5jIxxH8GYaRZ0Ha/WQ7GoQfU6kyV3pgOhNB2UikwbTJCYp/i2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-04T19:22:55Z"
    mac: ENC[AES256_GCM,data:gDxz71+24awHvPEckFQAn80u/z4fD+YNOQVsfInbNxu8zhUw2wKYO3C+8gJJq65022WbwUCud4hEsbg8Wk2HvvRQtkV4JOBU/KhG3Ulpr2+v8PbomTgKQQx+Xlec2GXjLnoXtxnYa1YF4nwbSTOb5VUuza/IezHLmw9FfJbOIDc=,iv:K3j419iCwgDgWIhZHx7Vss1ID8TN2hNZ4SZd2FZhrws=,tag:0Wqvz10iimOwnFdLahk5tg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
