---
- Monitoring:
  - Grafana:
    icon: grafana.png
    href: "https://grafana.josevictor.me"
    description: Grafana for monitoring and visualization
  - Uptime Kuma:
    icon: uptime-kuma.png
    href: "https://status.josevictor.me"
    description: Uptime Kuma for service monitoring
  - Ntfy Notifications:
    icon: ntfy.png
    href: "https://ntfy.josevictor.me"
    description: Ntfy for notifications
- DNS:
  - Pihole:
    icon: pihole.png
    href: "https://pihole.josevictor.me/admin"
    description: Pihole for ad blocking and DNS management
- Downloads:
  - qBittorrent:
    icon: qbittorrent.png
    href: "https://qbittorrent.josevictor.me"
    description: qBittorrent for torrent management
  - Prowlarr:
    icon: prowlarr.png
    href: "https://prowlarr.josevictor.me"
    description: Prowlarr for indexer management
- Files:
  - Sftpgo:
    icon: sftpgo.png
    href: "sftp://sftpgo.josevictor.me"
    description: SFTP server for file transfers
- Bookmarks:
  - Linkwarden:
    icon: linkwarden.png
    href: "https://linkwarden.josevictor.me"
    description: Linkwarden for bookmark management
