apiVersion: v1
data:
  josevictor-me.server: "josevictor.me:53 {\n  errors\n  cache 30\n  forward . 10.10.10.100\n\
    }\n"
kind: ConfigMap
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  name: coredns-custom
  namespace: kube-system
