repositories:
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes

releases:
  - name: pihole
    namespace: "{{ .Values.namespaces.services }}"
    chart: mojo2600/pihole
    version: 2.29.1
    values:
      - values.yaml.gotmpl
    hooks:
      - events: ["prepare"]
        command: "sh"
        args:
          - "-c"
          - "sops -d pihole-secret.enc.yaml | kubectl apply -n {{ .Values.namespaces.services }} -f -"
