apiVersion: ENC[AES256_GCM,data:Dzw=,iv:ZcKahfgqAjqtvXdmO5Wj/IVPVO+o6J9G9akchtfRKmo=,tag:9yJFxif+OM9u2Ue9dT78jg==,type:str]
kind: ENC[AES256_GCM,data:p0o6XSm+,iv:v8jqn3oVfpkwtLnhZwktDfvGCp4EatrHEt++oWseCCM=,tag:Iy5naVcOCIZ0aApY8mdMIg==,type:str]
type: ENC[AES256_GCM,data:4CTmX4hP,iv:lz66VA7doSXMuxReu+K4JvSOKGzz5z5n81FeliWx58w=,tag:3yl1NqPHTihZawwhSg/FQQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Wqz8kkUeaQdVQnmgqw==,iv:TzTG7eZeiPa4cdU9sf7uh87lvWD3jfRluNZLOQeIlRQ=,tag:8vvYccfFLp1XvSWlggiBPw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:PmEHBpvR,iv:Iad8l6nub+H8yo00F/DVQ04T670lEYdRaGX15cMsSOE=,tag:gQFiVz4ScGqKKJf7CY7RcQ==,type:str]
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:wJL/15oGkviL73rR,iv:xRM37C/dq1WVuOdiao1JvZZ/ueGHf0ews27sDa8+95g=,tag:i2NY7eBZ1/mkBcnn2j/Cxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQUgzL2oxdFFXNlYzNllp
            eTZxWjNFdEU1em42TGhBTXphTEpabUg3U2pZCjllWjlPTHM0Zld1eEx3VG1lcW1X
            WUhGMFJzQUNlMkFGT2V4b0M4MUVqbWcKLS0tIFN2MXQvdHBZbWRwVVNxTXJiK1Yr
            NWhGU3dSN2VSbUkrWlZBdHFyakNaKzAK1ePIDZF0qI75UnouhcwywsyOubV3PiR5
            pi3/a/4SJGRxiTojdZ9D8ijdAk7bQy6HKNnqiUsNoi9SSAckCjpxmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-09T19:04:24Z"
    mac: ENC[AES256_GCM,data:WMztcRHYwS73dBNk3MffCaIIIV9Usv1SO23rXwyZ0Vf80nsdtG8lzXJ3aw0UzG/CO2evXQC1PB0ZHWlRmtE0BGOo/xQCTOnUg61fEZysv6TDpn112c1f83hMCxE0pFmMZtVeiQidb1XZo2kuvmzGRTk3SfCDjR59pGm2098/ml4=,iv:13B/Q9tHv9KtEb0k0wP6eetfJ+BcP2tglM4JkiBm/9s=,tag:AKrxyIAKHTwFJq8P/WOdhQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
