apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+cAWiN7Ps2/LuhoDOEnWYBGiYnItiA4aNfRYvtfZXBrAJ4aRvLSZgoIuhdxxjmWWHrIwQgMPLBeZfpY1YebynAuydqOqXeJWwRuecQT07nrMd5zoI1cqdVRHIecCNAUwEl1h22nkkVdfAR0JfMuqS4I1jQuTR9P2u6WDhVKIBsLk+pdAQv+Kg7diS0aBQNXCQgKRqluIxeA257wU/WhRb8xV4JIrSR+pAY/XVHz5v7cvt7+qVM7mnrkRHUh54umV5+noNLdL7qqIsPQtkZI2obHbYesRYsQJHyGcpY+7BrSxbMNMkeVDPVSo0Z3Wa2oSPa1UvET6to3sAdiu9XyV8AN/yPSZ4pKEhgj/50UWpXNdbIOLayLrPrs+0hDQof77SngHuH4ymiQHd8IvEBEbN5H9eDajIGXMSz5S2yUA96Sx/D+tQnS5vawmmvb1u12fGc1H/tprSVza2qEfv0vjD5ZM/rm0ZNiRENVAYUzHUgXE+X0hn1uF5OyNv0T3/qq/Z9/RqBjkBuE=,iv:Cy5ip4JuHZVmZTPaiGHG2em+qPShPklK7LOf8SHwWPs=,tag:29F8IjwilBa8j03t+hfIqQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 61e049820ffea9214bcc5665fdd7764580e822d3
    name: ghcr-registry-secret
    namespace: databases
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRG1RVTl1WW5vekhMYnF3
            ZFFsdEFSeVpkcjJtMld6SjBheDN1Nk1DRnlZCmxsQnBQaEhBSE51djl3UitISCtP
            S0tlUHNBLy8zQ0svdFdmd2VVWVZ2ZGMKLS0tIHNiN29UTFltSkt0OWlIanJlV3dW
            Yzl0dVRaMW5YZjVBVHVXZzN5a21CNUkKTfGJ6pFbc6qUJ+YwDsMCVnk4F89jAiDY
            gybd0Oizu3WyDvToWsd3U8LiIt5Oztc1QMJwN82fgcJZ/JAfYIzqVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VlU2R3ZnWHNYcklJOUt6
            UkJoazJ3eDh0WGIvNSt0VzdoWldpSVdHMkU0ClQ2cjBuUHN4Ull6cnV2WllYTTdC
            endHUjZ4VXg1a0RmZUNVRlpHZkd2c3cKLS0tIFB5b0czTHlra1hOOVdEaEFKUWg1
            YXVXdU5mT05ZdFR4MjdyK3RiamNLNkEKc9kptbQjGsw/Pid3awVjYjjZwosySheg
            FCuxpbLHxpnvjVRzf0Nz2kayRdx14MNyLjdVRwoZEpHG/s9IGgDGUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTTkrRmlGQUpmUVhKRDRs
            bTA4VzBVUEpqeE14R2ZMUE44Vjc5a1padXpjCmhlTmVOZTJKQzJ2WERETmVVVEVG
            S2hXbXM2UlB1eEtLR24vVERyR0NRNEUKLS0tIE9za0cyd2VuWVVwVDNOb2k1b0pD
            YUcremtXamtVYlp6SjQ0cFRHM21GQVUKpy4HGcG0GzjwFxUt7gD3DvXBCzzMvOFQ
            NpVSYVYEZz2fLMRDmdJ+QE8qT5w1Rl0vA/nTLPhcAUAyuEjndjb+yQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T15:19:12Z"
    mac: ENC[AES256_GCM,data:zq5XsZSzbngNlbwQ+y9GrOuE89MyXSOcld/KVRnH6Smao8+rB3GRLRfhnBaDEeYp4eMTQ+RKwV8u7OJzY7B9MIHFE9oiOBRH18r+d9bklIpapj1UA4iwGsN3GC6bt2/wABkfXZpUxw5FCzI0oAu3npfVLHGAIZnGSsLwW25fMcc=,iv:kQr2s8kTTKwI9KHaFv6Z2YNyRjCvgpnx412T+GaLlMI=,tag:kTSr6JhAc//1gmWcx9RXCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
