apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: pi-minio
  namespace: databases
spec:
  configuration:
    data:
      compression: gzip
    destinationPath: s3://homelab-backup-postgres/cnpg/
    endpointURL: http://10.10.10.209:9000
    s3Credentials:
      accessKeyId:
        key: ACCESS_KEY_ID
        name: postgresql-backup-s3
      secretAccessKey:
        key: ACCESS_SECRET_KEY
        name: postgresql-backup-s3
    wal:
      compression: zstd
  retentionPolicy: 30d
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: attic
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: attic
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: bookorbit
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: bookorbit
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: dramaturge
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: dramaturge
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: glyph-production
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: glyph_production
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: glyph-production-cable
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: glyph_production_cable
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: glyph-production-cache
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: glyph_production_cache
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: glyph-production-queue
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: glyph_production_queue
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: grafana
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: grafana
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: hindsight
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: hindsight
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: ideator-production
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: ideator_production
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: ideator-production-cable
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: ideator_production_cable
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: ideator-production-cache
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: ideator_production_cache
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: ideator-production-queue
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: ideator_production_queue
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: immich
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: immich
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: keycloak
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: keycloak
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: mautrix-discord
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: mautrix_discord
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: mautrix-discord-v2
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: mautrix_discord_v2
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: mautrix-slack
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: mautrix_slack
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: mautrix-slack-v2
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: mautrix_slack_v2
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: mautrix-whatsapp
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: mautrix_whatsapp
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: mautrix-whatsapp-v2
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: mautrix_whatsapp_v2
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: n8n
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: n8n
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: openwebui
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: openwebui
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: poise-production
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: poise_production
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: poise-production-cable
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: poise_production_cable
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: poise-production-cache
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: poise_production_cache
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: poise-production-queue
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: poise_production_queue
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: readeck
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: readeck
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: synapse
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: synapse
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: valoris-production
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: valoris_production
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: valoris-production-queue
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: valoris_production_queue
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: wealtho
  namespace: databases
spec:
  cluster:
    name: postgresql
  databaseReclaimPolicy: retain
  extensions:
    - name: vector
    - name: vchord
  name: wealtho
  owner: postgres
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    kubenix/hash: 7a0cbd95c4f5d2167b756940596b7b5a22262eb2
  name: postgresql-daily
  namespace: databases
spec:
  backupOwnerReference: self
  cluster:
    name: postgresql
  immediate: false
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  schedule: 0 30 5 * * *
