apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 0f7c3ff7e0f53414e23ac9c7a4acd20ee739610f
    name: postgresql-backup-s3
    namespace: databases
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:zzidl2gLH4MoEyHMedeZb1yRQsM=,iv:kTNJaYaSmlyw3J5YwXpOiAlBPa4eB9Fk0rnxZROlhW0=,tag:MacpOCoCE3Rt4GTM9p0zrg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:StdRFCeZe8qUEmgGu9smXtqoJ9M9Pix1/xiOE3t8QsHIBo6Yu50hEQ==,iv:T5ExNLQR33+0dnej+B4DHGVgKT/L8NFtAyNmY6JvoKE=,tag:/Ic4q/o5b46CqwxlnoHr1w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY2lsbGdTKzRvQ0lwSFU2
            bnFLcmRvMXJSZTZCUjJyMDZrc3NnNzZaK2pzCi9qaFltTllzRGtjTUJFZjVMNWZV
            M3ZUUFRVaTQxTFF2NXd3OC9BaU9SVTgKLS0tIGZzT2lzQlg4WFNrK3BwQWkwbWJh
            VFNhNGlPZHl1QlBKbWp6Q2dCTkdRK2MKZrjZwbh3kVXl/dIIjP0huosriNyOChtc
            /ESYCNUoJ2DisaXI65wiJHxEHYAcDOUdgVhDZEzcQ3nYUZMuorE1gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS2hHWFBuSEExeG1TOUdt
            SmhhdFJWVzNLOVVoQ2VSTGwxRXpHOXdhcHhFCkFFbjUxeWliUkd1Z3VqTlBkRnRU
            aXZSazlmTVMwaHR0cFlYeHpFSGRtdXcKLS0tIGE5VXVSS1dGdXFDZWVaQm0rTno1
            N1l5Q3diZFY5RU55SWd4ZGZHSWc1MmMKfpoiGSlRCMiLiJ2hJKUhajUSstcmB+oF
            4uMuN4WN6ki0XWeq6KVR+qkNPEvQvzFyI+0PR8jdLZmE+0Y1y+6+LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbytMRHNCd3EwL3Ntb2FK
            eDdEZUVIMnM4YWlORjltOWFjaVkyNXp3YXdZCjlubWRIWVRtT1JhVzBiYjJVcXFD
            VUFSNGxYckhTM1Z6UlNpcXJ4aWJHdmsKLS0tIEZQRmFmVVJqeWVLVlRuZWNmeURJ
            WjFJYjRXeDYxbVorZ1B3WTRpVXVrNkUK21GRZfEUyPvZWErYw8NONkCbUCW2/ueY
            0msuQK3A5RXuUTYxHCzrVfy3Z/AGFSBI4EvKw71uwBZaXU2WvaxvcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T15:19:12Z"
    mac: ENC[AES256_GCM,data:fbDoCpNjsWbbnGRvxSEUo8ggoea7hbzfOq4eNjYkhs2t9Qx113JqQP2weYNrZkEPDaR5txiNQYoWTglUbypZ0VY8pSgoHsygI5WxhW6X73c1PqiJgP8tmdfmsw75OeFoJtnp2jfMNQYtuXY7GVjxCkoXYaGkeYG+tE1MZCrIKxc=,iv:bp3SsOtCs7ai3cfgKQt9yq3xHjesNsELczx2DsohvBE=,tag:Nw+U7a30tkqevvQ2g0h3Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 0f7c3ff7e0f53414e23ac9c7a4acd20ee739610f
    name: postgresql-superuser
    namespace: databases
stringData:
    password: ENC[AES256_GCM,data:9+/id44a6GSJ2gVc3g+RoatT3g==,iv:GRz5MO5esD/kVUkScaqZcdT3dx/CZEgzI7cZqR80SiY=,tag:tzDfYP6HJUYQI+qpj7108A==,type:str]
    username: ENC[AES256_GCM,data:pkruMUPxGrg=,iv:ZKkMQL8skeryKLFxs8FOUeMRVxZ+wlbQpVz5i9J6Iv8=,tag:sUJizP9TC/2zT8l0n25jwA==,type:str]
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY2lsbGdTKzRvQ0lwSFU2
            bnFLcmRvMXJSZTZCUjJyMDZrc3NnNzZaK2pzCi9qaFltTllzRGtjTUJFZjVMNWZV
            M3ZUUFRVaTQxTFF2NXd3OC9BaU9SVTgKLS0tIGZzT2lzQlg4WFNrK3BwQWkwbWJh
            VFNhNGlPZHl1QlBKbWp6Q2dCTkdRK2MKZrjZwbh3kVXl/dIIjP0huosriNyOChtc
            /ESYCNUoJ2DisaXI65wiJHxEHYAcDOUdgVhDZEzcQ3nYUZMuorE1gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS2hHWFBuSEExeG1TOUdt
            SmhhdFJWVzNLOVVoQ2VSTGwxRXpHOXdhcHhFCkFFbjUxeWliUkd1Z3VqTlBkRnRU
            aXZSazlmTVMwaHR0cFlYeHpFSGRtdXcKLS0tIGE5VXVSS1dGdXFDZWVaQm0rTno1
            N1l5Q3diZFY5RU55SWd4ZGZHSWc1MmMKfpoiGSlRCMiLiJ2hJKUhajUSstcmB+oF
            4uMuN4WN6ki0XWeq6KVR+qkNPEvQvzFyI+0PR8jdLZmE+0Y1y+6+LQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbytMRHNCd3EwL3Ntb2FK
            eDdEZUVIMnM4YWlORjltOWFjaVkyNXp3YXdZCjlubWRIWVRtT1JhVzBiYjJVcXFD
            VUFSNGxYckhTM1Z6UlNpcXJ4aWJHdmsKLS0tIEZQRmFmVVJqeWVLVlRuZWNmeURJ
            WjFJYjRXeDYxbVorZ1B3WTRpVXVrNkUK21GRZfEUyPvZWErYw8NONkCbUCW2/ueY
            0msuQK3A5RXuUTYxHCzrVfy3Z/AGFSBI4EvKw71uwBZaXU2WvaxvcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T15:19:12Z"
    mac: ENC[AES256_GCM,data:fbDoCpNjsWbbnGRvxSEUo8ggoea7hbzfOq4eNjYkhs2t9Qx113JqQP2weYNrZkEPDaR5txiNQYoWTglUbypZ0VY8pSgoHsygI5WxhW6X73c1PqiJgP8tmdfmsw75OeFoJtnp2jfMNQYtuXY7GVjxCkoXYaGkeYG+tE1MZCrIKxc=,iv:bp3SsOtCs7ai3cfgKQt9yq3xHjesNsELczx2DsohvBE=,tag:Nw+U7a30tkqevvQ2g0h3Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
