apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: etcd-snapshot-offload-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MRRlc+PSvmVa2VYesFXdBOX/SZU=,iv:v+u3gXSJRm+lqviX8hQW5a3wd4jjf+dWyr3QOlpCPtc=,tag:fnH+zx1WvmhWjgtn4dmk5w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2Mei7rCC+EJ3VDobg11KDALeyDu+J4x66KgNacx55v24QCZOP5p5BA==,iv:gLhKKCy4DZuP88zsSGdEWHMbZ0EjFGqkTOdxIKa/k8g=,tag:Cklb/pVBBj6gnslNBcpKlA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUGFlOXp5b0RaS09zT2oy
            Rk9YRzJBZjRFOTh5ZGRrbGxjdFRGT05lRWlZCncrcXZPNXB2c2JkbG8yeHNNbkVH
            MnJydWR2cS9QcUxGL3ovcURSSmk2SG8KLS0tIGxLSmFVLzVOdWlRa2g4cWNWdS82
            WmJvZXlaZDFtdHY5Z2JOdmVUNjlUT1EKQfYQh/5n5gK2e7OQAKKxY5fsJMB+2jj7
            QhuEsdPx/RLE3MGd7tg4uLM77YzMSoEcte3QzRtSO+iAQjgdnUJ7Xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZXFIWkFlNUJjREhPVHkr
            NC9SUU11c1BOdmVENm9OTW8yNkl5YTg4VFI4CjN4azh0QWd2K1JyQlhObThtWXZx
            cU0xYmhPMTkvWkF5eUl0V3Vadm9VclEKLS0tIDVzTUJyc1oxaUZCYlpqQks5R0Fz
            TXFzZlUvbVpoeDJjc3Fhc2FkWkdHbmsKAp+krDWjW9iWvEduCzxhvGS86l9WvPkt
            gy3cQ/fGJGVIhf8OLYVUGIGvRbMZYUeMBeLFddKuvApM+D1CcE7ugA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSc2FuMThoUlcwVWgySzRi
            clRDWlBoaE9NL1NQdUN2YXdGM3J4eVl0empzCm84Q2dhZGRQeEpudENXdldlME56
            S2MxMWFnc05mV2JrcDB0VHRYeXJDdWMKLS0tIEtHNS8ySERRcFRiOVpvRjdMVkp3
            MUZ4aTMvK3hDZ2N0dUx0VGw2TDZ6N2sKMCBT/9Zbk499kkdvxjckJlqRFrjx4u8z
            CPOxA0LlKNhvpCPKvZl3933UDAfEcAkAo2c0jMefgYwnLx7ih5putw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:57Z"
    mac: ENC[AES256_GCM,data:raT01ep2DE+T2vwRqPET4Koc1uowz5WzVCvU+DKiNjXyH73t3irV5i/RyQXCgLGH3IQmGg/+vyA7kp5VUQW++YB0KQ8OU7K8AD5Du3AD4/755ksIUYiriedvUCK55uTYxdCoIYWkcdSz+VI9YYM6Yuqg1SPcEleJOebFHDAdGj0=,iv:ZZT5E+7CRFEb/ioJvhANjP+gLgpU43IQjROCRbvkFR4=,tag:ePp892rE6A3VB73BgxmrXw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
