apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: etcd-snapshot-offload-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kFg9sFUeItCYzeUQNI+pPqXMYE4=,iv:CuJzqWvQN61S1k0gr6Vbcq+mHSzgDdzWWvtwIXS97LM=,tag:ElJwPTBUwq1Qq8bb00uj6g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IIgsaZocUJrJNngo2Xbg+w4jK8vkdysk1t79Ub35PwLiaBhMrdz+mQ==,iv:OJzpWTUKfOjUDPTEs3LN2s/Ygxma47q2zKfB9ClyLKY=,tag:DCDhpAVy6eER6sAvjtW3vA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVWpUUTZmekdRZ3Z3Z25B
            bTNMZTlzZ0F5UWpVU1JlSWViWmtQaHRhZW1vClI0U3hTSG15K3ErdC90c1pWazhp
            K3lnU0RmTmxVenVtOW1lZ0k0a3MrNUEKLS0tIDliMklZQjVhVjBNYnpvQU01bjcx
            dDRWayswV2lqOXVTeWY1QW13dVJtYXcKe8dEBzYMEoIoQU1kNJUOc8Bo6tdAci0Z
            fig9PIUnHOUs9AqN6cav7CPc9AJh/JTT6nfurYHW3WwBwjQSl0U97g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZ3lNT3R4cTluREhpbmt4
            VWE4NW5Rdnltc0dvVnFUbjIvRXFPSFdxV2hnCk5GWjFhQTdHSm9ndVdrQmJUYmxa
            RFVoaGdTeURaeUZ5SXBxY0F3d1JFK0UKLS0tIGp3c3lWSUtPV29TRlBSTGRYbVNw
            VzBqV0hRMG9IUEd0RTMvaXdUTXgzb2MKjryfs10AI+rh1dh1nIpIF5CiGR4dySGz
            G2+8FL0SM1lDbADJ1b00LjYVHDCTpBxCGRYk/k9ez9kXj1hY8iRFrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTGNVYSsxdDFEbDFuUXk1
            andtSEIzWE1oUEJQVmRhbDEzZmVXcVZEcDJFCjlSaWVzSGdmQTE5cWVqQXFNMUZo
            S0I0ZjVoWWlNVFBVVFp3WGJXcGYrTk0KLS0tIDkrb1hvaHpaZm5ISUw5TVdtUjd2
            blBYWUhSb2NzaGIrT2JMK21JNFF6T2cKxBYCbkjn5TDhr+SZmy5OSQ6B1o2+6T0I
            MtzlEbIe/PNnz8kGu361u2g7viUkK2q3VOOtHrBWJl6ylDRnkMyuBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:58Z"
    mac: ENC[AES256_GCM,data:8k8Hp8nGkJxY5evF8pucI+TOYJLTt4wsupWyYyhtMPa52bZ/MOKAWdnSDQv4SNfwucJ+XYRf5Jioze8ZLlz76zeDArru8aTB0/QKRgTK5O+MspnYGM0j8IMF4Y6uOqE9B9XZyrw5+FOT4XoMcI4mH+o+O6jfKnfybW4gy9VbSjk=,iv:ZgTj6eTGWUP/ffnA6LzL2tcOqrTBepN1qJO1kh0/rMs=,tag:cvA0X48YvwRRmpB0fC1wpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
