apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: etcd-snapshot-offload-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LdkctTcocsFiqqcGkKD9GqyjNdw=,iv:e/eskJTopNGofh4rNyAddLpHuO2tP0NSqkoFdBKjkYo=,tag:ZFTHa5SACGAvdD4CJIMSZw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vB4x1MFYSarkfiC6cjKDue3sW+cH+M9E3EQvwnhNN8I8rb1+laeBxQ==,iv:dC5ZayzuOi4JlAPASPmBEKC+Cdlj7CwdtpnUfsPmXtk=,tag:0x2LfnM/nhLm6uCFOSgFlg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZUs2OWpobnVrWThzQnhI
            NDhpSkhtLzFuUHYrNmUxUGRGd2p2d1Z5OFdvCmU2U2FEZmM2cnFwaFhOYlVRdGpB
            Nlh0SUk0NEEvL0RwNjZ6aENPRHM2ZWMKLS0tIEtQQUdBSEtsUGZhWEJEMklwZ1Mw
            OHE0OWRoRllpQlM5K2ZIb1NMSlAra1kKfDwzPWzxSpwlSTbUiSWVaouXHoxhS2i+
            Gtb/r0XdXw2T/9SBkV0cNyXcDYUED3RlSDnyBKCbOvqUMiuZz1DJRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd3hyakxBdWpSZ2JHZmI5
            ek5GNW1sZ1R1QkhUTkdXL0VmdXBIRzFtL2lVCkdERFlFQm5zZkN3RVpvUDN0NjJF
            V3J5Wm9SaXBpOWxYOXI1TUt5TVN0eGsKLS0tIDJyV25tbk9PdXJmNXd5SkU1SVN2
            RHoxNlIvOVJXdDNTak5OakJkdnNsNUEKyuCMGwueU2RLXk4DIMuyV8HhW44ucJ8Y
            8vIOn5rN+S1dLgLC1iMDgb3c+XyAZFPnzWUwzvozQzb6FMe+gZBL3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aElTc2VrVTB0OTlleFJW
            WFdnQktqMkw1Zy8xV2dyVlBPb3J4cHFIdFVzCjFtc290M2VlYlByNzF3RVZkWW1W
            d1FZdkk0NkgvSkticm4rLzZHSzVselkKLS0tIFJkQVQ2cncwV1FxZVZtemNyZEVE
            ai9VMzh0UXZTdEU2SU03UC9MSWg2RTQKF8gaUsTAE1mWC+S8Tq0lr3q9jRgEg0Om
            ZhaLLHJOUxUS+BaP3xNCCukcRwmPJcpxvlyBwhOxLQeqk/O2uOhaIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:34Z"
    mac: ENC[AES256_GCM,data:P4E3W5jATaEROfRkdwKjazyJ+hrOTC4/qLgMeGh4ckShh4KYUGHPMdonG5E4gjFGNInsZ10AO1DdH3GVuCFg/1tA2PhNGvcvsiQjHIYpqsGwCQ2WE2cpafUCIiFqsyVpaUc6cSX84C3mCFyxnngAJBgEJngqAaYG6iY67ztFDRg=,iv:4S02Dv0Dm+5VJHx7sKLw+yGRo9K9UyPcOmNEvss2oHA=,tag:LqWtwnMmD3bEWPazHthJHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
