apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:QV2Kz3cwZMzqBb0tnHw8AEDChhi+GYe3IHNiEXHkDr5DzOWe9c5KoTYLPMlUDnLcjn9iZMFeiAI0YaGd,iv:naoRMncWJKiLbElPGuWarcpFUXvlNLUaKPuYUimoUHo=,tag:7q/V5uhYDOltDdjtj12t5Q==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: backup
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcHhMS2JBREpHZDU2MXNE
            M2hUZUJKMmsxYllJU0N0ZDUzNmRkT3crTFFNCitMUXhLQ3lid0tEeis3OTFxL3o0
            NGlzVnhRWm5pNk4vT3htYThlanhwNGMKLS0tIHdqaHJXUCt4QWd1WUJaMzI1MmhM
            Tnd2SXJqQ3BJNC80c1JlZHhzd0FnR0kK13DqlUMxQg2iCJBj41SYaHm7v1z/wnev
            6L32/UQ9irZKY79ic0u5rLXKJ/JhCVyGWcOQ1ShyeuELMsy64uZcPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNjg0QXROQUZUUHdWMkY2
            Z2FPMXFxRjArOEVoOTlWNUhzbVpUN2N3aG40CjR3bFlFMEFPb3c4L0Y2Z3g4NUUr
            b2RVL3UzSUIrTVhKbTlacW1vRC9id2cKLS0tIHVGZUxtdEZwc0c5U3Y0aGw2SFRC
            R3VjZWZQOGxjbERuZlFMLzFyTzBoVUUKexKNUXXlmAl1xPkKq48Oh4MRCjk1gYOE
            txZlGOI1eBmhTW3xNU3jEhVR0oZFfNfzQahwubPsfkVrBuLknwrYlg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TVdCUmZZVmlJOTZTd09i
            Tk5TbjhRWmZPQWFVdFhWTXFIV21sU1g2OFU0CmlVeE1RRzUyVklmemFKeTU4Y1dK
            bStQbzg3QThHeUkreHRDcWpsejBwQWcKLS0tIGUxOGF4aElLWlc3ZmMvaXlDOXJa
            N09pVTNyNURMcjNRQmp1V090VHZQcmcKettdLhYjSZprrHeEYosyWgpqwd4KXZZh
            KNKa4rgBh7/SIr+F6eui9/HlB5pFMupDYKlbSVDgxwMQlFCFSNUZLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:02Z"
    mac: ENC[AES256_GCM,data:5FPEkLKhEgIrnLsmLpeQ1Wv+By5S2s7s8anB4e5J9FDn1oArgVAPTag/NeZpIu8VjU6VeOm3Wx3jbj+t2ymN+IGad1LRGZSIQktvf/h4/T+fI5rapBTS6tJg1TAHcgFk6peE8lgOQe3tHf6lJu6sTSRM0tVNapP2LE5rvjOIS+o=,iv:yGlgaKxvCdgU0MXgazof4wjWj4L4R5iG5eGDsbxVakg=,tag:DtO5rWPwbUHZVZddplQXGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
