apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:xApRSu0H8OStdxd81t5QN5553pbanBLqkyRcAsqxa8bORJR8AzVWfARgx1tqMpShfylN1xhf8goRACrWLdCAGpemV1nVpCCsxtQ6Xs/Q8MOc+kDveuC+GTdVnhiXaIFt15+k3U0QCuk4hUh03g+2/qJGGjdr5uaQn/dQ06ZUFDyx55M01i8IvgMs97l3mPOZ8xtD/IPLnIhYPJ8aATG7ymm8Z3tGaeQiPaKZkZzWg7OJjk6emh9aPABinDqU9xXGIeP4gNAJiP4apCMDQP/m+DpasA5zFG0Kqk5itVIfy+Tq7yHD9N3V7BZcIbE4pj4qAtwcM/d82wrrQrRFThRVC72II+kicAYwZ+T/QHxA46r1weBil2KPbaBZmAeIH3n83y27zKfvSe5IFhPSys2eRyD3/LS8t0rWdFXrgCfnbt7NfAfGLfOz1dbDPNK/mM47nXMY++TVWLmTuB/pPhr8Ek/HzBsa7aWzSVHy1V8vJXA38m+T607KAaP3dmuClqMkA5j/wPBcXaA=,iv:dk5fjY7w5IQQnL89hMuFq20HHD1sMEoUOtELzDPB+3Y=,tag:6DHU0k1k+Us0XU/jEk78Aw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: backup
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNk9xZG1kU2hrOVZTZFgr
            YTR3cDQ5WmJNZU9yR1dCeVU3cWgrbi9tdUVFCmFTY3B3NXptaEo1RU9rTWIzS0JQ
            alJ4NnBjM3NXVUZrUGZEZHNZeEUvMjQKLS0tIFlDUEdjMElCMUFkanAwdGdHRFg2
            TmlMQ0lSa3BJV29EcTNYSVJIUFNGYVUKHgrLi4yU0TBSzu650gVMwaVOuM/SSyDq
            s/zRRZH/ZavTeNWlZyl+REvrJaEZRm9oY2JnLM4wO/OlA50oicrjHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYXoybjdlbllLMGhpWElX
            TzFKbGw5NEM3WjNScjJydUJmd29QakxTaVJBCmpuU1VJMklXOFRKcWY3ci9zcW5u
            SnlhOUVaNUx3V1JtY1NzNlhZODNFWjgKLS0tIHNxZG4rVldac1JHcldnR2lxOTJa
            MTRRUFJoYnlMdHZyMytzMzVzd0JMblkKfWg+Hg4nVqkd8/OiYm/hgSqpgQcryvi6
            NQHLv/rEEneTNI7I7+Jh0VzxrGQjJV9Fq413wlFC+aqi4HxoVAu9Sg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MEhHSmE4OFd2cGRKalNN
            bEt5eDhJUjdZTDhyUk4rNWtONEV1SUFpTGdNCmQrNVdTRXZrbTIxanlpcno4ZERE
            Ky92WjlyTkdIbFBTZnJVSEg4V0RLM3cKLS0tIFFTWkttcmk3d2lHMUtjeHFMNElM
            ZHM2bW9UYXpIRXF1ZFpCb3pEbzdTUk0KlcVGp3eAMHoNPQN7YnnUb2zBrXoD4+Go
            wnoWfvm09Gwi0VMDO4B5LqN9omwc7LDjwZXHqdnyNlZtkLNG16Xe8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:34Z"
    mac: ENC[AES256_GCM,data:6kEqUuBrLO3nKGoxHiDIbGyWBJhqUVPoSFO2istJtR5EBof1T7TkgjJ8TwbQ7vmzKLl8MzqgGtKsCk+1WleAYwnmX2EhwQerIaIbtnzT36lbh3FJXMf5HEXKK9Woum/NIO9WgQmxVyY131B+sTptABsbZS1WoVbrwnV3F/m/e8U=,iv:z+PrcRQ42aE3YLDg6w7cMebwmphqJ+2GmjxkVDaDIp4=,tag:HroTxyniUsHePnJUpDCwSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
