apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:wOji9s7vZdZ8YLunhdh5UX8XQkpyPwebRUUEdiXpEqLecDJYjQA8wiiLnM1EQ3euNjKMJdGpDAfsD1cfZgU4YVvbF9YcVteFbe3JKAEVnkB4jAjNELSB2tw7PapehNPU5gRUwcBzlxou9QMbV5v2dkklhkWgYwIfrcRyrOmqOCzWZT16y/BpO37pSBdajpqYlkMokEeCHSiHnX8UowrimNMpj/4IaIRKCYHJloMp6neH9XS00fHiAJxzN3diZ1hwzk85zguyxAi0O8P4vqasXE1ltEhfJVBDL6RTuk2H+nTwAWV92B/S2Dl2/zhLHGrpTf9QZM7R20PnDXXbWN+jb33Rvz9pyxre8/l/T3EDWfTT+NkfGR0wwNiNhPKLdmUVTxXtOSFeCo6lynvityton8VhawuCDlBdtS52L78nDI6gEyAuBFAEK9WQvlYd+aZfeyWMQBmKtJPMCLkRdxjhVurz3t9g4t+Ht/cEHQQNwC6TpPBLAFSXT7GLMAMtIY7QOiCuE2WWTH0=,iv:jOyx+PpucEyS6yriaP1r6Y1rXARBW4Y7GvvoVFx/VyE=,tag:ABs4UeT7u76FwtLX/tJtXQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: backup
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvem04RUNiejlsdmRHeWFX
            OGg3TExsekJ1TnNTdGZxQlYrY3NjeHQ3ZUU0CkdVOWtoeklXdmRKQnNCeEZEamkv
            TkdJcU9nQ3FORHVOU29SckhMNkp4b0EKLS0tIDZUcVpjYjdlcVZyTkNCRzFZaHpi
            aWtuOHo4a3ZRWnk0TlVxTW9JS003c1EKHCa3/uZFYK2Ze6WVeV93GAN5bwpHvkuy
            Hx4k3MRdj7ORpjC+2uJ8NOx4H+sAYxlAER24sbeHQzqA2ESIyBvhsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzM0RlYVA3WGhOUDgyWC8w
            Z3RiRzJwZmZ4L2kyblpwZUZBWmdyVXhNc2k0CjdqN21HQy81UStvY0FWUmc1NjJz
            Rld6L1gvZ0xQTWN1UDc1cW9WK1VVTWMKLS0tIGNua1J2UE40MmU3QS9VdXkvWHFZ
            MlNoNWhEdGJsTVE0UUZiRG1sOTIva2MKl8B7kNWravTL/4J4FB0oRU7ewdWpaJA2
            TnP5JOMEhPlBp5tsDE5jLSScV1JU2u11Y3vbSFByOCZpHzGvs65tEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdDBrL00yZTJCWWlzMEFv
            VUFRZFFWNnEyNmtLTHdIWXN3MXRoZmZHOUYwCjN5MnRMc3JjdjM1NWZlWUFRSml3
            OXVITkh0cjB2bHAwZ2x5dEdueTgwSEUKLS0tIGVacnFZdmMwdHBidFdKTXNNVWRx
            enFNUlJEbVNXMXpyNlg3eEFZR1p6TjQKoc7/rBiUq20drlVE/RwD/RWTKj1omQl6
            7vo9DDi4U9eTTCXIfVCkO8htAqEy9on7B/2FdxWcwYiNflbPzGCRuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:57Z"
    mac: ENC[AES256_GCM,data:/faGf1Mhg8t7ygYxnXzsztklyz7z7xZAkYuoy5G6hkXPJiXs8TipPK6XTRUbrgT4X1O/IH1FruinbTiV//+kEsCO13F9lNjlP6uSOrL9UdDRNEY4+P0OXrPtRVsqlvs33peafkR9RxQ7Wl2A2wBw4gIJzuEmh7Zcc3puVAbJRbE=,iv:m9BhvkhmwSk2asc9LHwqNBT+r7q6Ngtwba3TbUJETJU=,tag:3vBfHd9fGbNoJyS6/O1O1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
