apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgres-backup-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gPqjjq0qDI8c/ruAf5vhmmBTdIM=,iv:mLTaEbfjOTTUwmJjftgcqFzejczRxFI3+Bw78cbL1pw=,tag:M/voYOHgaNfqSG6Cm3gAzw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:BfoRX2pnjNPLz+Vi6ZGp1i1RdMZjDmkTz7jZSAeiEqzbe7Fe2dHFNQ==,iv:DlDnXhjJ5gN7VrW26pph9eLVNKftY2nYhHOlhGUGK1Y=,tag:w5Vr3jMmH74FjLErB+ML/Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcmM2MkVOQ3YwbE55QW1O
            YUx4ekhKTy9OVkhORjdRSXNuZnVPQjRhMHo0CmJXRldDazN2SXozejZTTnJBZWNI
            TG94a2R2dzBZb3JYTit4bmVYSVJjWEEKLS0tIFFkWUJOakNacUp6ZXpyQW9GNlJR
            TlJ6cUpUK09DTFdDWG5FTHBaVUhqZEUKUZqlFNp3s/RmemQH+IsHmMzyrh3J7MZE
            WAR5W1VE7QsV0rOzlCGY72Rpc0AtkNsI2owJNTefyX6SPKHOLzwQDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMGQzSHZzNWozMXpjMy9m
            djZwVWwvdkJid0lBUUZxOTNxUVgxN1U2L1YwCnczZ3dzRFRTdmNFUFEvekw1Z1dD
            bnFnOWp5dUlWV2tJd0U2R29aVFZ2amcKLS0tIHlJRVNkd0hPVDEvRnowYndKVVVC
            bVJieHJGVjAxbTdEVFlUN0ZnRFY3eXcK9m29tbnwS4cpsg+AcaBuKP1ImjSeYNUN
            QLmPj6ZnylbE45bq+G2tWvldV+NXEW+DEqL55nPaG/deO+wzJDn3Gg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWGxaMDd6TU9ka0dzNW5E
            eUdHN2tZVmhtMS9oN05Qc1FsamZjbHg4NERjClZ6TUg3REpLQ0JjdzhUTFRVZUVk
            RWhzc1kxQ3YyalJGbS9CTm43ZTQxV00KLS0tIFdVamo3cWt6N0hIcFRybDZvaVlo
            R25NMmpxaVVTaUM0TFVGSlRwdUpScEkKovkdQRx6kJ9HD/z9FGw2hR9r1loBZtw7
            vIfIXnapFN4W8a1OI+elBqmscC1+OowuibaQouZdSe9D9CofAiHqHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:25:00Z"
    mac: ENC[AES256_GCM,data:yzt71HiXb527x4YEt26YzuXFLP40zP6qsTnmZOnstiG8Z5nuqHr2nZHfk5k9ZUhAonDrP+oGSXR6R+A57Rwgx74EXrn5rO6AlZdP+T4znPmVqXNNsU7v6w2hpyC2e4KQTO+NzTeI+zq/DpnRcRGN+jEyT+VUU24uDEwExyuw4w4=,iv:iswZsaeXu415E4RH121zWOAptq16o0tyZC5GJ3X5Stc=,tag:0Rz8uZYKEvGZYhpeoRaLVA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
