apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgresql-auth
    namespace: backup
stringData:
    admin-password: ENC[AES256_GCM,data:A+LyQTSqZF2mtBt3byQgt9p3EQ==,iv:wGQdf82L8aENaTr4nwcGwSEdjbP54a9D25waPPznNxo=,tag:5oa/oop1ecPyEahKqPzU6Q==,type:str]
    replication-password: ENC[AES256_GCM,data:qFQFuI7FlbfhQBuF4iVuVCUPVV4=,iv:GVuVSihsGsPAriMLbGrq5MTNAmS/bG4TnHXMPFh12bw=,tag:l7ba0QikHmj4dUonUQYDTw==,type:str]
    user-password: ENC[AES256_GCM,data:KY+AD9+6NJWJofruvOkTQ264mqYras8=,iv:RLRoqEvBvXtrOElnNO1u0P7eTZYgg22uYHqfqtlsgB4=,tag:mV5pQ3i36wNouF2R5XEXFA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM3Y2anRnbDhaT2FZOVhV
            eU5lb2ErS0RRUThHRWo2Wk1iK2ZBREd1TUhFCkYrdXNDcjFUT01jdS85SFo5aU0w
            c0FSaktibjFmSGdOalpSbUx4Qk55aTgKLS0tIFBFcS9Ld2dKVlIvZVZMdWN6eEwr
            c09aREo2Rm9ZcitJSjJyMjdrTys1eDAKPII5b0fq6HVPlTTeMJWqFugg6jwqvrjw
            uvxvJcJ034EI8Bstp48lTCWXjSPZG1WCEBjOIjlIQRTRQ0Xr/e13dA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPelBJWE5oNjVWVStHYlhR
            RHNlSXptU3pLcnpybTk0OWdwR3JwMTBzWjB3Cmdub1E2enNFUDR1T1pzWDJScEVT
            Q3lUVlE0Z2g5Uk5wRXNXRWtrWC9PNmcKLS0tIGYzc2x6U3cwVGhnWURsN3FDMzRo
            bUdMUWUydjB3U21kM2g2SVZaUnVrMU0KPbdhwCBC0HMw0fOZVn8vsnScUXBBD2GR
            XYSsyEug//m11Ix9z0ZPNEUodCBgv+hzRlGRogAWRSAe9YAXkWxDtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZVdhdnI1OEJGV0VNdUtw
            MlhCUkxkM2ZpTUlFZ1U3djg3Y0k5S2l6d3dvClNueG5XMVNQZ1pvc0ZJQUllVVVv
            MkpoM1pWdzU4Rk0vRmZKcTFhcVYxUFEKLS0tIG83dEF5SExPQmUxOWZSOGwrUUZa
            em1NRW9UNjdUZk9lejc0b1lUZzNTYlkKj/ZxqgC5AHP/I7s7cCBD6koT8VCqWdHv
            IK/DsxVx9YQoWWmmFdtrIm1ayY3/M+YD6m70tGkBHPofTifRt/9aEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:34Z"
    mac: ENC[AES256_GCM,data:BTvDwMpXhpcVbmXodtbby8nWPf+7lfp9skx6PmZhIpz9FEcg8uCA34DduOvlDyrH8jSwMMvccwUnsZ8a/zVmp6S1RNLFA0PDXUdB/Z7Nn/SqPFUyvdQTHPuh3cC7dRzdYd4hPr09AG+AhP0DacsCO25LH198EboWugoXhi4y5d0=,iv:I2iTpAMxPgnTSLQ1DuzxXTWvGiI8tnpgwlz3SJ7bpJI=,tag:KQGK9bCLJr0Th865N/2z1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
