apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgres-backup-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Y2+40M+5ihAf5XIqs8L1tK6dRQm18iLeZYCRQ+8PKr1JDIqO5Hy7i0BtJWZCic00MFP8wFEW8qxeZKsTwO2m31Mi1BXvZurpsgui,iv:c7wInzxAC8GspPJuGeui9JJetm3bnsU3kiIsBClzXKM=,tag:1ByfKk1jgNtaqPyHZUo97w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:teMRH3I1Pibx1JILBsaUANRz1ZmEkyZGXtubU9o4mDDuEfVQrTePXLEdeiDT0HE6P7+38MUssC8KGPEKeg2+1EbNhhy6+x6KJXGpaKXdzg==,iv:eFLle782iaCw06QLVE+y32V1Q1QSanm+tBCvSOq3fyk=,tag:PIWTKYWt3L9etpQHHsriNA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLY1owUVpDNXF2Y0h2cDZw
            YzFONjBaK0l1dm45Q3dDRTVoWmJZeEFLSzFNCnF0WFFuR1B2ZUQwc2t2alNOWWwz
            NHJYV1VmSDdjcVlmdTllZ1M0RDJDOFUKLS0tIGdhK25qUzRhT0VZTWRENFoxRjIy
            SlErL201T2NpQzBYOUo1WE4rTHVXazQKJHPoPh8jIIELOL2WLxbEZJBVwWhKWDSm
            0VcwTCh2CAdAH7WaqlS+jw9gU3t+zSgfpb5WFaunb1DE13O7apyrWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMUI5TzhKdHAxdHZXTzho
            Ym9MYzdpTm1ZYXVvS2xDcjB1MTRnUkdSOEJBCnpMK29zS1crM3RXYmxLTTZZUjJR
            aExLcTUzM2dXa1QwT0s1MzNJNmV1NWsKLS0tIFRCVnZMS2FkcEJsNDdXNnlqL3dG
            azM3ckhlSVpwNEhiUXY3K3lnVCt1dTgKTv9AyiovNiTc7zddqz9ABD/SThSfIDPL
            a7FkpjWYLt/vYfmShqSDxTS4StPaFs1gfjbvxG4aFM7sCDog9gLW9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrejlnSkpscHh4U01FWUJH
            c3JqOUFrM2k4MnlBZ3dNTldXdTFnSzNRYjFNClh5UDErdWxQRG1hdHpleHoyc3o4
            TUtKRlRJTlZkWWpyN215UTB5UlpLYm8KLS0tIC9HUUo3T1E4Q21FWUsyUmFtanZi
            UDFzaFhJcm0wdXFqSVFBeDZyUEZ5djQK6CiWlpkbEctVik58lWGGAeiAyCBqv9XT
            vcMIFEFkDqhopnMQoCjeXmuEGgR3+wvlHz+TqfqbMZGUGm9eC3Gkjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T01:15:56Z"
    mac: ENC[AES256_GCM,data:DWLDlLFfUwFzUI76lezoFNLLKDlFrSlBMJrNR0/cTgtb4XCOOwHLJxVWZW90hvKykJu1GegZhs3as0xcOy82Q0VLWzqAhRvHEGOoROIn+ovwwIP7uM3LPeAFLMhw2RB1srhCvjVbYXgF5a3OHrRlOPNd19EMuEN/hpW1palvHSY=,iv:KUehP2O8Ay4E/PFNnOcg0ZvwPcElXSqJUsVJR3KqsVE=,tag:V08ckLdFrUymjFCK3WqXJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
