apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: postgres-backup-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:jp8XsWYVe8TnOr1HJmYqksfKCWI=,iv:FhSCk8HwMxgVkmhY6QWIG/rw7/kkPmFuNX9uUTLK1z8=,tag:aOfybpkRDh1hl5HgAB8YVA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2WH+DMPS0N2Wggmy2WR6pI9IHlNruvgcp2rys2QairapkxBswC85XA==,iv:E2vzUO1CbtJRe9bR6G7GySgmi10URTzs/8cbEnUC06Q=,tag:jvTOZwuC1R/rn2XPIPXE0Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRzRjeGtRQms4NVR5Mmt2
            RlB1TjMzT2Evblk0d1JFYmRvVlpwaFR4WTJnCi9SL2thbTk1eTdUMHFUOUovbVhX
            dFlZdVpsaGZ5Nkc5Y1F6VGJDQjgzUEkKLS0tIGVYTDlyV084aUIySFB0cG9MVWNH
            M21UeWNoUkJKMldGSEMrUWNoV3ZBUXcKKSrX8LICfWYVpGk0rnWk+RXd5MPOTYc6
            CnTtpZn9ltfd/2DWWLvScfAU8IRNVZHF0L3weLi0PSKi/qRGrmY6YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNFUvWlEzOHVtRldBdHcx
            T3pKeWNoWkk2elhTL1dTSWFhOGxnUk54WXkwCklETlJ6YlVramhITVlBOWREc1B3
            d3FGWnFoM3dHTGZYd0pGTi9rWVJFakEKLS0tIEFONHBKUzA0K3kyM0ExWjlIUVNa
            VEFJbHlwdG1qVUdCNFA0ZHZjTWVxUWcKa3jT1mz6S4g31sDiuKQZiKMUIlsyLV17
            c7cvIKBK012YuXfCO5riy6jaGI3aUXGiYQc2NBOtcfBQHZfNw1elBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTmpKMkRjeThsam9hTG9w
            MGtJNE1nM3FEUG5VWUNmRnU5Wlc2NlhOdWxrCitFTmpiZDN1Yks2RXJWVDFPMFFw
            SnRSaEQvdGx1ZGFFSitrRjQ5YXNibm8KLS0tIEJacHZWUENzV3Z2Vno4UmxQT0JI
            UGJMKy9xbVpKMERDZHk5ei9ua2ZxcDgKrUA5/MWSvGXcstuyipqevfxv5ZZI0+ud
            9J/d/YZnabK+IBuRanr+KPw9C8zHf3XyCts4zvJ1C3mcyX3IxxChAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:59Z"
    mac: ENC[AES256_GCM,data:gk2iQcYmIysDEKQcMwEo37NJ7kdYERN8bshUWkt+gLGedwvIuMfkvd4lw/Ie/2qsyMpCe5QQprY4FeZn1GIg6ydiLnG0v0RloxdIYWkemH9V2e/UJwWAniiXttHHMEylrnryn61nMRND/Ig1LSkI85TNjL2eu0a5YChRUL0Mnfk=,iv:KN/HBhBA37lw/Nh4DsdNjvDvkVH19FOUYSjw3dJ0sn0=,tag:LlR9SnxdehvtG7LJq/BaXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
