apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: rgw-mirror-s3-credentials
    namespace: backup
stringData:
    RCLONE_CONFIG_MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:CDJO0Rah6EGVw+qF0XIpURo9w4M=,iv:c9smfAl0Vlsz8MNdqp3ES8q7lE9Ih9iAlENrCES1gpU=,tag:+MppA8pqv1QHKxpeXpG3nw==,type:str]
    RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:0SneN5AyYvjmXVbs0ViR1Kt1n88t9yq/Es8NzHupCcIfRDv84Cakrg==,iv:8DNXUr5+QxPiUny3+uTYC1ODJMDtmYDm/zqoPKShwfE=,tag:2JZrX0Nh2oPGtoeSyQFiGQ==,type:str]
    RCLONE_CONFIG_RGW_ACCESS_KEY_ID: ENC[AES256_GCM,data:wLVFBpQMmmeqtAzwbYmrDiol8Kqb/nak,iv:tkkEVlz3ffPmooVHJv69No9iS4BMC+Kk8uApBE5/I/8=,tag:JIWxumwazVW7Qgd7rXqm6A==,type:str]
    RCLONE_CONFIG_RGW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:d/ENUoYCaohWebDJvNbNHk8KsVhon4rqOE+DqvVNYCWDh+BWgQqx2ab6o+E=,iv:P0+XhQ/WE7GqpWm9CRkZCUNqeqZrt2ueRYkC+f3aLbM=,tag:tKl+oCFduCxjaKRfmoTTLA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM0YvYU9xajZmcDdtM3hL
            SzRSK044Q08zUEVURVAxSTlmaDdwelVvU1g0CkJNbjc5UnNSRTRFa2huMzVhTTc3
            RE94eFIvdHRzaE9MaVhNWVg5OGx3R2sKLS0tIHdHYnpQZWRHVUc1MStzMVlyM2w3
            QS96N0NzUXd0dDF6SFhHUWZOMjZlclEKBOJ+XWIn3FKk58FTI57B55Z6y6WKq22n
            jWTKsq44gOGZC0q86EcM4JON1RC87wwjRfa/EKX0djSsYa9TvFDYtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTzlGTE1teThxR01UY2U2
            R1MrbXJhWE5IRWlvM3JWb056eDQrWm9ERjJVClRDV2lGVDV3aHRTRzR0TDlabTl0
            QllQTEd3SzMrR1hHRmpJZlNCUG9EWmsKLS0tIHprV3NSNk85clQ1djF3aGNVLzBV
            blFCcFRDc0N6TGhERTdYL01GSEhla1UKvHxEKlXJ03BbIpPxwWVdakhTulLzF9hW
            tJ57zB6IsWiGfoiDx5yAmzupu0hJeTH0Oqx5OmemEQgj2zLIDCGRVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzJqRHhMUWlxZ1FWNHEx
            b0pRamcycjdURDcrSXA3b3Vha2lFdXR6dnhZCnlZblFwbmMvRVhsWEZvK0pZSTF0
            d25LWWpOVXlYMGZKWHQ3dm0zc3dRWlEKLS0tIE1OT1R3Q29rM0ZRZFBjTTlxdjVi
            WEZNaFpZa29GMHNHTk11dkpQVkNpUWMKblucwBZTBGiLiaqcRZKh1vPyqZp4wZv5
            LqFo7DOkQc8lbudV2nNzJMnAudWdMZ+rCwuVPHLy5sAkeRDHL8EqEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:59Z"
    mac: ENC[AES256_GCM,data:YSZSyLihYnnCvWYGtFUcLfmsa9fcOfH0t1dpsvstD8gfOc6ct/ZptOZOEw7os0DysuQLjoUGwYoxEi5bHJA5EVhF3ild10HcFMYlIwnRqqW6vTLorvw33eayLqfXkHMWCRhy/jNp/GViIgANJOacfbnM8aKiIbfW1ZIL77KBekQ=,iv:nYPMo+ixOA9IiYHXv+xqWTPoTpNfLf7omKz8cotw3uc=,tag:1xkszhXUMgJCWmNjO0LYbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
