apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: rgw-mirror-s3-credentials
    namespace: backup
stringData:
    RCLONE_CONFIG_MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:6uRaG2Cf1smPpz0T3AL4Dc/rs56sA6iFbpdfexThTI05e3iJCEzkcXWx41CLH6o1b3qp2e+41iaN36DabbTF,iv:RF8SY684wPCt6DbEYiAPcF2JyBVw31l7WFR7ekl5mbs=,tag:XJx/P22yTtPbK82UVv2Alg==,type:str]
    RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:T55f8zMdpAluIp80OkPvmgJEmz5xZ+dN3RJ8pOOU/trb/94xQjeSGK3Qqm3WXuzkeG0x8JOik31nauDSCRr7uJJr6w==,iv:0gDPlOqkDfTRoIjuAiXhf2J2TOpqm9VCCOGPEBr8Iac=,tag:19fqnHSEm/VRN1NnZad/Qw==,type:str]
    RCLONE_CONFIG_RGW_ACCESS_KEY_ID: ENC[AES256_GCM,data:0bFGKA2HGIitjKt6zqzXHHNDdQ3ffY5Qj5kaD3rrAaAYnGhg6Q86MdzczkIAjrbQzidBDPaQVGYZlegzmAkeNK95MDhm4w==,iv:HFXVes11DhD+laNxsyjhGNuHo+RcffiFq/nPtHTRgc0=,tag:6Vb1tR9LYtUwRfqqKpKsSg==,type:str]
    RCLONE_CONFIG_RGW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1ZSFWp/3RAzZrIqnk83TjOpi7V7XLwXGVr/766DlkFbkPrsxHkKjoYC77KUFJwPJWd+qxfKU5rV9ysaMqUr7ZI0zwLx9vZcnqAo=,iv:6HQRHt1vA4Yo1rI8Np+S4inJS7TATLG5xvfRtlQkw6A=,tag:SIFrsR3UOHV1KqsHkKDp1A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM3M5MGdRMStyeDBxY1di
            bjdyVmdrSWVqdS83T1FvbFZSeGNwaDNrQ0hvCk1aU09SVFBLc2NpeWx5TXFSamQ1
            d1NGZXZYNVlJVnpiUHRZZlBmL05sK0EKLS0tIHVLcXJtTHlyeXVJVkdGSmpOdity
            LytVM2xZem13VUg0c1RRL2phTHJsa2MKvrB+0gH1baO3Ywb+LDRv+oYfBH67paqr
            xvH4Q38MNBII1PuvrCzyG2KodKsB+IVZNwVh8pc3i3NxePdGZH2oNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKblliMksvaXR5cy9Dc2I2
            bjNNSEFPWmpEMExIR0dtNTd1ZHhjVFVnbEdRClZEZzdWRXErTktObjhPZ0Y0cW1T
            OTJ0aEdnUUlNRkFRZ241VW9rbVVwZWcKLS0tIFRyc2ZkNWNodzI2SjA1cURGZzFk
            UExRYVBIWTUyalR4ZFRJWWdMQmJOUFEKECCQrTzCla/8WGeLDvvMvfYp+zvS7wFb
            AQ0/Kkgq7NuU8Hhuq3a3mh4JY97MFGumIelQ8REnc6zgjyP7LUZEnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUi9NT2pOVHFNWVd4di9N
            UzJwazRqcHV4eVpnckVubzJRc3ZNb3hUS0FRCjRJOHlFeGFzV1dLMVBaNHJ2Y0dJ
            U3EvMHI4Z0t4UmdoaXpGK0RmeHlhaTgKLS0tIFdZQlUyZmlEcTRtTldOWllWQmRD
            NnY5VVdBTUhFdTJhYnZnMG9ybnlNVTgKEClAWaE4bh0RFwy54+YfRvAFb8BMpJud
            Y10KiYU6+li37LTGuW3VlxnQGb0PfII03d62EkEsXtXePRehxd8AgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:02Z"
    mac: ENC[AES256_GCM,data:3u5aCAJQTs7IEU9lA5tSdDBB93tXVYWbGdBnCprvNGy0eqAnVD6sCYiLAJ8N6Dq5ZLtDL/k0C3My8+rhnNzG8h0lNorhwkdGszna8apQQskKG3QJhqzJmsquZ2TF1tCRgAuU8AbvGB1Q3FsXQYvAtDfZsPuvp5Pf60HnLbhl7+o=,iv:Co2ma3PgPDsHK4L7tJwpam8NMbKXT8eSQcfGiDMXi8o=,tag:18U6twW5hZaoC2g8RpTMJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
