apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: rgw-mirror-s3-credentials
  namespace: backup
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURHRmVzJ2dy9xbzJxb3h2
        YW9sUVhaSXRmN2RqTGxoSGdrU3JKZTFKeTFRCnllbGhqaXNoMTNsOVVwaGFQcWUv
        cmJ5amtBQWc1dHRzeG5qck5ZSEpwVTAKLS0tIFYxZUZ2dnJjaHlST0FqNE9uWHk2
        Rkhmdi82b0EwWmRqNml4b0p6dzRPb3cKOfJs+59kfcntzy0rCRuU31BPIgDfbYAv
        8fcZYcowoPf3JQm+HNEb4OJ88Vhr6JXUfEZtp13GY7ce+fQPxa53gg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc1lnQzZvRE15R0dYT2Yw
        VVR2bnpPTWtpN0Z3Z3NXY0l3VXhGRFVnaUFNClJiQTljdS9WMjJKc2VkSlZKVi9s
        YWNEdDJ2UGo0TzlEUmxqWWd4a21PSzgKLS0tIDU0UDV2UG9ra2tGclJmcE45NjZn
        RVh1ZmswYnNIMTRzY3ZnSlhoNG56V0EKv9aWWT3Xn0v3XT2W9PEh3nO39FYLHm4E
        XQuiWGmqsHPXdNpR97M40Wm49Kr/BXK3vFFksCGLbxJPJ66zLf+h6w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdi9RODZrMFFGUXRJWk05
        d0JCdWsxZmNnb3lUWmQyZ0VpVXgvYkk0M0JFCmovUlI2VWNPcnd4UmhRTmg1THdk
        VGIzYmFzcnZmdzd0bExteCtGTzhqdXMKLS0tIDVGRXVrbXNDWCtmbDgzUFUrRWNw
        SEFDKzViaHYyT3JiTkJWYS9vTm0vWEkKuQF/UR9WISgKsY29nGvhkd9xiexqqEF5
        yDQ+B6nKbZoppGPpKuNQBPcadqAb6pnGop9KhrtZ5csvnGtNQnPhxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:56Z"
  mac: ENC[AES256_GCM,data:8/qfQeJzBrTOK16U1qwAXGroTcq/qJkypEx6yMUKbgDIw3xIE+e9WUwPQxojV2dQP2KsQOGb6CnMu88CzRPTeUTgsCvA8YBQOijjHi+Rv252QlUITj1iZcLjZYJBIgFhZFhZKaqp7+Md1dzUVQ4Dwyj+5eTiLlf7SBZIpfusOng=,iv:ghnlEgIQ33uJ86105sTZTlQS/6Zc8ZJUAw4LWlY1XD0=,tag:bulgWWjadc/m2PpilobAqw==,type:str]
  version: 3.10.2
stringData:
  RCLONE_CONFIG_MINIO_ACCESS_KEY_ID: ENC[AES256_GCM,data:8MBVo0Ou4rjSS1y4gUkbTtJXPST41Z6l5G4a0HyZyyDkwiiXfvnnDmUJFjsVNdzajpEFd91xX6M49eWGY8EZ,iv:YIhMZM5aLu9XNQEX3O1F3soy1nZ3yaMqHPElyU4gd5Y=,tag:kkawso3xzdMYMiUR5lQt5w==,type:str]
  RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ox44jtgjfZaHsvA5hOQCXegYvAscQWGI642x2he1n+tmXRlHVlZ0bcuPTYVw/S8LN+wVi34ePQ20JuYSNXufx1csyA==,iv:htd8Xkpjo4Ov9ccR9Nt+jeYVmypDvmwsgqtLN0sDvO0=,tag:E0M3fZjYu8x7FDcMJg2ePA==,type:str]
  RCLONE_CONFIG_RGW_ACCESS_KEY_ID: ENC[AES256_GCM,data:QFbb3umgy4txrttKhVzyxQD3jKaZItybgevBid+mjq6DBRiZpx7aEEfpaRnpbWQjNrwOtDu9+QO3mYLB5W66NLr0YGKSjA==,iv:GNaYygVKMXemaJ/pgVkAZaIox5wKpzw3I9deoxCYiN8=,tag:Xn+KGmLuJNh/0bJ5JAggVg==,type:str]
  RCLONE_CONFIG_RGW_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bQPJQG7KvEOn7uu/OV8LsPIvNZvPWaDba/KW6RUncVjdtr48EfQZB/x4dA/FYYeyahz6P5lfYM0Rih8u8/GHF7LTJSy6/6HVULg=,iv:A/oWzE2bf49cY7FKNxSHCZD3C5FmCpTYxeho1BA4m40=,tag:zPQaZjg7e5cqIGDrfFeaPQ==,type:str]
