apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: shared-subfolders-backup-s3-credentials
  namespace: backup
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYSs3N2FSQTJyZUxCdmJu
        bVp6aTJFbzdTWTlHY1lxZ2lrWlZjWks1SUNRClZyOFZWV1FKNXJ3UHdJWWcxR2pp
        VmdKQklsQjk5ckhkSmlDdDl2b201TkUKLS0tIDJ1S3VVek9mSStUblRGN2UyUU9i
        T0w5Vmdhdm8xeXRkMk5JU1RJbXk1MVEK3RuyTQPJ74+pbb61Z9t0rw6lXRw+RrOn
        uQtyE+d3SqrNpX0a54pOlVLqTFu7QcNbkwEwEFqEXSevctoVRvUkXw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhczd1aFl3c0EyeGs4OTJY
        WWxVSGFSV0xvRkpCRVE2UjQyYUVqaXJ5aUV3CnhaNVZOM1JOU2M4Yk5NLzBJamxH
        enlrSlpNbUZjQ0xna09pQWxucHJvQ2MKLS0tIGFGZkFNTU8wWlQ0Tm53NzhrY2pB
        cUFUUnNPcGlFdmV2TDZXNDBXOUlFdTgKMJCSfuRXe3gTavHA3bAPlKR9ClCz9nP7
        Ds1LdhM4btMJFvCq5reQ5XOfgWZqb/ACK3z1IKv6vWJ/lfrg6YD9Ww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWWtQWWk3a2JqYytlc3BW
        djZobnJTcU5uc1RTUHRaQUd1UEZuRG15OUE0CmFJbDhoUGlObzVaSW8zNzZvSXVh
        WnFGT2JGaE94SVBwNWMrWVJlaTIzZmsKLS0tIGdwSEcwYytGQ0doYWZiN2FnY2ty
        clNWakYzdmFRWFI3eEs0R0tmNEwraEUK+7cXHIR0Qzqgpkd0ctFo43dxoyk2rcJH
        cgctlFFpn1cvF/vstZ/4rtF9galOR7uj/EBLA/cOTZSL9j4pGoIqQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:56Z"
  mac: ENC[AES256_GCM,data:abmZhl2v4cCbXl2ZWNGMErfuz3YUcgNjd7IMDz1vJ6Ns0DGPHlcxLgtVuu2VXdG5hflDvcR5TpfE9fvVJP0rUZGlBMcLZO11eNBqFo+BTa4MbUH9DackeSnZrAe1rcAp/PqG/JoirN+DAH2il3jyHIqedqyNfeopJSvPMyEGif4=,iv:gnM5aI8s7KJE61FXb/xZm0aheumzyyQJnVtH4WpcNZY=,tag:fDTBGL2Znb66oV+EUSae7w==,type:str]
  version: 3.10.2
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iW6ZETC3ExrKJV1yfLR3OWtJypga6bx3g+gb4xO1Yn64mA6nBUHiFHaVCGxLQKh991jk0bCCA0LVlzgCS90U1WxOGKZ/93cKEQ==,iv:FxtfQXYfK7Xf8aSRmg6FXG819Ohn6seCSIdbsDQOKDI=,tag:tFZE2w/qn5J/zY2xaIjR3A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yLEAP++S9LAc98lM15/np6LpuqOyEIsXDH2YV9VEaJ2oPSAWT5vyFMvlaHtbqxFpwuavCQoa/zUM7rECrcqJjHAKPAULea6cyWxAq8w=,iv:mmnoIiuuEfmud0daziWEIgZKmfwkreZGh0L/cU3Uo24=,tag:L0NqGy0oh1tTWUWyPMu5BQ==,type:str]
