apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: shared-subfolders-backup-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:z9RmAw0LY1PUdUHg05Q7Sxc=,iv:OLy/uGBs5crDjY7ka78O3UWfGJ1Shi7t2z7kfFuw5dQ=,tag:BKhGe+1Lrp+KUtifV2YSkQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZHRwXHSLCi3aPiG4dpdyKPB5a4pz8WQSCxwvjvexJ/I3MM+7BECZscU8yrGvbSeJsgcgWltouDleXP8iinyJRw==,iv:BYPBqEqCinErey/nAJrppKNHz9RzNj5R7Rd8mAZPuRs=,tag:aXaV01ygfARY4+wJOzc68g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eXpzNFpDdUpDeXVYRjlH
            eUVkUlZ2ZHhyRXFzTXQ2TTdxRzFnQk9yYVhjCjNpa3k5clhmQ3VseU9kZ0JURjAw
            Q3NIdHdwSkovNzlwbUkvU3M2VHBiY1UKLS0tIEpQWXlhbGlqYWpWMUc1MTlhRVpl
            c0l3SG9OT3VCU0phK2RUblEzUDZncG8K+6ZAiFWppmX1FsghITFR8jkZXAyf4Mnj
            jPvYy5xvujK6pguZe/sBsABKXM+wXyBXJbHim33TK5ZYErcgVmCiag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNkJDajdwTzlKQ1h5OS9C
            ZE1sS21yOWhWYnp4cWl3T0gzbkFPNzc0bDNJCnR0ZmFlWE41TEw5ZnlOdUZYejNO
            eG50cHlPV3YrTEpwTXdRcHZOMXlmWlEKLS0tIEZ4MTRpZzlDd1BsS3BreGhnY0JT
            bklYMmFmeVp1Qm1raXBETG1LZFFjeXMKwaXAiXLwklomHFRQEKSBdMqQzyicXAqX
            5Qi+TGANql8AFKcIjViE1BIoCYneHrqhmE8ZoEOICbZXncteN03Z+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXSW9qTjBOeklBMTE5MkdX
            aHJGVGZwVGJFbFBPUnlsRy9KRmFMb2FQc0ZRCjNzZFdYU3BJbWsybkhvcXJNdlEy
            dkc2TVoyK1VPUzV2L2NhQ1VlNlp4K3MKLS0tIGJ6M0NpaUFnWkQ3Vmt2cWlZa1lG
            dlB0dFp1d3dONlBCTElHeFM1Mm5Jb0kKDpWHFYJcw2mqb3+FIciy0N40nf41Dn9v
            KJBK9undWRiU5Gi7oB2O/Pb7UOgpAMvh9hghZsYZvzvOQK2rWueBng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:34Z"
    mac: ENC[AES256_GCM,data:Il1KU5xFqevgJ+sPMOc5FC7lTlAF5deGU1IThkrHJovpQh7wV9ovpkpfVkjYdau9onvEFaXlduDgTFEu8MNBYLnZdDCcGUs6T8brg8G5PS7sEqyEhBiKelyE+Z2uWo8j09oGAQSREERrxZD1Dcwy2NtcQ2TI+BUb/Om8BiIX1Do=,iv:OaWxZ6DdFeeLUKg2o5rhGmZ56zOt01rq7rO1xAABUao=,tag:BOjHc+TdHV9AcSaMMUxABA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
