apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: shared-subfolders-backup-s3-credentials
    namespace: backup
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:O6vQZ2XdnVGil6XBz2rj7/4=,iv:lTUyx64aWmVb1HPhCoKG2r2ldF7noIFkuJJAiLZSx3E=,tag:lXnMOPYhc9jA6oNrt3MzAg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rrDigIRFlcWw2APtgabYlOweR0rGyWRKE+6YI5PQem1Ipj0NIJwXmiPtRyvJcCw8tnCYpeF4iU33ot1IVtpwxg==,iv:ABandYbGQd6pWnNExVfuCfFFAa23/oUYlow/YwNBFfY=,tag:Ah/D2Q0lb03w5nr80BncNA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJV1Y5Ums4a042WEk5cE1G
            Qm1SdzN3V0VudC9zWHBtby80R1N0NXl6ZmpZCi9GVHRvUmg0Rk5IakNKMzlnN0dG
            N1ZUcWpDZzlZVnFDZnhabmQyV093SEkKLS0tIEVLL1l4bWx4ZUdXcks0ZGU2T3cz
            cWdrVS8zWlNWLy9maC9KZW1leGJwL0UKLMM3wNu5yL5xXjD9FixF2eQ3Dd5NELuS
            LnwLhwbKK/BlXEtxyWLxrbPvqrCGJkoNY7K9KBlQj6ypLML3OqXKfQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN1BwR0xFTmNTQ1VWem9W
            WnRmbm5CRVhXOW9ScEU1d0RRN0pqY0lGUHlFCjhIRmpveis5a1h1U2UyVTNsQVpD
            MjI2eGVWYTZOOG0zQWRvNm95TTI4UE0KLS0tIGxRZXA3bkFreHM4UktLTWxXU0pu
            ajRnczZzaDZSVWIvck9xMHBZSUhVbDgKVtLHCi463PGjFDQ928hQ0ARr0fcyNq5u
            YsYHhyb0AXn31LLirYyaMphIcjZlrQe1AZ/YZAlnQmzDM6Sg5kZEUw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTFpVZXo3VVFsQjlkZXV1
            RXJ5OTFxV2ZadURHNmIwaWlOWXJjdGY2K0EwCnR4VDdDKzByczRDdHY0b3J5QnFM
            TytCN3RqS1B6REJLUit4SXRZWDUzMWMKLS0tIEZNcXgrSm1pOG41am1NWGRrS083
            TytwMmFQNkl0cU9vbHB6Y0dCTEhmcXMKThZytxIM64BICsBo1yvnfplsjysSjpA+
            0EERHm8XoaBS1PH+E3ICCNZGC6JSC0a8NsdHT9JlOYEHQhpnVYEwyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:58Z"
    mac: ENC[AES256_GCM,data:rufCn+qwjwi3jxWy9fEE5m6vfMSEuJ98HCg0aXaB7TKAKDI2uo9LR27OM597Le2R+V0kvU+RHS95q+IszJl+BYReRBPCTH55HKgR9jJGw4z+h2+pxtM6t3vyMfFqV38F7359IGfnRsUJAxFr47Tdu4/ehHn8DQcHuA3Gy/u7zh0=,iv:51Le9a3bTnNgH6ElzaKLMGtscTtXvlL45IR6XE+9yHc=,tag:Fe5bWUxqZIpi0ecI7AavtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
