apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: shared-subfolders-proton-sync-config
    namespace: backup
stringData:
    ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:JxUauoPmqiHx7BbXxW+voDIRlOamCK/VzSgaOqH50/4=,iv:WgHyKVq7wOuBo3b84E7j5SyNSGbof+yowQ5iEl3/IK0=,tag:6idglLm6uSyvqw/eJdRofw==,type:str]
    PROTON_PASSWORD: ENC[AES256_GCM,data:UQfP4ESog/1Zi0I8Pa8UZg==,iv:tX/BRdcAWSmu39N6HoPRcZjC2gyPXn3/jzLzMeqsfHM=,tag:7vMSIbhgPPMUZUB6AJ9gJg==,type:str]
    PROTON_USERNAME: ENC[AES256_GCM,data:2kL6xyajPpGTSTLtrW2Wjvky,iv:oaA6rL0ZZevaI1f4sc7qsY+U0Lvo1sv97JMBBmBwUWA=,tag:O7NruYcRK26MEZoqNoH1Bw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWHJWZklrL2ovbk1uUVBh
            ZzJ6ODhrUkhKb29CUWZPbVgwbmFVeGE2Y21jCnc2bmMrMmhraVMvcVFPMzVMZG5w
            eXorZUdqaEc0b0hsejQ2T2VMZEpnc3cKLS0tIHdLOTl4ZGRBTlRQYjFuc0p6cG93
            dWtqN28ya0t6WksvMnVBWkMreWErbW8K1lGBNcFNh41vzgKCOHEbwQ0yhG0oGXMo
            bsDyWLyCXfN0kwxDQy1vU96IW/ZBN0N3SiljLfcYlULp7tUxv/8J4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZjhoOU45cXpCeXB5blE5
            WTNZMDlhYmpxTkZyckgvRW5YR0NTOVpzMEJRCnIzekk1YThtYS9Xc2FmdnkwRlhw
            MWZQaWRsMDZHZ3VjWmlZbUJkWldDSmcKLS0tIDlRcHFJT0d4NHdvUkswWVpZQ3Vw
            dW5NMzczU0FYNHRsWkk1TDBNUHBzdzgK4PSGwkEFrzBEP3346BMs+v6t0x8yEa1f
            KzY4STyXhvM4vFYIiaglSTJUP2pv0EJJ6y1ybgIkXG3ibetoB/JtmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WW1hSk5wZ1g4M2dRWTkr
            MXFVbDYvY2h1TEgrVWMydnMzSjI5cmUvMkRRCjZpYWRLaTFhRFVKalNmdlhvbHdF
            RE4rcVZvRXllZ0kzaWVIR2J2bnk1Z3MKLS0tIGVyWXZHdCtyUW1RWCs3RUR0bGNH
            S2tLa2QvNTc4K3hZTnBRcVRCYm04UVkK1f1FT4Z0w8gb7zBYICq6ExUomX5tfAAP
            Y97OjJ9s+EFpwn/DAd0Fk5wYlXJvSt6C8fz+kA5TdoLfigdXxU5YkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-08T01:48:25Z"
    mac: ENC[AES256_GCM,data:FuxT/+xWcpbZrM2dFhg4XbflAI5IJIK7eWMN9d7e/z8Y/lx0u5IgaajFCh1yx0CoBH2PAkJGTUq0iaSabaH29rI0034jBNajeW6i0MpijCLPr5IplZZ5NL3ONeUv3+Ni4heF1EA9fHExyDYsS7LhUM3gat+magYfAAMAlOcsOUU=,iv:vjpWXXP7xvNJVxZhrbMcjrdSNcKFcielYKTMHw20v8E=,tag:rQZygwglcP1W2DFKPL6PRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
