apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: velero-s3-credentials
    namespace: backup
stringData:
    cloud: ENC[AES256_GCM,data:7s1mP1sYRMcnbJXVAuCgTBOCOpR/7XN+Q1rL400KPVL9M9cfftX4jHLPR0nDZqzdxRb9TAUt2idsmPiYSuE3nROeSxopVrLSe6u19UwKb8BFqT7jepF3TqncO6m1DOvRv2nWyDyZ8+m/6Zso10Tqdg==,iv:mhzyk9/69Rpr0Qbhg6CZH/rAdHWI/2N0ttGdq/+5HCE=,tag:PmsmLnlbMz/6uOYQOPOceg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQUhBTm9ZQWwvNVVteVFL
            aGJJa2ZnTm55OHozQ3JIM3djcEJoV1BkckQ0CnI2U2hSY0pJR0NaSldoUW9IZHgw
            bFh1Rmc0MkpCcU1wVFRJRzlEZEpUVGcKLS0tIEtKZmRMTXAwS2l6OW15eWEyaUN4
            VHNVdnNpYVlWUmNiMnVsaktXYUZEcEkKt/9myNzEtmalBvy0cXJtEjrj/9ZPkRaS
            6j4gk6C34pNCf09DXXFR1fxgli/y7eicmzL0UqJJcS9E+fzZhjZP7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TzA1RWloRllBVDVJVXM3
            VnpMRGVYSjRWdm1jMGppUE8vK2o0Qkd4Y0I0CitPSm5BNGNPZ3ZRanh1RGZEMENU
            akVmWUhZeStya0FId2xQU3R3Q1VrYzgKLS0tIGd6c3pSbEVGVTJiNkpRc3N4djlo
            VHBVL1B5SHdldXJPYVc0MlNNMTYySlEKFf9Zks9MeCle20Rg/Lz+3e8X+AtvobHW
            DsvCEMqZgkohbxwCJVOEiCmdOi151sjgDYqgWVviCwaN8n1MVsS9ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcjA5OTl1NG5kUnZMdUN4
            V1prQ0ZpOWxza1JTL3FGd2hwWHAyMVJ0LzNjCmQ2ejFTWW1qT0hLUkVSQStPNmF2
            QXpXZjVIa2NwMXhKZjBka01NazEvbjgKLS0tIDNrRWpoNXNUOUswdnR4TzQzb0ZV
            M1hvYnBUSG82RG1yZWp4akRYOU9xTGMKQT3UQLt7lwhDDlNu1yKPapg6Cu18qaYA
            41eYjQjN9Kf1cUYT8kLCJKQChOAHvlRQgnhLTagIJ2IPZxqGLQPYtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:34Z"
    mac: ENC[AES256_GCM,data:7DpXvuLd5HRSzVBMqffPcUSKOsmSAli7n1hjMhGVK44Rl22q8MePAlZSukkQe5UgaqpS3z3DSJp48h8IAaQNv7BhOoFoUeOU1KLaJTv881MdkxaP4035i2TN75yFK8+UJnGu2N8kUvzeh97ywa3hMpzT/LlmKrby6nqKKlHZ4tE=,iv:ecQl72DQ3RiKQML7qo0ej3SC7FKd8VLy3Xe69j2C8fI=,tag:OX2Wq9DLj7hsczdbnacH2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
