apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: velero-s3-credentials
    namespace: backup
stringData:
    cloud: ENC[AES256_GCM,data:X/rOsSEUftvtkH4VBfkhVauQ2XcFCWI5kqlpq3fZ/W737xiVFZNARrn7G6GZP+SI9e70i4TEFnlJxrDKbUvj14DiBQg5yg1SfjvAc7J7kbNS02gvD82snLYt/wYmJUKGGMRqGmQZaN09tlJd2+l5nA==,iv:dtkR/t2YHz92pAabXjf5m4u2OKoR1CQVuJU7xbpo9/E=,tag:li/cZSXkQbNk4TutEB1z2Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UEI4cWIxd3FSNjBoOTNY
            OVVEN0FIUElPcjRVQkpGNDZ0VXc1aWUxTnowCnZwRFRTT216VFFhWW9FS21vQkR0
            cUVsZU94UStGVi9LclBRWDJLSGlEZW8KLS0tIGpPdDRiMkozcGozcU85UitsWWR4
            SUpTcWpwakRSSXdiQnhhMzhmQ0locmsKL3zF0fRycrAADb3mbytS9Jp/kbZQZiCb
            8tRFc5JrW6dxwDpjYYViJv1C7KgjuT5HfAheBOBNYwQ+oxEb4jvDIA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaUpJUzYwWWtyblp3ckxI
            ODJuc21zMUhaMzNNMTRGckwrc0hxNE83UGhFCmlIMGR4ZFhUelIrTlpHaE1SNlFB
            L2tiR2RkMG4xbk1wQUpBSTF3TW1rWFEKLS0tIEJSMWJlSkh3RDh6WGhOdDE0OC9X
            WVV6Yk5INHFBT3JSU1NURG4vekRIQm8KuKaoKG/F0/xpABerEoAWYav0aGT3rBM0
            zn07Kg//X/RCZoDa6ZpHlXgUJAS4rzEvSorMf7ijAMd3Jwo6XC9h2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UmVucUJkc0tYeGlmaUY4
            K3dUOUJGbEp4d21wWVdzZkV2amU3VzJwRGdRClhuLzl3RDgxL3ZHM3RvQjhYUnFX
            MG4xSmhKdlNQTWZUN0dYWXdvclI0SW8KLS0tIGgvamZrNjlzQ3RmVXlrMXZWMnJQ
            SlZRMEcxZVM4Qlg1NzZ0QTJseDJNUzQKNpQhuTSw2UltFdaigUy5EN1YbVPxpG+8
            mZ0kD9TpwyMt3VmIxw7iT3SNzGdY2y1eqNFPGgE9PorBWBTvXk1mtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:25:01Z"
    mac: ENC[AES256_GCM,data:5t3us5T4gxJ/zkY/A1ArKp6q/Cp0GFe3rmXZKx/VI/2R748S/sInOGtOXFhm80Icqiono7xocQercTCZtF4p50Q1LtQcMTTyP6jzb9lowEiLirDyV8WBIW6DgQMRr1mhuPgRs7MPS7H5zuQyzVCiI4Xm+r8P138SXL5GA1B/jJU=,iv:QRletPagTlRa9XtinZxe6DtNrUknu6bSJrnd/NfKYWI=,tag:Sb5A/Kl1lkF0EYRivnjqIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
