releases:
  - name: ingress-nginx
    namespace: {{ .Values.namespaces.ingress | default "ingress" }}
    chart: ingress-nginx/ingress-nginx
    version: {{ .Values.versions.ingress_nginx }}
    values:
      - controller:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/allow-shared-ip: ingress-nginx
            loadBalancerIP: {{ .Values.load_balancer.addresses.ingress }}
            externalTrafficPolicy: Local
