namespaces:
  services: self-hosted
  monitoring: monitoring
  metallb: metallb-system
  ingress: ingress
  cert-manager: cert-manager

dns:
  hosts:
    proxmox_pve1:
      domain: "pve1.proxmox.local"
      address: "10.10.10.200"
    proxmox_pve2:
      domain: "pve2.proxmox.local"
      address: "10.10.10.201"
    proxmox_pve3:
      domain: "pve3.proxmox.local"
      address: "10.10.10.202"
    
nodes:
  main:
    hostname: homeserver.k8s.main
  child_01:
    hostname: homeserver.k8s.child.01
  child_02:
    hostname: homeserver.k8s.child.02
  child_03:
    hostname: homeserver.k8s.child.03
  child_04:
    hostname: homeserver.k8s.child.04
  child_05:
    hostname: homeserver.k8s.child.05
  child_06:
    hostname: homeserver.k8s.child.06
  gpu:
    hostname: homeserver.k8s.child.06

load_balancer:
  addresses:
    ranges:
      - 10.10.10.100-10.10.10.199
    ingress: 10.10.10.110
    services:
      pihole: 10.10.10.100
      proxmox: 10.10.10.200
      grafana: 10.10.10.190
      readarr: 10.10.10.199
      postgresql: 10.10.10.101
      linkwarden: 10.10.10.103
      rabbitmq: 10.10.10.150
      frigate: 10.10.10.130
      home-assistant: 10.10.10.102
      sftpgo: 10.10.10.115
      sftpgoapi: 10.10.10.115
      readeck: 10.10.10.111
      ntfy: 10.10.10.114
      alarm-server: 10.10.10.155
      libebooker: 10.10.10.123
      status: 10.10.10.122
      qbittorrent: 10.10.10.119
      prowlarr: 10.10.10.120
      dashy: 10.10.10.124
      homepage: 10.10.10.125
      glance: 10.10.10.127

storages:
  local:
    path: /mnt/shared_storage_1
    capacity: 500Gi
