{
 "title": "Kubernetes/Tanzu/Velero",
 "description": "Velero Stats maintained by Velero team",
 "tags": [ "velero" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   },
   {
    "name": "csi_backup_name",
    "query": {
     "query": "label_values(velero_csi_snapshot_attempt_total, backupName)"
    }
   },
   {
    "name": "restic_node",
    "query": {
     "query": "label_values(restic_pod_volume_backup_enqueue_count, node)"
    }
   },
   {
    "name": "restic_backup_name",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, backupName)"
    }
   },
   {
    "name": "restic_operation",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, operation)"
    }
   },
   {
    "name": "restic_pvb_name",
    "query": {
     "query": "label_values(restic_restic_operation_latency_seconds_gauge, pod_volume_backup)"
    }
   },
   {
    "name": "fsb_node",
    "query": {
     "query": "label_values(podVolume_pod_volume_backup_enqueue_count, node)"
    }
   },
   {
    "name": "fsb_backup_name",
    "query": {
     "query": "label_values(podVolume_pod_volume_operation_latency_seconds_gauge, backupName)"
    }
   },
   {
    "name": "fsb_operation",
    "query": {
     "query": "label_values(podVolume_pod_volume_operation_latency_seconds_gauge, operation)"
    }
   },
   {
    "name": "fsb_pvb_name",
    "query": {
     "query": "label_values(podVolume_pod_volume_operation_latency_seconds_gauge, pod_volume_backup)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Total",
   "type": "stat",
   "description": "The sum of one-off backup and schedule backup success total ",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_total" }
   ]
  },
  {
   "title": "Backup Last Status",
   "type": "stat",
   "description": "The last status of the backup. A value of 1 indicates success, while a value of 0 indicates failure.",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_last_status" }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Volume snapshot Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}) / sum(velero_volume_snapshot_attempt_total{schedule=~\"$schedule\"})\n"
    }
   ]
  },
  {
   "title": "Backup Deletion Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_deletion_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_deletion_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table-old",
   "description": "for schedule backup use only",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Backup per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_backup_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup success"
    },
    {
     "expr": "round(sum(increase(velero_backup_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "round(sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup deletion failure"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_total{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items total"
    },
    {
     "expr": "sum(avg_over_time(velero_backup_items_errors{schedule=~\"$schedule\"}[1h]))",
     "legendFormat": "Backup items errors_total"
    },
    {
     "expr": "round(sum(increase(velero_backup_validation_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup validation failure"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_volume_snapshot_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup volume snapshot failure"
    },
    {
     "expr": "round(sum(increase(velero_backup_warning_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Backup warning"
    }
   ]
  },
  {
   "title": "Backup time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\",le!=\"+Inf\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(velero_backup_tarball_size_bytes{schedule=~\"$schedule\"}[15m]))",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Restore Total",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_restore_total" }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_restore_success_total{schedule=~\"$schedule\"}) / sum(velero_restore_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Restore per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_restore_success_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore success"
    },
    {
     "expr": "round(sum(increase(velero_restore_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_validation_failed_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore validation failure"
    },
    {
     "expr": "round(sum(increase(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
     "legendFormat": "Restore partial failure"
    }
   ]
  },
  { "title": "CSI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CSI per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(velero_csi_snapshot_attempt_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot attempt"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_success_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot success"
    },
    {
     "expr": "round(sum(increase(velero_csi_snapshot_failure_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
     "legendFormat": "CSI Snapshot failure"
    }
   ]
  },
  { "title": "Restic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Restic Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(restic_pod_volume_backup_dequeue_count{node=~\"$restic_node\"}) / sum(restic_pod_volume_backup_enqueue_count{node=~\"$restic_node\"})"
    }
   ]
  },
  {
   "title": "Restic per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(restic_pod_volume_backup_enqueue_count{node=~\"$restic_node\"}[1h])))",
     "legendFormat": "Restic enqueue"
    },
    {
     "expr": "round(sum(increase(restic_pod_volume_backup_dequeue_count{node=~\"$restic_node\"}[1h])))",
     "legendFormat": "Restic dequeue"
    }
   ]
  },
  {
   "title": "Restic time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(restic_restic_operation_latency_seconds_gauge{backupName=~\"$restic_backup_name\", node=~\"$restic_node\", operation=~\"$restic_operation\", pod_volume_backup=~\"$restic_pvb_name\"}[15m]))",
     "legendFormat": "Avg over time"
    }
   ]
  },
  {
   "title": "File System Backup(for v1.10 and later)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }
  },
  {
   "title": "FSB Success Rate",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(podVolume_pod_volume_backup_dequeue_count{node=~\"$fsb_node\"}) / sum(podVolume_pod_volume_backup_enqueue_count{node=~\"$fsb_node\"})"
    }
   ]
  },
  {
   "title": "FSB per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(podVolume_pod_volume_backup_enqueue_count{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "FSB enqueue"
    },
    {
     "expr": "round(sum(increase(podVolume_pod_volume_backup_dequeue_count{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "FSB dequeue"
    }
   ]
  },
  {
   "title": "FSB time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(podVolume_pod_volume_operation_latency_seconds_gauge{backupName=~\"$fsb_backup_name\", node=~\"$fsb_node\", operation=~\"$fsb_operation\", pod_volume_backup=~\"$fsb_pvb_name\"}[15m]))",
     "legendFormat": "Avg over time"
    }
   ]
  },
  { "title": "Data Mover", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "CSI Snapshot Data Mover per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(podVolume_data_upload_success_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data upload success"
    },
    {
     "expr": "round(sum(increase(podVolume_data_upload_failure_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data upload failure"
    },
    {
     "expr": "round(sum(increase(podVolume_data_upload_cancel_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data upload cancel"
    },
    {
     "expr": "round(sum(increase(podVolume_data_download_success_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data download success"
    },
    {
     "expr": "round(sum(increase(podVolume_data_download_failure_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data download failure"
    },
    {
     "expr": "round(sum(increase(podVolume_data_upload_cancel_total{node=~\"$fsb_node\"}[1h])))",
     "legendFormat": "Data download cancel"
    }
   ]
  }
 ]
}
{
 "title": "MinIO Dashboard",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Open FDs ",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "expr": "minio_node_go_routine_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool: {{pool}} Set: {{set}}"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "S3 API Ingress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Egress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Heal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_heal_time_last_activity_nano_seconds{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Scan",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Online Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Read Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Write Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Healing Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Status"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Internode Traffic",
   "type": "timeseries",
   "description": "Total number of bytes received and sent on MinIO cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{server}}]"
    },
    {
     "expr": "rate(minio_inter_node_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "graph",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_kms_uptime{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Request 4xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_error{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Online(1)/Offline(0)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "yaxes": [
    { "format": "bool_on_off" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_kms_online{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Request 5xx Error Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_failure{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Request Success Rate ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_cluster_kms_request_success{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Started",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_started{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  }
 ]
}
{
 "title": "Shared Subfolders Backup",
 "tags": [
  "backup",
  "shared",
  "minio",
  "proton"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "MinIO Backup Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_cronjob_status_last_successful_time{namespace=\"apps\", cronjob=\"shared-subfolders-backup\"}"
    }
   ]
  },
  {
   "title": "Proton Sync Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_cronjob_status_last_successful_time{namespace=\"apps\", cronjob=\"shared-subfolders-proton-sync\"}"
    }
   ]
  },
  {
   "title": "Backup Bucket Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_bucket_usage_total_bytes{bucket=\"homelab-backup-shared\"}",
     "legendFormat": "Bucket Size"
    }
   ]
  },
  {
   "title": "Backup Job Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "time() - kube_cronjob_status_last_successful_time{namespace=\"apps\", cronjob=\"shared-subfolders-backup\"}"
    }
   ]
  }
 ]
}