apiVersion: v1
data:
  notification-policies.yaml: |
    apiVersion: 1
    policies:
    - group_by:
      - alertname
      - namespace
      - severity
      group_interval: 5m
      group_wait: 30s
      orgId: 1
      receiver: Matrix
      repeat_interval: 4h
      routes:
      - continue: false
        matchers: []
        receiver: Matrix
kind: ConfigMap
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  labels:
    grafana_alert: "1"
    kubenix/hash: 0487333a7bbcb2150e24f534fd46e3e6076371d9
  name: grafana-alerting-notification-policies
  namespace: monitoring
