apiVersion: v1
data:
    contactpoints.yaml: ENC[AES256_GCM,data:nPmxjY19ABNCLowqMaWBMHNPFrnY2e840MTjd62aElYxWzMBTENuMWzsmAUjup3Z7JaXfDoIHMvthrzavuqLE1ixq2IVP57drdrNWEXKDtBEy4d6a0aUt2gP4Bh36sfB5+cY+k0NIb5EsrZhkd1xzGBbMbjCX4woGZG9ivZycusQikd+gZDuJqVU8g9BElapUF2ZUX29mHeJqq291IkouKM1CtFOqAIhHnDU491+n5jDFdL90bgT9BDD/o/BuIwP94Xu63D/iQorHr80gWSS4OKQ+HkbyZPiHPItfvnp7AIfMTdLYfPKsahK8jVkAo/bzxx1RBap7CYS8CDlygqgySTHG3l/4tMseJyZKbkb/942LRU95JnPksoS3GioqjJDs6+zmGxYaAbdRE/Xx8FamWA6ErLfwqyA23hAwdgarl+USFSvggcK/fcrQqbuQwRYERI/hVbfj3LwV/fo1m0GO8fkIr7iN0MH8rP7o+knq4Bm+6SYrl/2G8WkSMjDynVM7Vlgp79H1VyKsa8/HNyY8NxcQvZtY5q15FY4Tu0Ilf/wPU+HlWqRpaDEe9rf8fJkKedwl5vuEpWPupdWDhvLdgLddm3rlI+doIAzkqk5pVk1+eYXd7DSk43Ngx7hxaqEB2O4GApOr9LxNNm4c7ZChG9fEw24kVI=,iv:NvT/u2VQMUQK4eWTVNPJwBJSX3F0Dk0Es1ve7FZoKRU=,tag:Bc1Gp8M6xztflhD5gtzMaA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_alert: "1"
    name: grafana-alerting-contactpoints
    namespace: monitoring
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSnA2M2treWdiSmc4TTJZ
            RnkyWVhoUjBXSm5NV3RYaHZVdlRuazI0c1VNCit3WjJOOWxTQzlBUnFvWnR5MHAr
            MXREVWYrUnVnTlVlUWhydVFYT1hjWG8KLS0tIDhTSTkyMUJ4bURQVGhjeGR5SzYv
            UzN0d1NLR1hTL055cEdyMmZza2d3bmMKOAyafTp/S+7oUXaz15eqdX2hid2ziHkx
            07GoSUDY75kd1y5T1iFtlN/HZiCTM4OTVBBTY9HUwgMWMomK3p2JVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSTVYcWo1V0VMQUJmSUkr
            Q0NUTVd6VGQrcTN0aHNWTnJnV0htWUtCY2h3CkI3dWx4UEd2bW8vQlpDMVBSUS8z
            VkdlbThzaDM0cWN4T3U4bW8yV3ZsZlkKLS0tIHRmcUJrZ1FmNlNLWUdjaUdDZ0Vr
            bDVJbnpZTUZjd005c01TRExOc0NPQjQKgYTTfRKVAA9J6/w3c2fvCKIkNOOwnOnq
            /54BkKoQiE7QBUpbaWOMVHFM+GyMkMV4I0Hkf/+4w2edU0rb771YHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlhDTnJhdklXa2NwMDU3
            dlltKzJRc3RndnNNMjRzWThzZnF6L2Q2TkJvCkt3QkJqSm1TM2QvS3lWL3J4UXlm
            WnpFRlcrM0s4cTVHa1VxMkFkVFg5V2sKLS0tIGhPbGEyUjF2YjRaQkVubEd1S2NV
            K042Q204Und2ZUxhb2ovWjVqbVNYc2MK0TCkWWKZ8wDe5q994ejdiCVhE3zqF5RC
            AwJrgCqSMVt0JYN7riH1EOBaTyOIPDzKZTK3mH7cwEqkNLsiNFHCLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T17:46:52Z"
    mac: ENC[AES256_GCM,data:RAiQwFfNMgaNULmOBpQ/bf6Ct+ct4VV8XBefGxRCTDhxqTlblP0AJQZyZ2DkOlegcsalfSMssgjSXAYxnxZpQr793zo0pAVrI/2o7qzgt7WXYKvCPa9GiLVCSNSC0LTx8JDDAmYDpFwUMSin/82+ExtBoIikwCQOFszVG/r2zcE=,iv:md6iy5MafuLeZIN62lzbbLuq/imBAzNh46dX/ug8ENI=,tag:j7krPVc7p6jeCJBJyrKlBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:OUwSOW7LB7wSmHCQFcbYGg==,iv:YOeg8wag5CNzRIvSND7CEKyYfF4514DWLyJJNX/H88Y=,tag:sY/5YYoE2LQX8B++c8gNkw==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:a1kCUp3ivRwzcxZ6agRX4Q==,iv:6O7bosgqFlfbSSVuYGOy1tD4GNQbufiWsH5ylnRq4hQ=,tag:gV9FVrNBOv7AtATCIjEnIw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:DyoicTBjufvFcyO6J/CPOMTXidhfHiyRJ0kXdtGR4Ws=,iv:F7v0mHjeQOpYks5GwoP205WG+fe6z1lgNrPhrHqjuS4=,tag:gJSyIOQRkmnrzbVPirz/QQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:CTQSPxrNfquWCySFHwceU27oNg==,iv:axUBbwrgAGk17u6gDOkVnmugSdN5uQ8kBZirEeZGTvo=,tag:jpFHd9gcisgKQUhFqbHVqA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSnA2M2treWdiSmc4TTJZ
            RnkyWVhoUjBXSm5NV3RYaHZVdlRuazI0c1VNCit3WjJOOWxTQzlBUnFvWnR5MHAr
            MXREVWYrUnVnTlVlUWhydVFYT1hjWG8KLS0tIDhTSTkyMUJ4bURQVGhjeGR5SzYv
            UzN0d1NLR1hTL055cEdyMmZza2d3bmMKOAyafTp/S+7oUXaz15eqdX2hid2ziHkx
            07GoSUDY75kd1y5T1iFtlN/HZiCTM4OTVBBTY9HUwgMWMomK3p2JVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSTVYcWo1V0VMQUJmSUkr
            Q0NUTVd6VGQrcTN0aHNWTnJnV0htWUtCY2h3CkI3dWx4UEd2bW8vQlpDMVBSUS8z
            VkdlbThzaDM0cWN4T3U4bW8yV3ZsZlkKLS0tIHRmcUJrZ1FmNlNLWUdjaUdDZ0Vr
            bDVJbnpZTUZjd005c01TRExOc0NPQjQKgYTTfRKVAA9J6/w3c2fvCKIkNOOwnOnq
            /54BkKoQiE7QBUpbaWOMVHFM+GyMkMV4I0Hkf/+4w2edU0rb771YHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQlhDTnJhdklXa2NwMDU3
            dlltKzJRc3RndnNNMjRzWThzZnF6L2Q2TkJvCkt3QkJqSm1TM2QvS3lWL3J4UXlm
            WnpFRlcrM0s4cTVHa1VxMkFkVFg5V2sKLS0tIGhPbGEyUjF2YjRaQkVubEd1S2NV
            K042Q204Und2ZUxhb2ovWjVqbVNYc2MK0TCkWWKZ8wDe5q994ejdiCVhE3zqF5RC
            AwJrgCqSMVt0JYN7riH1EOBaTyOIPDzKZTK3mH7cwEqkNLsiNFHCLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T17:46:52Z"
    mac: ENC[AES256_GCM,data:RAiQwFfNMgaNULmOBpQ/bf6Ct+ct4VV8XBefGxRCTDhxqTlblP0AJQZyZ2DkOlegcsalfSMssgjSXAYxnxZpQr793zo0pAVrI/2o7qzgt7WXYKvCPa9GiLVCSNSC0LTx8JDDAmYDpFwUMSin/82+ExtBoIikwCQOFszVG/r2zcE=,iv:md6iy5MafuLeZIN62lzbbLuq/imBAzNh46dX/ug8ENI=,tag:j7krPVc7p6jeCJBJyrKlBg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
