apiVersion: v1
data:
    contactpoints.yaml: ENC[AES256_GCM,data:YaapGRiN0UUEIQHxJ4v5E86b6kEeSocAQS+25z8JU1rEuKN8BotPtV6UGR0S9iAHEfsbg1OVj+3bAw52v+QSBFH0oJP7R8ncR3/UXLCQMJwqchVhp76yMN7TYj33q77TfEvYHXvrwN+A3tP2O3LDZ1TGc0VZfLxFl5/Uqcy2hezhe/o73u/O6wbLLwdhVTh+dBOyxWn0joAzY27e/3BChFNWuwzyUYZ6pBUsSX/Ox1kPidQ0LHA23S+3Td0cF7BCCjzqtEgBntMBh4ZcBiMx83j91gdgMWp5TAXL9CcE07YKk02owmEg/tdD6I6j7Xh4k9vI+MdsqJCbCo9pwcmAzu8h9GfS4O4dxJsqEMFvXW7+KsZt/WPkaz5KMClhpX4n2Xc/Upi+xACLH7SIvXNKXWrG7wNxd1Ad985lX1MPg2V1JXIdyKNgqmHlFZNNCca0A1MN/Y5Egkb8E5tLiHYHunFGkmFz0nNZr0jEf5DpV07cG7PU4GU7TTI+pxurEa+u/fM0thNqmJcxKaVp+BDDRsVrURF7ZlVmvQ5Y/dW3bmsW5mQ/kQ2Hxhu1cXKSl/TZy2vb3dCRnVqDJTzAcrCkpYlt+8Hv2yY6hKsgahFwJc/DsLASu9vSWJI0SRccA7sF98xV09IRTxFXwczHdzYL4rRp0G6FFNg=,iv:wbRGT0UQZ+hsKKgZlDq+4FXLFMh9U+OfptukB/xH+iQ=,tag:gedLwueIicYFsUdDxgdHEA==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_alert: "1"
    name: grafana-alerting-contactpoints
    namespace: monitoring
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWDlwbnQxSUF3SmJ5VEEx
            WjlFR0t6SElqYXBsRVYrRm1TZ3pIbjZQNzF3CjVPUFp1SHQ4N1k3MlpFeTZ5emUr
            Ni9oUVdkckpZa1R2NE1mekt5SHZUcWcKLS0tIHhyWGJhTDlNZEh2b2hZbllPTGtm
            K2gwTFhTMHVHbllKSXBsb3N0Q1BPNXMKwAUVBKrqOd3M2mwo7OKzWw/QObuoceLf
            9hRuoEmBilGHnX1NOm5d7WlBXSRyC86uRe2awPwqB15YILKamHmn8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U1h5dHZ4M2FiTDdDOXBr
            OEdKaEk1OTZCQVFuS3BQS0JBTkdyNURJdm1vCktHUzhXcUtiN2dka0R5ZnpWaUp6
            NEcrOHhTTHR3ZHY3UEk4R0p2eXJWdDQKLS0tIEdwTnNJQWtuSVZMNXRaNGxub0Zu
            Ujh1c1FaV1NNRytJclFuQUc0NThpRTQKhxQDsHr0AQ+kGP+R/4492uCTrJHHABNk
            JjYKiSndFHuA99RBQ4LcprIa4rHZAh+4dCK9j41XTGLZ0r5FKXntKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTndDOUZjSGNZRytYakFE
            bEZSZjRWbjlvWFZNbUxNUW45UXQ2TEF6Nmc0Ck9mZzFCNG1PQXErK0l4aktHckR4
            RHN1ZjJSYW5JK053Z0ZrcE1icnE3YWMKLS0tIGF5blNjSStXN2Zza0U0S3cyeEJQ
            V3BxNHh5WnhmV3I0SVdLWExVYzI2TE0KtGtOJ7OSZlv/bY7P3Ac6ZXhiMvYGsby4
            rxA3jMWk/ULDdZC7OPjPK/RSNppylmF3pld2SCAy2pLPkEG3kHrx6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:02Z"
    mac: ENC[AES256_GCM,data:ZMHj0mJOtJXFS+kL+NK70/H4Og2Ge91BI+FiyLDpxJ0a6lbICe2SjQtr7wCXnOn4lW7qLexV+o7eSGF9PaNz+ZCMkLYPuuP6eIB5zAG6eUUXzeR+eZU8qPVBre5oip6xg00Y9jiaIdFNXbVmLrM0QsZ/nvBEcMDcCoAC/37p6/o=,iv:reaDRYkmbDuL/DBz1zqEjYKmW78vvdyw0Re7+poM4nM=,tag:dTIPMuKk+jrl2p9Eiaw68A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:gNTPRuhIjheqgUSjE8XyZES+qQiTDCrV0U1dtxJ9to4WMYo7SOj5fVnLJU1fmHvII5fHz/yqcSELMMU4rqg=,iv:rnW0PAGU3vO54dbiR5l18l3DEVcTQboOTRLyJOYO4iw=,tag:lxMSIxkx90QNtHSGHREL4w==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:2pWYaYcIgFG9AXjtcE/XpFSfsOM4g0YGEila2GeBW98WctxXuBa5kS07c5xl5pHox6u+xUTEeuMmS96sDLE=,iv:MJvBl8g9m0jYuDWxy/mYMuKVQdAbQ9bEynVqqVx7+3A=,tag:1zuxyyXBeWT4vDtmOq1XBw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:SdNXIqjjSpSccsUVMhfgy3C11kvUtQxJ7sOGpPxVJ8HwYElrJzSyAEdJouvonxlmFTohMI8MpPHbHpQ0f51/2pQq,iv:dX1mCa2NbDi3JEWlY61WmfSlCfYljFIL5/9GHaYCqc8=,tag:yUmQzJTvedvyXC+ElXVnEQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:Luf7Jsv9Gt6VGOOaMGHEJsQuegfPsJrnsEONxRncy9iT7DHqRp1DeinpEecshcId8EptPOlcaeAMBtaAgnUfyqg=,iv:tyV8KPM/yrwtoufsitMud4ogVj0Q8o4hVyDrPyuCWe8=,tag:QwnNSAi9pSgIQAy+ysXT7w==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWDlwbnQxSUF3SmJ5VEEx
            WjlFR0t6SElqYXBsRVYrRm1TZ3pIbjZQNzF3CjVPUFp1SHQ4N1k3MlpFeTZ5emUr
            Ni9oUVdkckpZa1R2NE1mekt5SHZUcWcKLS0tIHhyWGJhTDlNZEh2b2hZbllPTGtm
            K2gwTFhTMHVHbllKSXBsb3N0Q1BPNXMKwAUVBKrqOd3M2mwo7OKzWw/QObuoceLf
            9hRuoEmBilGHnX1NOm5d7WlBXSRyC86uRe2awPwqB15YILKamHmn8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0U1h5dHZ4M2FiTDdDOXBr
            OEdKaEk1OTZCQVFuS3BQS0JBTkdyNURJdm1vCktHUzhXcUtiN2dka0R5ZnpWaUp6
            NEcrOHhTTHR3ZHY3UEk4R0p2eXJWdDQKLS0tIEdwTnNJQWtuSVZMNXRaNGxub0Zu
            Ujh1c1FaV1NNRytJclFuQUc0NThpRTQKhxQDsHr0AQ+kGP+R/4492uCTrJHHABNk
            JjYKiSndFHuA99RBQ4LcprIa4rHZAh+4dCK9j41XTGLZ0r5FKXntKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTndDOUZjSGNZRytYakFE
            bEZSZjRWbjlvWFZNbUxNUW45UXQ2TEF6Nmc0Ck9mZzFCNG1PQXErK0l4aktHckR4
            RHN1ZjJSYW5JK053Z0ZrcE1icnE3YWMKLS0tIGF5blNjSStXN2Zza0U0S3cyeEJQ
            V3BxNHh5WnhmV3I0SVdLWExVYzI2TE0KtGtOJ7OSZlv/bY7P3Ac6ZXhiMvYGsby4
            rxA3jMWk/ULDdZC7OPjPK/RSNppylmF3pld2SCAy2pLPkEG3kHrx6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:02Z"
    mac: ENC[AES256_GCM,data:ZMHj0mJOtJXFS+kL+NK70/H4Og2Ge91BI+FiyLDpxJ0a6lbICe2SjQtr7wCXnOn4lW7qLexV+o7eSGF9PaNz+ZCMkLYPuuP6eIB5zAG6eUUXzeR+eZU8qPVBre5oip6xg00Y9jiaIdFNXbVmLrM0QsZ/nvBEcMDcCoAC/37p6/o=,iv:reaDRYkmbDuL/DBz1zqEjYKmW78vvdyw0Re7+poM4nM=,tag:dTIPMuKk+jrl2p9Eiaw68A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
