apiVersion: v1
data:
    contactpoints.yaml: ENC[AES256_GCM,data:owbDAqM5Q5cD+0+2w7DCwZzfgOYaNX0vd3mbEVQQwuOxlCQlaYqiyDfhhJ6bfjIXlgUEgO6UV06PNpR3Vf6RSTxsAVMt/hIjdFGGFmXsLVVyF2tqDc81Rhp4ugbuzO4shGtRe/+35njqgRKBBGXF1oI4SOMF9T9yEpyu6K8HVPsrr5yL8TWVuX+9/R2lwAALrOGYrNsWEDQ+IHJsMhbdZTQucXpXQ1ljnR0TKsbjgnJfhyAEFU0qK880VYIaRD4j69LlJIoQsdaHpxX7D0Mno6Fi4OA86q5Atn+TdmdtkBvd1FRYYNutfnDTE+7s8zsA/ER3riBKEWeXJx/ErLPhqy3O1w8GQEEd+pzGcehv4mTADESbWIoCpLefZjjqgpAXaP09zudnfWGeEgaKFUjHxWabjSIR0CQjQV6D1sz9Awmunmlsm8VoeNgqQkHoTs+n8YUdDM/UItxAKhB+ceXENyqMZbzvpp2Q/miyPf+zRvzfTWryfH1a7pGi0QWI0d6c0/47+FTe2Ej3YPMQpG6JpECgc6n95M2b2E/gLffsOXsLZPwBtaTb59DAcHZ29hl9xJ+Kjtewy3YhmEcXNJ5oQehl/2rxGx2Xfq6varFdpEsmp42NftZLFjac2SSqyQlhYVWolm67S0AlbbvlRnWFYTzcR4SKFjk=,iv:ug7WrJ+KXd9sRC/N1VwNLkTpIL31adkXTPSN36ObDLE=,tag:IwDVA0njRcB1IhzVH+jqKQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        grafana_alert: "1"
    name: grafana-alerting-contactpoints
    namespace: monitoring
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcjlrb3FZdWtISWZ4NlY4
            aitXMUlMZ3cxVmlzMTJnbjM0K2tuMCtCV0hnCjc0NWZpd29UUGJtbDkrTFBLUWwv
            OFN3c2h6aURpT2dlVDNtWG9rNGJ3NTgKLS0tIGhyaEk2ZTJ5c3I5akRJT2t5clRo
            SnZRSkVsY2xkT1AvUWZHQWFSek1LOTAKQZN+lNNs6PUETe/qApZ+u0dD/80ToK+H
            5URc7W+Yjj51V7EEsYAARnU4ZBUmRcQcvO4PyVF97IuX9hNJlmSnrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM2pzVU9Nb3hQcmExbVlt
            T3ZmNkVlWHJhNjNpV0VjbS9JTFlKeUNpNFY0CldmN0g4V0FkWjNmU3BLYmpTdDZ6
            c3JpMlJpWW1yUFJCOEJ1SEgxL1hRMTAKLS0tIDErTU83RkVjVkR3eUwwZ1FFZ2sw
            VGJOdUIyVGhEOVU0S1ptdVhKT0k2Nk0KKZXmNx5fCRHjo6C6HwfQUkMALY+hpV+0
            1fBuoviN4crqKgVkOKSg3F0uLypOeuWlq1JjzQveqNrOAthBmJ8cMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNUV5RFhsRGJMakVudERW
            cXYzQVBsY0RxeW1qMjV2U1BBL2tzZ1FJa0RRCk50c0JVWGl0dnJXVUYvNFIrVGE3
            NjB2amdod2NWSUNhc2YvVHZ2L0tCQkEKLS0tIG9MNTRjcmRJbDI4VUJxRXBRZmxH
            MC9zQzNSYzFJak93Znlmb0RUaGlEWWsKYL9IADWB3RhYZ5p0S0aBE6NJ/Y01hVbQ
            utThStXLUbxNGoQX1z/3jRlIvd46mZCZUhiDYKamF+YQq99GRoKk3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T14:11:06Z"
    mac: ENC[AES256_GCM,data:jVfRQgaS/IUJp+C7QkwxgDbX8bTTrom1yl1in5tKtRG+26ZOPntSEIqBnzFhGICMAKIvn4Q/GEKtP4UqnAoXHo3tXxtCZBBYDmi7204Cw+gyTscsNKtRzSWokhmpFfRjhOSIwf+VwbU8JSGCDPpQf/QvdrmovopbndDpOMfsPVs=,iv:x1QD8HqeMzvWTqayLE3UVlbTT0J+xKixlrU4id/MnMw=,tag:py067o+/x0+q//772YqPgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    ADMIN_PASSWORD: ENC[AES256_GCM,data:U7x1Ip7hchXUjLP3v1f4bw==,iv:4VDDBnTSGgGtEWLtzG6UzUncO9OxfZ5Pe9QwrB4/hmw=,tag:F6KctvxxlyUXFhpFaglu5A==,type:str]
    ADMIN_USER: ENC[AES256_GCM,data:7gY6IGTRjrZVN9SSkWkOYg==,iv:J8QUbVx+Xk+rkj5V/w3ga1z1WzUysd009LDLPCXRLds=,tag:vAsQG5L9cTxaeSf+d11cSw==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-admin
    namespace: monitoring
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:6/2kQgEZqFut5XyfxSgRs5k6X5xLWI9o/dt3VS58IiU=,iv:BBXzIhx0bXsrRubyTlY+xSgUfWnWL6FCUNjYb9u9DBs=,tag:v/TJcgvlsjcaetdKKfYNhQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:QAKIXY23AIBgqDWOsOMH/Gftgw==,iv:gpovpojD1WobxT3y9qRciiwhz1uDT9Dktmf3+b/c+K0=,tag:16NLS7EoYc8WpojG4kWplA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcjlrb3FZdWtISWZ4NlY4
            aitXMUlMZ3cxVmlzMTJnbjM0K2tuMCtCV0hnCjc0NWZpd29UUGJtbDkrTFBLUWwv
            OFN3c2h6aURpT2dlVDNtWG9rNGJ3NTgKLS0tIGhyaEk2ZTJ5c3I5akRJT2t5clRo
            SnZRSkVsY2xkT1AvUWZHQWFSek1LOTAKQZN+lNNs6PUETe/qApZ+u0dD/80ToK+H
            5URc7W+Yjj51V7EEsYAARnU4ZBUmRcQcvO4PyVF97IuX9hNJlmSnrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM2pzVU9Nb3hQcmExbVlt
            T3ZmNkVlWHJhNjNpV0VjbS9JTFlKeUNpNFY0CldmN0g4V0FkWjNmU3BLYmpTdDZ6
            c3JpMlJpWW1yUFJCOEJ1SEgxL1hRMTAKLS0tIDErTU83RkVjVkR3eUwwZ1FFZ2sw
            VGJOdUIyVGhEOVU0S1ptdVhKT0k2Nk0KKZXmNx5fCRHjo6C6HwfQUkMALY+hpV+0
            1fBuoviN4crqKgVkOKSg3F0uLypOeuWlq1JjzQveqNrOAthBmJ8cMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNUV5RFhsRGJMakVudERW
            cXYzQVBsY0RxeW1qMjV2U1BBL2tzZ1FJa0RRCk50c0JVWGl0dnJXVUYvNFIrVGE3
            NjB2amdod2NWSUNhc2YvVHZ2L0tCQkEKLS0tIG9MNTRjcmRJbDI4VUJxRXBRZmxH
            MC9zQzNSYzFJak93Znlmb0RUaGlEWWsKYL9IADWB3RhYZ5p0S0aBE6NJ/Y01hVbQ
            utThStXLUbxNGoQX1z/3jRlIvd46mZCZUhiDYKamF+YQq99GRoKk3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T14:11:06Z"
    mac: ENC[AES256_GCM,data:jVfRQgaS/IUJp+C7QkwxgDbX8bTTrom1yl1in5tKtRG+26ZOPntSEIqBnzFhGICMAKIvn4Q/GEKtP4UqnAoXHo3tXxtCZBBYDmi7204Cw+gyTscsNKtRzSWokhmpFfRjhOSIwf+VwbU8JSGCDPpQf/QvdrmovopbndDpOMfsPVs=,iv:x1QD8HqeMzvWTqayLE3UVlbTT0J+xKixlrU4id/MnMw=,tag:py067o+/x0+q//772YqPgw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
