apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: 9router-env
    namespace: apps
stringData:
    API_KEY_SECRET: ENC[AES256_GCM,data:AyCZfWv97z2TJK80ds/sN96SNI27HhVM4tZMehY/1tZjGrCslDAWXs19c2e64w11yJng2ApQ84WA3wiXA73l/g==,iv:/9ydbn2VvxPNHRLqSyXD71bWbdEuMnNq1AixfGhDWLw=,tag:SeKMTZP6rIq+DxHrHXgxCw==,type:str]
    AUTH_COOKIE_SECURE: ENC[AES256_GCM,data:GQVTeeM=,iv:WcUOhu00HAODpolj5s4uC8mqlPfSBeFLknnuULn+uxY=,tag:9i/Vx+cumgrGgBEgV5CKCg==,type:str]
    BASE_URL: ENC[AES256_GCM,data:WxNsfnELLpJJH+0kTUy9VPXimbmZSA==,iv:R2XJXgcUQ1069K9IrOux1Ic3AgKDVOhFJgRLSysY9es=,tag:coYu7EAwPGCGlBGQLpatQA==,type:str]
    CLOUD_URL: ENC[AES256_GCM,data:Kh6nZiX7MvIwYqsm+hHSLNjRPA==,iv:YLm7hgRJdqn8T7sywUlSGUpM5ro6hzyUjdCr2KfedwM=,tag:f4kROLd4FfkIhd1lw1TLPw==,type:str]
    DATA_DIR: ENC[AES256_GCM,data:Lo0uH0KBtZk0,iv:Kr77pE+u0aG7QMMLJF22equ/4UWpVGMRIpS+WNpsf5U=,tag:khatMS+GMk7n7Aqv/qdTdQ==,type:str]
    ENABLE_REQUEST_LOGS: ENC[AES256_GCM,data:O4S8+N0=,iv:rcWdsyaAEpctdEMXZ1vyskw/MrCYUSWEKwPnVLlnDXk=,tag:S4Qsyrgh1EsCo/QxffAJqA==,type:str]
    HOSTNAME: ENC[AES256_GCM,data:8NoEYDRVWw==,iv:mtpEVV0gq/Z9TsfKmGynH1LORA460rPB9dHGMaYg1ZQ=,tag:zTtCe/PJb0+nkNNG+ofMVA==,type:str]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:zf6CG1ZeYKe2rtUqZWPl,iv:kjVzk3khQVW9swJEp6Q1IvSAR4Io4FbUhfoggyNfSjY=,tag:KNkEkd5HLcB4chIsUlpI9g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:fxUr9d2a2ehCdim1sZPFzrHrLPnAKp9NugYZun/tJhdCqV7h6YRQxPB3Ius6wGqXzoifk26XwonK/920ddPe2A==,iv:lVSJmSINXsqpfw3TOWIcFFtdid38E7z+bbT6n+PYFqo=,tag:4AoEnJ2QtbEN01D2gSrIKg==,type:str]
    MACHINE_ID_SALT: ENC[AES256_GCM,data:6MtdLqaU2rFomMkCS0+bqdJViUEP6yS0BuZJuAZQE6iW6Snn4hJsJ0H96bRzaaclzv2Kzw5rmUYA/Zl6152X0w==,iv:QnRFYrkSW0M4P/t7GRdpvdPsRJ03Ep8zRlUHseFR9gY=,tag:IVEkb/Pb6a4LOSOkv3DY6w==,type:str]
    NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:GlhsXHOxM9jgUmY7rRBJ4SynwXyn9A==,iv:w8z0XTuaYkh/ZQnAjtiF7ob0zYxm9TZZqIsGaYW7jdE=,tag:kE0pDIFHGDr4CicLcO088Q==,type:str]
    NEXT_PUBLIC_CLOUD_URL: ENC[AES256_GCM,data:3ndpjrW0s7O34uIp7SU3YyA8Ew==,iv:mk7Hls14L5sFOyonzfxjxrY5GiHWuPsjY9ILFmcmC+8=,tag:Xt1gsAmi2yzMlo4FdgA5nQ==,type:str]
    NEXT_TELEMETRY_DISABLED: ENC[AES256_GCM,data:KA==,iv:7yCaVbmIFYox/WMs0tLjbTgZ5VgnnF6KSDPB5cyZrM0=,tag:Q860LitpMfgUe9JwwgHQIQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:kgPTPGV/Bxl+Dg==,iv:yf+KR0FvS280OWZtYjVsi8982KYx6oLEB8hXWvfGMkM=,tag:bD+UvI2U8a84QquyMV4zbg==,type:str]
    OBSERVABILITY_ENABLED: ENC[AES256_GCM,data:cOnFxw==,iv:C/Paz/nO5MaaBJ9/H+Lp3IKAwKzXdYIiMN76MW8m9BY=,tag:Fozr0p0YkCP8O3pFArRfGA==,type:str]
    PORT: ENC[AES256_GCM,data:Y/IB9m8=,iv:Jz759lmyZN8qDM2qbupCAMckNad/XtWPrf6+t8hl1mA=,tag:hP0AvbAkD/fAPjvtziFf1A==,type:str]
    REQUIRE_API_KEY: ENC[AES256_GCM,data:RBBdEss=,iv:Lh985Qpwroike51rRO1a2CPqQ3WIaEP45Famb/T7nmI=,tag:11LABCGSylSY0k1KNRo16g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZE9GeVBkY3hlcXVuUHov
            MTJzOFRTMzdJQkU0U3p5dGo1NU1Fc0tnNUgwClBTTk1MY1Y4Z0ZIaElYazdjbUZq
            UFRTdXhhU3JmWnhBMCswVE9sT1Q5T3MKLS0tIHdRRjlMVmhMUDMvUWRCVlc1dmFP
            R3kwQTh1S1NRczJFVmw1ckdrUzVPWVUKzFzeKBM5qAfz0yMHgZv96rXoDlb4pDpz
            lJ+2pp94EUjnLj+1fI2IA++GgNuNO9d8uRqfYq+nqazzzgEWA50aew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaEpVdU93bXlFaG9zYlUz
            MS9xeUVhWEpDS2Fyc0ZITWxiY2I3dUdtV0FzCndMMXdsSktEamtnbytUZFUrZERi
            U3gwb3RNV2lnU3BORGFPR25YV01kRnMKLS0tIDZENENkdlMydW41Sjdma2ttMHRO
            NnROaXowN0ZCR3pyOENna0U3aUVlcFkKmvAUUILVRd2zuQqddiHgsSkTOMAqkLDH
            Nj9jL8SNlq3Pbk/SZQPWomIMxp2af2SmN+ITu+6v0c5eSv9/sTAIYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSjd2VTNxUW5McUFyM045
            b3h5dDVWSnRRcVE2YTlqR0Z4UE11cGdTaW5RCmRnRDk1Q2lIcGdXQWdYb3FLSW5z
            TTJoVjFHRUJqQ25aL2hjdVF3Z1YwWU0KLS0tIHlnK243M3o5ZWRpNGJhaWtlcTRn
            YTRVMnExRGFqZk1UZHNsTUVTcWN6ckUK7bEouTUchWSSCDFEMSKFqtHDIbWky4I/
            sDarA5Atw6jvzSmCWke6iTprFDJdgoxjKHRH7sGyK98dZH7zZLAdYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T15:48:48Z"
    mac: ENC[AES256_GCM,data:pYBw15YxHjq+VYNrxpmHX6uhUPo4aDK8SVmPkFotbAL+qLrQJDXTUuqQMJj3cxwCyrh6AMTXHTq4ZenGy+GRNMkAfqfXkyRyWDCE/+EvpWsq0yBbd0d4MGLyQ8mCdTSif41SWBIrg/QQaEJPcGbVgqamihE0TnNIGeZ9WFa+SDI=,iv:B86KubS9Equ90hpr+qlohAHoS0ql0/8BTHR5LapucGQ=,tag:/rlApI7JhG9DLlv8QVZMhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
