apiVersion: v1
data:
  userID: ENC[AES256_GCM,data:5GH6+PLEFAXyHzuPYkLR1Y7OBgkMirDKIcR4fKvR6otJRxJdXTBXqqnhUvOv2YwcovDb09YK,iv:ZetnwHDcn/wTH9AEWb7Tu1SWENZ326/6/yo4V6Z/rEs=,tag:gGC9lwdmDL5th3UOWhkzZQ==,type:str]
  userKey: ENC[AES256_GCM,data:Rhcyba67ID/JVP09vwMchImVzEn/zb+cNb9mVx9L6yEtcAnYBYef/m/jb6U4d/Xs/x5gKoz/AQ==,iv:FS9EiYKetk4HLJbVBNV+TKS5zk6mCZqPY3x9GPP0lq4=,tag:RPvD4GlXJPXukmjKHDI/4w==,type:str]
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: cephfs-user-secret
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZysrcXNQaEhxN0cxTXNt
        SGVMVlZPeTR5NGttbG5DK1dSVDk3cHFPcGpvCjlZVndSUkFHTWkza0dBbDVUejRD
        eDZxUkFyMXFqOXFueG11eGFiV2dsUlkKLS0tIEh3RzBjUm9PdS95N2ZOUllHVmQx
        aCtLZytkWGJVZUsxT3NFNy90V2czMEEKM/qBbFG8fxF7rKiSihBKuNZphRwhU0kZ
        hqFZAuUG5sIxX9pdZaXLCUdopnR6pvB1Owa6JkyIzLE7tQvg5mtfmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTE9qRlBLdGZNNkJQU3pr
        bkU1dGlKdmFZYnJKdjBxU01XVE5IRnlvR2tNCkhtU3JKRDkvSFVjOHd6NVN1dXlH
        WlNUdHVHS3NScjB0cnFENm9XMWxoQjQKLS0tIC94ajRPbnZ5aFBwQzAvMnM0Y241
        eVhZVmRYaGxSSVZ1KzBwL3gzRC9udVEKAiOLJwInHoK5Z9fbmGXO0+S1Ibn/W5Am
        DgKOUh7oDgF8hZ/BEWxa7Qn8vmCEhzXjp1pQdummx3+JVDN6auqLHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRjZkeW5GVkEyL1hRV2ZY
        Mkcxd0EzZUp1TU9GczJ2OGJkMWxEVXJhZlh3Cmw1UnhubDBObldRVHRydGFRNzN1
        SFErQU1qZTVCOGlITW1lQ0tHTkhPRjAKLS0tIHAzcTBQSDdXb3FTV2F5Q1lJRHoz
        VTlBSmhxdURRQkRvSU84UHdUSlRIeVUKnr1v+dj6lamNvsTFp+r4bp7klbLhFOeD
        9vtluLFyvbwS3YMmNjtx9jCqwInpibKuFtKh/mgPlB9Jv87i8LU/Pg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:53Z"
  mac: ENC[AES256_GCM,data:WyUOzmnSC2mrKui+dnOiwTH+k5CzUxm3jYlmHrEf1m/xMegIa7qni5EN+4Gmaak7QlfGeJ+KfCa866Q9YgzAus5rNNTK4XjOFZOLjqjPMTH07GdV1FAVgkTed91zEqO/NJORsNLcaMrNOiAy+f67aPZqVSFBxfUby8nTfoGuVwc=,iv:SkKue3AUGROYAuuYeGPFaKpUSwrBkktcjk+vMpqZ4s8=,tag:34RaxAJkfLjVrIHY/uMKmg==,type:str]
  version: 3.10.2
