apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:xRpJTrR8bG1LKtn7cqr2TJP2a6A=,iv:UBusoQbo7iyOd2U+MS2Fokni9cwtkOX457cnqdSrMr8=,tag:PtUKh4wKEfxQoRVnbgYr0w==,type:str]
    userKey: ENC[AES256_GCM,data:27nGTbDK/LEfZtzpILMVrSH+bN+gfd5alumKbPwonh7UQ8XYut6zQBPnaw57wfxUnsR3wSLAhFU=,iv:jaPtCu5NWSYM/HhIgkXpsvygh1obOoqCOOBHsE7G+WM=,tag:o9eLS1/nRCoBMxkjx3EPdg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U3BEcUx1blI4Vy84VkYz
            by8zd2FCczRZMWdIdnVVT25PbDF5Vk5CSkNJCklMZStYN0xiUlhMVHlNb2tUbzRC
            YnJFQUVCR08zdHNYa29qaCtEWGY1QTAKLS0tIENpOWlIMnNSZlZ5NEJtQ3JPL3Nr
            dGNWT244WExYbnYyRU9sY1IyU1lCcFUKguE9kk/VkdGZRZAtMzYzd91ByS3Gmwc6
            KL2sLgTNbOfmdd+LfeevM0oDEF+g3i02JZnjHV3TemUNuLS2k6LWxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ0dZQ2VsMFRIVG9VSjNJ
            NDc1bWhiODFUcTZ2cCtkOHl1Q01lTzR4Umg0CnJWS051T21YRHZ6ZnJBbkluaDc3
            YTk3MXFKTzl5NFV6M2U4eTNIbmRLV2sKLS0tIFJBcHBEMVlOZFk3blZCaUNCQnI2
            enBxQ05sNG5vV1FVMjl0QkVSdERWamMKxpEAXedBTMdcm64Cf1koWBz766LFZRFL
            oAyTOPHDpYjmWkdbAiEC5vq9XEvZZMdut4oAHE2vG96NL2owRfak/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UEdzUkxNc0lucVZwQUxm
            Mi9aTkVyL21XT2YwcnBZUkRTWCtleXJ1ZEF3CmJrZ1RzZllwc2NCYjdRVy9KZEw4
            aU1UV01KaHNvMEJUbHUveTBIMU92VzQKLS0tIGJTVTk0TlVyNGpsR2R2bjI5MkJB
            VnhiYkZyQkJWMVBjdldOKzlZUHdTVFUKxciaiZ2GX9nfsyP8TAw9n90pFlsrkafp
            Ym86vEqoF8kU4PZZEcd/K2dI71qvT6wsjO5AtBHoJSehaFp2FZIgLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:02Z"
    mac: ENC[AES256_GCM,data:U0z+ClzbIxQ2CP08vt92zu4JtinnrMQXlO9+yiHYEdspQnFLvunMyNGzDnq0XyVNEkzFRJd6lR4tasaGeGVVUWkYiBbBloaHnHiAAiZez8HQeJhm19oK+x5h+42SqtiTwb6i4OyccuaNtKzqYRH12CyNm7isajPeoaDlEqBwF/A=,iv:KtAwDagFaxGSmfwb+EYoA53tmIlMfoFXjmCRV7xOavE=,tag:wPrWC/TMsz1lfArp/jvPnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
