apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:V/KAWrq1fXzBN7wto7p/tHZ1wQg=,iv:uAVLZ8Aj/3fJ1fqbBcnFGJkAkrcNi3R3eI/4n3Bd3Tc=,tag:DzZLwFByWtBQ7JzLcdSP2Q==,type:str]
    userKey: ENC[AES256_GCM,data:Jj3ZSfxLWpr1cEKKRGlXBd7TM8HxZH0ViVzQ4nlGMWQtcllNwPosfHbP0gco5XPtnM1trwIdT3A=,iv:PV3NtbhOFYK2ICozWqr7sWsf57Pt0eGDy3qGPjjuqqc=,tag:lWIDN2dbVt+dL9Vo92Wnkg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: cephfs-user-secret
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTUNFU1kxYnI1SEoyUXBM
            WFVPeHNQc2xUM05JV05yNFlvRkZPWkFuSG1VCnFiRVUyUXpGYXQ0YTFJSnYwdisw
            a0ZDVHk0YjdKYkNkTEtKaUlUZ25EMGsKLS0tIFlPZWMyRWNYR1NoRU9UeE9ST2hL
            eG9hc1BqaTlSd0I5UmhLYzdDTTZkTm8K+xxSsI3A2ZdYb80neJMyw+zOgUmLw6hc
            mjeY48nvraG2+sqhk5vRuFPJgKo3aEQtuGZn/l5ZhgUTyfo8WzUkkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM295K29kYVJTdWh1Sk5i
            bDhTbnpsdnB3SUZYRWx3NGNXTnpZbDZURFFJCndieXpTck1ZcmpGTVdpaGxxcDFM
            eCtLempkLy9uOW9GS2pXRWFTVllVb0UKLS0tIGJRdHRKMFF2Z05iWTdaMTVjOTNZ
            QTdrb0RNREk3dEs5OWFtWnFBSnpxNlUK93GwLLC32Cf9P/qUBQ3vHOQtfaXR3ZKp
            p+Uu8WCgJpVsAIG1jl7rPSjiv9j5B3YMNsQafE/RZDNmxt30zQMaQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dXl0VkU2MEc5QXlSeGsy
            eUhrOEJrZ3BPU0tnRldQdTBOMkZmVitRRW5RCkNnT1VaOW91OThGWFJCWHM0Nis3
            WE56djVkV3EweVJqcXRRbmNsQ25GeDgKLS0tIEFBRVNHZllZOFhnSi93bk5laHJK
            WXNkbWl0TE9aQXJRNVZRbkpja3BtcFUK0ArtrafFGo+oxe1Z7qwH0IrAjHMyKauQ
            B5vQxlVQ2y54NJHAx1f01XuQzrjl7HiZbmhNXNvuqazgpOC5dErRKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T16:13:10Z"
    mac: ENC[AES256_GCM,data:LZvSZCwaZ7CIkCXzBe6NLgG3v7HIlX1e7VAwgI0TtgmFW0HcPPHzGv+a6OxI11vBtzv2m/xfK/+pwvsrtUDI8FYCH0ZbqGmg78PLUzyvGj68olzID1nbs3z8JLFL2WhArfEWMN/sURWpK6CHs8eIx3DNnDzXvXmKjNVYqpZiyY0=,iv:ic43EmcUSptTAzld17X86dmFv+0LsxcbAjDzD/cjAso=,tag:k/bZG0BL4SpFVqcWOVNkLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
