apiVersion: v1
data:
    IMGPROXY_KEY: ENC[AES256_GCM,data:yxZV/obeKAEyZ54vA4FfMNn0rYTXmkm1PGD8qU9rtJPRFbzTVFxbjRQsAfRBVb0yaersJgLplEkSxKrSXSye4vYR0XBTIzDztck1UdUrS6ZDaMKDsQQ0Fw==,iv:k0h9hwpi4v5tkZjtK3svTh1pErAU0lZPiAuxkLBipuU=,tag:zzuXMmDkvyvzVHV6nabA5w==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:ABMSoOSY5rC6L0APNqAdtqLyJ9KsqATRIxxRnlLbHKqtYKUU6lUG1L7daRwUh1cukIyv34OXoqUNHYEUBrASJZJdA/JlSdahvW1AkusVqO3XPIE4c5szpQ==,iv:gjMPQhHiMNDf6jg4luk9mrE9n2JTSrO12Zl82DcWUkA=,tag:tdwMy6VpqIJ7UtFBqdjsjA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 78c4143dee03313cbebd6f7c49225e820b1bfd51
    name: domus-config
    namespace: apps
stringData:
    DOMUS_DATABASE_HOST: ENC[AES256_GCM,data:HOBV/ab/fCVT1rC04xG41Q==,iv:d7oOY4JObieMpkaJoIdfRD/wz+YUXI8o4WGNXUhZKTE=,tag:t2NYTKX7qab4zF679X8DAg==,type:str]
    DOMUS_DATABASE_PASSWORD: ENC[AES256_GCM,data:jF6hcHHDseL2cxEO4ieLXUQMHg==,iv:YOl7PBlRMQFEG+2PNDS756RbRAZIxxnr4L5SBgN/1f4=,tag:77ebRyxWgQLdoxSVl5QQ3w==,type:str]
    DOMUS_DATABASE_PORT: ENC[AES256_GCM,data:ta4x1w==,iv:q2Hr6xFYYHuzBdL9z3iFB1tp2A6rVSuc1QI0a3nbgUg=,tag:rnLI3NlPhVbakO25d4Gofg==,type:str]
    DOMUS_DATABASE_USERNAME: ENC[AES256_GCM,data:UyBDqvdIwKw=,iv:gP4TSxkuYw4ERjgjCEpH5eb1QmbpFobge1LSY/W6W6Q=,tag:DspqspjTEfrt6l7tOUpvlw==,type:str]
    DOMUS_RECONSTRUCTION_TOKEN: ENC[AES256_GCM,data:qk3tDoyObHEi01ogeHAaN0LjF5H2oyJrgtXdVyKLLabR+tBm32B5tiOeArc9rx2xQWHOhbRD/v9fUJyMGcm7WA==,iv:RBC7oy/H/HDi/256ovaSl2f8PwBKucuhtALaEDIhOuo=,tag:0mCclUOcqMKswuR08WhE4Q==,type:str]
    DOMUS_RECONSTRUCTION_URL: ENC[AES256_GCM,data:bjqbtPLnDR6V+RPSHYbnEoJlCrRdpqw=,iv:v+gzy/qdjZNSlmwEjKeqE79pQDFQUP7PzsZobOtn1DY=,tag:7aNN20OYrGTjyhPEVlxgLg==,type:str]
    DOMUS_VELOX_API_KEY: ENC[AES256_GCM,data:JGmSRAFOimZe71Kl9p+GirJqqP8NeAOcyABA7RZJ5nxrNdFkhMbvxM5G17Si86oYUwiuWLupcel0,iv:8xoo3J1tsR5ME1D88uEHDlM8FdwjO7ujSzZE1/eAnfE=,tag:myGPg/S7HNI4PBcVJhlEnA==,type:str]
    DOMUS_VELOX_IMAGE_MODEL: ENC[AES256_GCM,data:v5m6ORuBLA==,iv:txmd7xk1qvQGA/yCHqNiptcrowYvhdZl7JNKlXF/dzU=,tag:uddxm73zToVKdMfKxxbTJA==,type:str]
    DOMUS_VELOX_URL: ENC[AES256_GCM,data:5gQo+WFb58YgCdyew5gbr5qPXDZ4/bAep0IeWxBaCHNsti4QLM333A==,iv:OvlFUAjO2ZS/zrh/LwQLyz94ekDZd0y0s9R0Qi8oTA0=,tag:MPE6t+cOGwxLCcWcTwdY9g==,type:str]
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:L+3N6x670UqmgJ0jwxpGIjBdk8SkwQShgmXBtsQD,iv:32Y1p2CV2q5WoBsacbTYdcdPJUg7fb3/+CLuc9ftIyk=,tag:igEGjvWQHHD8AE56vrzs/g==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:A479oKi/dEM=,iv:9XOOZsBpE3tNyq45S/IJ++mqy3cLYc+IJrXqJqJfpeY=,tag:fhb+5iKqkBYdpHy9FZWisQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:kKs0jF1OdqEVnmXOKVSAKivNnBo4dItappZOgceeuI41T64BfB60gD4HE/zojwrEVyP2lpHa+NgpTeRbKb90gw0=,iv:rypep5ykQpOaMthEU9c0MOd6b+1M6nDF0jI+BhVNsEk=,tag:sxREKpm4x0LPvtuPxBneAQ==,type:str]
    S3_REGION: ENC[AES256_GCM,data:vHp0bDZ3+3Jb,iv:O7kOhHjhCHhXdhfqAmVV0+XuckxFnoNKSzlz6Vqzr+w=,tag:oRZSX6Yn2YAGMkx6S9WPFw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:+HJ1qSd8Puegd7gnRMuDYILA+dcWvx1LgTjOQmekhYNge+MwqsQCSGpqiXp9MFj9nc1o7ye+WehyXIEp/eLL3QZDq4l67lrbrmQ+/riSnzGcoL7VklDqJRP/s4dhjTManGXSg1FjZfFcPgihO+bA060yFZFtThzm+B3ffNg6ZIU=,iv:cOUhVAxWJ4gW261IK3vcERpt2pDq8Abvxz4nP/X1bZM=,tag:SwxTP3ZscExyFXPLss112Q==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdFF2bEhScDdhRzJQNkR0
            ZTJoQk5MQjFjZllmSzZWUldhQkczak1XOFRFCjNJbkg4MjVhbUw4eWRJb1oyenNL
            bktrcCtUVXNFUDY3SWJqdHg2QWFzeVUKLS0tICtkelFhYVh4MTg2KzhmbjRkUFJz
            bHJoZ1FocmJ2SGtVTXRaaUNuUEpXMUUKBaZPtxoKuv2Q4Y2XqvlUmeWwU59Bklnt
            mSsM8eygFodUVi3wRkZ4+PNgA85CQaQh5t66qC51kkWVCw9xSTs7Nw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMd2FRZThPK2ROaDlqN0dI
            VDcranpvUEhHVlYzaFhmcEE5UXViSkJPMndnCm8rUjNnNDFnYUpJVlZ0Q2sySUhh
            aHdzT0JNOE84VFpRUkF1TVdicXVnRncKLS0tIG5xOVpHVjN6ZU9XRHJtTVVGcmp0
            RW81ckgwZWhxTWJzRkt1SU0rYVgzSm8KDTgxn7kqctF6NpLPs1TlOVFYaKVCjeIn
            OIwvh6VcHA4vLaotdvTXRF43YhxVjfFA4+2aOaWIsCZe/hvFU9es/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNUY1WEcvRkFJVGpUVFlH
            WWRNM2g3OGJsRUFkaVRkOTBCZENLcU1xT1NJCll1b2RIVUNONFJlMURLajNpWERy
            d2ozKzBFb2t3ME55eGw5VnJZbGtWamcKLS0tIFY3MWJYWHMveitrRDdzWXZYOGg5
            ZnlBSVhNaGhaUWVmZEI1RTdFVDgyQjgKKLUREUu6XglWy3SXSF8JQeqtGQbZ3K4u
            3azJ2OfVpEdc8PwE+ZiBD+TjH6JqX2MeJhqni90o/lmA6pi9RL+TJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-05T16:09:09Z"
    mac: ENC[AES256_GCM,data:mxfHKM5yJrnG+U5FK89citbxtRghOolGVs9XHHaS1bUKp/kf8Qf2y1l3LJ/wGFw7HCs2h/cIK2GKqIdkU+38AOFFOvs2IdCtorJtax4KxNnKNVUze+HOMrQcAQwk2BnaylUBqJUIBG1hrTphlD2XQA5V9nbZ9S9CLdMzexL+92g=,iv:F2d/nsz+w9jxEMjUU9WtpA7BDbykkfS4fWEKc6s3FSo=,tag:uqV+me8tO7Jmus0zXR2/0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
