apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:Vx5E/T5B896OGfQGUOAEerWMhDe9M9vH4atBMjXcAjaxiBO2sO7rxCt9GWIOZNw4t5G4y9V5k3HN2fE7,iv:ccw6COshdgQYH8MqOOXAEaDxQeWr6kgvXqf1KqWtFOg=,tag:pDsRYqFyITWhCQOxi1O4OQ==,type:str]
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: ghcr-registry-secret
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcTZkN2dhUGs2b0NGdXdu
        N055Y1BUWmJPdjYwbURqL25neG1zSUJ5aURzClM1Y1pHeXM1STlrMDI1SFcvN0hm
        SzlyN2R3WGt5QmZCZ0RSbW45cVhIYncKLS0tIGpUSzNEc0FLMXZERXlEa0xaemFZ
        ejRWV0IxYUZXb3dNYlZTdVZ3UzhIbmsKOqo+a6tjxNfEp9g+6iOeqdxg/Km3yjIb
        CQIuHG94SeAfCCIOh7RefbcOVM9DimduoTgYWMHL0GNJY4lfnCRoyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWWtNN2w2bzVXT0VCRFRI
        ZFBEOUdGWUxKb1dtaWt1WTNKZ3RJV1NpSnpjCjMzbjE3bGF5RE1Ld3IvODM2UDJY
        d2k4ckMxZklCT3d3Q3FodHRNSGQrYlkKLS0tIElPVVdCWU93cEZLeEFPaWNmSm1o
        MzRDejE4U3lPd05DSGpreEcyODRlckEK6iA6S0RZBCUOUFSBEBLQ1ywAPgL9zu9w
        wep3ol0DwsIxm1RUTWzt9JFok7kxlynDSa5MSE4l1l3vU6DIjUptsA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vm90WWV3OVd4VVZuRHU5
        VENjY1djeDJRZVU5M0RUM0VWaUltc2YyUVc4CmxmVUloK1B6MU1MQy9uMjB3MURP
        WnhRRlhrSC81cUR4RFVhUDJCazBGbmMKLS0tIFg1WHAwTUpOR2dYLzdhRXlOMGta
        TTBlWGs4MFNUY3o3TXVVb0FjSmxxbHcKsHR25nsXtgLWKx6lLtpOUswh9gppxQyb
        JYvgva5x540Z8nE4P+DnvoAZXDy6BoKDgi1ZAzxl2XrAdYDJVHJ+BQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:53Z"
  mac: ENC[AES256_GCM,data:8o/ycnjn/eMNomTwcAahUsvo5BGkOOKopKuYvuq0nIYA7iGb+3k1PWFj23xO//j+cbSv+ApKhFAIyPMZrfDNcIuledQiKaxdgcR+dRqQXDgArS20SuWw9Nprgk74V9PNH9aE8JFGZyGBsmi4NXdOKe7Ec1vGhZy0cyRPVt6XMp4=,iv:lq5JlD+lkEan7sBebUzFxfAr6ZKPEza0Dy71Hx4DXwI=,tag:JUfLsPSfYvJLK77SiwRsMQ==,type:str]
  version: 3.10.2
type: kubernetes.io/dockerconfigjson
