apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:S+m1ZxSD0k7VmwIso+gbs0j0F/FtGKbDYYvMRxRYcBbFGtI65SJI5rj2OT9mdgjFtqBZnGStIzqN9BdbQYG8Xd40/LQ6pBYBtqDuub0GpuG06XTIl+/y63SDbqnElJB0q6mWRx5Nkp66RswJaTQffMqNZUrveABcUlYnTnZILL1V+MizIkT29NrCKBQ/MYn+Vln4QTYdEE4/d+kPbf0OsD6G1hzyJDCeUQrd0Ayxr4bO1tlWkvX6FMoziwV+2vdyQMSe6zoSdt4IUy0Ij79dusP9JURZwY2z4RxNvIPXh7sEXgwlVLsWwPhRUQYMLYOZoQj2U+7/cecVVLlgx2rWZAvcqD+mFxrf0AZIpeWnCm86DNUFRzCVkKncZ/aoHORflPgGlNmqErfZvFQGqDhYu2DZgdZWngH2a9s3P3LWdmHvLXOHBL1L8CzgjOeaQoF/G2tjB9Bezy6mlsq1wPLMiBSgkBpO6IyuijSIJOE6CYrUqT6vxJN3gX7mo3L1VsvePcTS6Cql8ZI=,iv:BZSagiR16ZrtN9BT3Kk8tT8LsOWUj0jhycrNe52owQ4=,tag:J3WnDoL3t8s7JJLEmvB3vg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNkt5THdia2ZkeWtEMTV4
            aEN4QXNaRXJKV3ZRT1d4ei9CWVZyS3RaLzNJCnprUDM5VTN4Q2puQmVGWXJIMWZ2
            SmdOUG1XZjNoeTVGbGN3cVpKTmVBNFUKLS0tIGJUZnFSQ2lvRVRzUitkYlhqb1Nl
            Q2xiYU8rK1kxbEdOcHBNaFhESThqU1UKpRcG0IablTBkcp+pa/Xo8ppTbuNSa+93
            Plx+ZdkO/WMjd++hnCDvdDZkRABlNrydgMIguNn16peqPNVOiqfaLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYnhySEdLYzM5cU5vUm42
            MnZBSndZd09HYUl4VHo0dGloOGhzR1BZSjBvCi9QVnVWYUpSNnRnbkdtdnovS1lR
            ZHVpQVhTOTA0VTF4ajZFQnh1ZTdaWGcKLS0tIHFubnVIbmx4ckY1QTBRZFBCQzFn
            dEUrR05DZ0R6UTBETzJTbDZ0ZnZUZTgKNF+hnkP7UmqhCMO+nbQft3yRm399mpbf
            esuQqAutTwY5kQn3m8ajkQbBjMcp0PPGFPPH2mYkxRFLE4uPlp786g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeWtqNEdEaFQ0dkNpOEdD
            ZWVFQzJacnpIQVUxSTRYMHRNRmZVOW9ZOVJrCkxCL0R4YkVOOFcvSnVIY29xU0hS
            V3liWW1PT3NpYm5WM0FXZDhISEtNZDAKLS0tIGdyUTdDRm00OXV3d1kyOHQwUGlS
            ZGt0S0pLc3pPWXBWVG1DdXoxZThkKzAK62hgdeXszoMR8CISDz0rAf/Qn/n5sIcw
            Ic7Ui86siYBuZ6GYJ625dHyJXPAaNRHJMuaaqYnQy+s2thjJ4jPJlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T14:36:37Z"
    mac: ENC[AES256_GCM,data:/nrm5brSdBzgspPwjbphI+MwqsiWGmZSQ8bQ3cf0zYnAQt9gqbolVpBGPcT0T7/yNDqkpVFA1yg4ghm+baze4CJ2NkMf3GCjaupS+Wpk5sVFQpHksI4HRsoBHR8af5XZwaXGQxppnPNKSxiWjQpe28b1yaOFpOzqAclEOTkg4QA=,iv:i83BjvIuzwFA+rREn3UF3mxdj93HsQAwNpMe32Whyx8=,tag:Q2jPK5EFV7Hpk+giLjGX+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
