apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:TPKEYMaT2GT9nb5570yEw75qNy+A05G2OBo1sMDs8OidH8/5CIlRw8g7vgnrkCT1UfFDePjmyyR7liapoglVBX7tg9oRJPO9puFgC0f8A/O3wOvxksTCZONvc9F1vtgERcmtqjXOSxBpUH+/Rru1SFKrvam/8ckuyK4zBTe2VkvoaOeAFoH7j4I6/TIv2fRogBf17Qk6FmyGIWtG7vy7O51agtuW5w08KQFvZkAZMT9/jOxxveQKX72dNEwolKX6G/yXgWIjcchidmEBwm9HG2BVLzgL4VMd7s5g9TvVAU0yK1/dKcc0eNuVDXiHu5SOtelxOEGpe/0xCGbZrZSM50GXc0kZzV5P6XdUb142B9Aqkh+QiuGYAOQBNr1OOBCmIcZSimzDxFPu4emUohejGDu6dvSst9ShBkpXPef4oH+5c5lUeZkSLB0dFuaCoRh9QfT2kdiXfAdcF1uMdqk1Gik6MBQw+lmMF2Zfu+NxI59Ke9Mjx/dtV+0B6sGibIPmNQRtqLrIit0=,iv:AuU2cA2ThyjifOECQsxTScJBGoTrjx+wkN0vhs28gPc=,tag:jczuoYzzbCHL2M0ztH8Wzg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ghcr-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR2N5VTdaMmo2ajA5SlJ1
            VmhrbWZhU2NXZ0I0bEozUXdQTUdaRFdkQTFFCjIxU0ZFMGtRWFp1QVJaS0phY0ov
            eXpoRUNNTTVQbW5GQ1kyc3BXZjkxRzgKLS0tIGVyNTA4emhGR3lsSVdYUjhmS3dW
            VXJDVzlEY20zaEp6bmZaSUkxcXpreE0KjMN236fe7U4Pfil00uvrNMx5Da9jHmEr
            dWTjeD9/7YKR42v8R+zSNiyJICxNNBOzKrK6UNsIJ4mFpLCY+zmPJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTFpydlIrYnMzZmxsM1Zs
            S0hEbTd0V01xbUVpcmJiTHptTS9MK0s2NUFBCmVzWEdmdldJcnluVUZyOWdmRW9k
            enNLMmhjbnh3eit2bExTQklkb3BucEUKLS0tIHk4eERaYXQwcEo5N0VpL29OZjJN
            MytOY1Z4c1RpUlpKNEozQlJ6MjI5cTQKMRll94Hxj8MLk9Vndqan+HmENTtmO0O4
            /aI+H1nHNfGO7CWYvshaeagGROkd3T2fuVX3SPUcgozpQTcpEapn0g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WDJLRzB3WnpqbXJaY0xu
            MlB5d2liM3BLNWNieHMxNWt1QnNma25kTTFvCk95MDR0eGc0bnlBTVZPbzZMb2lC
            Q1FYeHFkZW1nQzJMeGNZWXo1U2hnYVEKLS0tIEZydiszOHpGUThkc2NiQ2ZXOHlo
            a3NHSGhtZEFYMytkU1FtVmxyS3pIcFUKzBeGKhRgXlZnaiWBHWLNhi4y2Ayyi+kf
            znuopHWqM2eDYeAbFUtIdzx4qPoD5xlFuXUIzucqTBj6jND5iFKftw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:00Z"
    mac: ENC[AES256_GCM,data:9s3G3BJqtnmZ/fbMuWDNoGFQx1L901ffO5w0HWl0bJxF9eRQl9nhqtH/vDUlZoX1H7wrnPCo+lfbfv3mDVpx3J2bs41Fer2ycOXcauBPhl1WtgC86SiA8BS+VmcvzdThpW1VA8sj8duKl/eKLlwZlalDEPtuYp3H2akIXtQHYcE=,iv:q4qWG8x9FMXM0c82gIprxlQ0Fe33T1cqSTqbFocaA2g=,tag:UMYjh8m3Gio6Hkkml2d4/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
