apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: gluetun-vpn-credentials
    namespace: apps
stringData:
    SERVER_COUNTRIES: ENC[AES256_GCM,data:uFtWk69putqhUiI3F+rqKA==,iv:0jDdX7A3gedGellEoKQEAOz984sb6Ny/0IqSyNyKvz4=,tag:RmXXm8Vq7vOAR4Ua53eVcQ==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:14duhyXkrHJRLVpl,iv:a26H+okYr8SdI6lBjQ2ZpYeNBaz0qkryShpZz8PMl6k=,tag:SCBbCnjRHhgjR6GQdk0DQw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:N1XC7rPfOky25YV5,iv:6mxKoRHP4cqdSJs4fn/C6bRm0yz0d4mNuZlCbdbt3vk=,tag:Ad5GMHvlsh5t6onWxcVGDw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:ga1vUeF3wJcKOJeELCCqH/Fs9iIVxz2ADvFOOF8bIrFq9+zvi3bQ+6ghAKdrFB38dMxCMPycXhSWDKpi,iv:i9/PCh/XvondQ6XXSepaMcbSQFT2xkRHaj8YGF1C6fo=,tag:Xw9/vK8V8uJesRctU6Q6kA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU0I2UTRwRDZHYno5cVIy
            bzRZSTFTdy8rRTR3MjZNZXpLSEV0TjMxa2dNClJtRFhVVGxaWWQvREo2cnZSek90
            bWhGLzExV2xtUlppRXhUVEhyR0kwbjgKLS0tIG0yL1o5c3p1RThMUDJyeWloejRP
            VEZLUFZqUm1Hay9TMU9OWXQyUG9scWsKkpo/Xmdi6W8jsC35WlLehiLBpN/ylDoV
            9v5NNiLHM2b5/4eWl/1wB+0Mp0dXa37mkTz+bd6NcJguIW4xHXrEMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMXV0QjVlenRjN3huU21m
            WXJ5TWFndHgycm1ScDRSOHphazhSc1oyRmxNCmMzODhoTWpSZytFeUtHRmgwUmdv
            QlRMNy9VU3BVTlZBTTV5azRhSzkyMWMKLS0tIC9vSmFZVjlhMVh2M05IdityWXZz
            bWZ0amR3RXNSYThENlB3SlJpeE1IZmsKWsI92m/m13fRepBJkFyDaB7VG6o6CobT
            dSijMqfrfMiZ/OWkJczwPAv4bli3R+xQ5A/l2mrY06/3/lqr6RIGHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWExtb1NVNzNDa0crOWwv
            cWlsbnZvMjBaV3g4b0d3bk1vTUFwdVB6aFZvCkZIV1RLRlFodTlLVkhlM1hWM1Qr
            SDRaZWh5SmdhZ0I2d1ZzLzlTM2JlKzAKLS0tIHczMTBseVdQL2tQTm55WFhEVXpN
            dmFISE1hVVhLVFp2cmtOWE9UMFdkOG8KKS0u28/jAoMbUqiZAwUd/T+6oHb3Sd06
            as0KLkIzaYzkX5+Nnl4ga4KBCl8hN+rfqXHlqHdOZIgLsMbRFkWAYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:58Z"
    mac: ENC[AES256_GCM,data:10kMXGm2gq9H/NZ6aMJN1VrXknn8kKev/LYmkFSxs1g2f3iTvpVutXgbV6Bi3U/6CLrjSWVV5NwRcg05u3ri9D89Ggqi0+tQbcXIcfEmZGDoEYe8uoEXA/b33kaPlEVFZLAr2vwrhPKMPz6xiW7GuMjGs1ED+9hJ1f//yQ7CKnY=,iv:zuuZfghdiMta0yg1O7UPr8QzRgjesjXtHDfX0GbBZ6Y=,tag:eR0KKfP6krpwas3kkoqFnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
