apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: gluetun-vpn-credentials
    namespace: apps
stringData:
    SERVER_COUNTRIES: ENC[AES256_GCM,data:2kijd8Unxxf9BozIgOLrrA==,iv:UgJp7ONmsR1csfBrjsi0CD2cfN/cIq1R3NWRSv4My8g=,tag:awTLJI9QcqttJaW05XH8Ew==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:o6mXjh18rQo5m/VH,iv:JdQDIKKSvy7yJCHyS+YqZcYhFkGdjBszcH5k7wDMAnI=,tag:bCssyutEGGYd6lfdTREhKw==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:5QeAPeMo380zdA8k,iv:YcNXe96zBsQ67gZRuMN72sPD8kW3mPk1nBWVRRrQe0c=,tag:liPv7iXHsLKHJiJM2OsXjg==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Gmq7CiYNvpkSWCaRmIniLDyJoz4O/MEWBSCFsMtsyZUuBrD8thb2WxY9am6hGjA052Ns51mWU7hQcg3b,iv:+zQ1m8Fern2r0IYxu8ay0QDd7wMLGWjgvqa9xKAkbZQ=,tag:VpVtWByGkyDWVitWnDbnvw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdVpRUVppU2YyUVVyUktu
            TzM4Q1cwQ2RGRW9CWUVqcWFpKzNSbFZRVVg0Cno0RDVrME5LdElYTS9vWFBoWjRv
            dWYzdTEyMEVINEl5S3U5MGRQMlpzVU0KLS0tIFhVeUVIYXdzNzQrdWUrZHVJVFNX
            cE5wWHY0QXgvKytVbFVFNFo5d1BXalkKY7GhgIQovKYsoX2uugnNrBM49y/mNlPN
            Qz9uWBOV2Gj47EOmm147xW76Mcv4Wam/IDlDNyGP2njNGHZy1z5pvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdnA1M2pqMFJ5UWErMjlo
            ZUJ4WnBLV21nbllyM0dEY3FyaVdFL283ZTBJCkFyR3RFTWhMMVIvMkRCUkFJTWRU
            SnI3WGtORThuZmlHbllYaUlYc1lMdWcKLS0tIHhqQU9nRjJKL0JKd0loVFU3QUVE
            UUgwaGhyU3pJbHN5QTFSOXM5eFdJSGMKdl+dm4Joza+n61MiApfus4qOTmnAueWT
            GsQIKDYG4qKC5g41s8Rd82us50yr3k6TF+0IQz59nfjEXvT8em/OkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TEJIdGd1OFpDTDBRVWtB
            bS9aNjBpT2pyUmRJRjQyVmVYeEJBdW8wT3dFCjcrcTQyTzkzV1RtQWRhNmVVaGdi
            Q2dMejF5VDZPZXBQaDBreWF5bGZzVkkKLS0tIG80aGJGd3lEU3FWSk83dVdiZTVV
            MG1qQjZ4elUxSUNFdXJYVzFlYWNBQTgKR0Yjrg43v2BGq1EC7YWMeQfMeUKkyd/g
            ReRvck1ifQH5uCrQxkniOLC89lcZP5vA84C8RsKKwRIPoqloZMo2vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T14:44:45Z"
    mac: ENC[AES256_GCM,data:LtirFeEoG9MctiP3XQKTZCaeMlCmGVh3u2GIJQTXup6SNa2LRakkxKBRYy7W2/dm2c3vggepF/4Zl+pm+ps6MJPxJbjEf5JO0+rWPNflGYxTgme9JNBtPHppQI0GvVA/IOTeCtsCdCPyuV2IoiLsyvYLHVfUbS4E+d7w44K4SLk=,iv:b1rspUv/tjwlI8yi48NiZ0vdmuQVljC4KS48h723RxI=,tag:r36h7hsqcl1BVEkjXoDiDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
