apiVersion: v1
data:
  SERVER_COUNTRIES: ENC[AES256_GCM,data:ZAEN7BDlpS7osGiSjDPc9EQzoauw+tlRhyBd5p1Gk+/HTSUWEuT+eOHzUB8EQAXhNxvgDwhROqULifNC,iv:/qp6k8fMjD0c1gLJl9S+qtwJPyik/3ZTEB1l3aTR0kE=,tag:gHFJzzBgB7SdvdJ22/61vQ==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:NID8/vbVKEXPwPdeLRTjdem2yMgw9V4zXdIKLEUt1WHSOaVpCvQL7zNTpKCAr5Ew2d8yhRzHaeBc9wnN,iv:d4ZSx/KPC+HK9fMELovCNxkdOf2rDyM4+0bWFNFol6M=,tag:MFJuNFPn+UVdouYUuz0GqQ==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:keghwEs2UyiDh47u86g4RH/uq6ZZJjrC173fMPOmcmII8hxgPGL+MTLST7RQlOKR,iv:g3VtyaT+ORDWkOLwM5gJhEOKG2Q2aw7rAKqWc/dmnZU=,tag:RJfhKM4u8vYEfOw9v7bPUQ==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gTQ2dYR4XHrTtqo/31+Xj0AmzFAXMHWOXlLR4nlxn26iFZFofb1kJnYtpWPqjkj6h5eljO2cLGUYz32pgwF0sUM=,iv:3N/A4CI9vG44M5NzlfljPQHnP6uUig6fK52KvPF9Xf0=,tag:+49q6zOd51g/bBwARDbwtQ==,type:str]
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: gluetun-vpn-credentials
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTFFtdUJDK0o0TEJVZTRn
        bTBKU3VYVVdjNVBZT3U2TFpkejVwY0xGN2xjCmhqVnltQnNBUmY2TCtZd0dSQ2Vi
        cGdHQXNUOE9CalM5OHBIV2VyNjRaV0EKLS0tIDlMcDhmbE5Rb0VRU2pDbTYrYS9i
        ekxPalhyRUhtcy9KdTNiSCs2YVFFWUEKyDJM9DHIif2o2iXOY0rhg9wSKavsd7Pz
        9t8XSvid27ss5bStZZ9R56rUUIFI97QtLjO56KFzbO0uphVBaEnMYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlS2ZXcmNwVE9VRk0rZndr
        YkJ0U0d1di92Q2NVZzhIb3dmd1BwMWR4K1NFCkw1bVF0aGt5MzRHRkZvOHlJbVVG
        QnZWUHR6elk4OTFVSHNHUWdpRFdIQm8KLS0tIGU5YmRoeFpMQzFYdmUxV3FpcXI2
        VGoybk04eUpJRitGZDA5ejMrVDBKY0UKTSfo9loNZxy/CtHDFr4jpvFMWvS8Au3p
        /xi9QsvdG8zbiCORayN1vj3mhpaUrMzkPt0fjG2onC6OVwXD0JN8VA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT3Q4U0EyN1grS0YyNmUw
        YXdxUFRaU0drY1BBeSt3MTZ5UGgwMGxUZFRRCkJoU1RhNG1BMjhodllHNW5XL2tE
        SXNWZ0VObU0wSDBZOU50UzJoTHcwa2cKLS0tIHB5ZnM3d1R1dXQ3L2xMdit2VHZD
        ZFVQOENGcU82aExOUkRkN2gzWVFTK2MK8CsFTsg6Li4oi0PBLCzGyVXtqUSr356r
        HnCg6E/STBzMadlAUSg8ab6xveqA8q8gjC5iVQ8hdi+cpLJL+AuOdA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:54Z"
  mac: ENC[AES256_GCM,data:/UN4LqAKQK+gNctAi4QxK+AO5Gnoqo6Oy+Oe0CKYvMJaZ/taUuCIrxeJC5MMq/vSL3Wl9EcNe3ipSdcKKcHhxtJGeA31/oEvQIxZAHo8b1adyLz+e8+c+72R0pjm8QlonUxAMSqjKHX6kjBmZRddNCtHZBwFDxz6xSLRCTdAZS0=,iv:1BlEzuNmsBHv+0srPTVGvoKZZXcLEFqDf2lVU9PtC5Q=,tag:Mvl/aQDtNS3SEuGg93K95w==,type:str]
  version: 3.10.2
