apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: c8f8b282cd5ddc21be5dc9074dd42f39b61113fe
    name: glyph-config
    namespace: apps
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:igXRQvTdRjtbje1rDCLXJ7M4qH60vt1/1g0K6+Tpz3G6mBnUlGfi74tQ8oZ2cOX7NNJpkw0mGvaRaSrkYAzC4nuqPgE0oNbxopwcVs2uyDGqpkC+YsB+5SQWmPupSg==,iv:J+6Zd6K509mkqRJr4HfeuW9nRhq4gJHcc83J1m7CySs=,tag:QAwRdLH7ATUiz0gLv2IWtg==,type:str]
    GLYPH_CORS_ORIGINS: ENC[AES256_GCM,data:JfBKgGikw2H8KNhyIq/OhkaGpxC8ZwUfnL7h,iv:S66NhRP8e2CxDN+1WRspUK1wdC7RzpJz0KhnGlXChYE=,tag:kHkvVIZsTN4ph0mhTi66cg==,type:str]
    GLYPH_ENCRYPTION_KEY: ENC[AES256_GCM,data:qrWzKaM+/rGUVkLjK75EeYicb3oaGpnAs7/JmKwT/ENy9YmwQLfNsQCdH5U=,iv:+Yv19eS+DZFzx5plKiBnvQEAM68d1Mn2KzrERq08d1g=,tag:caNChs0sRV44KEbifthdpg==,type:str]
    GLYPH_LOG_JSON: ENC[AES256_GCM,data:X3+4cw==,iv:1Z71yV8oO97+VQWXuX0NKL0oV5uT4AFzeSh5/zSifmc=,tag:wmX+BxgAKNUejgorUai3Ug==,type:str]
    GLYPH_PUBLIC_URL: ENC[AES256_GCM,data:+U0MEfjQjxsMiwh+nnnraUI+mmLxfnNupJsN,iv:0QFUSs0+XJO8ju7Q0vGEz3TnROLYiuH8CcM3cso9Frs=,tag:JynG+MbNw9ncCLVipVJI8g==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:E6zojuwlgvldnn+708s6jhvu2MA8hORs8ZybunNGOuVxOXo=,iv:HT7G6WEu5LtyUZtCpHYj8Z5Cn01zDJwUtkbjC14wQEQ=,tag:EhGtaH5V9A5axAg0b6aFow==,type:str]
    OMNIROUTE_BASE_URL: ENC[AES256_GCM,data:wSlNhxt/ftb2FhjSTAgretioGnFCGlZ/saIRyoSWTzytKHmXJtJZmuKrX4uhfo7d,iv:5qcMe6aEMDE1nI+Q5VgS1/MV2iAX97eOmCWWMSz3OjU=,tag:AgvhYXkmnvLAY0onh5W+kg==,type:str]
    VELOX_API_KEY: ENC[AES256_GCM,data:xhJvgmUu4g3qPZ9IlEGnh0CQxoeM0F5BsV9ni6NzipR6EvICnyWPtkiEjoG96KU5XWGipMd/M4Nw,iv:fECSDlQJagWqNZnNqrAreg8S+Ktam9ckrl3KUtuOkV8=,tag:dnwvHOqk/IVJJ1T0hoBjhA==,type:str]
    VELOX_BASE_URL: ENC[AES256_GCM,data:h8Rt8RDsOz9yXpApofWksX2whpkifLqueWoXMsq41tf2DHPgOx1TzQrnSA==,iv:PYSaiW+aolzqbpoDM5BAMp0A/2TNVbRn77sr58m3e1M=,tag:sjc6yYQBrybuTjmYV1OLZQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVjBKSXE3S1VKUDh3T1VN
            OUJTNDFWbVFZRFhiWW9QWGdpZXlGV2VQVkhZCjlXNVltQUNVZlZFZk1ucG9YUE9j
            OWV0bGRQSDdMWmUzTUpWMnpEMm4wUjgKLS0tIGIySkJzRmFGeDJWczBJb3RVYTA1
            ZmFRemZEQVFQcE5QTTJXU0MwMGVnYVEKdGnJK65sTv8m7ZLcvkN1rKv8LKQuZ/ba
            WC5kwRFWx+aT76TJHw8DaUjNvROjCRP9xofice1WEuH/F3w2dUQCvw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWW84WHQzayt3Rk1RWGxR
            WG1ycjN1NEszWUtZLzBJNS9JTlRpdFpnQmhjCno3YUtPMTkzTCthOEozRDQ1ZHdT
            NlNYMDZZL3VFUHJidThTMFVaM3BTMkkKLS0tIHZRelJKQUR1eFVWaWk5eElmWUsy
            YitpaUxhTUVWczFGRUp6T3VFdGtJNG8KpIvavCdI3HkX4U1a1E2eHUZ5cOtf8uCL
            dKF3KFHizMhRyfzTcngQRYKkEgCjrquLNYBy/4npFr/ud7PQ5qQENw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmlucHU2WUhtWGhzVWJ2
            cUFERlA4cS8wL3RqQ212M2RFNXZDbW5CanpjCk5COUtackNiNER1aiswZkR0SjRP
            c2pyS29hWGg5QW1EUVdUMVBhNGQ5WFEKLS0tIDZDRWw0dVdrbDdvdCtjc2QrL2hR
            R1B2QnJ6Z2xXbW84Z2x2K0gwQ2t5K3MKCzYiHsGX/FOxnoYPqnJNXQd5m22k/FfF
            mcKwPDWwhWrWYMIkL4lNFhOGLHZXEPZnfhcbkBkv3vRnm/t55zXblA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T20:57:57Z"
    mac: ENC[AES256_GCM,data:J0wt51lSEApXXG+Tq8hh/P4xSxzn0nmPOxB8b1J4Rh+qaz3hNfqLllTOzxWxXUZgetAzTJGekWsic2DxnZf8cMb473FN7pmHMLVQTmxuz+mcl8cW3tpqkialPmy+qHLIUCAWzZp9BM2ewBTMLZdU+EImym9uBRP96pp3bSLhDDo=,iv:N3vbW6V0gw89THjyCEFR0bU04TQSo0xngfj1+PyhCRA=,tag:xpjTHXj50SEbZPCn0s6Vdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
