apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-alert-relay-env
    namespace: apps
stringData:
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:OysEVbmbZNp2c1cVSwoVrgKq46TaUE0kbkYAY3/eagTOHcc6QPxxlCIb,iv:Uq+maF461cgKyFS0KXH9QHlynCV6BEgtw35KXXuqH/0=,tag:jkZHHc0HZ8sDbYFoaP8pjQ==,type:str]
    MATRIX_PASSWORD: ENC[AES256_GCM,data:TagDuyIsQrrLlTs8kEi+L148/nTAy5ed7vsxbu7IWg==,iv:F9IJdx+5Sp+tx8wjGxtpJiHFcwqnKVDTO23JoufJj0Q=,tag:tdZsF00fmDw5MsARv1qQ9Q==,type:str]
    MATRIX_ROOM_ID: ENC[AES256_GCM,data:5NceqYk5vTgmqEFciLGzVC0lJsdOwIAgiiw5uADooYhO,iv:/z3w05T5EU6+O2EDICNLvjCK8sTvuxVfdZ9mWfYcSBg=,tag:ctF0nCU8wnUxyfUEocZGZA==,type:str]
    MATRIX_USER: ENC[AES256_GCM,data:jQWiFh4tBI9oW0d4UODKriUZAA3TzDd3Jt5lOgM=,iv:P0eiQtjrF1fFNo3+nSWZOQh+JPk2JV7xqkBCxLbZ06c=,tag:XVwNBhy0moa7JlbpH0kayA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaDd0czI4ektGMTBQQ2tr
            cXFBNDR2MVUreWdKdzlKSjdPZFcvNEo5NUJJCml0ei94aDhqZFJPVlNEWGpNQW1Q
            ZDVWcFpZbExDeFV3Y3VMZ014bzhpUGMKLS0tIFc0WkV5Z2tiTDlRTU5vb0NNdjBY
            UnphYXI5UjBraWQrNzV1Z0xXSkxuN2sKPEFGKcinoIDAihZZ2B7Q4gyh1AafWcD3
            TamahGL8gqIKAoJ9u9ddqONjx0XKCgAcwdblso3KvB/3Fi/gjMGmkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldU1EeW5LTUt3K3lEVS90
            dzN6ejc2V2tlWlZhTjVRcFVxc0Fna0FlMGgwCk52MU9kZ1NCU3FkcDY0NGlOWkp2
            MEFSYlNmRU1qVU9RV1RqRkdKeU1pb28KLS0tIC8vRkJ0bUxqSzNZckRwNTNoaTJI
            bS9ndXFyYW05TnppZWszTzl6ZkZXZXcKBumP41fZuslEwTCvew+RwTCHl2cDDiT0
            m+AwmpWDvOp0/tOfHKWcrsNuiM6WGt8rwg8SaVnJGw+hwWxHFlnauA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNlA1TWI0bzlMeXJqbFhp
            QlpQejBoUUp3MWZlVVVGcUFhZTk5dmFuSDFjCm0zTVhSYU9qMUd5YkVDc3hqbUtV
            Wi96WTV4cnowMXRxY01DTUZ5UGtxam8KLS0tIEVSV1RJZ3ZLVDJrUVhGbE5JRjdH
            QldKZFRCUGpnSU51VHRCeEFXQXk4V2MKcCIHJ7H0COZELSEap1M1wK8985ni6nMj
            4s9phlo71duNMg+TZn4uhcdcacW7s6VyfK1GV39hZQfKzZ4opSeRmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T17:25:12Z"
    mac: ENC[AES256_GCM,data:9Xk/WqdS0PRQHXD6BbQZP59niMjd0r1lhfM56mx+ouW+vtsmCggBwuP0Drn3CqlD102kv5zl6hmpSJh8FotOn/9/liTKISBW4uqCgRwibcUKpkKkoUWLMrgwFowiR7LiPFOt1mOvmbwDvVMpK0wTpOcUri3mPHWCuJoePSYqBvk=,iv:m/DT8o0MLDca3zMdvpKQ4AdKdbhzHeKIwZZZ7Q9OpKg=,tag:jDdNAPXwrLUL6zLdm+K+hQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
