apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: grafana-alert-relay-env
    namespace: apps
stringData:
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:ARx0KoYJo/T+Ha13y40Zw5bXE9apR5P0/S2ipb3fLTm4e91y4f2svMgX,iv:0I0pRaOIAdezKXq01McAYsyNorZK1fTTKmQkCUdUHQA=,tag:6xEF785HEMEbGf4kwzh0Ag==,type:str]
    MATRIX_PASSWORD: ENC[AES256_GCM,data:AiZreKQJ2HypTZ00MfHeMOcCDx67KVb3Oko5Zis+6w==,iv:zxqEeOOS0VkFjPaeg9uaVrkbLmH4N8TzB5c7NzljCtA=,tag:pkQKCbjDgLOZfL1m1U1zQg==,type:str]
    MATRIX_ROOM_ID: ENC[AES256_GCM,data:N8gk8kCZ+HQp7rQt2ImCnl7R5zhdU4L7YGaT3fYxe6AI,iv:3rY6tPUVSgckPminxRESmS3lfI3OQrUpyogFck8SltY=,tag:RjGlv6aejOTIKRjY1oCIDQ==,type:str]
    MATRIX_USER: ENC[AES256_GCM,data:D1FsKcjFxp5qfwqCKaYAy039ZwDoAdcagBaAusk=,iv:WXfNHlxtFcSbjUhB7+lNobgJhb1nofrUlVIPkqJfqkY=,tag:cIidiYvcTz32qGpnSLvm5g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWjV2WUlYalExM2pzZE45
            MWFuNE5UV2lla3hvOFEzU3h6b1hrN1NXakRFCmNzSFBBS3RqaXhFQ3E0WGhiSGY5
            eERXSXNuVmxFakV0VVZlRmY3UExsRHMKLS0tIHdFKytqWThXQ0hDVWFoZSt5UTBr
            MUZpbmx0VW0yNUJTR0c4NEpneFNtNEkKU4usF5N1CtobwPOwqP+puo8GhHS8jHAI
            WnyqcwzkUBZSRKK32XvFtvDqCGFYbN8pPVvpLDay4wPeu82Rze897g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TUlvSlZiNzMzU0IwYXVU
            NWVFbnhSTWhiaHVsRWFUVGR4TDhqcTdFUzBvCmhvNEE4UjZLaEhIbDIwYWZWVlNZ
            djNHWWFlSXB6QStjY3p2SEhBYjByR3cKLS0tIDRTRkNtV0Z3elFHVXAxSTZyczM0
            Wkt6aWRKb0dMSlRHcVN5OUljTHdZa2sKrfJu8P6sMGMPv/CPd+IAbo40LIhl8Idj
            VMPnqOIYGrb4CN+SwA+xf52/+jBh9HQJHQSG+plisYuFv0aZXrCKAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKakMwbW1UZXQrbjVWTlZ0
            dDJRT0lRRWRRUlhaaGZxNkw5K2hUYlBxVVc4CjJ6dFdubUJvcGRNc3B4eXJIR1la
            K1FxUC92aERIM04rL1dhcGdVdk9LcU0KLS0tIGhMbWNYNzNuR3YxK2JqT2lSRVgz
            c2t0b2FrcFQ1cW9RR3ZvclgyVVVPTjQKAXx4MngzkP5V+jIurzYMZ1/lv92nDHwl
            Oq8om0Jzcn/geez0nCMQStk70Xdk2SYsbWWSXtQ3cBD/MrxprrFwDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T17:10:54Z"
    mac: ENC[AES256_GCM,data:oi2UN/g9+XjyPcfcwC8sMx8G8Bw8Xja8spPc1X87FNwm6B5TTEAx5AilBngk3Vt7xsuBTeydgpTw0OCQKjkuzxJUVqn6X5x1Ek0w4tFZoht29r8WNX9igfpAPUS/6SgIg49y0Ob2k/YoRN2ufvIn53Enlc+g/2Ghsia1iIrVDOQ=,iv:elu3HFpS2F+C7bTWiQ3MgwyoUV24ysnQVCowiEv5N+c=,tag:EXEMI6O2zBbF/Iha7+8O0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
