apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: hermes-agent-env
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:uaLRW4D+E9n9VIz9V+jzVA84YxgNJV2QJq2mhDaY1g1fB+FdD5O9Qdm33h+RqUWsLuCJ,iv:L+mVR+j851tRmBOqIvzjLRqWO3nsltD8Zlr+gnd2kV8=,tag:JC6GQrbG/iaHZpaflQ6Qmg==,type:str]
    EXA_API_KEY: ENC[AES256_GCM,data:2xjQAMnt9+fo33q4do3nyhHqU7slAzP34CHLJDCjGd4lqOQD,iv:/auVv41L/OL/tXKpcQhjhqbv+ALU7Q5IvmbFvMb21XQ=,tag:mbSyAcDhTTi98P2vgLMY+w==,type:str]
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:DQaQwpj2Hi3SfM6U8HP7Chfhjw0XBWSesZifXFdux5n11xc=,iv:h5zeliNAQmDnyGUZ9c4c1jtICg1O/ti7ZMj/EFf+Bjo=,tag:sgST5GqpRH5hD+SINaCLCw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:8SmLTPbdFsnrbiamkR2JJ6x5HOQmIGugD8LItUsghXVlWz9zHWmM,iv:u9Smv7IuZUJwY5i7O9WmQyg2xmqYFHorNk/ucfyjl8g=,tag:Mn5P+l5HctjMXNDgRrdPpQ==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:Mz5NxbHQkTMQuk4uYcukDGcNEQdVRRtDq7U6NgumCryHrtXef8mClg==,iv:CvyvCcKf6whr896uBh2ifC+97Rutf4UIBdVyn6uDAz8=,tag:06Jq6FMtU85tBf20TByzNQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:CPmFjhnnaIURSdZVGWl22b0kJ5v43JLXMndCy/96X7ss8Z1wMqzNgg==,iv:YZcM6qliHEr28AAT0SrmXM0lhHrXtG5ut6xX84q5Sew=,tag:Pju9K2yEmCUFc3bcCXt59A==,type:str]
    HERMES_KIRA_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:09ACra1O6/OSpxVjFTU6AMFsGY3RPZbgqIiC/G9g6/U=,iv:6y4VSWoDCKlFqzHF/vbTQNsEfrFNitC7wt/WxhiG0Po=,tag:SlbT9qf0oGA+Wjth9a5X0g==,type:str]
    HERMES_KIRA_WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:XRWKctPnyy6SdBftAWtFmGrp3jiDrS9ZLG0ExhDT/vrpisgpM2yleGIb,iv:iy8o2/wETYxr/NTJ9pCI3RriLPQCrVxSsIU7u7kIvNA=,tag:lr4ltsvWkaIQtuTDN6ERiA==,type:str]
    HERMES_LUNA_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:BYzgvlDn0oDNpSUOL3U6S83gSLitGQ2lYueggtsc5/8=,iv:4BhFIPLXocc13a0Y5N/d7JYDOnO4LMAsUzVDYl5oWxA=,tag:+wI6ZIQxbqMbxR5N+gzqQg==,type:str]
    HERMES_MEL_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:oVOqB7hjPY8tKaDdodiJHEtDHGfsXuVlBoy8VHa7Dc4=,iv:KaMzy5yx8q67f7Yxks02NEI13L3RSLmsgEcZAgnnoRo=,tag:TLX3ZH3RDkK9M6drcnudig==,type:str]
    HERMES_SPIKE_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:jZKjVzRsWa6IAi5MbG3+r+XIXKbWMO2brI83hjsenVc=,iv:ZCvzo9mIA19amwVYKJiLwjfTrAsxkBQhNmo3oazbdNc=,tag:/Nlndq1/UwB23bmQhevPmw==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:uyfCuy6vi9NF7meV2YNpGg6D2ctfyZQ3Gl168dqpONc=,iv:GBtG70FJYTIeDvaZWqUpkDTd9CTyyDu98zara/ms9tM=,tag:E1YoqTUnnPjtu5Wwv4kb6w==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:rsih8N8eIh1ffV5DN4OBsclB,iv:Zti923IM52zBqjri3DKuqoSvCgsJyXXARc08O0oqwi0=,tag:n2cB4mUX52ft3LQ+5+b+MA==,type:str]
    MATRIX_AUTO_THREAD: ENC[AES256_GCM,data:y2E6Aw==,iv:iIB3gBIbkD5YPECWPupba8RxaywBqKk2xb1pmZm4a5Q=,tag:3mR631Xh4w9/cZAQPTvPCA==,type:str]
    MATRIX_ENCRYPTION: ENC[AES256_GCM,data:q5/aqZU=,iv:zNClc6oSgNn11q4OQkLpNkn5CRI2GJeSqg2ohWapfak=,tag:9fVccA5t6I5s1Y0OIpm21Q==,type:str]
    MATRIX_HOME_ROOM: ENC[AES256_GCM,data:G4sVehBBVXSNjUFU9TaDRmG01hYFiYDn953iHrbQtZLq,iv:DrJ8oh9gWqB83Nb26Rj1Qi531NTDtuCTehH5f2kbo2A=,tag:GJyePl1l254pBe1/xoxrAw==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:eh6dbZ6+SmBkg2g6GXtNBk57tYDg+T7HYVziz+jklTEgN+JEC8JoqQ0g,iv:/QjdzYqsUMTt3qtdRAYx/vDALkc0uVj051uzksy3+1I=,tag:N+iSn9+ouOJX9806QgAbkQ==,type:str]
    MATRIX_RECOVERY_KEY: ""
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:C3gg1g==,iv:i0T1b4+3FYzBy2fjhu8uBtXD6EGW8qtP61GbBXXCt1s=,tag:LzfFZSYT+PZj3UGsXbj6dw==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:FP7m/qQivMF60nuNp3pfBDMSJyrQgWuXIYOy9oloMdw6W8MmEKZajN82O2XlHLjBhdXNZoAPQMOiGpAALv1Iqy96ItLmpzUM28F188/r/Vzq7BKePhFb/BLMot5XkBnWm1LXPK7JXWtuMoBdlqY3nIN3gmJBJp05O+uP+YM=,iv:VXYD59pTYVWI7RVUnhvqyKDdvdWkLQnBEX2JsZErL+I=,tag:RjiExcvxBnrEFlf6TKaD8g==,type:str]
    NVIDIA_API_KEY: ENC[AES256_GCM,data:HeNC9R2Mqav95LtV0LNmpIQh2N9uyOkk2g3HKMcaL+P8CYhZsExhL6OgpeOG8AD/gXR65Qjqt5lS+KR9Rys98fd/A228Vw==,iv:u7L5e8+8eBwvD2Eb7lKdfwKCgVNqgg9qA6ipA6gN8yk=,tag:khX9zG3aqgqcoUj3l0bJBQ==,type:str]
    NVIDIA_BASE_URL: ENC[AES256_GCM,data:eWcfBPYDUi1iapZkY6sH03hLK8tYCRqPEFuxZSnLA9MOteg=,iv:CSFx0TfiWu2JvL5bH6mE9hmJqORbTdO9J5SlXqbGwu0=,tag:xz8pZFrpE0O/FlPE0eTAcg==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:qxjzFqf2TAKBc4y6Fw55zUzn2OQBAx5gKw/qFJRwgGR2+8g=,iv:fngRtsN2FOFmeRcFe4Te3kgomra8ygac1EBUxP1Czeg=,tag:j6pc/aaV7KXE3QWhGgOYkQ==,type:str]
    OMNIROUTE_BASE_URL: ENC[AES256_GCM,data:3FPzb4U6cBmBU29SMMR3IN/ti6qjSpXP6CvKKjr7D+tvx3tfvHY=,iv:Z4/4zjnYdwqcJr1ryrl7T5qsGqNjKQxlIsWAIp7Y9tk=,tag:3BtnnwWSJF/MUowqpu4EDw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Bec/HHoSx/FcAudVZdUwhf3Zr7HIclPPxg0NxpsgCwKruakSJD/KXDULSXld0s1vMuOCgZ6U0cN8uKuvtnVBNzZfvoTRUI+twS349wH9KzjPCbRbrboAa/AawoNrDdOSm19mmTvlvTmQwcvoXHA8hdqlSOQNypev7OEk1ydjQe+a1+7ve1Xdba9ZPPCN8xa1iUbiXfgUZBxzND803uTWs4X4XHM=,iv:ON8EW4lA4vjqQv/f4r6/V/aVjvTr+CsUzAWS6LlgVkA=,tag:R99fTUw8uJq8b4Ky32m/YA==,type:str]
    OPENCODE_GO_API_KEY: ENC[AES256_GCM,data:h9tEFIyLWSaAtIo9nQ63JE+spn8iTPI1MjdfDjnhX/F5kd1pionrQceisWqcR5FqVtg5R+XblvLVeVhf+hj9wZHzhg==,iv:oHX1kej+b8nlfV6K8Lb01O/qyDRMPuriUPAh7YVn7S8=,tag:eynehtFwpSz1TMz0YHzKhw==,type:str]
    OPENCODE_GO_BASE_URL: ENC[AES256_GCM,data:kT9aQ7Db8gSPi13SlqWQEd/59Yx5iqKEg0iqyAE=,iv:+Ga0AqJScuJ80XhPXXWFC7Ejr7lUQFlIM8wq5Uvj6O8=,tag:EriJ+S1JU5nNK3PzcgV7Lg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:tOfu4SyWWqwWYOa49DNhxVWDgNft5vFG0/pIrAxfsNqdKS/xrxpRqSnZIgE9JBUSXgtn5DWgu8aBxaNcm7f2CSF/JhtAn+kt2w==,iv:HO6rLnTq5CQrbFEaLbubrYewbB4tVXJyaIG0tqMZ5eQ=,tag:6iMD4rL7CREfO08rcMXhTQ==,type:str]
    OPENROUTER_BASE_URL: ENC[AES256_GCM,data:HqjnPZ9tCMV1l3v2f2N7Zti+lbFzxmmgIepttQ==,iv:mdcZrnxOne6gnSRWd7jght5aFjah+tyvkh40geYzKF4=,tag:h1a7fYqWVCmVcodC/coHHg==,type:str]
    SEARXNG_URL: ENC[AES256_GCM,data:e31uwvxGypdC6eDLp286mNeLGbE6+QnkfX/hefDMzlQWJ601fSRaXUp3CVrSDUZNqk8=,iv:JyxRzcAT/kdC4nevGcNgnR62MReWS3PmoJXRM8HafKE=,tag:3q1D/PxJ3iZilZHcy1mQMg==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:AfoJsx7dwAfkXUS8ZFCJDzLAvEAGKQ5JsPsm1vNTW4/Y40SldUDPzNCfGZoX2lOq0s4IFF9k9vkGTw==,iv:QmuFvXl6q0hILzDkXPrvu4XPbti+DkFkTQ8htYZ9a9Q=,tag:kLemTIT8jEg1naVd0OQ27g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSkdpN1FzZDhMaXlRQTNU
            NzE4MGJrL1BCMTNJRHpCVUF1VDMyc3hQSkFvCngvdTkwYnNRV3M0NHd5VXoxS2hH
            clRLUXdlU1RYYUYreVA1U2x6Wnp0d0UKLS0tIFNjYXZPYjFJUnlNSnJGZzdYM2Ex
            Qy9lenNPZVd6MGxvVURYUHVrd2IrWUkKuMWuOA5Ln5WTR86j546gvEM0GASb4CoU
            zKoA9BxDGxKd+XosLzc7niaaH2rk9SXU1ofsf9W0R6nB+Y9znuUfpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSW5LK3dFOEJCQjB3elpP
            UFRYcjVWSzZGSzhhWkZyM2JhL3NzakxkcXc0Ckt4alA3SEdZVmVuVDEzNFcyQy9O
            TGNaNkhQUGcyczhpUEpDUmZ4dEhSVkUKLS0tIEU5VlpWQkVTdHdPQ2gvWFprM3Ru
            QndXQkhsVmI5UThXZk5qS0dyQlNPcGsKC05Q7anRvOPHYc52mPrq/rsV/Le9Vb8a
            2nN903Yky6+BsYgsQsDz1zpEIOQP17M77fIPuBzLT2BDEAPvbIqRYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMit3TWplaExnRzgwSWcw
            cVRSb3BVc3ZlOFM1UldaWXQ0amVRNDg1TVRzCnRrNXZ1MEFyRm9xTldGRmIzd1VW
            aTV0SEJWZU94cTZrdkJFRjUyMHJROVUKLS0tIGV1MDlJdGlIdXhDVGo5UWVXY0VM
            SHYxaklvdDRPZ2lseDVaNldFR2h4aHcKWUga2TcMrfLkAlD6YZ1xEbsngDtVKi1g
            1JMxrPlvg8CDTVRzsui3A07D6sD9jj/Iok4/hdS25ehTnRnwF+pELA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T16:49:25Z"
    mac: ENC[AES256_GCM,data:GIMqGau4P7QDiqs9SYSWVVk0+SQQY/XBZCh3mEQhJikDQpdS/6E9lOF9LdMl9YLUyqP+1RG9TTizmNdnqN2G+ZwJPtcon2m8H0BerOttNhs6KOrSeTf/wejCvUe6clpZZCPVji0c7y6DrteyOVJQPVHhp7VIAeU2dj0HozI2NDA=,iv:sv1Nh3jf3e8d4a5fXduZ2kMVi/xDbESgGSsK4uIUaFs=,tag:wViuWixAW20W/0LhtK1WZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
