apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: hermes-agent-env
    namespace: apps
stringData:
    ALIBABA_CODING_PLAN_API_KEY: ENC[AES256_GCM,data:OesXXxFoH8d0x3KyBuDXN0LZPulLhxwxj4fCStCaTaFZi8CHfW0=,iv:loTsu1cj9Jw7QbY7rA1WrPJ+94uJLbHWdmZTd//6iEY=,tag:4N1uIePW0H3yYo7TOzmrcQ==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:KLEIdikFj0ATSOVOkL+CpdRGi0tyxTtb8wOmQ+emrWuUgU1+dg8Ld715ud1O4QcqPeIQ,iv:Lz9EtmFZj/OW8wR7IVuckKt21JjKzL1HU8uh4GsLMhk=,tag:ECwrninnRsAINQKjwo44Vw==,type:str]
    EXA_API_KEY: ENC[AES256_GCM,data:U50Jxx/QcB3gfIUIbPb5Cy4zB2AJCN9A60FG/sl+qwOMQM8L,iv:TWp8sg+xc0pa0UEEqHvuZ6Fz0KfEOjrHMwpeJa5FCa4=,tag:x8UI1Blj22eWCu9c7mbFEQ==,type:str]
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:8c6Vqk4tveNvrtpHwBFvHAUIceOEt9wFAcaP0/ZS5eDM9Rk=,iv:n6VALOsxTuiSXdWfMgGycjyPfEU8wYfXYEWLAFfiZo4=,tag:67Lkgw3mUOp45niUT6KSlw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:L/TIrkNmGCQPnY8osuRYhbte1IC8z78lTlabsnE0dAgXh9U7SLM0,iv:kYXtK2tPk6hffR8jF85SCZpVfe1us85bExS0yiPZ8gY=,tag:xXhKB/CSb3xDCD4+Iu4v1A==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:c4OdLUbSjShPq0S2hgkoS4JwxILE//XoCXK0MlWKXva2UYnPN032Wg==,iv:h/vwH8enUJXlTX4g+bCc7TzJPhmGRTOtdX1b297e2Gg=,tag:OpvYe8z9FxwKhKXyxgdpkA==,type:str]
    GLM_API_KEY: ENC[AES256_GCM,data:5JYioXN8zSwoO/DC9tMbfdU1SLo00ggB6gymgJ9zMmoJ+K7xpekFmT3oFHEi6A8kVg==,iv:7D10X9p4OTkInIwj6/hHDOeU9afBEJSHLGRGmN36FCc=,tag:cS0Tsnt5Me47P0AxBBGyfg==,type:str]
    GLM_BASE_URL: ENC[AES256_GCM,data:ObBfxq4T6loZ5CVIPaIattyAvx5GHRXKNznBvlIBIiVGSUc=,iv:avqos/yLJlr1GH3BFPgnBHjqurtNvePg6v3pgMMdw5M=,tag:T8OprT9Nf0rgbF0pfaywgA==,type:str]
    HERMES_KIRA_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:rM8FSYZx/OoSz78msLLi/valk108aGEcLQPzue4610s=,iv:Eq5qlNEsZ5mOcsnU9x7TItjhwByT1hfiCWTYZ2J7OYc=,tag:Q42uJSXtMYXfcrFbY4i3Uw==,type:str]
    HERMES_KIRA_WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:eLeMIPVbhk0obiL40cdRz47yjRM0h5/xfFWAFca4buWBwZYKwgnULRA6,iv:1wcPM+u9UXcsvjQVurXfY2xOmAsK+MLR7I9Z7++I1Tc=,tag:IdP05enP+ST4ONsrHklqVA==,type:str]
    HERMES_LUNA_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:dptpjUqNQs4oqV9mNXXSwD5TAS3bO0iwGtRik7lu/W8=,iv:CJC8kiQuG0o8c4O2uHm2/VIENdc1VSdpX2CXVwnmws8=,tag:8819sFcHP6dRmlwuh4qrNg==,type:str]
    HERMES_MEL_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:/XumlTxlOw6nUHJQAZMHDIVmZ/kQw/Str2YBXWpq4xI=,iv:NGzccENV+1WqyBIf3Yygf+O+pTF+TVnCh4ie/TCwQeA=,tag:BYCUB5qFQ8t/QEvjqCmyeA==,type:str]
    HERMES_SPIKE_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:rDZnLjKPkkmZMSmSXMrFjwHWbvdLZSeVYZlNUamzOUc=,iv:2G9cy/KZgzvZXAtV87JcI5imFHSzTwdqvxHHaJdiRMw=,tag:8qLrImLJ4I+Hz+/o10gnnw==,type:str]
    HF_BASE_URL: ENC[AES256_GCM,data:EE3iQDlMjXEC/UO6hxiQi+Hoj4hrHW68EJCa/YEVpMA=,iv:q9mfrfLHp9KQAvRLCQSJ9nzl768KPwUG0ji7XgX5ANg=,tag:6cUSfw38lHBdFy1uzlbVfQ==,type:str]
    HF_TOKEN: ENC[AES256_GCM,data:HKllmFg2DYv6Q9wcQiRe8wFzKExCDV/Rq6vVf9BoUSaGrop4+w==,iv:UWzw1jB2CcKbgKMiwA5yQNP4z208vni22yDFlhkuNaI=,tag:TK2O4MxuiKkqULcY8X9h4Q==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:P0Eg4VVZ4gAyfXeq2+LZcOq2U9JJNTIocZNAy2CRiKPY6Mql1TJJFTpweFi2muknzTxC6WgZWek5DoUe9/QHyDKESjtdNVhs,iv:5SrESuGfsMmJRuZArPTXagsTNdomUsCj0WYjKn4Mfsw=,tag:Y6FO2l6vyGpCU7gBv5HKvQ==,type:str]
    KIMI_BASE_URL: ENC[AES256_GCM,data:GDTJCl5EIYxc+KkA7L7WP+M7bmGERmSFDJjEO0h1,iv:kWVb368e0Wovy3b7Ty6vZZgXRaP1YSjKrjIz+LkKGjM=,tag:ACID96aAKwY5s26rNYSMeA==,type:str]
    MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:CHKQu9Tia0B/jr5V87hEXgeVISm5/Lv3rW+MNk+yQEY=,iv:wNa38qb7Twv7FOGIl24P3M8ufjtJwJIshGZr/HgYTDU=,tag:u6kcd/nXXTWENoznjC/DUA==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:8sfFHPpTMLqHpV8BF99K3U4j,iv:8L+6X94rJKq/90Cy0PAnGUQ3rR0Dxh9EL8pJUAiI5k8=,tag:VBtgJAm7sRccTRQJ2VxivA==,type:str]
    MATRIX_AUTO_THREAD: ENC[AES256_GCM,data:cHrPTw==,iv:XGPC7mCCdu4bZD9URgS++ue1l+6XkdCe6+LntoJNypQ=,tag:28a9R/InsG84aGXUqJ7dOA==,type:str]
    MATRIX_ENCRYPTION: ENC[AES256_GCM,data:czR/ogg=,iv:kTVR+ONjmJtfMLxiN2m1ZhE9p6HfHRmNH6UDM2uKuM4=,tag:2BKWHG0ZLiTSKJ8P9NWkrQ==,type:str]
    MATRIX_HOME_ROOM: ENC[AES256_GCM,data:J3qjYuoJzwgU2j86oSQ/G3LNarvEapa5fKCffSTeQZpB,iv:Yu1O7Tt0tEvp6FyvH1dX4giLF6g7L+h427fbUYzFGuM=,tag:LlI5Rkz91De1j9CtdgC/cw==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:An0m8Yl7MrKQgu+fI/7JAz//ANsPLU+bR5O4vmaRYdWAkPrAketYWa47,iv:JNFs40k3hdf7YSpSMI6pHLqF1HT7YxTyMOXhlE4/vn0=,tag:ShP90W44YFFNoZ5JfAc15g==,type:str]
    MATRIX_RECOVERY_KEY: ""
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:1yelEw==,iv:5Fq/Sg22mOo53i6IYIjF7J6V47YQn7peZhrY+8cFi/g=,tag:ya+TkzkgZiFHvC3V7xKS/A==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:mUEvxlg2Us3lTGZY7oFVfc0loSl8h65gunBlPyv4ZvRaPrHud9RiDj/JdSe2itwrx5SiqiZiMydmOoywKwhg7ztr8ZLucCb9foYsH0pWoKB+B+bUVFS8Se96pmI0HwsNIabsjJCXYXV0rlhmwauoybS6GGFcVR928J8yvwU=,iv:vexDz1+8LX27lrguWdD24Gc5TRV3zGDPX8NN4ocaOJw=,tag:CjnRITQaDtQNojZM0Pnq/A==,type:str]
    NVIDIA_API_KEY: ENC[AES256_GCM,data:Q7KGoNzanYHZ+MS9rWf4KpYib3uBluSOTh6BTq4oT2JNkEetqXIY94FbvkEo8v1+m0iENT+4AYEpYV6QFhGrcaSPoosbug==,iv:M5KhZUsfH+PeO4vYtzxbLReq9CKplYN2rCkZUBtazxM=,tag:s3B38UTiiiZXi/Gmtk5Pzw==,type:str]
    NVIDIA_BASE_URL: ENC[AES256_GCM,data:WrtYTMN9qmjCqcyfg4ygTlhpEUz9ggUtB2N5UU7T+zl09OQ=,iv:Sy2+xAFnsIQmOzfHSZboKpah/DA2+7ALssMCGTh/pb8=,tag:/WvMb2W0xhcrFJNC0fofqA==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:ICCgyQRozSO7sT4U7oHKZvfdTc+rUN/JK5zqa7Rn5C/IkT0=,iv:ZT2BKcOZsnuNgl3oJWfh2l0sbz3SkmG+8MB2elKEqcI=,tag:FjR+ToXdswcLkRZmBQgLEg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Id/bVyW197IzY/Pwkn84ghyl4/fJzTpYClfSFlU1dxGwBGfuyponEWbgI7JdG81dG5Sx4xhBSjF8jDxlff5vZupNGkbTfeXxVsKGKeKz3Z/yj2DauNt3vsjZqa3OtR0Lkj7wP78bs3v9Cl69KjJ06vttBHXBETOJBuAGYTjckmeLagnuV+Gftk9sReC8fXg8nD4Y8eQea38vJIES8HONXF201xI=,iv:w+oeJniE1/Y79Tlc4CnYxuX55LoPAhF8LdyFPIdAsV0=,tag:9vFs+1GZpbaeAMntAsqAJQ==,type:str]
    OPENCODE_GO_API_KEY: ENC[AES256_GCM,data:1WlbHw/Jl6OdtCfFp/HflnowFja1SvJ++AkPIN1yz6ITdZJelyBlAE420JiT6FHdImnL2csjVKlRx9oxJu3R2+nDJA==,iv:JNAaJFxk3SVOFzhdiC89+4ocJAqvvL2aHN12Y1ivFc4=,tag:qCcG99SJxYPnCJH8jW6d3g==,type:str]
    OPENCODE_GO_BASE_URL: ENC[AES256_GCM,data:RQhXK2UHVk3kWFVEzRs6AFzXWiflzVDEavtBJF4=,iv:ezlzQrXb4ChJgaIyYUm4yXRBStHm54G+LvUpTF1qv/s=,tag:ngguZaf1lVayzJ9Hl4L5Bw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:RfDLGn8deocRpl4W+fY8jYkigODEHXRSQDe97mx2vNujSN9n2VWUbQd8T+JcouOKXWnZD3UXIQbmSKtaFTQeB4iMYonK6N6VmA==,iv:VSDJbnt0TqrdcjwUo2eVzeAx/DsY8iyuumTJfI+30GE=,tag:HFo6kfU9U+wI3Cf0BiX2Rg==,type:str]
    OPENROUTER_BASE_URL: ENC[AES256_GCM,data:juUVnSciHrP6Q3qcXgghTxBFYwFCZqq4XH4ITg==,iv:dHwqSc6NYvnvL6SUZ+pDaymCK753RWQ0J3fJSD9uj/4=,tag:+A/XO8UGuHDVyqeSAiioog==,type:str]
    SEARXNG_URL: ENC[AES256_GCM,data:ydxdLMyicrAnc9I1WxfEa1U8juEkv8C9unmVToc0UU2CEfHApd4HiZLj/LYwRMi2wug=,iv:3U+2A984HitgTC+PEQYmn02XDwmQPtJdv9uHN0Oxs2M=,tag:DrKg8m4NlmAPXbq3GU5tzQ==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:JGra85eN4cZYu9cZQ2pUCMIk04xmWORst6srMeBt06J68Yu9l76fpt6rH/zr/L/SkOfmsBHwmuTyPw==,iv:eexdpdNyyV6BFPCHxdxfW5eGofoaCej04Y7SEGuny2c=,tag:g6oO1YXgmH2TvP2yLeWM6w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSkUzRlZoV3dSNGw2NE1C
            cUNkY3RMNlNVZzAzdW0zWkoyQlZXdVdzYXdBCk5BM1JwOWJMZ2M1SnE3dWVuRUd2
            NlRFejRHSE9GSlpGMHN0LzBnckx3OTQKLS0tIDU0SFNIU3J3dE5tVnFIaWFMT3Q3
            ZVloTkx0TWF4WHQyTTVIQWIrbHQwUW8KhWRLE9DiA0vBMSODgXJtkHCtGC+eoL54
            gcoqrqLPjhzq4Twn8ITD9THotQZxd0r4cTV3YTSIPrHYLwjQcRBocw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL3VIZUFPMGxBcDd0UEkw
            cURkbDdoK0lEbHMrb25NRDBMTU5ibk42MERBClBqeHBROVZzM2ZyeFNETUZqa04w
            b3liUU1GQ3NqQWJKK1NRVzVVOWV3YVkKLS0tIERxRS9UM3AwNjJpZVpKZ1RBeEIw
            WmdJVHNreWF1QkM4RVBrcE41c0U3a28KxBtmylwxDoSdsI1ngA7qyjPx7K+LB7iV
            cWLhgXF/tO5Zt7YMS91tgWTW7lx5GLWAmJoOcCLaZOzTcTnRLduKkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpU2E5bkpFaEdLcUFVM1l4
            T3VNU0s0Nm9GRkFHTW5oaEFzaHE3YStpZnprCnlzL3JxWjZ6d3hmWm1CcGdTQXBL
            Wk1QOXdUbUNBWXBsVE5oNEQvY1pOYVkKLS0tICs5SUEyaE93N0dKbjdqbUlrNWdP
            bXRtWGl1ZFNjcHdMdDF5cnUrZWJPaUkKtJ/ULQ3L/QkN5zmtCWBLYUL6vTlWKpa9
            sEUVGkEW2Abv3hPzws5unknFWMSZ4qBIIz7eZgPGS/vcvsP1WH6LXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T22:09:51Z"
    mac: ENC[AES256_GCM,data:YIRkFZ33N8rAJJBxtqKJOkv0sHkFhLIAqKMmLzt0MJ/HnBcmG0nGmKDZISj9Ga7NAnewpcP9F9/dNLF/I4/mMdRwxuiGBCoagK1QTkLfRSdmVovbYBdq4bub1ewDyjoKZMPgEdp5J+UBKIY0zdliphlHLprq29guwav5fn0qNNI=,iv:PPm0Dtfxp9jaVDgWeKZGSh1bxO98fV7K8hFF7vfk/BI=,tag:A9N7rtpSKvs0nGqFULMOsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
