apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: aedb1aceb8d691741bea6010ef13cfc1e4446312
    name: hermes-agent-env
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:4q2buCirmx34gHcrgjCupVVCx8W8dHHTAulBan4YV6giImVXnqMw4PVrYy0D1UEZiyK2,iv:HAkbl9Lxz/Yd+HKdJAkqAF4h2Mg4V6uJYDQl7lTJyqc=,tag:BICPbUnYfnpoEvqEMBb5lg==,type:str]
    EXA_API_KEY: ENC[AES256_GCM,data:Uw7JMcpdg4G4egyNpktEAsFMPDbqT9OdNK5e4CntCN23y8j8,iv:HEdR8YIxBsBmJCXDsXo8cvP5i8X9OZIlCXjVKFHXl4o=,tag:nypB8LJ4Xw4MXhbYbtHCEA==,type:str]
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:kXYwBQ8zSCbwFEkzOmpoZjQp/LRS4txQTQwyUhvW9D4H/Ws=,iv:jYE3dA+lBjYjDyo25kQNJuKQtTXwLiLWEtybTEx/oC0=,tag:OC3+6pTdiVo81/9l6uk8sA==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:uWUFpq09YaR1FR55c0pVwzFLesqFG0JR/eUO7xoqO8Poh6I+KqJu,iv:n65vFOaDc/2qsEfo1mrHgYPIBzpou59T8MjkvilhUWE=,tag:pTxFdZpGqJ36+ftwkRyjCg==,type:str]
    GH_TOKEN: ENC[AES256_GCM,data:b3CHcLlxZsLOWzIlYDUZWkPM2AzhjM9DK+48pY+6fGmYmZfoqXgAeA==,iv:BWey4tPweJ50InJ43ZOgMn0zjoV2FL6FVIBNH2L68P0=,tag:VNQDPwNd6h3yKeShm9EHVA==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:voxRHUz3M7IxqQ1tnn9x8JsT3uy0Qk1KKiHmLYp5829/jQRXdjArMg==,iv:POVrVpetmrINyzdmCPVOURTO+ZWmP72DheOXRrK2DaM=,tag:GKsVIoO6fT7eiDgh4qvXeA==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Nc6jITHcTtahAVQ17gh64MjevJJiHg==,iv:cIhxVIeU4pPDSM+0ag6oVAHqhW8Meqszwp9Yrd+6Vlc=,tag:74UEmxLb+DWNjUyMKNfiGw==,type:str]
    HERMES_DASHBOARD_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:dC3v+5wh5WKzObPNwBN6dteKQoQegPADHpGHLVih6Tc=,iv:njCPQnHJd8kR2A4kuRpYLx3Nd5/1/EaDepzg7GAYRXk=,tag:rvypT+cO37Dzd6QPFS3c5Q==,type:str]
    HERMES_DASHBOARD_OIDC_ISSUER: ENC[AES256_GCM,data:a3ML595swEoq3GB6jvQTMuGfGv2dm2vr7S+RCNYIJkX1cGtFmUwMcW2NdE7w,iv:132bj/A1NECY5yK3WqngtiEcA527kvASDtJBZSy6Fzo=,tag:EpHgdo/iErRxOqIF1psDxA==,type:str]
    HERMES_DASHBOARD_PUBLIC_URL: ENC[AES256_GCM,data:zzcZJT87hLesi6ZxcJVzTTvSSdVkFHUWerbBuw==,iv:wDXOG0sPTa2ZVrmuNTAvY6lBEwdmqOR1BLVU6OATG8E=,tag:3RDCTLpN3e4/wf+idXYxkg==,type:str]
    HERMES_KIRA_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:H9ffl+53NROfTUmscz2BNIwiI+rLAArlTacmwbl5CIk=,iv:T9oOZALgMC/efzQVf9K/fHhRn331PE+DwG0T3zUhPIs=,tag:eLZFSMwz7AvXZdWCZl2udQ==,type:str]
    HERMES_KIRA_WHATSAPP_ALLOWED_USERS: ENC[AES256_GCM,data:OSDRyzkoWWaQD5jbPGnbtPx8lTkkATe3zAdLCWFIo/Ca6zezdI9/AA9N,iv:3HJcowFUxCe9v4k+P3IYDJSA4dksGQSTW1Qx5go0/rg=,tag:DxXtCv35eSWbPT5u+ShKEA==,type:str]
    HERMES_LUNA_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:WBnH79O3W2ojW9NZ+cC1j1y03BLEgsDPz+SyGQu5LqE=,iv:BovgLwGGpy5dKRjjYWkFwjTScVgbbcib42O0dYQDZkw=,tag:ZUZpeuUFjeaiV1WYzSZN+w==,type:str]
    HERMES_MEL_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:cfnnmxz/ywO/U1vFXJyknPzZk38ZWrj8ktQatL6hR9c=,iv:b+qDmz2OyodfZ7FzeE3U+hXBzTvkwkD7avA+gxZ60BU=,tag:4v5ux6hk/81GgaewiPFlQg==,type:str]
    HERMES_SPIKE_MATRIX_ACCESS_TOKEN: ENC[AES256_GCM,data:10IDk9iDW+8Uzqh8Y1mY+W2LMGkmxvdiik/SU4UZyoA=,iv:lPq9zN/OuxAGKDALwu7M3QyQp19TgCYuevi0NQJtcHo=,tag:dIe4fyhYFQQDdE9i+KUaMQ==,type:str]
    MATRIX_ALLOWED_USERS: ENC[AES256_GCM,data:QKy+YGw62zJG3oRJF4TVZqAZ,iv:rus53L3m121QIYJHsMO+cH9IcOirnnS7ivsrRsalagg=,tag:TJCik+F2sisrGxdZcTHu4Q==,type:str]
    MATRIX_AUTO_THREAD: ENC[AES256_GCM,data:VihTJA==,iv:p5YAWzXEl5iB3kfQAFbLeyzkmPywu4RxbUyk8PeR3CY=,tag:WbWwp3hbsRY56aI3uOqs4g==,type:str]
    MATRIX_ENCRYPTION: ENC[AES256_GCM,data:lTslHpQ=,iv:b1No2duFQWF90xBo4UJzCekWMh27Hbf6u84E+5jWW1s=,tag:cRner45ORIzcgYi40fBK+Q==,type:str]
    MATRIX_HOME_ROOM: ENC[AES256_GCM,data:nSfs9G8C+mlVx015QxGSSllRMn4fP1oqQZUbwSjHkugZ,iv:QuD5RDyRHBwdJLpxlFe8/eEGf73GBuvDVnoJNSQCXXY=,tag:O4+xlkQad+C3v0Vo0bvr8Q==,type:str]
    MATRIX_HOMESERVER: ENC[AES256_GCM,data:afVwk41Nggbhp+QOtt6HhHBXFwcKrPWFVQkWpPfvzV70K71WJQYGDiBB,iv:cDueIbPlGuJxAvikya7+HMTaDPAtIxJ2zdFHUHcM/ms=,tag:BM8711/V1xGojkJ9jC7oJw==,type:str]
    MATRIX_RECOVERY_KEY: ""
    MATRIX_REQUIRE_MENTION: ENC[AES256_GCM,data:Z5/qDw==,iv:v1ThNU3sQ4mxuW8/IN4V1CLTdA+/tFVSHiU9Dg9ZWM8=,tag:sO34JzHVMKIbc1tiJfo0Dg==,type:str]
    MINIMAX_API_KEY: ENC[AES256_GCM,data:vRStCqN6gOby96qIhH5HcZas9lXL6ju+Q0cvaxdlFX6gFHMn5fNdC4nprPezqt2wW7nW7BcfBxMxqt59BKBU2sXqPSnRD8jm+7SZID+OtTWo5F3cS2uFzu39gP7AbIDgtP+FYwPjpopj2VsuNgNNBSwsbiZWI76Pvy6b2O8=,iv:yRsAaodc2oqaZU+5zePPhwwWmmQRvSEstDwaKcT68qc=,tag:+fz+RW9AJm2J5dycQAyOFg==,type:str]
    NVIDIA_API_KEY: ENC[AES256_GCM,data:KVeh6tg8HysWD0LUodwoOpkZmPr5p04rzxaB31lziTKkWCtXQXx759aYBfTmEPLXXHruuBxZKU/LlX/3yCVXBiGO52cMVQ==,iv:OAyWl+4hGAGnT4BON2d5fgGt/c23I5VEFtHuzNAEKBo=,tag:/SobxD23AHNVOTH3eTIdVg==,type:str]
    NVIDIA_BASE_URL: ENC[AES256_GCM,data:IdBUNDgOvcz7/VJB+R+IUrMRpeE2a8EHT5oV3r0YR49l3Dk=,iv:PEL6yhIK0YtzTn8q8nCphoNyIvfKZBd2rsnUCm1lsFY=,tag:PVLFUUBsQoNg2Wi3rk6nkw==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:L6QxQlcwDsh54s9atqwSM2TBfaEKm64pelXa+D2D4eZedkQ=,iv:kXE3VSs1mr6XhkHKXUN44KdadHPzd4/SnE5s2F7ATk4=,tag:wGigR7kz6HQVdo+7q7MdZg==,type:str]
    OMNIROUTE_BASE_URL: ENC[AES256_GCM,data:R5npfHp1nW10qJNqoL69GDWFKpPy1I8s2ACuhd6lLu6CPGyzqsY=,iv:jS7tg96WUa7uQG6xvnuK+Sx3wylNI5ZnrORopTeFOiQ=,tag:lK01rxsvQUdUSS8Y4oh+Ww==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:a68rTyAfZV6R/HN9hGToNYpcIEEX5uQUykTTQSQ2y7PgXTpNuo9C/l9HeI+vQND/To1yAQgP6eCxUwXa5zYwdBucZ1oCsSqeMAg1uLlOsAZrReVy190X/NQ2U/rna7uUTr++me5mQ9JNJhmA82nhAC7El0Vld/9mzd4lajqwQfJo4X5i/hgIs8Gj0SgLKnQGHEW+E+aSCoz+1VMmprYuq0TXMEU=,iv:eTflfOIHnhRf8eIrFrCdeIKfBRX1R+Fow83USboN/TE=,tag:ezRErlZ+U2NweMeNQsxnGg==,type:str]
    OPENCODE_GO_API_KEY: ENC[AES256_GCM,data:0/LTy9v66OyTE46tYv4h7QI1a5vl3eXxcsLUOA5V5R6Q0KZ+1YxZm6nNTVT2/dGqEmuUt5UA1ioo/iAmX8AdRuMGgw==,iv:h9BubRhqPc97fH/QczG8jXfPytRlJVa1tr7byJtiKts=,tag:tGXVP0xV1+ki9B5inNdZpQ==,type:str]
    OPENCODE_GO_BASE_URL: ENC[AES256_GCM,data:cHAKdlbyeUg5ONQYz/08h+3LCSPiNm+tQBHbaes=,iv:hIYaOfXpPM9OLgno+vQ3wGelWfSSXz4h+tnY8635Ak8=,tag:6H6JU1TpkCUEJLQ6Sya61g==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:gOahX22fJSPREpw02vUNhGU4tozXsQ5cyNwlyMW55A2aBM7TJJnPpN73I3DXL+N4VTAwXM8eg41iGnlS7Wnh5iRzGWYQjcIyQQ==,iv:hV8tZ0FJiLzvaZxLbLvWMyWa746YrVl1oLx+cE8CZao=,tag:0EAwh6/vNpkcJIg8vr4yOw==,type:str]
    OPENROUTER_BASE_URL: ENC[AES256_GCM,data:6lOXOMGDCsVYP1QWHGPA8HCRTi+COj3hWkFm4Q==,iv:s68mCtpzLGrUAYhxBel/dVo6agWJvUHeaObBlQM0fsk=,tag:Sf3o4RB/q0tWbkgA1TLPcA==,type:str]
    SEARXNG_URL: ENC[AES256_GCM,data:vAxihVbZ+/JgiHCciGojxBYg6/DJjTZuT569G1D9X3CTosiCXxTjaSRPm15bXkcOdoM=,iv:la4ztDar8Gz/Rkzb1sEnN58adFOIZoLf+bjPogewmro=,tag:I2ogdwJohkT/4xG5GKhIbw==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:HnrMc94ZFiSJGeRX2ChxD9HhxhDgBPo43bWvDO4lQbU03XdsjMr3g+1aBW0lRm1LCAjbL9+U5Z6Yyw==,iv:oeo6HsnDNFyX9fSqIEfGINzl9df/MeNAGMlTrFmKJao=,tag:MLH93pFhKG6ZW5QlJy5CLg==,type:str]
    VELOX_API_KEY: ENC[AES256_GCM,data:ISpA5NlUSLUnviXYYbbddMpjLPCy8qF94UPQEBkaaUqepr+G5zbT+5zx4YezJJmdUsAvmWjABuyJ,iv:CbYuImi9awmTt7LsmsmNZ/vrpcfw9I833XjuaYUBIPg=,tag:oCCIvwgrAF/UHo7P8qTCnA==,type:str]
    VELOX_BASE_URL: ENC[AES256_GCM,data:QjOabvm9aFvBbGGEVXbNPpwonx78hsJJxB+T+MIDaH8QIeMnGIIzGtTc/g==,iv:KwKGaZTzpetP0SB9TRl3pyrUMDY/PU8psKrMJ8X/qFI=,tag:roFoSznAmuacyvCLFwoEIw==,type:str]
    WEBHOOK_ENABLED: ENC[AES256_GCM,data:/USjzg==,iv:wwNaVMasPlqbFzX3o3Xy6Q4WNQI4yhuUqV5PchjJoEI=,tag:2DZVs/h5J8v3TksXUjYwdQ==,type:str]
    WEBHOOK_PORT: ENC[AES256_GCM,data:rQH2Wg==,iv:ju/dRK+aSI5FlXIcrltyBYhK4RyLHxabyRzlwF15LfA=,tag:AlMoy40TsGb4r53ZiwVB1w==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:GZyPg0KCbJH92EQ1Bd/ngvYdb5R00cyG0tZgsPr3yiwUSDqwMxTTmDrsjLeNFiKi4Kga0Kdem5uToUuZa6DGMQ==,iv:04HYqH53v/ajko8Njw6jt1KSgx4BAe+Nca+To/D4GmQ=,tag:oM1KNZJqerzZOxHGlkNpJA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUklSZHhJc3JCazZlTzk4
            UzgrdDM5a1lGMm05dFByb29KTUZ2OXRieEE4CnNhMkF0eWRwckxWelFpWjZMNmxX
            Q2FEd2lBdmM2VGpMaHNMbzhzQlBBSUEKLS0tIEdPQndwZ0N3VUVBVFppaFRHNDFx
            a0ZESCtweFh6RmtjbmYvRm0yN2lQMzAK2c0FDXSp9BrO4+hgEiWUaeXfFvfOkXUQ
            hlTIQ2Lvd5aCPFe/d09NCmxrNWzdfyj4WjGNqniA9/R658cYnZopKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVkMvOGpEQ1pjSWJzR0Mx
            UEtJblNZbThUdmx3QUU0WEMwRnlNcFNRSDM0ClI2VWNpYTg5cFV6emhSRWp1eWty
            OVdJeUNreExMeTczVUFlV2NiU2xOMW8KLS0tIGtPTDlKV1NYYk9nQjRnT0Z0eXh0
            NlNmcUNVaFR6SktpelROSVUzZ1RjY1EK44j76kUMoAdtPF1QcLvtg4wCCA+cJv7E
            H2l55JJ+BC17zEGWD8FSWQyJUHXCaVCXeeJP9cgIZvfB3PZWoPxkJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXhLWXJZSHFFeXo4V2hl
            dlQ1STUvb0dYeWYraE5PUEhES3VnWTAzTzFjCnVGK25Wc01vbVgvbHFJNXN6VFFh
            ZmZrZWlEV1oxaThxb2tnSEhsMDZsYTAKLS0tIFpxUGJQOXJOcC9DRGJUN2Z6eW9M
            V0hickl2cjlqT2JPZU5sNXdzRHR6TG8K7NG6kMoiBoIX2Eay367lZApZZ/M4VJA7
            UK31ccm9gPzZfx+QtZrXeJw2FHMy5nCSvIZuZA6ZyEJp4s9Ma/xDkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:04:51Z"
    mac: ENC[AES256_GCM,data:xbFe57+r+yKF9pRZwTKoOcw/p+pf9zmLM1dx5VlprC+f2xGsKXHd3sb7/ob/0XsiMM0F6g2hVJec6mGZiR1P4Sj7r88AKQ8TQJWNVBii3tSHwWBuY85gmTlQ7xwzbZ1x/1enXSnTnjQITfmCURIKPZWUzBfayJRXKP7SAnInh5o=,iv:wBcOJWL2iypjgWUZoKa8j2BnGaICR/YQAJCJ5Zevyjg=,tag:Ir6eByao0cQ1NFJa+V4BnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: aedb1aceb8d691741bea6010ef13cfc1e4446312
    name: hermes-agent-sandbox-nix-ssh
    namespace: apps
stringData:
    ssh-private-key: ENC[AES256_GCM,data:PeOUzp1+GlD+4A6PcG+NdmaO3lO9HOHkld/0JyTaXv+7RKCXk0wpPiGdmKW9WiwYzVvsgrXZ98jZvvOg3CXYAo9Z0PXmy0wIRQxawi9MxljWw+SO538FFFS8+FF2KR7Cddgpn1tUhzf6Zm/82sZ4u4VqrV2oD90nsF94sHvFpUc1QXKs1Y1RdrQ1m+l4MK0wEiRZlOBDSga44Uj6cHrbJI28L1HgbCXNVoO31qdU4ddzOfHxziOpfScaloP2AWD9LyK+ilVkyNkxFwtoHNIK1x/uceBBdOztyWqJ/ekTt5dQdjNQgZ1PDD/mB8KydU0/4RKP0ZV+UU0V9SMAeBXgwJuhCKmbiT0VFHpR5p9O5hcurfsGDKghcJX36JTDWNPRQsxE/q+FdYt4z1+yamrO7cjCByuUzHLWq65K52h+rOaK3h7XyV5r/HRg9MSnVLa7vdhUMb5qlTdHge0xzemWz3uDv9S550YBbJzcMnM8ylc9+Fw/POwmKjwidgP4scHiC4F1NYheOeJHLLPPyyfe4den+Iv2v8EkGRWov2b3wA79pH4=,iv:tEWr2xTT0xHPZIH5eiYq9sdMq/L9luiY4wl9c150XeE=,tag:/bVGSbKS1iOcZ2uSxUnJSg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUklSZHhJc3JCazZlTzk4
            UzgrdDM5a1lGMm05dFByb29KTUZ2OXRieEE4CnNhMkF0eWRwckxWelFpWjZMNmxX
            Q2FEd2lBdmM2VGpMaHNMbzhzQlBBSUEKLS0tIEdPQndwZ0N3VUVBVFppaFRHNDFx
            a0ZESCtweFh6RmtjbmYvRm0yN2lQMzAK2c0FDXSp9BrO4+hgEiWUaeXfFvfOkXUQ
            hlTIQ2Lvd5aCPFe/d09NCmxrNWzdfyj4WjGNqniA9/R658cYnZopKg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVkMvOGpEQ1pjSWJzR0Mx
            UEtJblNZbThUdmx3QUU0WEMwRnlNcFNRSDM0ClI2VWNpYTg5cFV6emhSRWp1eWty
            OVdJeUNreExMeTczVUFlV2NiU2xOMW8KLS0tIGtPTDlKV1NYYk9nQjRnT0Z0eXh0
            NlNmcUNVaFR6SktpelROSVUzZ1RjY1EK44j76kUMoAdtPF1QcLvtg4wCCA+cJv7E
            H2l55JJ+BC17zEGWD8FSWQyJUHXCaVCXeeJP9cgIZvfB3PZWoPxkJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXhLWXJZSHFFeXo4V2hl
            dlQ1STUvb0dYeWYraE5PUEhES3VnWTAzTzFjCnVGK25Wc01vbVgvbHFJNXN6VFFh
            ZmZrZWlEV1oxaThxb2tnSEhsMDZsYTAKLS0tIFpxUGJQOXJOcC9DRGJUN2Z6eW9M
            V0hickl2cjlqT2JPZU5sNXdzRHR6TG8K7NG6kMoiBoIX2Eay367lZApZZ/M4VJA7
            UK31ccm9gPzZfx+QtZrXeJw2FHMy5nCSvIZuZA6ZyEJp4s9Ma/xDkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-19T16:04:51Z"
    mac: ENC[AES256_GCM,data:xbFe57+r+yKF9pRZwTKoOcw/p+pf9zmLM1dx5VlprC+f2xGsKXHd3sb7/ob/0XsiMM0F6g2hVJec6mGZiR1P4Sj7r88AKQ8TQJWNVBii3tSHwWBuY85gmTlQ7xwzbZ1x/1enXSnTnjQITfmCURIKPZWUzBfayJRXKP7SAnInh5o=,iv:wBcOJWL2iypjgWUZoKa8j2BnGaICR/YQAJCJ5Zevyjg=,tag:Ir6eByao0cQ1NFJa+V4BnA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
