apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: hindsight-secrets
    namespace: apps
stringData:
    HINDSIGHT_API_DATABASE_URL: ENC[AES256_GCM,data:I89a6/Qb5Ui2x6woi6TcY2C8P8KjTleqByrszJKrLTOc6l3D8gZGjGpUPqkVZaM4Bt6AY5RGQ1NHX9tpWcLJE0gR3dz714KuCA==,iv:3Fy5FOtRlGVukhgQWIIOb0kmldvYek9y9AQ59f4NFPw=,tag:TRVIsAzMoWKCcRfZKyr7mA==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:J1Y5rPuIP+HrDnHPtFMwKFjY1ZEHuYpH1c71oLmBaFZiXkc=,iv:ZGdzNTEKIACT3qvcASNzVrtIhYsRs6he8rWO82QWtS4=,tag:kOf5pujCgNouhruGwezJuw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQb1FQdGszRWRDMHdmTGta
            SEI5QklSSnJvdGtBdWJzeSszU1N6N2pweVVjCm80S1hoeG9GVDA2TjhqakVVQ20x
            dVBhWng1REg4eVI1WmhpVUhFSEZZYU0KLS0tIGs3YVJHbkhITzlsY3BtY2czSmh4
            cjc2anE5SjdpWFZ4Q0lqVnlPbWx6Y0EKoSGA2yRRgHMD8W6M3iS3Cd4tZGt0tPm4
            lwkHl6w01CYb2vFE2H+6NuYkF37Usmypo7xbEABNf87j7iOiZ0YPKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aSt6V2ZhbjRCdUJaSWUw
            emZzbER2ZEdvRm5MS1VHU0NYWUlGc0dnTmdBCmRmdCtpR1FyR0RwQTNQSTYzdEpk
            MW9reEwwNHh3V0gxM1hwbGxhZGpRQlkKLS0tIDhMV0xZdm5McVdYL2Y0UEYzMmlW
            dWJjMjlkTitmbTFLVksxNGRnNUk2MU0K5Bc624PR6vwUPVWjvDMMdXRJO7j4g29N
            YZJdPleXoULiN4r+W0h8rsHn49pqqmNZC0xdatf7cwt6dpxq1rL4Cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRFBXYkNCa1NmYUVEeE9r
            QzgzTzNoUkQrT3pRNnB4N3g3d0JaVnRRQ0VrClJIblVMUDkySlczNWRxSHVBcnpF
            SlhieENpSDV4UjJYUlZKV1FwVkdDa3cKLS0tIDRRWVFHR3JhYUxiN0RtVmxONlJT
            RCt3QjV5TVdsQytsUXorQjZXdTcrZEEKQNF9EpQcB0A1suGKExrGMjm52/jbr0W3
            DjIJX/0FpJ76uiN8fAdJJZKynXKre0iq/soibSIqbdlYqu6vGo0SLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T17:02:40Z"
    mac: ENC[AES256_GCM,data:ZVdhWIPTy63kbyCHL//76cVrsei9vt7Z+y8FUAT9ei2SSyvUNnkgSVweczSM+CANbgAfIaM6L8Kgm/0FxPGwl1WGzL9SoZb4yn8k3q4jA3XtqxqKensjbsdRPmzrijAF4+4FYiRT4PSWN2+2Djvq/ddq8ViN1p5Fnhws0AeQvJM=,iv:uttmHhqKTXcIT7rmyAZF5/RJZ4i7/U2LJ5ExTLmujcw=,tag:4s8suvL008/fI1yhJYi2xA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
