apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: hindsight-secrets
    namespace: apps
stringData:
    HINDSIGHT_API_DATABASE_URL: ENC[AES256_GCM,data:jcSntGNpoGgZpcLDjBRyGPAi2fYhWBp6iIFiE1qu+iEeCt4CO6cjw9NuNkZK3ptRFqwiebPIdobypBtXyaRvAbn65sJXrjr9tQ==,iv:D319ntlQoQ/BWxFlPogKrj3wp1UuoPixNxdkaZNYiLw=,tag:wmaKZghE4z7rJzCdcYtKPA==,type:str]
    HINDSIGHT_API_EMBEDDINGS_LITELLM_SDK_API_KEY: ENC[AES256_GCM,data:SW9TO77UcKvWuUmDgg38LkzIH/qopcOU28PNP1HB/XPtp5oMJ2UVe7/M4lZzZEZnf/C0ZSAHc6Nup0G0KxLyCHNS/Jun5cwhmA==,iv:CrD7K9iYSPBmrwebX4Bs6fM404zoRhStsWP9p+oKZv4=,tag:Stm7mzcX9dLDNUzcelItOw==,type:str]
    HINDSIGHT_API_EMBEDDINGS_OPENROUTER_API_KEY: ENC[AES256_GCM,data:mfXeROvcidobbLbyfpx5WfvRKbESg5p8ZBWdNGwmzdtBSx12UOsEISMo5ipGxKz/R++tuk4WvWr4EPQBXbVYOtbqrLKfW7v5kQ==,iv:R0TAI+WOVzrKsrgxwsZUzsE9YxJ7rdG14v9y17pD3+M=,tag:2iI9hssblbnvt4WxdxTAjQ==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:Bm1QfPBNAlBEdJ8AAXNRj1vhCFtfdZA2OX+BiwAI4+SI6ti+w7q7bEnBFv71xUX/ogn+/JVcM2GVabDOUJv2jixt5zR27uEhZw==,iv:b6wNCysKw+rOwlz9cmpooaPDhRf1fGllBc/kTN9mT9M=,tag:GRueM//v3H1fsxWq93wk+g==,type:str]
    HINDSIGHT_API_RERANKER_LITELLM_SDK_API_KEY: ENC[AES256_GCM,data:3pvbeIMonZme+u9CTaG3I/IsTZ2PMevKfjK+6ddKoXlNvdO19vNCfmTZ5JTjnukb/TIQAQUPiXdDfQF+ZskFuuH8fTlq5g==,iv:Cx7edqkZmRRdjnb6iSGlwjXYRh3uDmF/vSHtcoHCKJ4=,tag:rx99xAnbjAItCPHtc/LEPg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWWMyK1RiaU5PZVdhR2pE
            MmVGZWZUMkxMbUdzWSs0MEl2N2FrMDNnUmw4Cmtjd3M2cXJQU3NrNm1iRnRQTUlJ
            bjJxcU4yNzdoYmhMR0g4eTdQUWxIdVUKLS0tIE4yKytHYy8yYTlDdUJZNkRRWTkv
            eGNTNTM1UmFVdHdSUFhBaml4WnJOcWMK9knNSR1p8iGunYKt5Ly4eLcjQNxUop+r
            mdhGGuG+E0Y8rWcCMCbIfFE1P9jKSfBUQ6rICIDYHloJku8vh1t0iQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWHFtVGMyWldXWnMza1d6
            QW5lSTB2MEtXUko2NzNJWExMK3BJcnA3OFVVCmoyVFhGK2dNL2lpVTM4dE5TZVIv
            ZllycnoyWGg0V1pmcENHamtyKzF3ZXMKLS0tIHAxMmJJS3dtcUhqTmVjYUphaDFo
            Njd4VjNOeTRLbTlhWWJKdEFpTW9lM28KUjCb9qkU6oTsrXQdxMp8NItq/tTigqTD
            eX1e3qXu7pjWlZ8segJpdhL5ncfu5WOX1D2KDEPZtTaQrd0jP28nXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMDFtT3lRdHRNY0JrVDdH
            MDZXZmxvNSt2VG1NcmZPdjdoZFRQUWN0alFrCllVM29kUEwzejcwbVM4N3dNNStl
            bEZhNUdZcGJBUGdsUXlSa1VmTVA1MUEKLS0tIDcySzZYL1NYNGNOYjVZb3NkcC9H
            Q1Y2V29lWmNDcFZ4NThqSTRHTCtiNWMKWU5D7odPlF9us4LpKjcVw1uePKyr56ru
            BkuBdQli/DERl5102Oc32dd9GzV6A382qcTehIMxWTTP8zVPTZ+hOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:02Z"
    mac: ENC[AES256_GCM,data:R2v7CsCSL6/l6rL20RMBteub4CQhr5q3CyyDXeN9gJQ8uxdeyK5KcqHK3MEcGrOj9ABC7/xA+Iy9g9EZmLMtiEHGhXd8kN0mk8ERPNX5RRTpSSMLLuY+ATjoNWshG7tM2S+HTKbPovdvp3RD+5pLf3VbJl3hAH/c9i+EOLsJ3gU=,iv:uc9shB6s/+1LyFpcLa3PiVLAkCR2g93s/SSq6eR3dAE=,tag:TdVJqmAC6hakuNIRCDnw/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
