apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: hindsight-secrets
    namespace: apps
stringData:
    HINDSIGHT_API_DATABASE_URL: ENC[AES256_GCM,data:onBmW5eplavoUD448X1ppVo1YtyJzdDUa7VqLV3Qc8rt/QVnUG5cPoy2ODOGLKqZ/SamkfUzqo4VGk61ixmaIdOam2xt2GxMiA==,iv:4CxfJuTOnHAyH4BME6ECdNAdRHxvwqybhtm1P3tiJYM=,tag:kG3sMjAfAd3YhBWlMr7C6Q==,type:str]
    HINDSIGHT_API_EMBEDDINGS_OPENAI_API_KEY: ENC[AES256_GCM,data:evFCrsSsNqYX7Octvos7lP7sTxCftWHNmC0fHWFYPePuJRgFd2f3XmSzHPRwC+bpeUrFtiqpuRK/Qzf5M+SBor33Kns4LSgE1A==,iv:JeycenwyKv/7Hs22H8yZsFqaAEOI31Htqm3eHbYf30Y=,tag:MoVi8fXRG4lLVNnZ7lAt8Q==,type:str]
    HINDSIGHT_API_LLM_API_KEY: ENC[AES256_GCM,data:1pXGlGs1oi1lXjdiSodTZ897yZFaClxu+Ca9n9nVzrOVTCM=,iv:ZPPgIxn1aLLBL6KVhEgF1V/kjgKOs2DQlg8VvjisBn4=,tag:7Mqdmfyo+usoxNzJFdNXZg==,type:str]
    HINDSIGHT_API_RERANKER_SILICONFLOW_API_KEY: ENC[AES256_GCM,data:XuNVjqRuKNQ7rjQ+vQwpZqcrqhztIcNMM5VpJA2wMjo5FK121LsHFMJ4FPZKsS1nlMLM,iv:gtWTKPE+TAv3A4gmtDy+kbxP+0NyZlQA87wbHXRpG5Y=,tag:Vb3aavKCikdNOfdcud5pRQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZDl1Y1JZaDRWOC9uNkE3
            WFVJS2N2WHBrKzFkY3p3MkplTlZwUVI4eXlzCnJ3dExub0xQd2dYdXlnbVVrUmZm
            azlockZ3UEVnamQzd01sclgwSE5FTGsKLS0tIE5WcHU1Q3pWZlBUZDBUVTc1bFVu
            Vkl3eXdWc2x0dmd4V3ZsTEozV2k4dUEKRvjS/SJjhGhqZUXfp5jU0guMquFIiYR5
            KkI5NvaoyNtsZg3SGr3X6CKJrVUeecrUt5dolONf82IMZonqtZv/cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZm9kYmE2L0o4RUtFY1dM
            TnJPSk5PM29WbHBrMkkxbVNWd3VyQTZ3bldFCkltelRlU1FlVHhNQXdtMFhxY1Rt
            ZlNYcEFNV09nbmZiUnI5SFgvMWhqY0kKLS0tIFlsemw0ZmkrNmswUmtJTGZma3BT
            TzQvVVhKbzhsSWtJWVdmQkRQUXdxWW8KTPI25QhcTGbEzk9+goWa2Tu2Dc+Mb4CQ
            Hgl1UKCOZYzxRsaLghKNBEy3OuiGFMhr7BaMX35oOyci9wV4oA239A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBET0JHMTVVeE5sc2JYWmd5
            N2RGa1ZpcXdHYVpYejY0QVBiRStoL3YwWXhNCktDdXdXaUdMcUtsRFpZdzdiWXQv
            SHNuTzArWmkyYVRjOEozY0JVZnZxTzgKLS0tIEVLWEVoem1GQ1hWWHJsbkI0b0Fx
            U045bDIxeFF2Qml4OVJheVQvZFduWEEKMGttQC0ycpR6ELOvzBzEUJUtF2n7l7z7
            8qG/K9jAPaQLC1dTxKc4ZEYBF+l0Jokc4eN2pF7Z1jwp5+wyi0SSnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-29T20:48:00Z"
    mac: ENC[AES256_GCM,data:egnrp+jiQXslSkUWhnDemGzIFLSB+d8zwOFXOK7rBj0t2etTE+54h5/qgQtH3Vrc07w1QpfqYDcx4JAjpATmIFzvb7WqEJXDSTqME7lkrUQnUZ/Owvn/jw6ZWpIKpGs3LkbzUc7J2RqGXtGsL3qG+ECemoWAK43oE5x6Xk4giDk=,iv:dJovGCFcCafVgvCo1Or5HfL/2IiSVkj+tUyNjtBA2E4=,tag:Enmd0vdPY934KSPS6XXtrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
