apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: homelab-bridge-env
    namespace: apps
stringData:
    GITHUB_WEBHOOK_SECRET: ENC[AES256_GCM,data:0UxrwjLTV+cOjeFjv3hsr9OBwnREX4rXr6Rl3SiyRrCHopWxQVnCW+FK2Ciqb2obtkQFYEBYRgu+HgHHsrRefQ==,iv:xzuIbI9Zn17kYlcIh9f+6AL7GQ5kP58zmV7FS7AeatY=,tag:TrUQMXJK818GlyBntOd6kA==,type:str]
    MATRIX_PASSWORD: ENC[AES256_GCM,data:t3dcqrW3bNarOxPTUGy8uFMm+6wRp8flhZoKndSsRg==,iv:/M+gvJyexDQWryrIunRN7Zrm3niJ07E42Y++WSjTn/U=,tag:PnvHT8n8kMcGvUyYIZIq0g==,type:str]
    TS_AUTHKEY: ENC[AES256_GCM,data:lcBgjw/RXQOhyqMjQLxalaZRUTV35jvBuUMU6Ovuzwdwxzmx4KNBrY2eusXooi2li+QueCqQD3rZuyfO/VE=,iv:Jvz2TGKZvazcHSzeQ3NmqoZ3gi9L0tj7RGa4r6P3nvA=,tag:ylO3PubOOKhvvsFzZnnxaQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa3lES0N2QjNGRitvQzBB
            QXBEZ3I0dWVzTHlqbUZQY2p0UGxzRllXb2tZClZPT3pxcnl1aHhTcHM0WGVheVly
            OGd6dFIyU2ZSb0hWWmZIOHdQNVRzajQKLS0tIFgyaE5nTGFtVnpXM3JCRE5ZZnZO
            V2FXQWpJZS8rZ0VrZHJMZ1lwUVVrYkEKRQHbxqSzdH35lEjv3UfBfHx0QrBGLYSC
            Opwqq6zgWuW6Rz2D5kndD9EZg6XDqi0k2glmHgoWFeYw0yO4ynxjyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkL1RaMDR5aVYwMWxkelVL
            cGVIVy9tZ0ZDbDJPV3VoOStZdGVnSTBDYmhjCnRuSGV5RTk1NnA0aWpNWjVkbHRD
            YzFyeXlGOXFEejlXQUtENFp0bXVjVDAKLS0tIHRRemlYTnNST1pVWVdLZ0gwdmV6
            SmFzUFlnK0F2L0ZwUlY3N2JuM083MUUKkbLkn+akNi2nOS9eg7aBHHAj+H/LMj3S
            F2Sd2Gdu2FWM7ZUdQgJzcA1zyENK2y34THhVw2FtIS5txbfD7XQSdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUzNGaXNoMDhhV1pCQnpU
            a1puWk9RZmQrb2l1T1NNVlpLQ3Zyejd5MmlZCms2VDdJdGdkUUdtOEMzMDA1a3Bu
            azBXUmpYM1h1L25aRWdDVi9qMW1YZzAKLS0tIFdlMXVLaGdwcGkrVVJhZGhwUTZT
            UVBORThtWW5iMkRHc2NkUkNnaHJhcEUKsIIRDYcJRFI62+Sugy8hMNDTLamY7Q8Y
            Oid6AgRHpPykQl901nl9SqjuPiSDHT30dUx7XF1ZWFJYzhdpgnFOaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:32Z"
    mac: ENC[AES256_GCM,data:0wCuzUcniG3kx3oSV0CdBR2iYYLMl/W3lQAuLbFTRJ64yh0EmJFpyssnwG2A6L6XPfpJcl9POL7phTt8uLXoFFFAy5ESwDbAseb4tI3nxJFIjjQQWrfS/wZomuRC0PApx2SjUv5fquPxUWQX2tzZTykdAl7d0rZE2VgW4PQATjo=,iv:Jtokm+xaIlBO7gVJyj2Dg/fK0FLT+U5w18T2j/uXu6A=,tag:tiZeTKPeR1gyIl85L3hecw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
