apiVersion: v1
data:
    configuration.yaml: ENC[AES256_GCM,data:3p7DsCq9UAOiKed3s/9Cwj+QHEPPzbzgm8d2NDB3/LLWiQOD7s9QqQeCWy+CvUTVFNI6vans1wnPGQyKWh/ryPJlGVp2D9GJEMqj4/dV03Ds/L46VDhQW0A7lB5CWSJnGrzZ3dvY1+HaV3X7outgIq1Xibi+m2S2mGOcbTGF2R1OQaHGpuYANzO23vsCUskzY/70XRGfYeU5w+KHxcTAvKwH/yXZ9uIrO9cbShSk9EfgYZKeAt1TLn8Uh7BAxR3R/Jv9Yhb4U8eNQUcdszGZ3NYvqd5h9J++OhwEItVDB+pHF8eGq+AwExHJj/57mDym9r3BTDYTNVbFg+0fM9B3UHZN6PdIlStSBSrdScevu0ENSKaRMxdxZuavpe4v52ZNf7QZkhLVfyBIM4TMwGq+6I2yuc6UOi2TEB3QmvdjtaXO6tIHkJHk+m23u7RzHCMuXiZgubN07jjHMzDH3tDTiSd+ep6h6NTOtRIKDmOXTEQST3z3XlPnDzE/0HM8k1hgqKmjoJRy5PNT3EymGHiUNbMSnYtBq7zS/P+ObD1XsVa+YMav/ML1GIumtfE1NE/+SHI4OgT4FnvTr+klE9B6xCGblWRV/DKT/YLL8blpooA2FWNuJUvypvDuFHTXyJ+NrFLi38ZwzhdYBM86Mgfy8lYgnmpONS+co9OlGGo71QZ0qACbAfBkikmODB6Qa+V6bh64FoyU7F1SioqKsPxWIMnsK9an+kspUxg+dctbRsFUIEzJDw896/jEfAGaHWYq9ASIY+rWG8IRR8dg4t/m/F7yzertOh5jdON4O4yRKnTKrv0EhV+jgvhWOr+G/JcDowDdT/RtCTXSgiKWY8jRIw5Wq0or4A==,iv:PPc/bQ1lbcNpzP0T19aOZotDVO0J1c0zcCMkTSTu3FU=,tag:HU2dX25u8gElD3QEvkcOYw==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: home-assistant-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bllCeEZSa3ltYzIzTFRU
            bjc5YWhNOGR3aGpnYm96cSt5YktJZFBWNGtjCjRRQndIK2pzSWlVeVowWHovUDBL
            UFhFYTl1KytHTGt3aldrK1pBSFltcFUKLS0tIGhPVnVxaWJZbDIwc2lqaWRGNDlS
            MnZXYmozWEpzMUJoNElmdHpLSkZQSW8KfGex8IOYKhqXZDK/WH3GACALxzUg2bfy
            CWmqR7Qp95mDG5b4wXQtq/IH3PmrZp8UJa9jLNsuMsaOxC1NAPFQfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZkFFMmJZTXpHaUJuVjE5
            d2swTHVJT2NvUGQ5aXJXR3NIaHNIZkhDL2k0ClY3ci9VaStsMmRWS2ROT1pMLzRS
            RmJMRG5wN0lRbXNBK0ptSExuTm56cFUKLS0tIHRuaFhrdUYyOXdlL0tpME4yd21H
            MEptdTdHQVJNNVZtZmZYNG9aUWZvODgKZyyblKCUQ+AijQ0pgXqnF2J7mJdZ8Ps/
            8RBuMea7TttAH3C3ON4+mA+bBt2ZeVN95QTuqwb0tt9jjTUBI/CCoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VzFvSzRmK2hCNDFZczlu
            STNQNUVoYW5lN2haTDFZNkhwUzVPbzFLeDFNCk44R1RpdW9BL3lwOHpJekVCUDkr
            cll0VG9GdDVmZTlXQ0NvSVNhaWNROFkKLS0tIHFlYTR3VHNjMzkrbzZWTFZoUUsr
            V1JMYXkxQ3FCZjdBRU1MWFNvbUkwcVEKlkC4F52Iubiz34wI8svnwzi9J3xPNNog
            uN7z8ZVntHMV087HewzW7tsCpnYZGRbptQcG+wUbTS3/QyoeDfzUrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T16:12:08Z"
    mac: ENC[AES256_GCM,data:pvgw7AkST233Qh5qeQli4KpTYWqP9XpWAzbxeCEkOSWh9Hqk0ZB5hCSM7W+HRJcF9N3JHzD2+TsqxIIfalS7Tv/8JlwJJjiYHrdPBjpJkaHoRUTOOPMUxnvLZ/9Xw17l0lreItyfh+pbQzBFxfQ34mqXxwFzNywHbq1tBsGJ1vo=,iv:YhaPE+uSxXuVJmi2p+BkRHu5W7smHY86p4DXWM128Os=,tag:Z98A/KqZdUPYNSje4bEvsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: home-assistant-secret
    namespace: apps
stringData:
    HASS_TOKEN: ENC[AES256_GCM,data:YbDw8+I9rQ9E6l9i8VfIdS4=,iv:/WoVf4ZWNjj23DERrTH7WoqJizNQHis+xMhF8YKZbr8=,tag:FZBX4WedWRCwEMsxbyEkRA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bllCeEZSa3ltYzIzTFRU
            bjc5YWhNOGR3aGpnYm96cSt5YktJZFBWNGtjCjRRQndIK2pzSWlVeVowWHovUDBL
            UFhFYTl1KytHTGt3aldrK1pBSFltcFUKLS0tIGhPVnVxaWJZbDIwc2lqaWRGNDlS
            MnZXYmozWEpzMUJoNElmdHpLSkZQSW8KfGex8IOYKhqXZDK/WH3GACALxzUg2bfy
            CWmqR7Qp95mDG5b4wXQtq/IH3PmrZp8UJa9jLNsuMsaOxC1NAPFQfg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZkFFMmJZTXpHaUJuVjE5
            d2swTHVJT2NvUGQ5aXJXR3NIaHNIZkhDL2k0ClY3ci9VaStsMmRWS2ROT1pMLzRS
            RmJMRG5wN0lRbXNBK0ptSExuTm56cFUKLS0tIHRuaFhrdUYyOXdlL0tpME4yd21H
            MEptdTdHQVJNNVZtZmZYNG9aUWZvODgKZyyblKCUQ+AijQ0pgXqnF2J7mJdZ8Ps/
            8RBuMea7TttAH3C3ON4+mA+bBt2ZeVN95QTuqwb0tt9jjTUBI/CCoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VzFvSzRmK2hCNDFZczlu
            STNQNUVoYW5lN2haTDFZNkhwUzVPbzFLeDFNCk44R1RpdW9BL3lwOHpJekVCUDkr
            cll0VG9GdDVmZTlXQ0NvSVNhaWNROFkKLS0tIHFlYTR3VHNjMzkrbzZWTFZoUUsr
            V1JMYXkxQ3FCZjdBRU1MWFNvbUkwcVEKlkC4F52Iubiz34wI8svnwzi9J3xPNNog
            uN7z8ZVntHMV087HewzW7tsCpnYZGRbptQcG+wUbTS3/QyoeDfzUrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T16:12:08Z"
    mac: ENC[AES256_GCM,data:pvgw7AkST233Qh5qeQli4KpTYWqP9XpWAzbxeCEkOSWh9Hqk0ZB5hCSM7W+HRJcF9N3JHzD2+TsqxIIfalS7Tv/8JlwJJjiYHrdPBjpJkaHoRUTOOPMUxnvLZ/9Xw17l0lreItyfh+pbQzBFxfQ34mqXxwFzNywHbq1tBsGJ1vo=,iv:YhaPE+uSxXuVJmi2p+BkRHu5W7smHY86p4DXWM128Os=,tag:Z98A/KqZdUPYNSje4bEvsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
