apiVersion: v1
data:
    configuration.yaml: ENC[AES256_GCM,data:gOVRK/7nzqNAtl9fDyNNePMzQ69R/XG1Vw2UJvpnByRsiZR0qfj1s+HF5f5orefEuDpJK1iKsqF7O5DBN8rWk6jzfKZ5UVl0WCHwg6H80ud0XK3wYY0hpFcq/Ccxg3RWOzArLbHr0xlPPRF3PLE95UBAkSS4GinY4LHEB3gbV9/7l5cQ/piNenjDvQ43XJjBV/oOoARSlz3OXm2RdSRHBaAfr0CQZTRmCP+2jMTKCuOFEWe5pCCm5KEXfMOEpuEPPNcZq+SMoSpQ5Oq/XrzsD+Skc/4gY8TmHFic9EL8lSH8qY/8R9PMNBAawEcpm0cTcL1+1BhaFpeAti7YNHsWBL2Y0/+j7puoGo0lIJ33qMIfLE0ZFDvHF3ooGTBC2yyCtrFN6Ujawvukjd+pivo9SAcE1YB+CQQ0gkp7Gpsc62rh6ZFSZI/V6HSPAgfNZES7WcOsCysD9gQ+mpCPO1VWhN+NVanz7jXteLi1HfjVZK3AAuMSz09NZ6udyjBHY5hoOe9muraInE78rPbTRFX1elAcKqMYZpEPOsysFEQGfiLSha2gVpp6JcbYN+C2wwbtGmekJWM9nve81RIIkmy2ZH4sCW0qld5DBkIJsCCUe8MrKv4ZpTksW4YKNhVw+p3FjuxqPDrjcW/YZbDq+zU+/mNLxYRSnmsW6eG/2LgdBM466vN8jiMWUXmcy77nnPs/22Z87Tcdv8wALz/wxNm9rF+R6WZvJusbk872zYFxj6NEi6RNAX4AD1PR+7Zz+3LnqjxSofBZZCpbZugjp4VENtYwS3+zch65oYksYOfocX3FxbTJ/7p0JAuNuRMecRM1sJHfNO9FIbMNFp6Ty+6ruUxRh9wUVeZVNovZ4nxQ7auBziMp7mpPe36YBTqdKpnLdUrK1f7EKCw=,iv:1eVYS7YjlyibN+ntT9S8teNeDI9Me+e2haepO/Bf4rA=,tag:MrKk3/BWhcsQk9wtmAlcxg==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: home-assistant-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTmVnTTFWTldLWC82Wjdv
            WG5jelpOUHNNc20xWUl2Uk5NWHV4dkQxT0Z3ClpMRHdjMDNGKy9nb2J0WWFWMzVr
            TlJFQ09tb3RoVnhjN3d6Yk9sRTV2dTQKLS0tIFI2eWowR1dmYkxvN3h2YkR5Tkpw
            RnJuSTJXZzRYdTRLQ0lOK0dSK2hmam8K0VpSGYND84DF83A4/oLiWuRK4sW97x08
            VJ0YvnRI9wkzMa5SqFOoHWZFAYj4Uox5IYo+i2pYNkFjXcNMJdmNng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TDdveHpHUVZNVEFaS21y
            eHFoUHVUNDBFclpHNnFteXlqbFpsNjIrc1hRCmNYUGZxODZidi9nYXZEUFNDWkVD
            bXpXclo3MElIY0VpKzc0Z3owT2pXRVUKLS0tIHg4bUJJeWFHaklMZVhOYTlyMVh6
            elRYV0UyUWtzY2U3eEN6Mm9VS0dLRFEKVdsmkglG10kPAUBEEeSuWVLulMcmrDu2
            PX/uzfUnWZZVUAGVdt5kLpH9FsyGsIbkoDkIWGks/ZD4b+8gQ5cuIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSmV6TzBWMHVsRGE5WTMr
            YWtaVXBqTlUwNjNtWDZtK1VPZWlnVG1ja1FrCjZJVEk3Z0RISndZWE8rZlYvRVVD
            MS81UWE5aXlBakMxeVdqcmVSeEpBamcKLS0tIGlPTE10UEM4bXl0OFhxU0VBUEVl
            YTBxVlhvdVhVNFVIanVxT0E1L0o5U0kK9YpHiOcschAGBNtL494XzP+PR/J3M3Ez
            LEZaw9iMQVS5pefXcYkBLNpIUysPS7cL/5Y8cj2OI0NTorhd3hhUQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T17:28:47Z"
    mac: ENC[AES256_GCM,data:ut7jKqiTD/v/izivkgtbShbBiAilFARR7Y2Bciv5lQlmCvDD30aylL6krgSS+JDiOLzRox3MocIJF8xYnUHgCfnS1lD3TUPwJPtscvGYg0HsjPKPnxLASeNgTlG7tOIA3UY2yCUfWKbdJi0C34lOJtv+JdPoSXKPyR4aMWlAFuM=,iv:L8TDOmrJTtm21f/rIklap5Ey2aBAULlN+rz5HaZgH48=,tag:SklyzxD+nYnY3ZKhGDOB8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: home-assistant-secret
    namespace: apps
stringData:
    HASS_TOKEN: ENC[AES256_GCM,data:CYtgZGIFjCeBnuhEd9iqKvE=,iv:47c8va+ZuStkIIRXVv+TkSWQAkWn1XYsD6hYTCe3FzI=,tag:jZTPPxb/wk9T2nNwknwQZg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTmVnTTFWTldLWC82Wjdv
            WG5jelpOUHNNc20xWUl2Uk5NWHV4dkQxT0Z3ClpMRHdjMDNGKy9nb2J0WWFWMzVr
            TlJFQ09tb3RoVnhjN3d6Yk9sRTV2dTQKLS0tIFI2eWowR1dmYkxvN3h2YkR5Tkpw
            RnJuSTJXZzRYdTRLQ0lOK0dSK2hmam8K0VpSGYND84DF83A4/oLiWuRK4sW97x08
            VJ0YvnRI9wkzMa5SqFOoHWZFAYj4Uox5IYo+i2pYNkFjXcNMJdmNng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TDdveHpHUVZNVEFaS21y
            eHFoUHVUNDBFclpHNnFteXlqbFpsNjIrc1hRCmNYUGZxODZidi9nYXZEUFNDWkVD
            bXpXclo3MElIY0VpKzc0Z3owT2pXRVUKLS0tIHg4bUJJeWFHaklMZVhOYTlyMVh6
            elRYV0UyUWtzY2U3eEN6Mm9VS0dLRFEKVdsmkglG10kPAUBEEeSuWVLulMcmrDu2
            PX/uzfUnWZZVUAGVdt5kLpH9FsyGsIbkoDkIWGks/ZD4b+8gQ5cuIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSmV6TzBWMHVsRGE5WTMr
            YWtaVXBqTlUwNjNtWDZtK1VPZWlnVG1ja1FrCjZJVEk3Z0RISndZWE8rZlYvRVVD
            MS81UWE5aXlBakMxeVdqcmVSeEpBamcKLS0tIGlPTE10UEM4bXl0OFhxU0VBUEVl
            YTBxVlhvdVhVNFVIanVxT0E1L0o5U0kK9YpHiOcschAGBNtL494XzP+PR/J3M3Ez
            LEZaw9iMQVS5pefXcYkBLNpIUysPS7cL/5Y8cj2OI0NTorhd3hhUQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T17:28:47Z"
    mac: ENC[AES256_GCM,data:ut7jKqiTD/v/izivkgtbShbBiAilFARR7Y2Bciv5lQlmCvDD30aylL6krgSS+JDiOLzRox3MocIJF8xYnUHgCfnS1lD3TUPwJPtscvGYg0HsjPKPnxLASeNgTlG7tOIA3UY2yCUfWKbdJi0C34lOJtv+JdPoSXKPyR4aMWlAFuM=,iv:L8TDOmrJTtm21f/rIklap5Ey2aBAULlN+rz5HaZgH48=,tag:SklyzxD+nYnY3ZKhGDOB8A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
