apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 166018f9700243d898e1bc2d863b5ee2acc8d897
    name: ideator-config
    namespace: apps
stringData:
    EMBEDDINGS_BASE_URL: ENC[AES256_GCM,data:y6YIwUzuYfOWjjVGRCRMR8XpMMpUsoCgdUZNYIaHRmnOeTyJ00N8gUKuqg==,iv:6+mI0+UGw+nFZYe6U9DPiqN2tLYhTI1y7MX4tg8pzWs=,tag:Kx0KV6PLrxOlqHJ2K6P84Q==,type:str]
    IDEATOR_DATABASE_HOST: ENC[AES256_GCM,data:Xi46iZeFMqFVRN+6YAqX1w==,iv:x+5vpazuJmTV2CKiaFekTNXo71BQqBrpXJcPcZ8oQvQ=,tag:SoHdrPsBCnXQ3YWMNz9h6Q==,type:str]
    IDEATOR_DATABASE_NAME: ENC[AES256_GCM,data:wvYOa1XQ/IORBpq5OIblWGcw,iv:Hctk5nuWQBRCdGmZ4yiYaO0Kl5XcVmPHhu4d78L+uZ8=,tag:a7sKGgQkHToG2kABeuCyqQ==,type:str]
    IDEATOR_DATABASE_PASSWORD: ENC[AES256_GCM,data:R5TBrMSRBoTGhG/26N3kys77DA==,iv:MZXXbmc/CUbWS69P8b89tryv3B7ulef8i5sL1doYBI0=,tag:4Prb9y3k3HhOvua+NNRzCg==,type:str]
    IDEATOR_DATABASE_PORT: ENC[AES256_GCM,data:NoAVDw==,iv:+lvh6N30+fQym6ji/s22YsepAXw1Bl92QTQbSWYhDfs=,tag:g4suMssSgxrZ5JFATrepeA==,type:str]
    IDEATOR_DATABASE_USER: ENC[AES256_GCM,data:EQb+mmhhtcA=,iv:kGUIZ+n8EQBgezcIEXwLlvmB6sTQdkOfoeCOwZaiKc0=,tag:8Vutnbf9KuxiGlzr2767sw==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:bnz94musaBPTbJiQDltu1aVO0j/4b3J1ojpGYvt/gs8gtLUes8IQltWXZvE02TCvmeKjEH824Fss,iv:ABk6GQ2lKA6eNXv/+O5YuPCRJ5osTSgIOokyXxieqBs=,tag:TckHIbi3BpAknIt7JUXiaw==,type:str]
    OMNIROUTE_BASE_URL: ENC[AES256_GCM,data:PxzCUywyAZ6w7JxiBbFAtar7jTQqVpMiGF267sph2auIyJZ/fIc44xYmaQ==,iv:nfzSV5myshHoe2fbyjP10FSps3h31oBWKOwVQfkA4pM=,tag:zDPHk7i2GK7iSwWY1cdByg==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:db5dYaHvJBl3FVNE/T6NdD5YezxTuzbtlR7WBMzkzCbVcK2yZqL1o/T7UNzu+3ohLUSg0CGEoEr14klSL1ebGEkjLzYt2CtmQSk/8uItB8+3M3uk6VFpjqUeBm+H6z9zJK+5mGejXwjS5l852gvWAz8CyTkbzrN9BF0k91oaaOw=,iv:UQ+gJwO5ij7wXd91rYJFzypBlrOnmvCxdM9HHaabRK8=,tag:5i6hDw3whcoMWx4BQHwxXw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TXI5UUk2ZjJZdG9ENkI1
            MWcrRXkrTUpkQTQ2dFRsOUlvVkpUOU1kdmxNCmZwNjRyWTUrL0ltY1p5bDNVeVBL
            TmxFTk80OXJ3VUtpV2wrSWtGUElxUXcKLS0tIFAxL3NPR2l4c3o4UE1DQzdPaDlC
            OVF0d25JMkFKb29yWkxmN1FXSnV4TlUKXEQ8k6obIDLNxqBpHklYE8iUtmQA8KYQ
            +ohjfXB/FENCf/cBm8BLGMJzzyaxmqG2YnS55olqyxb87TljT2TBCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWEtzVjEwKzlmN1pNYS8r
            QU1zaURNOTI0aTNTT1lNNjY2Slh6cDQ0cndJCjRZL1hwcjRDMG9IZ3JuNmhLdXJs
            NXUwT2FiaGJOc0Z2VTlFdXlINmdOTVUKLS0tIG9iWVMrVXZNTk9hMU45RDJ1NVRI
            WVhSYkFxd3NTa0hmaG91ZitEUkg4d2cKLrwnd0oDYA+olIvXdz9nQOeCxSkLG4UW
            vr01OAem+bVJtbH13J3dItOkX9Z7DNfIHcH7ul4fycYo86ZkICSbxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eVBkdUoydXVnSHV1b1hj
            MnZFTEdqNmxpZFQrQzlvYm9OSXJ0RUNhWjEwCjZJck9YSXk4SmhnLzVGTDJZa2Y2
            M1RnY2F2bUFVWmpTRW5lTHlxdmp5aW8KLS0tIDRjT2xUYXdWdUdubkpGWlNoa3Bx
            YnVXR1Z6bThiUC9vS0hGYjdZYmN3dHMKgT3lPiP+NwXdXj6kAicsKlvm1I0lh1Af
            Rv8VkT7EGYHUMhcIxAJlmt7kF9axDLS0AEU3Qg654aGdhR8Gmfgjmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T22:54:51Z"
    mac: ENC[AES256_GCM,data:VDyB8tlVErTKS1wmt2ymi7NLDOGQ0zBBCa1AfOStUbNifSNKD68mYbFB+myTbQeiWvlh3r1S/NpbMNShq0d1cpOlJE02T4S8CtS9aL+88/1ErY0CGEByCk3RDGylt3LKa5QM5qmd6o+sfSrjb6ZDoydh6o5cIanhcT9TR+VXAaw=,iv:wzyxYYnmP4NnilQGck/fxtXnjEiuK9knRI0Xmv0i98g=,tag:SeYcup8A20b59g+jKWr8OQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
