apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: imgproxy-config
    namespace: apps
stringData:
    IMGPROXY_KEY: ENC[AES256_GCM,data:/JS1yuYDBPb3GRAM8+g/7yiBkB4uoux0WU3tT7BIwG4mBy6MRpi5Yl7nGo01yxQ9JAQpD+W/qwYaZER+ffyJW24P+2QfKph011cixWTslg2i44KcBzixtg==,iv:MkxRdSgf559yRFlyPr0+zPUtTHzdvdvCoZnTYpIqUv0=,tag:l8OkDwy+vj6mr3/KYCMrmA==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:UbKyLXyT89zeXOGqpv8nnyh5QMEZOvHr80guzrfZT6gt8NZZzKG1oR4kpvJDz9d7eGwR0L4Hkjrsb6PZ5Dz8rX9IdSkXJzXc9EkzTdabqDkXbgyqd8RUSw==,iv:XbjLSi+YFqn9GW4GC2aVNaobN6jaOKhWkLQ9eCB0D14=,tag:2nlvvw0HrFzAI0ZNYV4t7A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaU5pRG0rTXRaek16SWJ6
            YVlvcEtMejBuWldjaDE4RkoxMWNLQTVyWlJNCjRJNU5rK3duSGhFelc5c3lRd3FL
            L2lia29XY2M0UEkreXA0elR3OWVlamcKLS0tICs0S1NQa3RWd21Zdk5FWmVHK2Ry
            NCt3TVJBSWtJYkRCUWtCM3NWWjArV28Ktjv0/ybJQf2RLT6kHEMSRKz3+73Vm81C
            rPcHDX772POkUcdK3c+hSAlXPCFBh+stDbW0z2FiIOL4nYP0QuqgBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QTBGTml0Zng2cEtraFpM
            alBnS3hFV096SlNIek1LcUtZbXJnQjJLeldJClFvZW5vNU52OVJXWVNLV09TbHVM
            d3M0Z2M0T2N5VS9qUkpIWngyRUszazgKLS0tICtoYTdqKzQ0RDlLNnVOT1JNcUxV
            ZHZpZ1ZSUFZTTHNVN3BqckMwZ2szZ00KUk1twdG5N6POErRSVsR8oKhX3bfjm/b9
            MfpV5wb0PHaqmR9V8vidMVx60+beIFnWOOKyiyHFCMha0R5sedrH/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc2hjVnhla29CTE0zeGhM
            dkt6NEFGRzZYMHJNQzI3TllDRWFBd1Ura2c0ClFzQ2ZJYUg0TnZlVG4vRXpNTFJh
            N2lmRzB2UG51T2RYVXdDcXMwNWxQRlkKLS0tIE9MOHRDc2lKVFB4RTRVR2l6VHVP
            MzNqWGZzWk0xSzZSRHNQSjNSbEJTZW8KIhn3ElPCtQrH76OytbCoJxURsOA6FqnU
            tRuPHGPlcUYuYiULWuBK3KdbvT8OYAJKYQsMvnIMkqpxbXyifyrnHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:59Z"
    mac: ENC[AES256_GCM,data:ewloK712zOTUsE1sPExauXqnPKzQLArb8l2ChV5ypCik+C6nKiOfSuFXoLKycZp76esNp3c1JonrXmsj/gTVnJgWooQwKEG7K6bBCoFTrUUecnZx+rrpxd4lpSg4HniPZPyq6Ngy1dvNRuP7Z8PPaIJ9pkQ/CSpS40zVi6Gu18w=,iv:vvjh51wonR4an5d9+PrnfFxgEUAgsQmTbBNeaBjeask=,tag:vqxjOvUqpfIaKCrtsAf6dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
