apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:2cT2zgV2,iv:ncc4UqKvAJuCRpvYKgZtfzv0Pb1xPfb+C7oUDYQtjPY=,tag:b2UeBR/nVQMDzSNfuz4nXw==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:FdTjG7JhrJZudkm03qLgbQ==,iv:h6TbhaSIihIGyXxZ2XhE+rhozKk883JwK2SsnmB/Wb0=,tag:+w0rRude3DvgR6jOZatk1g==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:sdPJc14USgqC+NCXazcUWN+0tA==,iv:XedMzJ+OV1g5pn7n5QS1n6UMlWsp1ctnHSSzqW+Seu8=,tag:jtUvctdTckjdheqgylNrKw==,type:str]
    DB_URL: ENC[AES256_GCM,data:K9tGGGiD9nBNTLR7CGtaMsd9MtljO7Zm/w5sIvsgkq6iFKiSjdUNR2Tc5MTjux9AEnEhSo4zlXmjVFcZmuivRyMx7l4THA==,iv:0gN4Ij76zCQhDCbg2PF1xONzrK3gG9pzHXuHdls/dZg=,tag:UKi6pgEK0eGbp6fzzwM3Xg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:rTOgewZ3slo=,iv:eZVRcCiOhc7Mr63fkJ6mIhrB1LSmX/NImj/eYgRefjQ=,tag:iyXRr9DToRYjidEaedMEPg==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:QZGrmWdvd4jZb6nnOP6CPI5XWgq5S/XkpjsxIH0tEGoxdXk=,iv:+6P1lV4zHz5ma2x9yqUXwEjW7sqw8CH2cQvIg2gWhbQ=,tag:L1Oo63U4ucbwpEVj0kzSbA==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:TUHVWcxFgRnETDGD6R82DoRA4g==,iv:wyAhZAEtoT2ZqzSYcddXVA+2GP5FTtdxflrzAjAE96A=,tag:ni5gC/rQlKTPrpU0r2oX+w==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:C1k=,iv:l4UcrQBVyOkXPbHDmS43FvJp9+J8X3GNgRaFOes6KeM=,tag:HFkJuic4cukoUGoXqgf4Ag==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:1pSKmBqXgFvMx+LNRjaRElIerC5lpA0HOjMAR4zkgWLug055TAYw6tL2ODXz9ufSm3tLPjbdgOpWYYC1uywq4UxTfgkegTNHnv3cKA5kfmfV8Y2kLeidVqeBJUIcXFDA62D2knJ1Aqi4DnDKioY4GnUKyKmy2p6/la/iwG9bgtSVxON3iIM/1julT4YmUTu7IkQ=,iv:vo4C/aWGATKDxWrx36QvZDEDWxBVopmssO1uyalPHPE=,tag:Q6ykTTVfVZxQVgdg+QJNxA==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:woPrdEtjf24kd6j/oSiMoQqTng==,iv:OzBrVukRIymgSpBs35pal1OJkIkav+lABQKVKDznG78=,tag:gof1O9tvAHxSyAlCG0dZAQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bHFFRHhPd2EyTnBJamQ3
            di8wN3ZPRzFBZEQ0QTF6L050WTFKbC9IRERRCloxYno5QkRQWlhscFFHZE5QZ0ho
            YXN0L0k4S25Za0hlMDlMSUFEdGxsbHMKLS0tIEVCNmI3QkJRSDFoMHV4ZlJzZDJ0
            bUtDQmJ0MHNOQ3JadkN2aVhQelBjSmcKez+k3rNI/rggdqiiEj0W85tM8wiVK6SM
            J96PGytaj1ZneUrzSynN7Ht9Mdyg+CjcSVVxn93h/SbY/KLfkSX9+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdVBvUXBsUXgzK2Z0V3FR
            SWZpVkR6YmFaVSs2a2lOWHI5aHhyYVBzZlFnCm1HWklFNXlVajM3T0t5TzF2MTFI
            Y1hRWDBEUVlWeWNjTzl5ODRuWC9BamMKLS0tIFd3UXpXWGh1dVp2czVBbWl4OFF4
            TXVMRmllWEtucFNXUlRZenJ3QkRScnMK1uhGx33Cvv6rZiYIOndma7oppwyOiY/+
            ZRfbhr4COD6/UmBdSYERGZfxPyoKtZ8Bfq6/IC2quE1iT97at/xtyA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWVhMY2ZUcE9lOEVxWmpV
            NWMrNEh6M0RDemJRSUJmUk1sMmRhc0w3UFFvCjBQTjhueTVjVHdqcHk3L2V6N0tq
            RDUrdTVjbHpjVlFmOE1lQTFpNVZTd1EKLS0tIEN5SkY3UTUwZGpyaHIrVjV5eEdJ
            OGFkRkxPSWJjYUxkeUROeUN6SXE3QkkKmw7oiWEPeccxQSUq0wTBrKnNQoWhj1DV
            JE8+IkNAWbIvAhOoQ7GpzwGtPXQ/gkos+tWJNyg3CkuWcClIO31Z+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:55Z"
    mac: ENC[AES256_GCM,data:NS52KOhNStu76TdFNuPXgFGpyuiP3LiujqBdd8bjnbOk6BMq3015yY7rNqjE0/xoBH/MF1vxvaHh9Ok6Gy3kttEW//EdTjOekCIq7vbCUYAfchuTlS71beWJwNeXteL1j5zvUxHNGN9FZ3g84VcL0RhtAp6/NVccVlOajTENElM=,iv:zdOlJYZ0i7HPnVplczjbFPP1nn+cFdDkwgZVtGss2Pg=,tag:T/gFSGsc4eTnFCI6m53YsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
