apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: immich-secret
    namespace: apps
stringData:
    DB_DATABASE_NAME: ENC[AES256_GCM,data:bRGIxSIr,iv:gzXPO5dba+lkufdcg09qtpJkp65vAgPDxDW9+CGBgvY=,tag:so2SWV9d2CbvvHuw7BD99w==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:8eMLsHPgwkctjmvcyLYEMQ==,iv:AEcktTJwB7oINN5yYfDQ+kxZYs72mi+KdUbRFZElYEk=,tag:PbDWzFR4I8mHBF+S2XFceA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Q+mHC5CjqJ4gpMxxkObf/FddYg==,iv:EaYwXmS0IJkTRgbX64TC7BL+jz1IYmwi0YeD9LCnEls=,tag:gqN7K+bJ/SBE1OAXCzgu2w==,type:str]
    DB_URL: ENC[AES256_GCM,data:lpgIOeFHw3HjPHRNRybtefY5cTAljuWwdH84ujvvfPxA4DNnz7dE8osqfiWbpLLN6r5+n9B1BLJNQCCWE4UEmXsCG/RYug==,iv:exaFim898YcX907oKIbBFU5hsQMBDzjKdd02l9EoSx4=,tag:vO0YiyYqA6TZQMatIoN5gA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:t+G+lAH4rFc=,iv:9uSzxnOtvEGEv7aAY19t/cGKujAxeOofRBzE9vH7T6Y=,tag:8y/Glj3W2Yi1kMWpmA7qVQ==,type:str]
    IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:11trdfA6iXl5kozYJVGfMec2aRkvHxtUQImXixCBGOA6Fio=,iv:dDFYDL9LTViS1+gXvR6H+zmKQe9v+prQZZTi18wfaCI=,tag:aw16yI++Wa4VPqATl8Eqpw==,type:str]
    IMMICH_MEDIA_LOCATION: ENC[AES256_GCM,data:XMfzMRGcH+Lu/DJ1uSH2V5FqJg==,iv:KU8wSCkW+p+BFOIYjlrzXzDUNjMBr/Oz+szczknL4n4=,tag:tgobEim9N3NS2Ei646w5Vw==,type:str]
    IMMICH_VERSION: ENC[AES256_GCM,data:E6w=,iv:zcqk83Sp75sln8zWQLxKkkGbMIEysmrQPEoflB186wo=,tag:JR+4iSnID7DN6twgvevchg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:P1VxKLdneOxSdeL6Evwzpklz1OAHxT2keETiBIjGt1hju+08aGrxGlMbPiD8Z9MFFju8bDE+ZriwV/m+e5fwNULiYOF4+55KrlpSoIGOBRRB3Yh+W1aHTZevIFqAE9fx/wXrOjYI1Gar7P4zjM+oCL9M/pmupioTM6AWa9L+KbQR1fNtkLN+duHtt6o+/1kyTFU=,iv:KWRTJw33uBCHLEjtZLPVU1SyuZaRf3ELOuUkJTY0YrM=,tag:EROXlexGqeQFFbmgu0D9Kg==,type:str]
    UPLOAD_LOCATION: ENC[AES256_GCM,data:IAnCbW938028FIcUNUJH+gaSTA==,iv:Mhcfy3GzEBi5bhDb1xPFCAsqRxrRTg1xearletYmPM0=,tag:E1xNl+ASJXx7Cg8L7ADx9g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bERyUTFuOHV1OXVwWk82
            NnI3VWdhQXZZYU5XSTRZZjBRcFY3dm5QUmo4CnA4VlNiWmVUbmV3UEt1WWlIQURQ
            S0p4N0QzOFdwY2FJUUtqU3NCYUdwNlkKLS0tIFVET1hxQ2JrZkRhK0pPZmV3dHRM
            empnRDdBczE1Q1RRTEFSclZLK2FXQVEK70ryKHefJ31BoVEJTuIpGXA683Q4eeBC
            srBsdrJUXDqkE9iOtki/o6y19TX23ZP/dgHv9fbDXcSs/ETIJPTbFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMTF0KzVXckkrT0hJNFhs
            NmN6amU2UGlkdUJnZzROUjVnSjhJWmowL1VNClNLK05IWXpIS0RSN3lwQy9iY0xC
            Q2EwVGhTeFczRis5SUVhL0dxSmF2YkUKLS0tIFBVTHJtZHdTYXJQZlFyNE11R2JS
            SWZka1hVdHg0RjdoZkpRK1JYT0I5c1kK9olcz/lRwChlbHEWCf4K6+mSVJuhGc++
            09yvWh6i4IY21oi7P3ojmMfpta1K+6OPijZpqWNZlC9K43dKgnEZbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RGNqNDkrdGpOQVVlakFu
            S08vSUV1RDArUStlb2ExdkwxamhVMWVTbjBzCjNnQ1ZxdHdJUVJCRW1oWkd3MzZr
            ZEROaXNPTjNDZmQ2bmJpU3EyV0E0Z2MKLS0tIFdVckhwbllrSDRzUUpOTjVDdjR6
            TC9KbFhhMlR3bWhBNkNkRVlwcHhLRWMKx+k7mvUwAk8qHUN/mhxkeZjie/mbbIEG
            DOX9ApiOh0uOoZUw2S9EumpzW3fICkB0R/CLTxWf7ewFzRj79vZYcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:00:59Z"
    mac: ENC[AES256_GCM,data:g3KIqIZyC0HDAqeELzPwV+TJmIi3JLbEq44vHwnDZEK/JpbYfVtw+eB9115UGkITLDxVQR3CR6uOs83jax66tU16I1XXt2wJeAI+rAgvk5Gp4wS4WH4pfP8mS+2H3vzWaNHO7zBPPSJ49ifGAvAGv10h037dwD4hDOKAwmj0e2I=,iv:2HptxUqd9+T15dInPmODq1Dl9eqFtRiDhgTy2gx5SYo=,tag:7OIpgVB6e4G253WML8pXbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
