apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: keycloak-env
    namespace: apps
stringData:
    KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:WoFkcwkcZzvMAw7McWsokMwgucVocb2+PuwreSiJtmZuwliXzkC0kWz2GFQiXHlY,iv:3YxlwGQUTZWEKhWBVKLGGMdXn5001O8B+2T+V6j4uWo=,tag:yHo+lcJk3VEpG/VmvYmdPQ==,type:str]
    db-password: ENC[AES256_GCM,data:VO1F4VJ4BMFHylPz7gmnzJhjvw==,iv:gZLm5wBgQG7oHB0k0nNMw586Is0aDLK1ijQFuNsRhn4=,tag:jt5ZLRV/psvoJNVsU7pQmw==,type:str]
    db-username: ENC[AES256_GCM,data:RZqNqaxzJlg=,iv:VjwVSAaGsKLt52n2KY+079jnOkSQMw4h6/qLxrQhTQ8=,tag:Y6aAQxmDyTdypbh3YDBShA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMndvSjJVeVMrekxYRlYz
            TXMxZVVGTzkxTExadGhRRDlsekdvK1Y1WldRCnBnaWltVUdRblhya3IwdVJkT1B0
            NUZ1YldGek14SXVxY1IwdHltUXB6MU0KLS0tIGM3NXltZ3VxZ1VrbnR5MjdrNldC
            N2YrRnN3YVlKYmNiZTA0QlFHMEtIVzQKe5vgW88xsJ6mrjfezx2R0ZUHcjP/+Ks2
            IJd8AGVC13d7HOylNjLjy7L9jxIOFE2mpRsGeen2Pj/FYndx5v52kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dndrMGdwajlLQzZCNUp6
            ejRYU1UwdDR6bFBFWEk5SWZWTVQ1QTJOTWpJCkZIWmR5SEVPS3lJRXlYMkc0UHFO
            K0FZTTdMaDE5WWZYY0tpVVVPaTZKVncKLS0tIDVyU3UxTGMwSEY1dFROVUg3aWI1
            NVZLZEN0MmRncWkvMFpxcWxOMWNxT2MK5IQp59j362MaOpONM7KOPJNZjYflJWT2
            8+yyyY3dlxM+IsmImpuB6V1cp+mPtULmu3A84lXf+zgL0Itsk8em3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT21GMTd6d2tTcDhnTGJk
            YUVHVUtPVWhSWnRvU1diMXVRa2hDODFDN2trCllIdmVaZVBMQm82anhpVUhRTWlX
            RGxNV2k3U2hYRDNzemJaaEVpd1B6aE0KLS0tIDFWSHIxRGQrekdiVThjdm1jKzFD
            b0N1MWp5bm1VUUxNeE1TUFY5ZFJreE0KLCX0laZQ7WzXoomr4dn0ictsCLEvs0Cb
            INggWtUnY/oFg8Csl/hJBK663ZcH6SLFcTFmmNCnR4WX8LsKfs/1+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:59Z"
    mac: ENC[AES256_GCM,data:9eB1fFdzegJzd9VV97szhUYPXx7qJEfB77eJ/SF12njXvZDs3Yj0WHwjoxFuXMBiEaggz8Dpt21FRXAqwFK9OJanPIvqAQGjrparcV1wrVW08mmNt3dbttVE0nxV0ZjFyoVkZadqiCThdIE3UauFEgfaIsgLwaE9Bk1W9wjdRL8=,iv:O128X8DYk9zEG6Fh83c3hHfToPaOn4HRapL4vxRWrls=,tag:uSRW7aEzRPLeQjRqbrW80Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
