apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/component: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-matrix-synapse
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: synapse
      app.kubernetes.io/instance: synapse
      app.kubernetes.io/name: matrix-synapse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: 4bdf01fcc93bdfaaeca8cb21c6d856b02e768683dc64b65f50ab7e36508d298d
        checksum/secrets: c0dda94304107c136ceab50fbf5acd4a5883941c2e6625a801de8256965182e2
      labels:
        app.kubernetes.io/component: synapse
        app.kubernetes.io/instance: synapse
        app.kubernetes.io/name: matrix-synapse
    spec:
      containers:
        - command:
            - sh
            - -c
            - "export POSTGRES_PASSWORD=$(echo \"${POSTGRES_PASSWORD:-}\" | sed 's/\\\
              //\\\\\\//g' | sed 's/\\&/\\\\\\&/g') && \\\nexport REDIS_PASSWORD=$(echo\
              \ \"${REDIS_PASSWORD:-}\" | sed 's/\\//\\\\\\//g' | sed 's/\\&/\\\\\\\
              &/g') && \\\ncat /synapse/secrets/*.yaml | \\\n  sed -e \"s/@@POSTGRES_PASSWORD@@/${POSTGRES_PASSWORD:-}/\"\
              \ \\\n      -e \"s/@@REDIS_PASSWORD@@/${REDIS_PASSWORD:-}/\" \\\n  \
              \       > /synapse/config/conf.d/secrets.yaml\n\n\nmkdir -p /modules\n\
              echo '[default]' > /modules/aws-config\necho 's3 =' >> /modules/aws-config\n\
              echo '  addressing_style = path' >> /modules/aws-config\npip install\
              \ --no-cache-dir --target /modules boto3 psycopg2-binary\npip install\
              \ --no-cache-dir --target /modules --no-deps synapse-s3-storage-provider\n\
              \nexec python -B -m synapse.app.homeserver \\\n            -c /synapse/config/homeserver.yaml\
              \ \\\n            -c /synapse/config/conf.d/\n"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: synapse-env
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: redis-password
                  name: redis-auth
            - name: PYTHONPATH
              value: /modules
            - name: AWS_CONFIG_FILE
              value: /modules/aws-config
            - name: AWS_EC2_METADATA_DISABLED
              value: 'true'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: matrix-synapse-media
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: matrix-synapse-media
          image: ghcr.io/element-hq/synapse:v1.146.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: http
          name: synapse
          ports:
            - containerPort: 8008
              name: http
              protocol: TCP
            - containerPort: 9093
              name: replication
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources: {}
          securityContext: {}
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - mountPath: /synapse/config
              name: config
            - mountPath: /synapse/config/conf.d
              name: tmpconf
            - mountPath: /synapse/secrets
              name: secrets
            - mountPath: /synapse/keys
              name: signingkey
            - mountPath: /synapse/data
              name: media
            - mountPath: /tmp
              name: tmpdir
            - mountPath: /modules
              name: synapse-python-modules
            - mountPath: /synapse/config/conf.d/mautrix-whatsapp-registration.yaml
              name: mautrix-whatsapp-registration
              readOnly: true
              subPath: mautrix-whatsapp-registration.yaml
            - mountPath: /synapse/config/conf.d/mautrix-discord-registration.yaml
              name: mautrix-discord-registration
              readOnly: true
              subPath: mautrix-discord-registration.yaml
            - mountPath: /synapse/config/conf.d/mautrix-slack-registration.yaml
              name: mautrix-slack-registration
              readOnly: true
              subPath: mautrix-slack-registration.yaml
      securityContext: {}
      serviceAccountName: default
      volumes:
        - configMap:
            name: synapse-matrix-synapse
          name: config
        - name: secrets
          secret:
            secretName: synapse-matrix-synapse
        - name: signingkey
          secret:
            items:
              - key: signing.key
                path: signing.key
            secretName: synapse-signingkey
        - emptyDir: {}
          name: tmpconf
        - emptyDir: {}
          name: tmpdir
        - name: media
          persistentVolumeClaim:
            claimName: synapse-matrix-synapse
        - emptyDir: {}
          name: synapse-python-modules
        - name: mautrix-whatsapp-registration
          secret:
            items:
              - key: registration.yaml
                path: mautrix-whatsapp-registration.yaml
            secretName: mautrix-whatsapp-registration
        - name: mautrix-discord-registration
          secret:
            items:
              - key: registration.yaml
                path: mautrix-discord-registration.yaml
            secretName: mautrix-discord-registration
        - name: mautrix-slack-registration
          secret:
            items:
              - key: registration.yaml
                path: mautrix-slack-registration.yaml
            secretName: mautrix-slack-registration
---
apiVersion: v1
data:
  homeserver.yaml: "# NOTE:\n# Secrets are stored in separate configs to better fit\
    \ K8s concepts\n\n## Server ##\n\nserver_name: \"josevictor.me\"\npublic_baseurl:\
    \ \"https://matrix.josevictor.me\"\npid_file: /homeserver.pid\nweb_client: False\n\
    soft_file_limit: 0\nlog_config: \"/synapse/config/log.yaml\"\nreport_stats: false\n\
    \ninstance_map:\n  main:\n    host: synapse-replication\n    port: 9093\n\n##\
    \ Ports ##\n\nlisteners:\n  - port: 8008\n    tls: false\n    bind_addresses:\
    \ [\"::\"]\n    type: http\n    x_forwarded: true\n\n    resources:\n      - names:\
    \ \n          - client\n          - federation\n        compress: false\n\n  -\
    \ port: 9090\n    tls: false\n    bind_addresses: [\"::\"]\n    type: http\n\n\
    \    resources:\n      - names: [metrics]\n        compress: false\n\n  - port:\
    \ 9093\n    tls: false\n    bind_addresses: [\"::\"]\n    type: http\n\n    resources:\n\
    \      - names: [replication]\n        compress: false\n\n## Files ##\n\nmedia_store_path:\
    \ \"/synapse/data/media\"\nuploads_path: \"/synapse/data/uploads\"\n\n## Registration\
    \ ##\n\nenable_registration: false\n\n## Metrics ###\n\nenable_metrics: true\n\
    \n## Signing Keys ##\n\nsigning_key_path: \"/synapse/keys/signing.key\"\n\n# The\
    \ trusted servers to download signing keys from.\ntrusted_key_servers:\n  - server_name:\
    \ matrix.org\n\n## Workers ##\n\n## Extra config ##\n\napp_service_config_files:\n\
    - /synapse/config/conf.d/mautrix-whatsapp-registration.yaml\n- /synapse/config/conf.d/mautrix-discord-registration.yaml\n\
    - /synapse/config/conf.d/mautrix-slack-registration.yaml\ncaches:\n  global_factor:\
    \ 1\nevent_cache_size: 20K\nmedia_storage_providers:\n- config:\n    bucket: matrix-synapse-media\n\
    \    endpoint_url: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local\n\
    \    prefix: synapse/\n    region_name: us-east-1\n    request_checksum_calculation:\
    \ when_required\n    response_checksum_validation: when_required\n  module: s3_storage_provider.S3StorageProviderBackend\n\
    \  store_local: true\n  store_remote: true\n  store_synchronous: false\nrc_admin_redaction:\n\
    \  burst_count: 200\n  per_second: 100\nrc_invites:\n  per_issuer:\n    burst_count:\
    \ 100\n    per_second: 50\n  per_room:\n    burst_count: 100\n    per_second:\
    \ 50\n  per_user:\n    burst_count: 100\n    per_second: 50\nrc_joins:\n  local:\n\
    \    burst_count: 100\n    per_second: 50\n  remote:\n    burst_count: 20\n  \
    \  per_second: 10\nrc_joins_per_room:\n  burst_count: 100\n  per_second: 50\n\
    rc_message:\n  burst_count: 100\n  per_second: 50\nuse_presence: false\n"
  log.yaml: "version: 1\nformatters:\n  precise:\n    format: '%(asctime)s - %(name)s\
    \ - %(lineno)d - %(levelname)s - %(request)s- %(message)s'\nfilters:\n  context:\n\
    \    (): synapse.util.logcontext.LoggingContextFilter\n    request: \"\"\nhandlers:\n\
    \  console:\n    class: logging.StreamHandler\n    formatter: precise\n    filters:\
    \ [context]\n    level: INFO\nloggers:\n    synapse:\n      level: INFO\nroot:\n\
    \    level: INFO\n    handlers: [console]\n"
kind: ConfigMap
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-matrix-synapse
  namespace: apps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-matrix-synapse
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-matrix-synapse
  namespace: apps
stringData:
  config.yaml: "## Registration ##\n\nregistration_shared_secret: \"viwvoA0V46fSG4sYuiWC6dHq\"\
    \n\n## API Configuration ##\n\n## Database configuration ##\n\ndatabase:\n  name:\
    \ \"psycopg2\"\n  args:\n    user: \"postgres\"\n    password: \"@@POSTGRES_PASSWORD@@\"\
    \n    database: \"synapse\"\n    host: \"postgresql-18-hl\"\n    port: 5432\n\
    \    sslmode: \"prefer\"\n    cp_min: 5\n    cp_max: 10\n    \n\n## Redis configuration\
    \ ##\n\nredis:\n  enabled: true\n  host: \"redis-headless\"\n  port: 6379\n  password:\
    \ \"@@REDIS_PASSWORD@@\"\n"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-matrix-synapse
  namespace: apps
spec:
  ports:
    - name: http
      port: 8008
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/name: matrix-synapse
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-replication
  namespace: apps
spec:
  ports:
    - name: replication
      port: 9093
      protocol: TCP
      targetPort: replication
  selector:
    app.kubernetes.io/component: synapse
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/name: matrix-synapse
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: synapse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: matrix-synapse
    app.kubernetes.io/version: 1.146.0
    helm.sh/chart: matrix-synapse-3.12.19
  name: synapse-matrix-synapse
  namespace: apps
spec:
  ingressClassName: cilium
  rules:
    - host: matrix.josevictor.me
      http:
        paths:
          - backend:
              service:
                name: synapse-matrix-synapse
                port:
                  number: 8008
            path: /_matrix
            pathType: Prefix
          - backend:
              service:
                name: synapse-matrix-synapse
                port:
                  number: 8008
            path: /_synapse
            pathType: Prefix
  tls:
    - hosts:
        - matrix.josevictor.me
      secretName: wildcard-tls
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  name: matrix-synapse-media
  namespace: apps
spec:
  bucketName: matrix-synapse-media
  storageClassName: rook-ceph-objectstore
