apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: dendrite-test-password
    namespace: apps
stringData:
    dendrite_test_user_password: ENC[AES256_GCM,data:aFMXfqxFFnDwFsMgViwbEkgLi0kNjLA=,iv:GdLxE6AvcAoqVlZ3Wf0h90LWlv0siUnSv44bW6gt4I8=,tag:+QHPMoiDwB1sSDpMBvIMkw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMWYxcWJuZ01GcUoyanRU
            QzlyNHV0T1loY1FjTmwrRmRWWTFmb09BUWtVClpDb0h1b1h4UVNqckFyczBpdmRR
            RitwRWVSQU1BODVPY1MwSHQ2Y0ZZTFkKLS0tIFI5cWR6eFI2UTdCSERXUFFUakxt
            STNhaFNXNGVhVU9VaHJKMmFJMHV0L3cKLwdOVt3MG3C2iun3UMosS08oYtIMISHE
            c3uyMl7WV0rpKPzjLu8sZPHyt8C1zB+0zytLMdQffUkl3EkapFK62A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN0M5QkFCKzNUSXVTdG1E
            U1FySGdzeVcwU2s4aFpscUVJTWtWY2JOODBjCkx6TEV3VjFhcG5ZUDVwbUYvRHZD
            WE5OKy83WXF6dnFtVWh4YVdxR0pnY1kKLS0tIHRaQmhlbGx5OXdQRkZUUFZFemJy
            OFZ6bUhTSVREUDlOZXN1SzBYWmllMlkK0YmsCsapG4eb2fBUU6rZbj662ahTD2BD
            kMEx4BDQDF8JC9zeIOs/OWlwHovKPqpdUeXoU0y/GPwwpAtvmPCKug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZTRaMG91Vk1OTys3czlz
            aFk5TjdBYUovVkhzVVZORXF6QnF5VWZ0UHhZCnZaWFhIbDRMRHl0Ym53UGsvejhX
            VDRIWGs2emVtWWsybUlhNHRaNkhiOVkKLS0tIHN1d1hROEV2d3UvOWZBYlhmbVVZ
            eFJRNGpWRjIycmRnVDQ3Ly9RQmRRUWsKIPKrwaqoU+iXUhzn92UmWdI+7usUn4nz
            vd67+i9D1v/DYTwdtvgFomjLQNzDZioME2BoXmzH+LUFbpHULnoLsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:40:58Z"
    mac: ENC[AES256_GCM,data:wlXjCgxTkvivMG2r5IiUWAaWpe/uQM7s7n6Z+ATlef+L0zulEKyM4MjZ/g61m/avkp7P+ADcGWnotTMiy9lESzbC3hXh2hPVMERlvCYsIP7dXUiapsemkmSeT50oZTg1YBL/4GN0rZxt3NKhDUravKQr2eu2UXGCClC7vi0opGU=,iv:+pzUz++lLXSB277UTUaZO73h356O/Eb9Efh7Uv7K+xI=,tag:4iCinRIYySPgFSmnmXtcrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: matrixx-config
    namespace: apps
stringData:
    dendrite.yaml: ENC[AES256_GCM,data:sbccAXTBHEmmE3NaXlHwYD0tb6BDVhbgmo4SQi2x7zxR+fhxdLuUP/6P1EHh9By8H38coReQjVXyA0W8cywNv5JSxP8Go/2uluKvfOwznI4ZaVivJLUPBEuMcGMyymOcgkUDcu484p9OZczSRQnvNASbx0fOwXAqoopgs7IOsp7NFb7X28uMjidbFB6Md/ftDySt7AMuNiDOJBiXuIUH5xV0BZtQ/79SdXFhRpqAoBo0NR72/1bFtR6N6Gn8Efzf4V/GI2Id7NqYdT1U/rBRyttkm4BrJkynbmqatq5oGGCD9PkMTOe54RR35FRh+XvlrmKM1InqvsJg1oQDTtC0qdxXAVkRR4zIUQ5VrIFQpvQ+nXzlEu3WGeI3u5sYY73HowSqITXFr6m5qzgy4oGeeSTI4Tmv9CEXkIkGpMpnh91ZoUkPYMTqprWWGXGRZRbeagcFIwLvCdsyGD582edMi8jbb9hyj6BC5bSFeqdT/mqO8Xu5AiFj0x+istIQ9K5Zw113aDHo5w9r595PA0EmMzA9l4bUf8FAAnS7IcK6vF2ul8w09SKIVcsOWKC++CeDebnPb6zatjfMnKMYyd/Ipnpo2m3JXCGACG8a4K/hjuo34ITvtrsEHGfsA7YBzVfCwOC1jBG5AHbSpOdtYTSv0CXtzBEhPv5NQvI/voI19PuWfivI+6/NMpEQXDRhI8aM1D9FgYRktPlhTPuRCoBBbaucUY6v+CJeGtzruNW/DGXHIfA0JMUmPIYAgpmgIbLy3H0QJBcyL4x3SYbBjs/nDjbVhHiBEYXKOmu7ZNdyel3cIAwsEcsptZ2G89FzdR1AJI2rkUJtVRxiniMmvum6tzuB7u0VYvoN5Fjz1fuL3Mz4r0+eGSWK5qMduzfqnoyZnGfWpvrihEzE79w=,iv:25bpaFWCof5shvHi/obFO58Pa2JbLxi7upxwiC4HEG4=,tag:EojCL7MzoUPlC48h0vmddA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMWYxcWJuZ01GcUoyanRU
            QzlyNHV0T1loY1FjTmwrRmRWWTFmb09BUWtVClpDb0h1b1h4UVNqckFyczBpdmRR
            RitwRWVSQU1BODVPY1MwSHQ2Y0ZZTFkKLS0tIFI5cWR6eFI2UTdCSERXUFFUakxt
            STNhaFNXNGVhVU9VaHJKMmFJMHV0L3cKLwdOVt3MG3C2iun3UMosS08oYtIMISHE
            c3uyMl7WV0rpKPzjLu8sZPHyt8C1zB+0zytLMdQffUkl3EkapFK62A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNN0M5QkFCKzNUSXVTdG1E
            U1FySGdzeVcwU2s4aFpscUVJTWtWY2JOODBjCkx6TEV3VjFhcG5ZUDVwbUYvRHZD
            WE5OKy83WXF6dnFtVWh4YVdxR0pnY1kKLS0tIHRaQmhlbGx5OXdQRkZUUFZFemJy
            OFZ6bUhTSVREUDlOZXN1SzBYWmllMlkK0YmsCsapG4eb2fBUU6rZbj662ahTD2BD
            kMEx4BDQDF8JC9zeIOs/OWlwHovKPqpdUeXoU0y/GPwwpAtvmPCKug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZTRaMG91Vk1OTys3czlz
            aFk5TjdBYUovVkhzVVZORXF6QnF5VWZ0UHhZCnZaWFhIbDRMRHl0Ym53UGsvejhX
            VDRIWGs2emVtWWsybUlhNHRaNkhiOVkKLS0tIHN1d1hROEV2d3UvOWZBYlhmbVVZ
            eFJRNGpWRjIycmRnVDQ3Ly9RQmRRUWsKIPKrwaqoU+iXUhzn92UmWdI+7usUn4nz
            vd67+i9D1v/DYTwdtvgFomjLQNzDZioME2BoXmzH+LUFbpHULnoLsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T16:40:58Z"
    mac: ENC[AES256_GCM,data:wlXjCgxTkvivMG2r5IiUWAaWpe/uQM7s7n6Z+ATlef+L0zulEKyM4MjZ/g61m/avkp7P+ADcGWnotTMiy9lESzbC3hXh2hPVMERlvCYsIP7dXUiapsemkmSeT50oZTg1YBL/4GN0rZxt3NKhDUravKQr2eu2UXGCClC7vi0opGU=,iv:+pzUz++lLXSB277UTUaZO73h356O/Eb9Efh7Uv7K+xI=,tag:4iCinRIYySPgFSmnmXtcrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
