apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: dendrite-test-password
    namespace: apps
stringData:
    dendrite_test_user_password: ENC[AES256_GCM,data:wLvXtYPHrNIbdMx+ea8i780NcpcxNqA=,iv:/SBwZQ4fXyPZfmd78NUKycrBcT2/tZdnIG4sS9k0QMk=,tag:+xScEsIjmuJQ9pQm6k6hjQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVkZlZmpLZEx6SXNqV3Mv
            Q0JDUDE5TS9XekFNenZGZkk3bXRmZGJOaDBVCnRhZkhpbjAwUzhscHdEV2pEVE5F
            Z056dkVITk5idCt3YTlLRUxVWFVScEUKLS0tIEhUYUV5RHZaakJacEtwOEJsU1FN
            WkdMMUR2R1RVRmp5eWUzbWJZNkVYYXMK49HX8vpVQ4dRpU/c6Oeqdrf2L7YQPIaI
            FQfG3gjCOG6Gp3Tca+8l9kibBOcG2VOgXQsWWEcCFgCajHn3j2SDyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYUxpWjhTRUFBdk9KZG16
            eVJSRzZkeENOQ09OTHZGaXI2d2dZcTJOOTNZCkVOdjQraHEwaWYxc3ZSbjV1aE9V
            cXgxYThEeWpKQmpFZ1EzRXpJbDJOYlEKLS0tIGRsUWZSd3AyamdRQ2lIa2JGNnAr
            TDB3RWxPZkMrS0J2ZDZpejJvZ2RoSDAKusRwahtJxSJ/Txp2ZSPbG2g+13YXvDmm
            mddC80Am7+Sp8wenXyY7RWLbmzVVue6BudHlaH0+TcYLSjrJsgFaPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR2pGakdhVzFjUGJHdndn
            VHp2a3dMSzVUamc4aWFqY1laT1I4alRkYlVjCmJKeTdBdUlNTnR0L3FHcU1hWjJq
            Y2QwU2kvdWtuMmZnbnMxa0VyaWZ2WjgKLS0tIFlBUWxTUktrT05MRXFKNElUUDJr
            aEJSTzVkSXY3ZjBLeWU2YXVSN0xaSVkKN+qEAY72p2pgsCsL3b5bZ5YdXoQcIz1k
            64F6BYf+XWeojHA4dAJGx7ytw8CrJIlypZhbqYb1XiRfrlbLBWFoYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T17:58:59Z"
    mac: ENC[AES256_GCM,data:T72aAv4TXb3FllSMJJwWZhLx5j8MCcbqAryQ66mtK200g7nOfk0Hust78FLbdtxYJwvFOF202tU8vZU4iRo33qZdcFydSs47VbPx1YVTE5OyGiMV/xkbR8TZ4XJ490hHkV9CM7q9bFvh8bjDGsPfIEbRWDbWv3QhfuW2RTMed7Q=,iv:LaZoAu3RSWQeJ+AA3lpFWf6fz1qTKUYh6iNmxgMTewg=,tag:kAUuRutOOXKM/I7VU7lBKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: matrixx-config
    namespace: apps
stringData:
    dendrite.yaml: ENC[AES256_GCM,data:zQrweda14LopAA3YzCJQVwRVSS/WQeSqy4+ihQae87vHWHhx0ajarhGtTRCLCJ1ClgkcYjRRsIqWs5XE/1HnDCTDV1vZ5Hgh986vSyo1FUIT1saZW7Hrge9sxFtfGYdOhwEi7Co7CjH0dh/ZxjRJFd6r+6sXZtzCwdCa5HuqPEDc5BXXmwmCRJm4P4jE6ow9/zevHAjWy+NRoeiQQ+a5yKIb1WLXSHICTMGBJlrctDa5tb7YMFdQAvjLs23hN6wj1upvpDEVGY67t1fyr5W8QrvH+Joh9SMxtL6//LO4m2CEOobqZaOBOCBeZIDB/WGbEqjZVbVoAklkJrq/6o/4qMW+oFq3rHGE+t1SYLCr7BfTE8vikcZe1/xBTElY65hRMYU/Tfd0OFli8kyi9Zt7WZOFJcKCSnEeyAGcFADCUpnu0fy0TtkhkViAK2GIDeqmYjJ0IKNrXdyfEwxVAPDpOv5cZuRzTpdWxOHY7DQVVHyFMQluYSj68aMReRTUMZKIW7B9cnAFOSAwUuZLcc6KmGQaFOCj7Gw6slxLfXwrh4prNUPcbHvi+z5iGP7EhKjpNSXQ5KmjHDniR7CONCi3+2C5mwbOR0PqyXXWr7dVqW+LsIpgIhn2qhSVFwqAiGZmTXBAu3WqDCcpqrpK4SxwVILi8aP0i9woXgXn7eIh1vBOtDYJ4zhAQnn9BLGcmZ0TnNpR2QHlexUWLPlYD/r1gMuxYa1LROXyeYxs08vz3Y68GEO5fiqrbXiYqzaH/QXhrBxW8Erqaw03nRTJvA20X6hsruHJlv3dQTF1uRxQx3yJbZZ9DOXIbeTgYLgCoiOjgyFzNON5k9KqHRCIgTpz0u5Wc3bSlbHSKO8tcx9fF1J12uDqzkB1bpiAEpguhbM1sokwscYEl+pG7bFFuyAhI0hF0wdXWphX7yQkXX1B6WgCqlAWJ4a7bOznD1P921q3TLrW2To8pnQw4dCQ3+UkNP6Nawm6AIh52oU8weP5zARK4NL5VrwSJdE6il1sclwwiYUjuEyveSAAruS+gVPoxajPOzOqAdqM1P3Vfn+Vis1pyPXtCLna1Ih4bqOzmZFjCguRNRvLPjhzOA==,iv:sB3csOpa+8Hj1c7P23lPUInO6k8BJi4GreR8OX5itRQ=,tag:u7XA7LXqa+aZF1nRP1F0pg==,type:str]
    matrix_key.pem: ENC[AES256_GCM,data:erbtr+7ET10Q47FxcI9X8x1p02ZqWvSCUkufAoU9DGrzzoNcGXVR1PAxyl+zeyMWgLllybSOFBMIiDl9kQBCsKsAwcVJW+kPH0WJKK3NffpbIVo/Pzlo82uJRgoZ+xlLvbR1MZz0mLOcKtNHxl5MXxo0Vm7wZmRT1IMexq8JTbo20ucQ2tspR9s=,iv:v69s/N2M2DTPG50rgYfmvm7ms+el3nPrVZWI787uVj4=,tag:AxnZV3CY8+VQu68IzvOpnQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVkZlZmpLZEx6SXNqV3Mv
            Q0JDUDE5TS9XekFNenZGZkk3bXRmZGJOaDBVCnRhZkhpbjAwUzhscHdEV2pEVE5F
            Z056dkVITk5idCt3YTlLRUxVWFVScEUKLS0tIEhUYUV5RHZaakJacEtwOEJsU1FN
            WkdMMUR2R1RVRmp5eWUzbWJZNkVYYXMK49HX8vpVQ4dRpU/c6Oeqdrf2L7YQPIaI
            FQfG3gjCOG6Gp3Tca+8l9kibBOcG2VOgXQsWWEcCFgCajHn3j2SDyw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYUxpWjhTRUFBdk9KZG16
            eVJSRzZkeENOQ09OTHZGaXI2d2dZcTJOOTNZCkVOdjQraHEwaWYxc3ZSbjV1aE9V
            cXgxYThEeWpKQmpFZ1EzRXpJbDJOYlEKLS0tIGRsUWZSd3AyamdRQ2lIa2JGNnAr
            TDB3RWxPZkMrS0J2ZDZpejJvZ2RoSDAKusRwahtJxSJ/Txp2ZSPbG2g+13YXvDmm
            mddC80Am7+Sp8wenXyY7RWLbmzVVue6BudHlaH0+TcYLSjrJsgFaPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR2pGakdhVzFjUGJHdndn
            VHp2a3dMSzVUamc4aWFqY1laT1I4alRkYlVjCmJKeTdBdUlNTnR0L3FHcU1hWjJq
            Y2QwU2kvdWtuMmZnbnMxa0VyaWZ2WjgKLS0tIFlBUWxTUktrT05MRXFKNElUUDJr
            aEJSTzVkSXY3ZjBLeWU2YXVSN0xaSVkKN+qEAY72p2pgsCsL3b5bZ5YdXoQcIz1k
            64F6BYf+XWeojHA4dAJGx7ytw8CrJIlypZhbqYb1XiRfrlbLBWFoYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T17:58:59Z"
    mac: ENC[AES256_GCM,data:T72aAv4TXb3FllSMJJwWZhLx5j8MCcbqAryQ66mtK200g7nOfk0Hust78FLbdtxYJwvFOF202tU8vZU4iRo33qZdcFydSs47VbPx1YVTE5OyGiMV/xkbR8TZ4XJ490hHkV9CM7q9bFvh8bjDGsPfIEbRWDbWv3QhfuW2RTMed7Q=,iv:LaZoAu3RSWQeJ+AA3lpFWf6fz1qTKUYh6iNmxgMTewg=,tag:kAUuRutOOXKM/I7VU7lBKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
