apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:vblB4NWXDPh9VnqgDnaI6v55W6GVUP9RxKP4EK/2o0qmnz1M7uklGFMReKkf/JXRLGd3vZV62+WaWe8=,iv:y08tAoYIft7rkWVI2cKp1WQqZR3yGCz1ydLrtkEWpu4=,tag:srHXcGi0q9sMfyYsYSeoKg==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mau-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIb0lzNnFIYm5qTmNHVFFM
            MDBDaS9IazBPNTZYL0ZwQ29VcE1LQUczbVY0Ck9rZ1JxRlppdUNEY3Q0clhwNTNG
            K0M4YzBpc0NTUzJqRyttNHUxay90bmMKLS0tIDlZR2sxYThFdlBvYlJuZzNhNjAy
            a1pqV0xSd0p2SWpPZkhuY3M1cjBESGMKZEF+OCqlCL1yG0+lJ1fI7qVfQZw0q/QM
            sLVmNgHyuki0A/Lb/ACPhPkFrocsErhFQnrOQoQgmT8u0VmlTeLI3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocmUzeDNmMWxjNXN5ckpW
            U2ZVSS80WUlacUtJVkViY1FncVpBOHZOYlhZCmNwWjl6dytwUVNOL2tadi9sWmI5
            L29tMkxQKzAybldTdForaUdadEFkMXMKLS0tIGVSc0tUNTFVTG5jKzkrZjAyUUV1
            L2FKZ3JoRG0yRC9neGpaWXFtMFE0TkUK6lJpx3hChBSPkmwv9j+m1Nt/ti++ghKW
            PKL9NGR2gE4a43QhAoaQzMS92Ol6/rFhBITo93yBfoXAs3aTKFRSXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVHc0OUUyTW1WV0VCSkRh
            MjlKei9iSmhaS1B5eDFGRTVYaHhGVHZJTlVZCnRZOFM0UjlFUWtlVGxaaUh4ZTRU
            VGlNZFZ0a09hSHlGYXRUaU9qQUJSUTQKLS0tIHMwbVZyaDU0TUdIYzlsbUNIMk5Q
            U1kwZThIWWZMRzcrK2xSWFQzYlJZVVkKU7a6DhDbE7/4hQMF5OpaVxRJHus7HtJT
            rO2Q0oFMuwIK+x1fNR+e8D4yuwDI211a5TVC/zSWjOzXGxxvcnigfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:00Z"
    mac: ENC[AES256_GCM,data:Xr8rOrqdLQtNpkUvIpXh1shAspRrTyDU+cir1UYlSsLPmxT3YbufDPnD0XIglRsYOXMmmtdC19GhLJKc8cQp/Hj64UWi8Zkru3BtxWURzooZlSc/nAhAEw9e+vo7gB5JcwrIaQE9NHiw6JB+mWGleCGLP5D5sA5RMF7Jbq5YY0c=,iv:X1TzzHM8ZYnNdvumdMj1c6HT21YGVGf+kJc0jQStXSY=,tag:weIQXXTWISDjotrznQS/OQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
