apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qgExnYuzQAfATeCKVLabdle9X8SNLyKHSR7E+UJPSBz1AjgnXqm4vvFggYtVhZn/76YD6cKTQMYtMZFqTKa43c7VcTIqKfH+lBdOr0LjptrMBaaMIcqP9Un59/JivjbcaO62x2aJS7hhNROe/yUxatXpb5tJaLYfS+Wnt/FWmVY9i/5HIwwQqG3iDjc0NgAxpA5K/Sw1ms4ujKIk9MmQGdJ7tIyUa5uEruvQPK6JRVTcSlZmczYqnzfZoJJyNwxOSClvcOmFrChOjT4CJ7MwuSum1fCc7EVnu7P5TXJJ4oyDJzCKUVbufpKcqENwn6PYpOvy/cFOamMvPXReSzUaJUp6wE3tM0tC7GWWbZtbcusa2zWM7iQLOISy2wnnhXlMgaOezvoAdYvX5ihG5U/gdUC8rHzoiqIo+y6KE7Clgil5ppGRDLPeW/y1B/u96zy2OeVSHgvWRtaG58C/k4cbFHURIj5Wtda8o+K8phcXQLFahQ4KDkGnimTIJxgpKk+TlIllh3W7FbLPaapIvTrAbQQY+PODrS8cH2r7ooCgkCTonsG3Pyv29kBqZGHyTCwr2b4CfkKh+iOxE38I,iv:vmpA2DaFBob3ht9NXSJ4tu/IStQByy8wMh8OVD6cxTM=,tag:d42wfs1zLD3XNvE2salrwA==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mau-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja293YUdHemtWRGl2K0JH
            N2FzNncxS3lRMkN1bEl4OVRrbU5NaFA5WjFNCnE5RkVOYUhyaXVUZHpXb3J0VzVZ
            eE8rMVhYNDAzK2EzbmdDS2xqWEZwZE0KLS0tIG1RQ2pzNm54NFR3REE4akRrRjdl
            MEFDdnNGSkpPa2xSNTlzcEM2WnIrYUEK0P5VMZ7Z1dbQyY33XBKVDhxg8wbCHJ+d
            bWS7tXbRREo/Urwb5otLzQRCpXjV/yyWMoUw/A9EVpnKEIuoXWd+Jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRkY1cEtWTm5wZDJwd29z
            SmhjQklaclJHTnA0VnNOWUZUU3FJczBRRm5VCk1idXVpcE10REtGOThvaW5QNEtD
            MGxwK2FsaW9kVlpVV1R6MHlVbVUrbmsKLS0tIEtaRHBHM3VXNmdoR3dyRE02WkZx
            QlB6Ulp0T1c1SmIyN3MvejVsWEJVQUEKgnv7sfgffqwJSaxdwtwfXpzvsGUbH+S7
            kaJwMRDPugw5z3GS9v4BMIMCzvc2rfp966XJk6GAP8s/63x2Lmzu4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRDVYTEJDQTNaOHhpSU8z
            RXU1elVtQ0tKNk9xV04zalFJTGdqWHdmRG1BCjZNOUFNZjdrcTRiRU03YURpeFlR
            aVF6Ym4vNEd1RmxxZEk1L1IrTDNrZHMKLS0tIHhMVXVnOVNTTkpkM05BS0U1SGNy
            cVFmZy9leEQ0V0oyLzJqcDVjU2IxWm8KXD1HQHh+DrP/W9KXXLOr/8X7q253U+Ih
            kXU4rqJ5S1nfj2SShc2eHv/byMXtedP7wF4OdN5nZyuTP8iFkOp1WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:59Z"
    mac: ENC[AES256_GCM,data:/oW+2suW3u99sf1jwtjkQcIWwCXPPcyYDNMBip4NkXor3nzRAKjvQlZr8jwPbFXHF7PSnoC3pniTf//zW29yWlf9BWRbOgL9LIywexGwXGyeuP14BcLxCs/VOyElEVMwF8/F4nlCM+2O2j0tJ1tO6yVGw5OsKGsBuNTziJ04ZqM=,iv:Cv36TTFkXqPtaLwNtqzLimKVgTleSfCeNwPkLlyZAKc=,tag:oOWCmFEJwJDpbAduf98SWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
