apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:TdvggQuRSULFS3LSvxYZW1sQl4blXaJcXtciyC2qAlDsP5bTiVr02XcfRfNEqkOMArrxWTPjFwdpISf2z2i1+4PBMTDOBz+ZSoHioFoq/F2nn3jUR8JyVdoYp83QOdvsFiXK7RNIQdFcZgpNYj0a3xSxVRqhbC2YTGyYOTcwSYhQmpEt+CFJrqEKzpxPJcGf5N3zQVd26w13FkbwgT0OJl+dWTEGMc2guKWgq/R2pTho7fx3DS+YV3E9OAPO9LgGIe1cNMd78IWG4adEzNjxab6RDYiLypGEDRFcXSwOCb33226oI3suK5YDB53eNfDp6McydtXw2BC9BKVjMKWarAKdhqBBiHfMXesLPvZr1cVRQz4snPs86dU8Q/ylZl/2LwLZIcgmaX8y+n72rujIRh5fqOAmyP/s//h+I94fxECUcHLnT54jAszggXlLuVygoNbHP8Q3WebSGbFApRGKA4fdZkpK7gVTLgostmUKnI4UVqLswpGxb8u647r2LTeqo6SlWoTvCVevg1g452DB2DhmLsHdVz074H7rEIgustsTQnH1U91y7fNhbEhrPA84N61raH2ZNJ5B4SIu,iv:7ETBdhS+9KJKI6SGPKEkTIIZoc385kKUnJlNkJalO4M=,tag:joDS4pZ+OR5gt+xHYJY5DQ==,type:str]
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: mau-registry-secret
    namespace: apps
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSU42TVJ2dFp3ZlZDMERW
            K1NaTFl1SnBZQlBmT1dMY3BtNkc4eFZURUdNClhSOWxLTmQ0R1hIQk14Tm9VVkRG
            bDJuWnhIeEF0U05odVc5QmZDdzA3N1kKLS0tIGJlNzY2eEk1SmVURmFLTUJ3TTN5
            azhzdFdUY2tOcUU2NFRpQ240VUYwRE0KF9RLXEbU4bJUFJSUh0W8++clyByiBa/m
            TivDezKoULvwmxENCwTtyozXDlc1Cc+CNXqpxv/gFM+WaCUmoBQztw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGK0ttTEl4SVVDWWVrQ3Y4
            ZEorRHBtUlJYbXlkS05iSXNIS3Q0VlQ4aEhjCk5CUmMrZFEyTllEeU5qKzZzeTVY
            djBRcWhHNUFVZzk1cVFUNG9xcTZVR1UKLS0tIFVYdzczY1BKdGtLQ2Vod0JaN1FX
            M2VnK25oNHFJQnlRbzUvZnY5TXJmSTAKcqx3mk+ESMWb5KhsWBhXdj/46Pp46zWY
            vjrVppBA5Rb80XZ0jXjkmpo82MJg91muZXlKgN9P3/QIq4AktP9oSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqT1FiTmRSYXdSZDlCTDQw
            UHFIVDN4Zkk3Z1UxWUxTSmdORldSTTk3TDBNCkIxcG5TZzZ6cFFQU1dqQnR3T2tL
            bUZYNW4vVFkyY2hqSTBlWU5iZ1hUMnMKLS0tIFNrZldFdExUYWxJUWdkR0lEYzdG
            REh0cXNmU21EOTNZYUxxa3BZNnZxYjQKPW0W21Mqdba74M6RPuKweZEdD62yByDH
            sC5EOE5ViY0xTHVKcQCwmPrrbgasnk5tFh+ORwpIT7v0/CgE0rexdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:00Z"
    mac: ENC[AES256_GCM,data:2UCZoUEzU+2rPMksX3PxGG4my4bPf/EQmZNP4I1CIrizh4vOjmWemmlBRB8dMbM4kg9tol+W1vwMBL3jcHkUcE5f1cJf9SWYXq2U8p+lqxFAWGjmJoNu2jqg2g4nf8GU43mKKhay0sY5PSYm+flsDl+ZMno6X3IfxFKqEuk7tpI=,iv:FVkJki9D9CNKeQ35HZXO8FoTm+kr3GkXBdRiyek3O6U=,tag:8AVyPgpcbbo/oHsr7GJDig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
