apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: n8n-env
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTm1jSVo0ckI0a3l4RXht
        WnVTdGJMcm9KWkxMTTNPUWJSWThoZjJab0dVCkJ2TGtpRWxrVFgxaXpZbXZqRjFY
        bzB2VVJ1THhVTllvT2I1a0R3Snp1dFkKLS0tIG05aHQ4UUNLa0ZzTWtvUXB3SmE2
        aHhId3ZBNFRvZTcwYnpzQ1R5VWVrTm8KdlIugg0yXzTlprut8lCcoMDbMGIRO+Qi
        YjkGIjWnIRDjAqlFCZcyDvGPNjS6f5os3tnk/dT9hEymVdh+YsTpxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSelRmZnppK2FENGdHejEz
        Rk5OaG9NUElOb2gzWFlzN1BuR1BjajQvSEFFCmdQMUFaSE9icm5URlNhUEtSZlJD
        SzZSMHF0VFdyRThtMWJSYlZxTDAweTgKLS0tIDJnNFZ0SmpBQ3pWVTYvU25yY1FB
        Q2JhZFVwZ3RiWFBuLzZQNVAydi9WZ28Kew1LMAU61nFDNdN56giZrgnl3sKkt28S
        M+dOzP9l7MzL7uwWbsHIXNydU/lmQ2HDxiMPka1nuIRbSNA4r5ZO4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4STBiZ2o1V0lVbXRtSkpv
        eHBMUWxGUlhhUE9CUEZWZUpJQ0F6TWYvZW5JClFqWVBhdXFqR2V6cUdCY1Nsdldp
        Mmk2UjJjZXMxeFF4dk1ZSkJWNllpc2sKLS0tIG1kb0Z5b0J4NFhoMWQxVzZiak1M
        RDhFRVg2Y29rWkF4RGRuTndZV09hc2cKEddn8igpMRWtTb5OARuJ62zgIynvTeFk
        y0UJQK7N/5+K2g80WAoOWEyIPPZoYnqZyRv1Tb1vb+VjpuPavIdHFg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:54Z"
  mac: ENC[AES256_GCM,data:4IncD3tOaENIiM6mI+JOyifmaXsyScVrvbEvehTb2plLsIT0NEgdE7LqZwloEfSuNooVIQKxG0X5L2t+yj+ecz1Q4LBsOSzW8VbjtEU0ncUe+p8KJoUtw8vrXzHzAJMLkG4AaB5k9ZOHqgESeYDvWtkrwh3uKGXOi5lVdedxLjc=,iv:OLmOVefpEm/ZvGjmkJEprrlt62fxZ50qS3UPSv4QzZ8=,tag:QyaYDWHKJYQLaN6UimLlqQ==,type:str]
  version: 3.10.2
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:cvK74a0l9KO+2kNVNmsAjfRH4S/orgzPTUz7QpWGrHc0oCGDPB10hHV35cvjHAWBouI5S333Siu+CA==,iv:vQHiT0ylCHDfKvwwMWV5W+QYNXsw4UN69KoKfPy7RHw=,tag:nj7+JMSjWaoPEQxOx2qR4A==,type:str]
  access-key-id: ENC[AES256_GCM,data:i5dhhKL+nduGsh9j/Nwn8DLXwWaX4+qCEBNlpzfNgZOhIIbURZka3bCRsMxeLWRsapFwFJx7OCsYQVEewoSA0X7h1GEbzg==,iv:cJdgIxOj4VmtPJr5ufnwzjasZmnHFDPQoV4Xe8z/Y5w=,tag:E9a7c2TaXNtJZHNnPQmDXw==,type:str]
  postgres-password: ENC[AES256_GCM,data:FInFqOdP0Dk3IwZ+eVkP850wFBTN5ulPNaHxt1MQG/WJbD9o28YoWpNL5cKwM1TIyPfMx9Oznbej6Tg70l/PM4g=,iv:TwjSFAc/jifM3+RvOsS0Y5mHf0jqL2uZMNXrvb4BUs8=,tag:vuobeuGk3s01WxdVExHPIg==,type:str]
  redis-password: ENC[AES256_GCM,data:MeZMMt3Z7QwGulrS6GueCcTmUpIl5pT7SAc/3K/1gKhNocmh2rLZHJY+Qa5Mou6pn+goWkln,iv:v1xTAMZ2wN3kzKMTqiFoVtlcBCU7ctYIHQ3G1wGwbDo=,tag:I1eMvroof6d4uoeW3t83mw==,type:str]
  secret-access-key: ENC[AES256_GCM,data:xU0/ltrtpeSfRCo4DLlO943L8RPOG/EAeDsvb6rrwKELbq89ekgm40lBUxBLJaaapSRBEcpQ0stcCkrhXokh4khL5WPYq8ihImk=,iv:42IBAmSlBaw4SKSjM1L6CkthDjE4b8NCKTwenznVpB4=,tag:nCfjAuO/9UlW0C2isRq57A==,type:str]
