apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: n8n-env
    namespace: apps
stringData:
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:XZXD2CQaukmfU1gQki5KoVqBvP3cOXZy98XTwjrO0Uo=,iv:EIk4IN0cx5K3Z2pjL0tEisw3L8WaDUSbDCzfvTHBLzI=,tag:x4hvB1vgRjYVh5pA7ZtKqw==,type:str]
    access-key-id: ENC[AES256_GCM,data:rsz6QTxPFasc5hRil1ZanvA16jvMhkKQ,iv:Er9ts848g1PsZFJ6PtT/pZa8IkBZMPVXJpp2cMwWIro=,tag:1PaimLU0L2KZZQD2t8+7qA==,type:str]
    postgres-password: ENC[AES256_GCM,data:2z0gWzGN8uZMDdwvZN5GeWkiJA==,iv:j7DNBVtoh10X99yo1D7mb186INkjCBAQhSbSd5w3CJ0=,tag:UBm8aQBnTfTRTduBeTBvbQ==,type:str]
    redis-password: ENC[AES256_GCM,data:5gSc6N/MfKHKE7VrWwjkXXaw1uU2rkUM,iv:YrMFo95HUEilcEto4kAxuuj7jjjSesWzrU2oFaQeVhA=,tag:GEqT+si5YPI61t1bBAEtRg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:MI/zXlOkrfWw6HCeJrveNeTkcq0vZNtmFf/3ALPHqFk5z4zHP/JTLIw35dA=,iv:gmP/SGS6iAilzDYH3nLUfiUMAqoYY9amkYjExqy51nU=,tag:G0cnUiS8TonjX1HUvnEgTA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dkZzSnpmOGI5Q2VXL1VZ
            TUFnZzdtb0ZWdlNGSkg2QVkrZTBqZ0VuSUdFCkw5dDgxekFSbFl3ek5BK1dnSTJK
            enlGL2tDc0FLckxhZFU2NndDbHRUeFEKLS0tIEcwNzlZMXlwRnJSUEV4My9QRmV4
            UjQ5WU44dWIweU5UMjNBYnFJY3hadFEKOEUBq30d00AKUXIudqML4LcA13NQxgxW
            SULTyvRel6xTvD5Sm7wW4nASxgTBFlY0O9c8N68hdI4PoiBp+ykx7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVTd3djdVanJ2ZHM5TXFn
            cXd5ajJ6K1BGdFB2cWNqUk9rMVo2b0dlTWtFCnY5QzlESTBvUmdmREVaTmYxbGVU
            U1BhLzY3RzFKSk9qRXc5UlpvcTVMU0EKLS0tIHJudXU3bG1jQ0NaUGlhdldJeDcy
            ZTdpejRXdjFrS2NwdUdDaWdVanY4R0EKyFuS4rBlFBoTDHW2gf5d5qFVqC65xFoh
            1cr9RM5+cMC+5ZhVqEvih/DNbfC0/4YwF7/FHTZSpdVldrz1ZBiuDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z3hDNVhjaUlvUkJ6YUtl
            cTQ3Z0c0SlowYVNRbHRlV2s5WUNJVnZMbEVRCjhpR1JtY1I5ZGkwaVhGN3RSQzg1
            Nk1UTzZFSFV6SnF4ZFJpMC9TM0hhUVkKLS0tIGVML25rZy9rRkw1NHFHMTlGYzhG
            MjNmSERKR1RCNzY5ak41UU8zMnhSUVEKI5f4zX6/bag+bGglSE48wa63m6aeKBbq
            IXeJBZCltH672eslRr9q1NLJdW7GXd6pOc19lHpOmtSLB3o36pe6Tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:33Z"
    mac: ENC[AES256_GCM,data:xlBfHvcgfgIUuTwpTPoTBYXrYiBkefLyTpjWuQ4UhoFuJUQL18zWGoRb1rsG2mUqdi6MNqjC9cvQwXQfUebH8BTXw6Cq0VyANO06WGm/S/tT4JQCJUnFa+pgDItIFxz9Wii+vGMCazNwHRsbkzayeNtHceLHqGtCVJ/HzPDrBF8=,iv:4D6M1yqo0JFhPdgk1WsnWjDA/m4Qs5B80BSh0LcNFgM=,tag:nbjA40gMlBkDKFGtq9m6kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
