apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: ntfy-secrets
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWEpCSDBKMHRjdm1PUTY0
        QXpXSGR5QWh2eURzajRlWXhDR1o1bEg5bnk4CjI3R0dobittWWpyQnlRSVhIOFFk
        a2ltVWE1R0x0LzMvOEJGQk1yZmlxNVEKLS0tIDAwK1lPWklWb3ZsMkZmODl1TFBZ
        MWVvc3ltMFNiVGRIQWVqOWRRWE5HV0EKT1n0RgpEGz89yeX1wxD3MVuPdMUHxUr0
        d3Sxi7oFehuAZ/79jDnlldi7YJoDA72yI1i5iy6EqdyFGpqT+3Zgmg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvazhHcW5YK3Vnb1NNellk
        SnNXUzZlS21aLzIySXZieGczcEkvUGpKcVFBClB3TEtlNVFTb0VqZTQwbWFHbEtz
        VWxoRzI3STVnWUdsQTQ5OWtHMjQ1NjAKLS0tIFNQZnVNVmQ2WFYvM1B4QkZwOXZB
        czIzZ0kwY0l0TVBaVWhqSWcwQ1RZT0EKZ80E3I1h1G/8r7dPZNU3uV4pQyg0DQU8
        IAuVNXQ5kBIc/D/VS0DXM5rw2NBJkYrUT9QW9TWQnB+xlwJ9Ih+i1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdHE3OUNNQUxCVzJJMXNG
        aEp1S3dTclRVZ1J0MXJWbmcxdGpueWpyekVBCm9PTzh1RE9RaGFQUlNuY1RIOExj
        TU1vdnVzSktvdkRlZ0hEbmlHbFJkVG8KLS0tIGtMa0M5M3pMN09kTU4yZG9GU01F
        dVhqMDBFMHBPUzhaWmFydU9RRVV1eFUKQ6E4v+xNamYBCJKAgNR1R5DFtx9mwqGO
        hyf4DfqlgNsiwMmqTs6JCnh6IIqL8WMSkvkK6kqTeIVhz4AK783njw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:54Z"
  mac: ENC[AES256_GCM,data:1Ewgd8M0jgCRH+jv9+hzb3kMHI4HS5jqg8OgXxz48TDm1cx/33BnW8F2rATxpnXiM+PHOfa5WFu4W3Ho9FgQFoIdg4VCXpNz1jnWegkqByGEhPYYywQPGXLz+fYEe/aoM6k/HVxTU8jhocwKaOiaoR5BtcLG0TEKNvS6Did2vsQ=,iv:5MQ9jwAAZub4oUQzeTVXwkkoAkkazs0MdHSvezZRHjI=,tag:9ZdZOeFstgnvK0wQ9ceOIQ==,type:str]
  version: 3.10.2
stringData:
  privateKey: ENC[AES256_GCM,data:sDwmvQ9lL1FKRH35pxoYuBsEKLoD4nkBOdoQ1kxSPwVX2qdAw9CPRe+gNtqaV0nHphjqa4LHl/KS,iv:bQplume97F9oiMx8DftWqP5SBOhCd+FydlubbglhN28=,tag:Pau0aAKgq2eg2AwE1KPggA==,type:str]
  publicKey: ENC[AES256_GCM,data:j3qc2lWwEjktLuhENk9mbZPCYGePJFDJSGs0unNXhKdgQ1H5m51vdLg6QVT8pQ//0Rf0yCzNFM0=,iv:/J+PdnaadgqW9rMRSrf6TJRjF3YowUFzhlFd4VFvmeA=,tag:ADD7BPEPaLnIhSDj8u5JDQ==,type:str]
type: Opaque
