apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ntfy-secrets
    namespace: apps
stringData:
    privateKey: ENC[AES256_GCM,data:9kTUZHlDfFiDaPUR9tjeeP5jJlRrOzeosbMeyjFAPyXt9cDxLtfGiLBKMQ==,iv:pmeqKMFfKJX3RcfwYQVMTQClaorpnhmMn9iU2NoI+44=,tag:71SA25UBuObcIUFuZjdZ9w==,type:str]
    publicKey: ENC[AES256_GCM,data:QwUStCvm780yhiC1Q3sSMN0qdWj9gXdDnIQyWd6v99+I39O9gE68XSo2MJ5Db4aAJOT//16ncOQE/O9i8Tg2zll40SFy8J7E9PTjryZrrDgDnVRzZYz8,iv:wsw0anG0B+0H8q9Ly3TPUzs59yYri79RpVqlqeCuDyg=,tag:r0GD5pE7ol6wELM5/GUO8Q==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRazhrTEVvcWxrK2lqTDAy
            RW1iZVNDUkx2ekRYeFJEVkswZi9uRFNzZzNZClJpK05hYVBCT0RBTm9YQUQ4RVYv
            QkQvRHFCcUVrUXc5NjFES0tuWkxmNnMKLS0tIDhubDBrVmdkY29MemdKSytSdGRh
            Y09YTzdmOC9DQU1NaTc5WlJOTncrdUkKUyHkPyDtxRr7affixk681nAwmYesoBi+
            1H5oy7RLbwOxyxLcFqFlL4U2HaqOx8/hY/5n5g2tr3EnMGPeGqIS4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUVpwYkFQcmMzZmVxWFhT
            SFBGbS9ueWU5SUp3NU1ZVlplMFJ1dXRVcHhjCnJVbVdmeUpKaEhMelhiQk5TWlh2
            NTFOU050TUZLaTB6cnIrRERFTGhqcEEKLS0tIGZ0cmlmYWFydmNmSGZ4elU3c2E4
            cHNSdlA3bWdhN2xyR2dtS1p2Y0JMQTAKiRTsmF6XD+4RgSvhQIJoeH964lhKzBD1
            ZRhxT0H0DI2ErGs5J2shVFxjhxqQb9bAn8vGV9+aQPgsGIhISoJ45w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbVp6TzJ2Mk9ZRWd0T2Rs
            blVqVTJ2b1Z5NHNSWnQ1QkZkeE4vTzhySDN3CjZSU3E4eFlrYmt5VEw2bm15Szh5
            azJUWjVrV0NLZExGejRkTzVQLzBVTDgKLS0tICtSS1hkVHpPa1RmM1Z2NjJiUHBn
            dW5xd0FVSm1pNGp4WmEwV0dMY2loZmMKhMWWlCsAbxKPtJwGe5hS1mPK7hWTC4S2
            xdE9mSL/Uta14XdDTqlrFmbOMSI8MaIdpSXQGptaRGt7Na5Shy72gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:33Z"
    mac: ENC[AES256_GCM,data:lEKZuXIEacd2jwyAZSCKRIRVfubglFvgAlShZ+2HFIqhMBLd8cr1KYjDOBFyRT06xQS79ZPMon8XBqAJbjX7xESo1cL5JDmdoyADPlXfKF59nDqHDeazjGVj5aCL4dc+WSmyRD27FzEINCRwrSKSyBEw2gPmuHsLMULsbL657II=,iv:RWUKBpsd5hUQqTl1/GjvTnW8cM94OeA1B3zg4OWYI6w=,tag:AOUXdX6kpAP8E71DSVZpew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
