apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: ntfy-secrets
    namespace: apps
stringData:
    privateKey: ENC[AES256_GCM,data:IPI/5dpvwEaCDOBmwaNIPgIQT8w7rZNbohnuqm9jFHJlmMYiZOZRPPePu6ZWpI/xRMC7oxsccoSr,iv:1Wwb/ZV0s5CAaJ3joCeLYOlknG1nqPRrTWrzv8U6XOM=,tag:Q/kzCyJzCVqSfKKCGWDuBQ==,type:str]
    publicKey: ENC[AES256_GCM,data:Qu+fy1dxIvXCrQe0ADUAmwJLU9nx4m1JUjTiU3a+60V/CJdQRqOdYrfw7Y9HoQxoI2jFFp2mnBc=,iv:j84C2X29GfckdffPEekmPnDqzOSAp11hfhLlNUW/qRQ=,tag:BFaOIPp+w3qXDSBqxujebQ==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUXNTUkIyMXRiU0RxU3FI
            anhUUGcvUVQwOUtYZFFGZCsxOEJqaDJ5S1ZrClJjY2NTVWJIQ1Jwa0llL3VFbTNM
            M0NMOFRHYk5LYy9DYjVNb2ZkK3d2WWsKLS0tIFMyTHNhd2RRUjlJMXgzd2luNmt1
            TVZxclU0YjJpWEpoT3VVcnh1dnlYQnMKyd6WlxxQKOgJOkNhGJMqF3Ukk9253O9N
            0sCJpxMaiL7PEN4BSCOTXfFZ6cNqWEfbjT8I4NcBad3u3TSnZ3mHKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V2VRT1BRS3RJNWx5RHRt
            QWRoc0RQRUpvbC9ra1dQRE9jdmdac1NkWGs0CmFMRk1yL2kvVkpXVk9IUGRISmpq
            eDlvVzNTVkNxTkJoQ0hncmQ4WnJiRUEKLS0tIFlncldQRW1GK25sREtwTEdLSkRV
            cVA0Q1ZLb2ZMdkFFWXpuSnJBS1lYUVEKoRtpWsJGscALP1OC92MdGRMih00GonrU
            NzdHmcG3bKRXUgPrHszKLPr1l9fweQKR6hC/+idETB+oh03ztXE/4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArY0FGRlh1ckNlQjJWNGE3
            NHpSY1FxdEQwRWZWR0ZZU3BYL1JsZU9JTUdnCnhUcmhHZGVLSmROenJsK1UxOU5S
            TWxpSmRONkhBRVMrdHVwRWtNQks1NFkKLS0tIENIOE1SVmpxZ0k0QllkNzBDOGtV
            YUNCTFZSbnkwUEZTbGJIbjhENDFKWmMKpvrwMdJh69RD0LicOGPsoz1hMOmFCMqr
            z5qE84LH+ADCN9w3mK+09gf1bxSVTxe99thaGMdfejNeu1lJOYcEcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:00Z"
    mac: ENC[AES256_GCM,data:+clbt/uKyJ74ASECOZd7eZarQtgXMFbvyNxs1cEW1gmzx07U0owAGII/TmwHReL5k+1KSZakcm3cq8R1iw4SacjIgBCqhqZJpMBzDJu4cWFarDMV28IGXp9jSgP1J2ZYM+JWbdg8dGLdKXriEC2PWoPETSD8oes2L8sXSIsaIE0=,iv:DfyKxkVsQTFaa4pqdEKcL1mDsyT+ZNIqLPZgzWJDbBU=,tag:Yphx3mokzY7BYzJpn1wTyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
