apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: omniroute-env
    namespace: apps
stringData:
    API_KEY_SECRET: ENC[AES256_GCM,data:PYGDSFrFRxHYx4tQBWYB0Xmws41U8umfnMEOF/JMJuGLKObfUiYBaIU8mEYiS8M2MQIPqszKEaJDvVFfx6Csnw==,iv:NVbnTkVueGN/PqdWlD1JjxLOXKV2GaC5GGusuAiHZhA=,tag:Y90p7Il2XNZEfKkji77PlA==,type:str]
    AUTH_COOKIE_SECURE: ENC[AES256_GCM,data:npav4w==,iv:Umq+PjKk2wZ4apmQQ7x0yEHjiWxkeYhNvMHGOcpOSXs=,tag:UqcdoS9Q7qZnYJeoUy8TWQ==,type:str]
    BASE_URL: ENC[AES256_GCM,data:oUyQWDHmCRCy7uaNExNOHVc4CpCSM9E16IOi52cCUA==,iv:OujAgy4PE2rKiqch4qpSdImr6KLw0gC1aEoAkTWKZnk=,tag:xcG2/zTz43pyasBLqajZdA==,type:str]
    ENABLE_REQUEST_LOGS: ENC[AES256_GCM,data:oQ/N6+8=,iv:QY5EL5v+J7ZdzHxp+LULiH6BjIOYQmxYnbJanms+oBs=,tag:taddm6vig8tOGEcWfRABWQ==,type:str]
    HOSTNAME: ENC[AES256_GCM,data:TlMJNNArmQ==,iv:Y/1vbUYcgwGmpmGQYiJOpxoop0uXRKarmYDXsCn0G0g=,tag:EKOt7R+LW6Sw+3MjQVq/+Q==,type:str]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:AohrK+LekO7AYwse3SLtN9C5eIk4yrMgOHCm1Kk7lPO8hpd04s2ZQdg5xj3W2/i9uUzD+QK7jXHzUGKcXhs7vYsu,iv:r9T4L6mdpHtTd1UeaXo4vYj1DK0FBlm7rZo/R7Zgc2M=,tag:nCzJ9P32kQShOEjflzXmYw==,type:str]
    INPUT_SANITIZER_ENABLED: ENC[AES256_GCM,data:psbhAyU=,iv:GwA1Ua+t+8tMHh0plk964UNQftNY5E8Le+S2RmroXhY=,tag:gDQSOLvyv1IcE9T/U198EQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:TTEfF+dNpbdBraoEAEZtyTw7ZeYra0O9dPQIcwhMgy4Ue8S7T8n5obOUz3OenR4vH/gHClNBucpJAG2g,iv:Bz2ZNTh/ex6jatexHfdw5ok5S7DHy9Lx4IbStE7Dsj0=,tag:iaaOthev3T5Ro/A2WAcv3Q==,type:str]
    MACHINE_ID_SALT: ENC[AES256_GCM,data:XCGIAgOfbU8vuLHAsqVrsUVqR+osVNyM0BUIsV6YvqDAMKClTO9qc49TrbuQ4h+BNOdEm4c1AdvHAhXz9D7qOHE=,iv:Xq25Q9DWxI3musAb30QeuIS8sI9XpeSNQ3KDnmQ11bQ=,tag:HW+QyRFMhIvmxDAwb1mWdA==,type:str]
    NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:IcuDarQtlkPoYECHlRBjt3y0tpogNPP4Hn9QeDwrnA==,iv:OWLn1qYf/ILN/9oLH2tF5fROIRz7I+C9TZOG6vXTd60=,tag:2x1qrYv3Wx8W7OIGJO3/Ww==,type:str]
    NEXT_TELEMETRY_DISABLED: ENC[AES256_GCM,data:pA==,iv:89ptz7G0+pe2eEGE4hKElOF3sHn9CYwV+0OrlOE3Azc=,tag:KVbwdSBJfjTjlZ/dPPtadg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:ncYBQY3hEHoRcQ==,iv:WYP2SLihkia/UraK1dnYR9bwJje/Jeib5CWvFU3E7vU=,tag:TLv6OZ7pJro0tyCnjGJfPQ==,type:str]
    NODE_OPTIONS: ENC[AES256_GCM,data:hMLyaabHrybuUK8G7p97Dk6qlQDSE2UkoQ==,iv:RczvU152/Gb8rw5aRule06nPKYTCCCuMJ4GDrTfd1Ag=,tag:JPSybqoU0IN3xpaN5ItsSg==,type:str]
    OBSERVABILITY_ENABLED: ENC[AES256_GCM,data:42Yg4Q==,iv:YHsxHJjxI07aCZHjcOXdXgeskkiGj4xQa0NFkhnMKdE=,tag:2i1cvMJf+c/I3SRt5ZtQDg==,type:str]
    OMNIROUTE_MEMORY_MB: ENC[AES256_GCM,data:jkabkw==,iv:yxPULt3RPnvGxr59xA9xXi5DCNCPAm8JX+NINgeXzqw=,tag:OvTUoU36QJJ+6zA5VcVJnQ==,type:str]
    OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:SkUNAS/IgJ3jKZKgXjo2Eij2Eg1rijLy4acUXjvaCiWTSSWFJy3FRFA2brTWNSxkfv9oXp4oIZPz7pyfjSf+INB3,iv:b45R2j794X3XZWPitgwbjB2ydgyVPmHrT0TRyqIpPcU=,tag:QFZotTEaGGST7DeyNHBOJg==,type:str]
    PORT: ENC[AES256_GCM,data:avuUZ1o=,iv:pXIX/VNPHe9lDhcTm9We/+trSWHJiyeTf6VXSgsvwbA=,tag:ngFfr7H0s0UCXgZIeTwb1Q==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:sivCTdXcgvkdBcNrIviWbehKlXYWtS5M8SsiP5amAO1f9APtV0yyZ7F7Vy05IpzgkwnEMkamI9UoudfjEWDRSZikBVNoRrM/5erozRVNlF5W4Q==,iv:ATqURihkdfROqFOxkyRmocCX9uPQKUKFkjFFI042tas=,tag:EwvoZRPZC6gQFhQb3s4ZwQ==,type:str]
    REQUIRE_API_KEY: ENC[AES256_GCM,data:Sr/LF8E=,iv:galFyO15W8aR6QkBdeB4/6IArArubFobW9ThEJwPxd4=,tag:BnaGJW5+gSzS/+Azq8r1Lg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQlBsMUc3VFlCTjJ6WCs5
            dlFxQmlucWdoOVQ2Q3RTWmYvMituaVNrWkFrClI5WHpkNTRCNnJOVTV3SWc4cWZY
            UXJJSmpLQnVnT20zR2hhTmFsMk1mbkEKLS0tIDRDMWw2WmYwekl6NzF3T1NPTlZN
            dDFiRmczTVFoM3Zid2huVFlDTWVaclEKMSP3KoxiHQsKCB8Dbj+pMcR0hepZOvKU
            O1nqP9wJxKBzGHDhAKbCfPMC37OTDz4ki0JAwWvOUUoLIdg59EcCxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaWRWb0ptK205UjJBREF0
            SnBoSDE3SWZMNFkzWEJidUdUai9DMDdzcEdZCnB4VTljY2lFQXQzZTBqbk1BdGdR
            UGhaVWFsL0ZyMXV4QW51YytJYVlWRXMKLS0tIENZa2Z2Z21tcHgyZHE1b05hVGc4
            L2h4bE9tdG9aRHNnWEQvbzNXQmhmY1kKjdmt8kGQR51eSrIaEkk8iRiqEiN6xBic
            ykscTCEi2/EvW258bV6FmLmECRejyVAge+DHI7FCauhMyBYOrkES2g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZ0NxN1I3RnR6MXdudkQ5
            OTFLVGRnSUVTMGltR25TWUdkVDltYVV3ZERzClBPVVNab3pxOTEzYkE0ZW9RbUFl
            RHhKaFUrZ0padUM1SWJnWDZDNzAwTncKLS0tIGtqbnAvdDJ4OVo1bnRORWhFUTlD
            ejZ2L2JPVVgyYUpTL1UrSDdCdUUyeDQKDtyvGG0CuDTOgKKo5VZXb7WCe0hSL1fQ
            OoBN+8Yjuzj4/DF25kyt9Ehla6/NHJGEnBOJTkqcT3S10sKNdcjA7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:00Z"
    mac: ENC[AES256_GCM,data:aBGAdc0Z0UWcb3PkUX0ZtHjMWqRv8n6MZq4VIYBogsgimY9INVQHCE7a6OxkolyZjEm859RoxmMSaqT/0ieHtOSZW49RnIRojmyFzs0hNoVfN2y2TVbx5Z7FEJOSqc67htUQi/tlZsk2kaRj6dl8FohUiXJStlzOFRyltfvl4xc=,iv:J/0jBvkvvoLVX2XxosyGBb9f9KPmDuphdcPUiW4FbaI=,tag:qXYW5PIPW9AF+kEWVszJhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
