apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: omniroute-env
    namespace: apps
stringData:
    API_KEY_SECRET: ENC[AES256_GCM,data:q9VySj3ptjLTOEjNICfHMjOEtypB2IFhBON7Te/g/4VIwg2AX3EMN4htTAJRWlErlKuCsUOakNwaaDEXnURrVw==,iv:rs0y9nOEmrNuZCYeqoi6n9Hl0k3YZn/JUf/ac8khfPI=,tag:uKq+ucDTHi9UFcpVQcD0aA==,type:str]
    AUTH_COOKIE_SECURE: ENC[AES256_GCM,data:ZRzzug==,iv:SfXdMmoO714P0yWUYhFqjzBDaHNP7H4KD/S6NymyS/M=,tag:d926zcsYELWDYYei5EUkBQ==,type:str]
    BASE_URL: ENC[AES256_GCM,data:Pd+CEogCAqXWytKo27dnlxdui59rbNwUoiexG/WR2Q==,iv:vLtpAfc8gdWjn+NKldNoC753/6HC9F700O5ke4HMLAc=,tag:bItgEYHN6YcLCbQ4UIrc+w==,type:str]
    ENABLE_REQUEST_LOGS: ENC[AES256_GCM,data:ZERlW5U=,iv:QAjkUwZPetfmiJ12iKvEOzCKapq0sKcgK1UFjnHxm9k=,tag:9tYbwDabDNa45bpUA9uD8A==,type:str]
    HOSTNAME: ENC[AES256_GCM,data:RLa4Gg/MjQ==,iv:lvK+2zG5+BuiLRgKj9jhtPN7N/F9XpNI9vqKktF06B0=,tag:9c4Gfe1g5vcG4mcjj3W0uQ==,type:str]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:CtWxiccLZU7LRcpN9gZM,iv:Tg6iTwSw87hgrOblRKp8p2mfYSv9A59YC0mWkUwAKuw=,tag:AOmChW0p1lcoybK/qXInaQ==,type:str]
    INPUT_SANITIZER_ENABLED: ENC[AES256_GCM,data:zM1vnjo=,iv:6XmAoa4uANRaEVE5VrliFmNJZGgVE53wsXtQ6HrjJ1k=,tag:Ci31ExsG9D+axECEK9zv2w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ElcKgg0H8q6N4LAASpvmLdOqMtu8BcW7Z8WSmTcVPsjVNJx3oalrSu91o0kxhVVQRnfjrRcw3i19+LWVVOoEhg==,iv:6Bcz4GEl4MyGwtdf3rBbXB/Tl8BAjKgecBJIUu43Cm4=,tag:FkamfCJ0pk7i7p1FitzeaA==,type:str]
    MACHINE_ID_SALT: ENC[AES256_GCM,data:a+i6PRCtrkeivXsUrtQ2qNcYGVz9gdCTLFxyvyuVebD03tOmDZrx+1swtC91FMhIrbpogEZnuknPnrGNdMjU4Q==,iv:r/cXvmnSeu9dCQh7J1lr1S2hM9Z5vlzAYC7YBx7LKBk=,tag:vWl2NCmqZOZwopcKu5Gr6g==,type:str]
    NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:O3WxjaU+fOzPi132NXXdSy1P42ZxD4nSL/CeRY/Ccw==,iv:gAboTGtTnv01S19KlHS7BhLapLXsVYyj8OMLbk/L6B4=,tag:DxGfm/s+Ydo5OXNVoBN6LA==,type:str]
    NEXT_TELEMETRY_DISABLED: ENC[AES256_GCM,data:Vw==,iv:gxZ/pMeVnpfpzIxCQemDZP3aDKVVix0bO+C/x5wbBm4=,tag:b9XaK58k8iHHfir4bwoLgg==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:lY1maRCwbZ2g9Q==,iv:qh2JZ4rxplSmM3uPlY187XxvLIDEOhCUovd1C55Jiac=,tag:oVLs/BzRJOBiAKAMWHtgBg==,type:str]
    NODE_OPTIONS: ENC[AES256_GCM,data:hDRfd2CY198MNbIHTiC6Eilv3Pm5WIgcuQ==,iv:WIB5W44LDV71EXvcGzaCMD90hMqAPT82dGPc1Jvdh4g=,tag:iK0wiYwyGvwdSiYfsfJjVQ==,type:str]
    OBSERVABILITY_ENABLED: ENC[AES256_GCM,data:Uee4qg==,iv:qN/cLmMJHKEKteC98JVP6+sktCMvGPSvYKN4K7N89Vg=,tag:9LdYma2GMCBjdF+U8iw1qg==,type:str]
    OMNIROUTE_MEMORY_MB: ENC[AES256_GCM,data:lMZkcQ==,iv:pjmuq1p9k446J1gE5sVhNeqKSrMedIQruPPjjFC3rk8=,tag:MZ1UDVr2Y7K2VtRokWI67Q==,type:str]
    OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:xaffPvhNkwKZS903aD92yG4QkyqnQqt2WODHluwq6dpZG4CGvygR4lHhtqxl9o0FI4VBwbbRcCF6hIwAxqXSoA==,iv:TQxY1AMxDnCgyT396OCrn5hcimittJrlSysnbYuPs4E=,tag:8OHj25LQrXmbOp0/WFSlPw==,type:str]
    PORT: ENC[AES256_GCM,data:3AJAMlQ=,iv:8HuT7nX5J1qs7JSR2V1h8uU19W/wqC8vbzmyPIsh60w=,tag:vc7yleKVYzwqm3ppeXZbwQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:h/YNOy5NNmA9jgZsYCw5VUFFwAyDZf/rRgSyJ6R51e08W612phjRqBCKsJlxIduBZqWp,iv:I10F7LasNTwVHjA9rZ09PM8hh0nGO0NmbkNH+VMvGcI=,tag:FVVJrZPx0WMp2axkuBwQVQ==,type:str]
    REQUIRE_API_KEY: ENC[AES256_GCM,data:QCWWzVQ=,iv:FK2hhEL4EADCBOBMd9TL6h8wx8X4sw0dn2F3MJQfvjg=,tag:2Z9xJxJoq5Pu0eHCGdCB2w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUTZzc3dYTWlZbkdkZlQr
            bE9iSU5lRGl1K3V6Z3hVbHBxUDRSZHZDdFc4ClhQU1JZZlFUVTdYMC9EU01wQUNa
            VE1zWEJGNlAxMEFQTFNUcHM4WjFBbFkKLS0tIHFYdEpZL3NPL3FIUjdIUlg0UkpE
            em1kanV3L2lBdVVRVjJDamV6VWFINWMKfOfAxqAxpJJwhjnKGJubdqknape0dTYB
            OvyRhthG8Ff6VTwWYXX+qahgK6Cb+eogzdYLFsXWRGJba9CAV9zR/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVklCN1hyd0xhbUNNY1Iy
            YkNDN2FjbjJkOUZncURyd1VHd3NMN2RrY2xjCnovTk9ScVhyVFByRXNoTXN5a3JY
            cnMrNDlvT245U3FSUTNadlBQY3lrTmsKLS0tIGl4VnRwNGFMc3pyOHFCaXo1T3Zw
            MU1GOUlqZ2puSVJnTEVXWm83d2Vhb0EK6fudtKeo/Ps0udY07D3uVsNN7AtyUfwT
            fw3UKTzEZQi8oqUy8xfbz6YTACP9XHnQe4mPKlRjsUxdJJ5B4ecxLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cElFWlV2RkdTaFhMNFlq
            UFZVMEJrZDdSSjlST3BabERqVFNLcXFvTXdjCkgvaU5iTGxnVUJkOElGakpDNjdV
            YityVmtSdEhpeEZDdU40V3pUTjlKS0EKLS0tIEFFNVFKaGhnbVVKMWNjOVNFN1NP
            cUl1RjlnK2g5MDdhUmI3VW1VWjJEaW8KqdKIpiNkdNbxUUEEhev1fDBlKmSn1fE/
            rYURX26YLQkkgBgJwwocBC/r8Gy+lb69hT9fAXP9wYYF2Vczi4rojQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:59Z"
    mac: ENC[AES256_GCM,data:Y7oHi9fQNlFZuwvXHE6cLU3miTGq5BjYruj8H8ixK1BuWDzQXO9rVg106YxrO6yst/lRuHJJG+Q32mrrHdYBh4WI+UoqQaE7LaXZCQujCKrTIVRea+qHhPf36vfN0Mt85csnUox3t9LhXsYbdJQ7zbcIUM/s1Zm5lbpJQswtuQU=,iv:uJ/xCmHp2TjUlN6Ick+KwdFPXdpIY3rpUqYJ0Kj1PyY=,tag:W8rTlyLM/9Jpu3jRZhCRSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
