apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: omniroute-env
    namespace: apps
stringData:
    API_KEY_SECRET: ENC[AES256_GCM,data:Dfl15gbFFsA9LAOcJewW6KgbO34391tu6388ZuN8jwMimQfvMCNOa299d8M/EKwQgBpn1SjjMVzJZQZl3F9ceQ==,iv:hjVoB3hFOqt1UIFh3wQ2Wv50UZu4Weu6RQ0gzbjCUOU=,tag:B+TUMRDS8BbaLKJvtgoITw==,type:str]
    AUTH_COOKIE_SECURE: ENC[AES256_GCM,data:dOXJ+w==,iv:UAmrDz/oyGlr1khlLSkNM6F6Gl/P2RPEMPSI9nOy59Y=,tag:+YkPBRxdxEF/1ip6dSZ+1Q==,type:str]
    BASE_URL: ENC[AES256_GCM,data:OATZSwc7mkAjoKowUgHu2Mlp33Kf3NkBuWqDtGSqAg==,iv:nSgH+GBdxH6U5b+wl5FGEJHRDnzJ7XE4gt2OL+B7OBc=,tag:mcNDWMn88RASdq9sBSFK7Q==,type:str]
    ENABLE_REQUEST_LOGS: ENC[AES256_GCM,data:BStyk+A=,iv:S2tISKbkq6wM3KAJ66HQAhB/0yzTFmTsDhIE5WhfX3g=,tag:zmGD6FZ07kHr++dVZzuYHg==,type:str]
    HOSTNAME: ENC[AES256_GCM,data:LGLRnbce/A==,iv:Z1ku5i5QqCfdh9ucuy2g4XxnQQlLsmSYdZ8g6u2yKzI=,tag:oBlrKGUeRz/WQnS8BVa/0Q==,type:str]
    INITIAL_PASSWORD: ENC[AES256_GCM,data:J74eyk8hdsA/QeM4eJ//,iv:g5FQmNI/iJr6aijikE2PZCNDitSOcGB6SlvH3Jg07+Q=,tag:4J+cNrvuZh0OJm9ClNeuvQ==,type:str]
    INPUT_SANITIZER_ENABLED: ENC[AES256_GCM,data:3C/DW58=,iv:KdCn+OLcPQw7sXc5AYE2QX9WSNazS3C7J/dwF8S6vvA=,tag:ohmGXvjhoJBVbSpzCdeLfw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:tzDYwkBGC0jtSYJC7TLb2nkKPW12Ja/R9Tr2qV4KlU8s2nIt5WZzaf4OMxWp8HLizCm/OBCO9LWX8cOP3RUcHw==,iv:ab9++B6GbwjJxl7tLkZ7+YnMIcQr4QpiNCtTpnw/voo=,tag:dkCXnfyiIL3qN5x4QpG+Bg==,type:str]
    MACHINE_ID_SALT: ENC[AES256_GCM,data:JMWH1ysxCIcKfpAKAdcThNI1mxKA78xJF2cmxG5iVgEaLlLxk0Pt5I5jvZEy0jOSsHP89uchefSR2gOeEXb14Q==,iv:PMO/lC54RoEjnMUuBZ3AylY1BD58/3CgcbAPGzNTAsI=,tag:klZmb3xUmD9rVS0tqfIm2A==,type:str]
    NEXT_PUBLIC_BASE_URL: ENC[AES256_GCM,data:StAfDGqleYhLayShJA0+Cepk1yGy0zq0868b2cz0gw==,iv:DZIhus0sFaBWeelULITWw8IsC68txfm8e+kbjqR40DM=,tag:5SwY+lQAvUmP2GVimOmtqg==,type:str]
    NEXT_TELEMETRY_DISABLED: ENC[AES256_GCM,data:pQ==,iv:k5OGHPXpi5EbnrRPGQ+oL4h0Gm4+oN4E08u0jtHZmHA=,tag:QohmfqMgmroqyN1V37G+9w==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:vjEPa1iFQDDgdg==,iv:wIB9A35MSaG0ByjLnwrrsUzq5HXMNzzav/mRf+QY6bw=,tag:BD2KwiPVui1+X8d27EvvbA==,type:str]
    NODE_OPTIONS: ENC[AES256_GCM,data:b9avJ2XomAH0Yn6j8+Bry/b76RzJ0S7a0g==,iv:1fm9/66R1Gb9vlFJ1PpmC1lsV9Rmu01kYYTdYi0PLMk=,tag:tMW+ARY1SZUaW3YhEoqbAA==,type:str]
    OBSERVABILITY_ENABLED: ENC[AES256_GCM,data:pWLd5g==,iv:HBiLyts+NeCNwe2E8WIqDDHgezoTF+5iOAFyYptKBLU=,tag:UXEmYNIJxnl6yLKijkeyvg==,type:str]
    OMNIROUTE_MEMORY_MB: ENC[AES256_GCM,data:9MadkA==,iv:7gYKoamMTUjN1H7W+oDOKOLZqD4qRz5HTRttloYR4Ok=,tag:N6vCHIiWWcBVq5RKxcWxpg==,type:str]
    OMNIROUTE_WS_BRIDGE_SECRET: ENC[AES256_GCM,data:O9xsjFRJdBufD4rq7ezqQYJH6nYMiwbXc2CHhK+qHalsE625to+aLubH6QD2lZ1Xs2Uy5Aimpsnux4nuXpU0QA==,iv:3w+UEj7RZ/yGlxLwWVrsGr0UPa8u+kcaX35LzvcKgwU=,tag:fxZUcIK5eKWzTfpZS6RLVw==,type:str]
    PORT: ENC[AES256_GCM,data:yJuIFr0=,iv:mwz8QOFPGIym2vk5bqVSkYPz+Ttr3x7SzUXByA7KKd0=,tag:Q+5qlLv+23q33s4+71D8jQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:kXTygIRDnTY0D46Ga2BeqZ3pA6AytzKy/g3N0uVi1OlZHE7lf8uyJWHMtHf2Jpn3yDcK,iv:I+4MQ3bZINEJxcFFemc5Z54UncF0cWyNVTeOOWqzh9Y=,tag:wlHWR/ohWyNXQLIR1ycWiQ==,type:str]
    REQUIRE_API_KEY: ENC[AES256_GCM,data:FkPLvLM=,iv:btKcs+xHRmSd583A/aVaiL8lp1/O+/k8rHmrLax6V/s=,tag:Q9JoS4fwT9jo/Q1DBhl+oA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaW1iVDl0NitFZWg5eGpo
            VFF6b2RtekFoOGhHQlI3eGFNUlBsZit6YndrCnQ0NmxmZzN3ZGxCSGJCS1hPbVd3
            Z0dVWmxuUTR6MEo3N0czMTBESGtYMXcKLS0tIGJBeTA5QVFIaEZEMHBiYytRQldT
            QjZiRk9XdVlxZXZTZ211c1NyMEdiRlkKQASjLMF9qoGNJrZ+32jNm3w4AYeVZXGi
            TNz5j1Br0tHYZpTNCejcgNRBdzfl5UVS9Va3D9CsRO9op9sPwBWyhw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3WG42NWZJc1R6UFNlbFZB
            UC95Sk1jWjA3Q2FKOXQwQlBDd1Vzdi9RaW5nCklrNGoyUSs4Y1hJMnRhQVBnQTJY
            TnR6NnkyVXkweXd6bUtteUZSWndvMlEKLS0tIE5ML01vN3J5aDgzRFJ3TWg3Njh1
            dSt5SWtYVjBpWTgrY242N2krQS81NUUKhNjyfDUEt4VyNjchaMjKOM9vBW4Hu1S7
            tgVb5mbSnXw4IkJdUPuQTJjRxN5nQdtuv7mI9551pdikx1tsy1TTdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVHBidFVaZTJEcEpaZ2F3
            TVB1bDdzblNwOXlEVmJJS1RlUk5md0dWSGdZCkJ2TjBRSUdvc0tpSjYyK0FpN21i
            N1lDZEhDeHlhaDFZc042M0IxSUxER2cKLS0tIC8veUE4bTFIVy8xTkRNWHBpOG5U
            M1N5SmMvblRUL3dmWlA1b1lucUl4TTAKvDAdKEbJLLjhpqzS9EBq/A1gq+ZHZyBq
            lxFv5erhQxwl9rObNHKK36nQcZ33KnAg5ZhcQ4pnbC9lorpHFxYeuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T16:23:20Z"
    mac: ENC[AES256_GCM,data:hnvqTfhhXqP3wyG2L1NDMGuENQ0OL6sn/ezfWAOenxyo4kLuDgIg73n6mZcjKZam7VBiTV2L1K63zH9d0gfnbvh4mvHoZUv94k50T4/IAIumKeUr0xPWH5/OOXRLObMQNUWQXvJnKEcBaZEwDEc0mF5x1E5+0O56HeA1Eed6S0o=,iv:xeNYrEsmdcIlmLgPwhq+1oCegX+bYi+/cj5DwON7EyU=,tag:rJm55tYyt9xjNNS+ki3PTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
