apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 774a54413b2fb8e7b064df0fba7fe6080d1564f1
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:VjrmCwnRdqcy7TuRRJo1SVp2,iv:ZhxX29LuJjVFPY3ZBiT6u4e57IF0E56R/67itXaPWt8=,tag:KOljvvej621hWnlFRgiZlw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:R67pt0ij1OJqOitRVjm7pZg7bR6qvuuZrIXj/QVRmaqqa/bJ36jHcJjuhQEEaNaM/v2RwXADP5pcB40gtSoROiue1uq/W4GT/PmCSMoAG4I9Ebz8ZFJPtGcxDXWMGGAXvmQ=,iv:IKkoiULDA9P4wr+x6qKpXpi+3ReelsuHN1ctx5zOX3E=,tag:nGFcZhRv10VEe6GFh3frmg==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:SP5EqA==,iv:+pnQk2FTn1s7l28W1hnMuZYfCateVMo6TtOlsp8dAmA=,tag:a6jkrbYiDuXgn8q3+2duxQ==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:BkC+6g==,iv:QPlFNGifHm5ExnXFpt5GOW9EmP8wght3SZ6SKYVcrJw=,tag:CUymp4gBezKPyzv+RXLaWg==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:YcWeAg==,iv:1O+jOT3O/D3HPg5g/ou2WdGyWd71cPlGqheKzaDYD4c=,tag:P4GBjoQgEzAWn4ZFtrShUg==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:sz7cNQ==,iv:5FVKxPjc+GxyRN72KqhsgsdkgZOfTa0nGFI8OG58qTQ=,tag:PGr8jbhnQmduuf2HZakOwg==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:5dCIvw==,iv:7phr8507vEvFRS8e6bhFyzGg02NwWTQktETyH4rLORg=,tag:dUCFQ0f2TJEmyPMqfPWy4A==,type:str]
    ENV: ENC[AES256_GCM,data:3wSuWQ==,iv:xwZq3ADGFggrx8DV3tI2UQyOl6m4fYDE1p/HBeciNyc=,tag:hI2RElRXI9qvF9Psy9vepA==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:OoO2sA==,iv:U0pnNW9UC0kHgQ/Oi5FqJmHilLqMKdtWlyI7nmH+Mh0=,tag:5FIOClm8hszCQCaB8QTPUA==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:5vJuRw==,iv:wkUtYH7L631hd9BRd36T7bOu96wS2JiJ1Ekg1mDISwc=,tag:pp2REOykSSM6akpzNnTXhg==,type:str]
    RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:6b0ZZrjCWXtBgLb8Cwz4FxwkajQsukCq4yEZ9HVSytHFIR9oA2g=,iv:KkkUj8CbGXSdJN2Rsmw1880TSgZmwY5WtUCAovTIOQM=,tag:OIG9/USKmRClVR97pfnNuQ==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:jl8Beo8B+rGzZey7b9xhhzq5YCnuXfGa1auFJw==,iv:Cg7YZYD2lS51oeJwUb7+03uqIuitG2agf2C6E9Vab5w=,tag:TpmjkQeULoq2yXaTUn/W8A==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:KzqVaJedOmRkxsb5+YyHr9jeZ2RU8Kq0mSqd3PIzwrPIn7VTnzt7zqcxg6TnbBYCtxFDapMXUihNUGQhOePHGqeL2wJEVyUOIQ==,iv:ha5nUz2g5ebpyAhWvGCmWAcPdvTgky3SYd6dMKDXyLs=,tag:WD3OLJeIuOkouCL65Qi+Ng==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:CEc=,iv:Jiq9witzBpmQ74ZsUgMWb9ozlgnRaeizHYXnrp8Yo4s=,tag:5id9QSYJhSZi4O+pQEc6AQ==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:rdWW0/HG4Q==,iv:VgQfEC2anMnXzIPaGJV3qO46I9cg9AHqido6RMoPepc=,tag:ZttzvRDcm2YprEibnrlq6w==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:0w==,iv:p1GqQpIBmKh/remweMnN/tmrmzQ6MOrh2ST0ANc6Ao0=,tag:GoAPN+UfdREtDjuXa1BzvA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:E3MIHBlsz9JUNI25UTOCM3WTmDxKXQE5AkC6BUsC6D7gEgP4z/Upcoa14yD17fyeGd7ugObdwQ==,iv:A8NqCwG9InVKbP16uNu9kMJXx9iMAjeHeE9Ol1XsfJY=,tag:VxQxqN6TjcTeA612UPx/5w==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:JxtwHkcHeujKRHW6eUo+RpppVM3caSWOV6k07YmtL+lHnkX+WwioJRU4TZbOubnHjeXrDGbq,iv:8lNhEsIqj1lrEDroc6fUF3P0LKcHayOkzTCGF75Uam0=,tag:raaoYBS9knBiMZg9geAXrg==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:EsfVf8sJKQ==,iv:DevlbbjOE1LvP/2Z9lLi/Sz3xWFaWoAGBBjAChc+ByY=,tag:REp+Uwn1oE9jqiq6N0jE8g==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:9fcczA==,iv:LqkD5S4w++84S7XtT0AuM9fQwdbfbqCo0vwpYERBY5U=,tag:lBriBkrZiUSDqjV+gvAZAA==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:WzbWDGyZJSY1ei2uM9U4FQ==,iv:9339Utr5SiNN+L63d5ZmLSJ0cbrrg3oZRVYd+Y2ArQ8=,tag:hLhr3t1hcW0KtjYFHKxlgQ==,type:str]
    WHISPER_MODEL: ENC[AES256_GCM,data:Aq/C2SwMp4p0SPe1/LDFpQTYtFCltTThmsKW,iv:3CBbeWEt1fkh0XViMe/t3ZJXvaJBTtrE8NIICeWO0Ik=,tag:6Py4IIatV7X7qYGBv9vIew==,type:str]
    WHISPER_MODEL_DIR: ENC[AES256_GCM,data:en1rwDx8XXWTdtV0GgcagfBma2+fR7XQsUlBAbNYoGpku4ZTQQg=,iv:8qUpU2XXPUKeXsnwnOCgvTyisP3IJkUeBQfQKOCRIBY=,tag:9Q2arng1SpTslu1dQ/vScw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSWlkUDQzRnVPbFJISTVm
            bkg0QVk5WXZ6OGw4bVFST2dhcmcxNDd4SFR3CmhEcG0yYzl3TWx2eXJvaStNQUdX
            NkR3d2tpdGw5dnRBUmt5SVd2ZVJsWkEKLS0tIEdDMVQrOEl1YlhISkJhcEFYdkov
            TFpxZElXa2ova04xVmhBc0FaMVFmdWcKftmOZivbSaFR+Q/tuYhXodqMKt1XlRxN
            LpyWAGUFXOwVq0eoDZA0af8gSOBuY1KruPHiy5KvlqAJKF7UPCC8/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUFBJc0tEaHNyKzIvMitt
            YTZHSzBSUng4aCtQcXhjUEwrRm0wY0hJT1hvCjlOSnVVTElJU3VCeXZLZkI2anNu
            Vmo3VzFxVXI0UXZpd3hYRHN1TTM4b3MKLS0tIE5aRlN0VFAwVS9CSXJrOTl3WGZt
            SkFTL2FKZDM3V1M5U1dOVlF2djc1MTAK7YIuPLYlFfZkHkmtIEVS1AteMunLykDA
            YxOctWfEDSCaQu5IlnVcoWbcAyuk4vG51QnVNqO8zhzC0zetL3sjSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTTJOWjdMTHlMWG02WWJQ
            bGd4NFBkM25qS0l4V1lsdXAzdC9zSzdGK2hrCktSYkppTGtlY2xKZmc0VEgrcUc4
            S1Z6amRpMis2WkZud0E2UW5MUnVla2sKLS0tIGFCU0R0alJTNmR6NzBZTlFubG9W
            S3NBcWdhbjA4Y3l5WWZzN0hya1grdHcKWiok+vZ5tkBgRcop28lhoTfnnKfOihcw
            9HGk3xvqAzz3LtlwNaReh6XD8hdrZv7pHdMvmA9iHDM21daQ/aorTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T19:20:09Z"
    mac: ENC[AES256_GCM,data:OJDo8E5gF+HpcDfp31XwWoaZGGv6te1xdyGJMvpOxNamAVJsjGvBaE3Uxs6Zri9i/+P2UnBletm0A2xNIyCOhJxX3UrvVxJbYvjriNSjrd9vw+ShNEl4rrlsRuk/TV26x49nYfO5Ozbpe6r2b1gxuTzGOA06f8tfJpQO230ob00=,iv:YneGk79lPv9478emTemiCvQMcafXMOrvQ64NlJK7PXk=,tag:nQieuWOCIOaHi5FnofvP/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
