apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openrouter-secrets
    namespace: apps
stringData:
    OPENROUTER_API_BASE_URL: ENC[AES256_GCM,data:hZ0lcnN0YQns6dHk/wkZbjtQB3r4MJLvU/QSGg==,iv:+Z1FIqAlAHB0gocf0D2RX5hXydxz8I9NWnmI5jpreK0=,tag:W0j5l+mjWtHv737oQDlxKw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:g7FRgkREuHG6Tj2CJjZtRqRD/Dc8U8vpdPr2xs5IHtMmPLY6bzdiO22mfoRkbl800lldLZMx6VinHelspyD1kf8oUJNi,iv:iGcUPC0mjJHADYd5fYYz5thF2oYeNYMBeIrDm9hBhNI=,tag:0aA3YFYzs6FwLjad+eM37Q==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:YPfk6+HeqfPnmm5ft+O7yw3a8iTKVz0CWe0SgwlpDOM=,iv:L2EuJJ3F4e3Nmdomc1j9yM1Sn0ugBGbCYf1g424CDDg=,tag:Cr1BTDo7Q3iNaGpkVBkffg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYlFOL0E0QjNhczhxRTEy
            U0VobHhoTkFqeUJ2NlRCdnpKcHJhY1VOMWlvCm9Oa0lwQWxTRHArTC9CRmEzbWht
            aG9SUDYvS01ISFdNNlpza04waDl5ZEkKLS0tIDduYlVrc3FTeDRoVDE3N2VaalZN
            KzF0WFVOSjM4Tm5TTVNCb3huenFJaTQK1GyuYwWxG+Biq+xgxQCqb8qEXfAnJZJY
            uW9TwAY+Fm327JgUX0D5SjIK2uunXmRts6Rz9TvkVZoeGQy/bQt2dQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cnI5SHhaTDM5YmZRczdp
            Y09uc0JON2hUemthbjl6VWdZaURORUZUTjBFCm9vbnR1L0R4bC9ZUzl4eGQxZXdW
            NitJcDlud2tORUVXODF1MDc5WDR2TTAKLS0tIGFrdTVPemNycUh5TVR4bEpsMzUx
            RU1VbzI1eG0zb2R4TkpNdm9mZjBlNGsKd439gYyE27WBdmAYGLNTg5aX0NwpThGJ
            horTSYw0uVn2gNZjv9KEkPy6ukINrXlRoV3sYw+fur+TLubxnJTmtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R1VtemVpeStQbDNkcjNx
            UTYwcjltY1F2TzhFcjdpMlgybHJ4MVhQcDFrCkNjMmNUTjJOM2tldXBjWnZKbUtJ
            RGpONlBva2F3ZVIreUg2aWFHRk5HbzgKLS0tIHVxTHhMSWY2TFQvWi85NDA3UkFk
            bUlJekFHSEIvYjM5R2wyeU1SVDk4QU0KzPEZB/lRVGGjOvQiHDfFLQB2q2UNG+DN
            LHraCeBBUE/zdJyL3W+mdeQ1C5XtZjz567E0bUJZx9wV1MtpULDdzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T01:15:55Z"
    mac: ENC[AES256_GCM,data:+/tXUkWZ50MgIhemErRlF7Y+DdtMUFr3iyBsv7BxAf3F1/Dhq8DaN34mrvyESHkbV9daEHJlqLg4bRa8jKt57EohpZxHHlURZ2BfQ2f+TwmSAxPWYWFSmHHEqycsiLZWwTxUI3rsTFgptLUdOeOvwuG+GnycEqfc2c2G9F88sT0=,iv:qdcIWavbCt88JbnMJMJF17eV0978l6JGPjQpdhVddK0=,tag:dNUONar5hZqblVQ/3JwDbw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
