apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openrouter-secrets
    namespace: apps
stringData:
    OPENROUTER_API_BASE_URL: ENC[AES256_GCM,data:yzAohgqyS+/myasKmt1661JOt+gMk6rpO3T0yA==,iv:z0UUQhXU04pcdWGf2Qn7w1cXetIGygX8D+uYSHDrkT8=,tag:XDuxof/Z5uWJi9sJFnDD4g==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:1BKJNJ7YTz5OXOQ4FynXtStzqvbQ15u4bWd7/VA5aHKJ+1OBTExlbKzyHyj7fohzJok8xjx63v1x31Sl3uEV+TBlMBvbydm7UQ==,iv:2lVNg/FSuxCTftVBMW+i+fRZCc8S5sJCfnlvO2Mmn/Y=,tag:VOHdc9AjtErh5jff9FUeAQ==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:pdh1z3fZUx2lRl7UOSraQVpTeifBhwppNJOGCptf9II=,iv:7afoq8qAWNVK0naJYtrNyHbN9h0DwDVyTVR9fDN8rjY=,tag:dgEWcumuyg+sVa4C0tLveQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOGVkUW1FRERUd0NncDNT
            ZzRtOFZwZHlPUUdXdWIrTGlldGRRRmI5NUVvCkVpaGJVZklreHFuQWxrenl1ajY3
            ZnBxL2o2bytWWFdjTE5Gc3ZROTlRRjQKLS0tIGE3WUpIZWllWTBOUlpKemZTbTk1
            Y3lCKzk3bExsSDMwZnByN0ZZbFlpSFUKLkU1e3aEMr4GZG03MPgcbrQ931RSgj84
            lD08QGh+b4RqMvX0d3QJHDIiKeuaGEcr/V4/XdYCjA07jxgiatwfuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRERCbll2dWdKeXFsVnda
            SldOZGFIa05PKzBsV1JzSjFkTEoxWHpSOFNvCkhSRTFUdXh4bnVWSGRQTG5YVWNN
            RGFscERKckk3Q2Z0RVFXeGtGSjdJTkUKLS0tIHZXT3o1WkdSc2ZGR29qaEVUd0VC
            OWhhMm9VVWJlQkNUQWJuaUp1Z3FtV1UKxVeF1mxOAXd4ZKxO5uzTrtVP7zayKTiD
            T2tHOCzRTqoNVODFvDCKt2Z88MdoVZLo9YlCxd8W5H1jQYrl8/Dnog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbXQzbE9VYUdNY0hMM0o0
            NkJQQmdoeEVKY09vcU1WRU8yVVBPMmNMNXp3CnJTck1QNDlqaGd0SE9pOUt1VHRZ
            MzlkNmhBT1ZHUUFqRVRjVDR2RkZ5alkKLS0tIHJXd3NPTXQvV3B5bUFhUVFHRnQr
            elVVNXlFN003eGo2M0FaYWZXczlxZ28KwG0bc0fRCRSA5KE2AG0ik7ivMiVvHMOM
            CMn+6x0pOKaK/GZQW4SHFZs3Dfcd5l6JimDDxe4g6GyNFF2+x4jxCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:59Z"
    mac: ENC[AES256_GCM,data:d0mhhgZ7lLh4tjSpc2v1nHj/XsnRIjlG59/wjqMznGFethzP9WxCtivGV3yJDWcVYrkE8IsYRQyYb1unzxngDEXQlTlhsfSKuo+gYBxfYP7053Wf7xQbNSRoPRHu+Nj7RZXFEHgvs7S/wciXHRQG0h9eR79bqnLLBJipEu+cIiA=,iv:10T843HxBKQtT00MpXeDWRCtNNsWkDAC3O6xEDCjKZE=,tag:pllLTozKnEVU9fWEVfS7YQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
