apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: openrouter-secrets
    namespace: apps
stringData:
    OPENROUTER_API_BASE_URL: ENC[AES256_GCM,data:AHwP7SAYNQgTiLh2tbR2GYIyoxul84aNg+wD8g==,iv:yVggGzal649IjMJM/Dq4Z6Cyvqq5luiGEAXN46Lfyag=,tag:Rgl2QFV1UeTbH0QLh8bZFA==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:0vhu2X2u1jLqkHQacFjt+FSNyljj2FpPhyCt5cso7CNp29yhZ3ngGBymH1R+Md5Scu0WJ1y5CU+9kNWJ+dPGVURy3J6k,iv:w3sahpDuHmij7w8MogkNnMcaGD8XPANEA85/1wX58oE=,tag:YYgxMwLNhsd+ZAbm0RWxDQ==,type:str]
    OPENROUTER_MODEL: ENC[AES256_GCM,data:zPOTcXaSOsCZBr2IfpZrACQkrUfXwtNZhDLsHwA+5Yc=,iv:HnuFTxdAJJ2K1XwmV2HMUuAd+ZBLyHQHvrwnkT4ePiA=,tag:+aa/BfBEQ691BEnkrPZw8A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QUpDWSt5c0lZWjZOZ1Ns
            d0E1QXpYcTJNdlcyZkJRNjBoWEdneU1sR3hzCjRsN2d4WVl1a1A3ZTdqdFlrRGFL
            dTdvNzA0SXd5aHd2VjVZbmhBWDZJTEUKLS0tIFIrajI5Y0FPcEZUdVBKeENhVjJp
            NTY3OEJiYmRmelhtZlIxMnUwSStKTU0K6Am1xoP6RL1MMBkuOMtKLyBhW7tnrjeA
            mIp2zmaiU1Qz+CVv44+87Ex6bovZUm/RKdaUUrFZ1UjxaHGnlpS2Jw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRHh1N1UrV2lXb2ZrOWJv
            VmM4RVVSL285RTgrcENiR24yeWlhUW0zdUNVCmxkc2NlcDdnMi8wWXgwNmZXL2tS
            b2VlQTVXK3Y5NDhhaWcxdnRzZTZIR3MKLS0tIFhRcW5Bb1dvL0V6V2NmRk1sTjVw
            ZW9ieFJYZGZ6dU4vUHpmdGwwYnF2WlEKnBq23KJX1l1w3CqF3iM7E9BguB7cAOOI
            zIoVW1/9ya2KqTosX86lwyOD+f1fMmmnlwq/xM8JMb85bIaJa37lJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQR2RaL1dRN2dMOW83dTVD
            OHJadjhMYVFTbW50WitmQ2NLNzZtM0pBUWxZCitvS2phc3JraDNKdklqTlNoWXpx
            cXJoYnQ4a2FxL0VzcE1ST1NVVGh4OEEKLS0tIFhneGw4ajVuM1MzUStsc1luWWZL
            bEFIR0hVdnhoYy9UMEFEdGNFUC9aazgKGc0MqY0Y5nZOMEFEVoaUby+kc12QGinp
            C2UAHrNRykoBbHBzsJ2DcCoJPOpSh1PkFJc40eu3+IVdJqh5/Vm6Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:01Z"
    mac: ENC[AES256_GCM,data:LIq8unqVRLZsW4Xpg27gH715LAif6lN9ONeX/VdP0Qlpn2WyhRGNAQVJVmEzg3yekHQCU54/F7fDZTWfEjnaL+P5P6LWfn//mk7L4JZXF536y2E7lZeo5XJt6mI/uqvkZVeiwU4Frt6VVKEF1lDX32qyqMwMzWKMppxuMA6gPVQ=,iv:mFmW8UxKbLUs+Yf7OeJFNJn80vx3alibAbitfhi1JsE=,tag:7cSG6TekZ/G/EEse7YqWKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
