apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: open-webui-secrets
    namespace: apps
stringData:
    ADMIN_EMAIL: ENC[AES256_GCM,data:A84GTBh/X0mFcRqw6Lbo5hnT,iv:vFdzxyFwt2nXHrgxblG/lIJ66MSUsCO6e9ZVQt1/7eM=,tag:s7X5VFaEdWvcQLazk/SJ7w==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:V2S41VleOnhuk1YHVIFJ6jrWEm68I492TPK+r9QlSf344n1GXYQov3Z/mKajXC50Y/Y2FzQwQOUPu+0d0+YNnAfvHePzRGcc+Q==,iv:/KQorAvFxMNOVs+lS/MGPpeG9JERAuptMGWkhjC0nqA=,tag:N799Z/lrJyrLsbGPQrSmww==,type:str]
    ENABLE_RAG: ENC[AES256_GCM,data:T7jG8g==,iv:mPP1HlqSW8tHDOvRvAGq3i5gBKxW2pSQ7xQT8sk9NCU=,tag:aF1fZOicFnVb0RWBZVuBdg==,type:str]
    ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:lMqN1w==,iv:D9ETnAXeUWKY+tKRyt2IB4IV70U9NwmbWc7G65E0Mro=,tag:dpTtkUKRFq5O/aVq6SUj2Q==,type:str]
    ENABLE_SIGNUP: ENC[AES256_GCM,data:bmfGCg==,iv:oDx7MVO9w90qnaqqWALVPu8LFeBk61/gbYj4grUXtfA=,tag:7oaaH/KT+o2pZXOjaq+v0g==,type:str]
    ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:rJRucw==,iv:6h28ML9Bo1oR6KmF10AqsroS1J6BZsbkNP2sWCnLUrs=,tag:Qxidju06aXTE3KSe+8BLPA==,type:str]
    ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:Mydlrg==,iv:FURbxOawF61rHKYkAZBW8/6NBpzadIeWSpxm+SMv+kM=,tag:6B7hX/Ll18ZNKeRzTT25RQ==,type:str]
    ENV: ENC[AES256_GCM,data:BT7irA==,iv:mkr17vvrV/5ViZW6tJPOD9lvYg7h/KCyYyOV+krXzh4=,tag:j+6HCTrVsRvgHC60xEdZQg==,type:str]
    OFFLINE_MODE: ENC[AES256_GCM,data:kpLJDA==,iv:hxHHTYL76MxjUebfAW4afreTgjVzCR7IPA/kGV8IOgE=,tag:5rDQGNmYwkL0F2mK+oPVTQ==,type:str]
    PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:tA4akw==,iv:XWi0MmGBFUqYY4Fe3a69qn8M77/plbZL8uajBn2zeAc=,tag:ZMwjlIbs0vu3IJTe5VrE7Q==,type:str]
    RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:slbr8+Ky+4p8l2XDh8+w/xNm3j2T+vMLAecSX077mCep5ClWJY0=,iv:e/WMHgP+C+33emBrrHdHBPA0ZMTby4SRlHKwd0S3peI=,tag:JczDrfL60bFkSlKtlAQvDw==,type:str]
    RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:5DZtdGHHUYGoaqC+rnliYUy8HQa6JdK8dCWgcg==,iv:4bu3ca6H96FyV145BR2CXATUwGuMxPz8ant84pgdigE=,tag:Kt1wLMlyVKimLkhRj0VqpQ==,type:str]
    RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:eyjDV08a32bAbVplVS7aiERfTTg+cRiFuMGNvgj/JOyMhw855cV4h86TdUmdlLQ1MFyFXJkgJjBH8yW+jUPG2iwlVUby/wM/EA==,iv:dA2n7HO/fGCi4XwsUQiZ9G/pqo9nLpeIzXX18j0g01s=,tag:/Qj7gONUWkj9qEpgpEXJ7g==,type:str]
    RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:kdA=,iv:SlNvpuO1kT4iX3pAqSlnuE1oXcanmf+10YntLWlJMYo=,tag:zCs2reB/IF5cB2mxng5RFA==,type:str]
    RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:8UrpEY4g1Q==,iv:HKHhUb/9gJ7X5gAdrlZ459Q9+7hQetlFyboiPd53taM=,tag:OnPrVo37xvZh8zWgJzAHHg==,type:str]
    RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:cQ==,iv:SCCiD7tHG8WBtVW8yMN46NyQemNb8oOenZ9g3CDy5pU=,tag:1YUPUjKgYS+G7qrCa2Hryw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:A77ocDN4qg3y0lNYSM4jrCDx3lRGqeL1Oa53UUxCDDALuigWbZUE75v/HUi8aG6VU/kx2S1JSw==,iv:+BhzqhOE4RJSL0fAjTF+N6oA+eNrUI040scM07IwuSM=,tag:fSm/azZ1L8jlWjEWHDOQmw==,type:str]
    SEARXNG_QUERY_URL: ENC[AES256_GCM,data:4r0gorPE4sPtVCmn8mf1UHOdUe3b1b4b7mfzogeu03UgKb4duZBgZ6xbRzELes97TIjDHlqU,iv:boaKmzLZSWUrBdsl6i7JlOJb8nGeXiJSegPg1F6VZ9g=,tag:ziD4Z9AdiJSOjm+8n1/lfw==,type:str]
    WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:UUeQj8CWtQ==,iv:HxWm4uSBbkp0yom7SM6iY14+MdfEJJqwrTZU8VAYkIE=,tag:mrotCkwTpLIWoE8fK4zxuA==,type:str]
    WEBSOCKET_MANAGER: ENC[AES256_GCM,data:HY3tbQ==,iv:HvVpgccn7PDOBi+5RaxpJMpHHOqdN/rFDSbX6CR7KEg=,tag:N3Q57pYxlqmsDqNzu30BJg==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:AjoD/sqoI74IGIGAQt5YVA==,iv:XlAEO9POJALNanhsE4BpG+JeUzW4IVuVm5UhkHlj0D4=,tag:tfRJcl33UtTSRIr/Op9VFw==,type:str]
    WHISPER_MODEL: ENC[AES256_GCM,data:pMYXLAmzqQFc8c1iEH9FPvNx+LwnOwiKcJ4u,iv:P+T7b+z+JWerHUxxGgXUIUXUp9SiJERKrmPdrq+kX0w=,tag:jeVFHuY9SofpK7e6994xnw==,type:str]
    WHISPER_MODEL_DIR: ENC[AES256_GCM,data:bC8do1cnPO8rEIYvZs8gUz/M19Fwh+UuHmm+N6oxvI3QHbMDZ1M=,iv:EKz1NL+bu/szkMNfBI6svKcGigh9glFaZC185a1wWsI=,tag:MMKKktInrhdFsxjHRawz1g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ3ZDYUltaGdsMG9MNmhl
            amJZTlZscXI2Q3lPVWlXYmJybVdrU3kwb2x3CjV0VlFqeHlUMWQyZ0o0UmtsNTJX
            NWtGeGt6YVVCRDBrSDl1SFVZeUpKbjAKLS0tIFdYdm5jaWMzY1ZZSjVTaUJHci8r
            TUs3Z3NKWW84RmlWbWFkd3QzS3J0ZGMK8LLGx9M4jpBRm1NBF2e5bjdbfUIEr1bQ
            P5Au8bxbUva+I9W8CJ6O2e9hVN35TtIIUvCm0fDdx0zIM39oOo38lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZE9FMVNXbHYweG9nY0JZ
            MCtkckpNMkw5NW5NUWdtYmF3UkovR3o5d1RjCjRFUDYxenpkU2QwYUVlRnZFQTZE
            RDlDRWlzSU1DRnRBU3pVNFNPNytPSGsKLS0tIGZKWmRtc1ljMTVTYTRmWFZUdldE
            ZVBCQVpCejFMdS9tdHdqTGxGVEhidmcKV3BMCPtAxkkWOsS6WKPIoWXds01sA3wa
            Q3Y25SGARqYUKpwQCo9+l1ClCLX867S1PbsltH+XUf9Lnwm70nyOTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTjBCaVZuZnlWaSs5bTJ5
            aTZ4bTJNaStEV0lYL2QrRkg0ZnphNGZ2djNnCmZQUERhUCs0SFhDY0lGRFNNQTg3
            bkQ0QUlDdnpQcSs1RWprSXVwU240c0kKLS0tIHJOVGpkdHROVDBNNCsrVjlKNWRa
            eHdiUzRBdkgzMXgvSWYwSzRyVGpwUEUKRdcPBypMrn3igtbavvvXZHif5n2rW6D2
            CSl8rMUPDsMJle05egZmhMBTOnSAWzYdhWyJqLP/CdEnwZCKZ59Rhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T14:32:20Z"
    mac: ENC[AES256_GCM,data:3flPYF1R1lnCklkKJd3/YwOrFF1oVkbD3+yQnN9aHYIS2HFWpnjta63njzbE6Og8SzwWdzMwCIT3GWmdX04o9tqChTXnlC53ozVa/vNjQFTV09/jxZR2FFs1KTmNXtHYSyJ/5LpQ6wF4L+Ji0jAEmeaWcVFUp+H6r703AJu25PY=,iv:VSIqQlzabLxl0VDbaUzhVH9Zn40kgXCBtaDI9lNB5rc=,tag:VYoIKO9cDSYAs8K8TxWSDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
