apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: open-webui-secrets
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNkowTDUxcGNvNStnZ3ha
        UGZzRlg3aTNmRFFncUIwZkVwUGpMaXBNOGhNCmJwUThScmkyN3JhUWtsZlNNQ0hJ
        V0xOUFlzVW42QnkwMGlQd21LcHpOMTAKLS0tICtxTXYxaUNMMVpTQk5DV2lRUUlh
        WmpybGRUSVZBVExQUU9QMmhBRnY2aVUK2NBOktk/hTJeXao+/AmOsGzd820P8618
        8ylB3D6G1AKpJhFhJEucI4kWq2EqA0o/Pf0wB+RDT+tkvINxEAaC1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxRy94aXlpcFpzTW9ScFRP
        UFIxaWVHQ3ZIZ05TdjR2d1FTb3dWRDNWdGlNCmIrNnBUMk05ajNWcG5hUWgyV0hR
        T3JPVTFnaFErS1kzWHFxdVkveHhkMkUKLS0tIFZUVkprSjc3bi9xN1pHMnFyRGc0
        U3ZQSWE0cW5rN01FMys4Qzd6UEJhcEkKtr2dkq6LuP+j5L2W+MV0cv0WSzfoUCdw
        QYhlHMnX/GaORqAPuOSKiH+pa5fDxVGlyDBqJDivQnnKKhTTWzIkPg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVnFLNTltNjdsdmVFYkJj
        ZWM3QnFRQU05Y2gydGZkYW1yQlVUL2NqWENnCjZKeEJSV0d0bmIrUFdKSFFqeVlQ
        cVBXSFNvdm8xcUIwSkNjS0pyOUwwZjAKLS0tIG5mekt3MXlSbHFiU0VBem5XL3hm
        cmtzczFRSGhNb2VFZGFvN3ZiamRhYTgK1e8uRFucWohMi1xfzhi401sYijUyO8dN
        oCNrBv06piXCJKrrT19tIzrdw8Fa4C/qwzwZH0twBmC+MkdajBWHZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:55Z"
  mac: ENC[AES256_GCM,data:MQdqtDAGkZQ9KFCiP8YBTNnjzq3cxPqtclENejyhCyjr2ISso+FE0oaVrpKl8NSUcPt79wB80jPqdtw7D8DtMAoIWjjP779ts1uaiRiNCPXq52P1i9Hn+KYuA5QoaaGUKZIf+arqD9caF6HBrsb0I7Y3QR0pN7kKwX+vGHus0t8=,iv:on3FHBwj1NVzRFFMxRjW4a8o2VGqwSbxza/nIu0sSw8=,tag:U9X/NQVgNF850WPvzWxG+A==,type:str]
  version: 3.10.2
stringData:
  ADMIN_EMAIL: ENC[AES256_GCM,data:71FVXwCiDg05XDqj6zRi/OYM,iv:xK4I4l5YRwGgpYDFOxJpPxGKiJjp/WsfBwpvjn7JeHE=,tag:iwiMy3wsXZIiemkDKsmMyQ==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:0RFPvn7jpfIkHiyJtDljZblv72Za+XpTn0DZzr2H/2OrPRzZL4H3bt0LS74o4PeHtya1VhVZXL0sXpS680BoOvOszW4EnfQkXJ6kJzQ8cj63uxKykqAhvfyGdif9uZKrFvcSkhjcOi9d2QhrnUbUFMBok/q1m/64,iv:zv8ZmFGOexpW5sx290X7vnyQm3uLJZTB8CcMliYOl+U=,tag:AvidOxPLlml0MWwWnCBKEw==,type:str]
  ENABLE_RAG: ENC[AES256_GCM,data:vqnrdA==,iv:DlwnHGM5GhE8U9ab3hSzBGZTmasD5sTnkceWbNYyRbE=,tag:cOj7MhZlSAajRaSntUNWDw==,type:str]
  ENABLE_RAG_WEB_SEARCH: ENC[AES256_GCM,data:S3BOgA==,iv:jy4C9ztqlpRbelDGVV8Zq4OELVjR9PYATw8FNZzopaw=,tag:l3wE5ccVa5knoTPka52RzQ==,type:str]
  ENABLE_SIGNUP: ENC[AES256_GCM,data:gYo+Tw==,iv:bfImHl0EYHdR1Dcfm9YYh5yv940N7vGj5zgke1giKeQ=,tag:4Gc/dWZwvBxnERT4Ly3lyg==,type:str]
  ENABLE_WEB_SEARCH: ENC[AES256_GCM,data:PF0OEw==,iv:uWecBfL1hYCf2ooFqL3fnAQHYUd3c3bHnEQdFYgxjzE=,tag:aYBmErKfdudXlzcuR7idRw==,type:str]
  ENABLE_WEBSOCKET_SUPPORT: ENC[AES256_GCM,data:zX5fwg==,iv:wTqpOb8mSdDLlYG0kIiCCMokNtPgV5Lrw5Bc8+qDaSY=,tag:Hlt90X7MIagTAboMHSW7uQ==,type:str]
  ENV: ENC[AES256_GCM,data:Ckhuug==,iv:A0tTek1eg4a7vagu73YDnQECIw+H78ZmtV7ojLhdYaA=,tag:0SohRdU+cw9u4wj5HOlf3g==,type:str]
  OFFLINE_MODE: ENC[AES256_GCM,data:h0gAWQ==,iv:vEuQf6exmZDKJuBE19Tgsp7YPm3YZ8zhqyXQRdRxzPs=,tag:/PRJ14g+pETsEkYs772ZuQ==,type:str]
  PDF_EXTRACT_IMAGES: ENC[AES256_GCM,data:L0Q4dw==,iv:fvrLXBtIBm//xs4xHA8h2PJ+CC1VCt5H7DKL/a27xP0=,tag:LhMSZq86mLjsgD/ebHqktw==,type:str]
  RAG_EMBEDDING_MODEL: ENC[AES256_GCM,data:G6AqyKMno98KYJogSonCGtpc4QPkAuXgGWh866dSfqLrpntS5EE=,iv:IHF7ezQesT8syEtq26xLzuu5720fJ1UdnPQF/8DZAB8=,tag:PwTZvcgBSsE6h+r3/n4OeQ==,type:str]
  RAG_OPENAI_API_BASE_URL: ENC[AES256_GCM,data:rp8eqGklUMvBWg4t1BCFmOLUCS6YTGSApv9snA==,iv:WPNFpDfvvkF6gUzjwuD2wiiJx75HY1g+VrjY2TIScI8=,tag:OK8qVCI4Jv8I6E/ABQOaJQ==,type:str]
  RAG_OPENAI_API_KEY: ENC[AES256_GCM,data:s7FZfN56HXRN+QeDa+9TtXa73vMhcY49ajcRTbKAbPF+reCEPH7qyIWkW80hw5utFsihvof1sAtq+TmsMSqEN7iHAtg=,iv:agaFO9lTubUNn/+6atC0EYgsuZCAB7y3lbZieklR3vQ=,tag:IegjcGFCawVyt58p2FYgEQ==,type:str]
  RAG_WEB_SEARCH_CONCURRENT_REQUESTS: ENC[AES256_GCM,data:r/w=,iv:694DukmZPftGJNg8Dzqig4DJtLzBObKiWBcwDHQUFqI=,tag:EGJNtz2sfnU1zwUyz/a8Zg==,type:str]
  RAG_WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:I/mzsPLVvw==,iv:WBu74tYiA6T1MIsRnSQnMiGjbdUN35faB4OTODuGdEg=,tag:AfwArlmao9nMiDY0fCulcg==,type:str]
  RAG_WEB_SEARCH_RESULT_COUNT: ENC[AES256_GCM,data:5Q==,iv:tMuYFheiRedlHjs2SweSpvHAPksd3Tpyys/neYHhnVQ=,tag:jMKSa4XU8qeTsgIPEwrUQw==,type:str]
  REDIS_URL: ENC[AES256_GCM,data:fuzfId0NSjRg45SQIJ7I1jZq4PxS7GDOk1/arhY3o6RvWQvlsY6auKf2t+4NnO3gREZVigMZQrK7p8CvDKU3Zsg3jrbc7DFz0FM7VMOp9ruSvOVh1ew=,iv:CrkpCfAqRTtglZ/VZr9zIXsxwgRGGzCm3GKoT4v8KD0=,tag:acJsR3xB9xY6wT1QKgSuGA==,type:str]
  SEARXNG_QUERY_URL: ENC[AES256_GCM,data:ndSkzXX/VFR5UIy5c7Jzs14DJAMnMnFRAfcp4QRw43nFD1dtxPzu3O3xmLxuakrU3YjXl202,iv:8d37JETx2P2a0KktroxkoWFd4Nq0O/YBMy7BTAQulrE=,tag:8ZG/TdEI7L9uWhKF1RihCQ==,type:str]
  WEB_SEARCH_ENGINE: ENC[AES256_GCM,data:Mw+OI4Yk0g==,iv:PIw197u4Uf7Af7+kHSVyYxAt4IIjJAVMyntv/rEM5aU=,tag:rbfvmEnnEWeaqnwvkj6GXA==,type:str]
  WEBSOCKET_MANAGER: ENC[AES256_GCM,data:JCFtaA==,iv:QgiW2QdCwysEPUiTIavIbMQmean/WBSh+8wVciM6/Mk=,tag:JOfEFSfLRpCxKK7ZQByemA==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:539gTumitwGshmCjifDdnaJFrFepvANLJpDxpA/kTPhHwOGeY2CARXWLCAsd1CDzbdaPVLgi7J4b4yeG,iv:0lwJ9OrneBo0xrIeabd4q+L77nQuFosPLK9f7Swaicw=,tag:U1ht60fCEYQIW8Uxh3zVEw==,type:str]
  WHISPER_MODEL: ENC[AES256_GCM,data:fDqrBUGwTaKHkStoLi1k8247o/zPwTZQG+Yf,iv:9VNShqlEmZGJtAdzNILYZBdk/NxFa6rmuUKrgklFJpc=,tag:2hKf44Fs2ZWlJqO5SJEILw==,type:str]
  WHISPER_MODEL_DIR: ENC[AES256_GCM,data:lKxSeloXAJxLJ5EkBD/Iv+N/spFYkn+9Cm2p1TfZS7jUmJcTA7s=,iv:6u79SFJvipykHlBnmVBUh58atVHQLzam1Ez/i2Yx5Ak=,tag:NETPxEDIhu4WJoD7I1AYmw==,type:str]
