apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: oratoria-config
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:M8WR/5wp2zitw8LRMCyvQB5JVTt+BYL+2Gyoe0D3Rz7eiXmvtRAj/b8RNt8tFUCDayFw,iv:fci5sTpPM1pwcSH36w4qJntw6GzcsV/UPS3vZx4ds3Q=,tag:KK1CCAs0vFfFSAxPJc+AEg==,type:str]
    ELEVENLABS_MODEL: ENC[AES256_GCM,data:AXOORyV5G+w+,iv:DnRX147BEAyShJb5r/L5Lp8Wb66Yb82v81rE/9Geouc=,tag:nzghz6i30cLji6a+1SywuA==,type:str]
    FISH_SPEECH_BASE_URL: ENC[AES256_GCM,data:ESrj3Sc4NXLJiSqB4IMvL3F/Tgfneag=,iv:Bl7Pv6N7piPYl8ha5rwZqVFiPoyTwUGhnme2k5jZCac=,tag:oBbM3gLjbbvvJyBq1yAiTg==,type:str]
    GEPARD_BASE_URL: ENC[AES256_GCM,data:IBp3i5o3J+QX/ja9GMAyQFq3kNJOiXE=,iv:JzCpFY0Fq6oPL8g2E04Io68P4svq/HGQLaqh++S8MN8=,tag:L+jx9WbsEZhr8VcBrP/0UA==,type:str]
    HIGGS_BASE_URL: ENC[AES256_GCM,data:K3lETO4PqHZrPcirVnY2j+MrG1PriTs=,iv:hO2RpE08mF+gEOmN5a0oNj7iguwxyGBOnj6XqX3vQFU=,tag:JmapWQP3sYKPQI4ycPTJTQ==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:Xnyn3xA=,iv:EsoWvbwsfhlpKApVttYnnDTzkTr+8GR8yc9kI2MYc/0=,tag:1MdW0SA3ZTjrJ5GM2rTWWg==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:xFHAtJhhp1yfmg+NShl+dnkldkz87+oMG9PLorQdB6+WeBA=,iv:L7eZM7wXH6tsskMw3tUw0UkGxHj2Pobcx9uyE4RFdCI=,tag:DTgP+eh1y0J70s3mEU5Ciw==,type:str]
    OMNIROUTE_BASE_URL: ENC[AES256_GCM,data:SWQcKsAevDQuJREgXvNP5zk1qsKbBSKu57LgEcg6+w==,iv:j+GxlZ3w1mVCsEdaYUlCJZ/3tOAsEKvuCYbE1WjRHao=,tag:93V9FOsqB4tpNU0tURqwiA==,type:str]
    OMNIVOICE_BASE_URL: ENC[AES256_GCM,data:7h7y6VHpezcqtB1Hukg/xk7R/yB/m7A=,iv:UcbyAdADMUjdCrKe5vrFbKrUSGP9zq45dhCLwd1A79Y=,tag:Jv+diWbfTJS2ATkhhDvHUA==,type:str]
    QWEN3_TTS_BASE_URL: ENC[AES256_GCM,data:mIhSxPGxuZpOAk5wuRcxrPukDbc+aEw=,iv:de3vaEj4Jh5jukKLAewuVVg9k5TyQojjXiWdx4iJJ5U=,tag:8BNDrCHWsx34z7on6huX9Q==,type:str]
    SUPERTONIC_BASE_URL: ENC[AES256_GCM,data:jZ902APKfXlHWv+h5Ql4vU5YbV67fwc=,iv:kj8abjiZOUP1dRKBLJN+Og5AxgFK6m2a8tFsyCSUiMQ=,tag:14wn2JHLXHmLaVljIfcmUA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbTJOQ25mRmNaY0JvZldC
            MGs5OHlsb20rbE9GZUtJV20xcTJFWU54RVZJCnFBL3lGR3VBVWtuV29RQ0N5d0ha
            TjNFRlVKMkNuNHZqV1F0V21aUzlNT28KLS0tIG9lL01pbjRYS2FJQW05UGx3MHMy
            OXlTUkxPRm9Yd0JIYVU3VU5PdVplckEKzFWsbNwFnCQp0wzV3P6twuPi4387nW9C
            lPmng+c/cZHg00aLoJUGz6iHsRvxdGTLmb5imlnl3PVyVec4nZMHhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZVUxUkhoNDFrcmZxZnIv
            eFRpWVFvaWNKVnFTaGJhR2FxSURCWXRsVlNBCkFtTkNRajhzSllIVkg5U3A5OUZn
            enkxU3ZBK2tiQTl1NlVocUN5ZXd1Z3cKLS0tIC9Uckk1c1ZCY3ZtZ1A4SXNlYjla
            SnhFZFlLbWErbUduc01QbnJ5TnhDYW8KSJhineoM6aXbZ1cjf2ovx9xAtPKcbNuR
            5fHCCO7R01C/LO4TKba7/ATSYV6JP9nTmeCbK/Ph1Rky85tv5USPwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBamg0aGxlemliV0RpTis2
            ZlBpRjdFZGZHTEgvMEdkV1BueWlCbUVVQVhJCmlUM0FSaVY5dlBWOXBDQ1lRVW9y
            OXJ0azVxKy8yUExsdGh4U1dHaWpaUVEKLS0tIHRqZVhLREtvd0p0MWpFL3BXM0FH
            ZnlRMHN3MXNJbGlmT2g4Sll4NzcyVGcKpFrPKNv8KhIg1fBkhuQvJwuGHECdmUCN
            WAAr5a6YqhNryi8BjC2a67ZFmjjskkLJEAb/ABykBaQIbBPME0JMqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:24:59Z"
    mac: ENC[AES256_GCM,data:sQcFd6YL7IP/iPd/3GPq6olKc12OXzetftGDd4V1SIj2jejdIwDLVNhJJ93OL3WMDcgIG7aYh9szS5nXU9ol9M8lXaiq8sybkI+D5AcdvrK1MqXdl3dTG2qeMsRhgzkrf4rbQEVszd5JEIWoVnHo/gZxZUVC7UE/HI4s/S4vk/4=,iv:mxoMC1xNoJweRdR0OX4UzvauRxaisS3/0Djhm8WqTPs=,tag:TWq9MUUBbeo4pQ/MGtITIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
