apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: oratoria-config
    namespace: apps
stringData:
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:trnIWCb1tAZ5nI2LwSCUNMsF0WTtLnV81Eq/YDvBxHBzSBsOJEsb/hIU1WbnMSDUid1s,iv:2YEHU0mAruxlpujyw8RLraTcQfcMWi7wOfzFQZu6icQ=,tag:ey/aleqP8tSggPy7FP77HA==,type:str]
    ELEVENLABS_MODEL: ENC[AES256_GCM,data:x2uHI9GkWHK2,iv:y/SMPWQ3PzYvoZFvhyfYNIWsu9h+ItLGA4XqHtMefvQ=,tag:5WaZLgHWihtK5SDW1KhAeA==,type:str]
    FISH_SPEECH_BASE_URL: ENC[AES256_GCM,data:Nb6Owy0+bWY265Ur7phpin6MIA/yxaM=,iv:+756wIUiPPlwZEHz7Z6Lhs1QS5tBNzQfhxoip4d3TVw=,tag:n97cQ0g25NQ/3gUmMpSGTg==,type:str]
    GEPARD_BASE_URL: ENC[AES256_GCM,data:ILNGVgOXSidWR0s+ypSkpnK2IqgVAUM=,iv:7ryP5Hzd1Hwl+SvgqBHNx2MgkXEFXaFQacaI/rQfuAc=,tag:lnfeM76fzwcApSxPCVg9+g==,type:str]
    OMNIROUTE_API_KEY: ENC[AES256_GCM,data:kenUzcYhBnAHea0f80yZTui2kqpz8TJiR80Kn3eCYzt/Evw=,iv:5xFcuV8lOsq+041Zy4CH9R7U1toPOLVCeqs8eUvWjM0=,tag:W+l98vzd3ODtdCC3yub/gg==,type:str]
    OMNIROUTE_BASE_URL: ENC[AES256_GCM,data:bqM3MYkE77MX9yceEwQ3E1qGT68I2g+0JGOkJYp+rg==,iv:RHOK0PSxU8Sk8B0syogjc7cQozhokJiSAbGQeCB3YTc=,tag:ZR/BSbc6wswjLPgNCq9olA==,type:str]
    OMNIVOICE_BASE_URL: ENC[AES256_GCM,data:IB9/zYJyGF7Ez2MA79nPaQjpgnc0p0Y=,iv:A4p3G85EYsOuv6dYaenvntOBoZGB/jFuINRkGd2VpKg=,tag:smb3U6nKFxmN+FOVY7u5Cw==,type:str]
    QWEN3_TTS_BASE_URL: ENC[AES256_GCM,data:KjmK4u2DE7cFR33BzGiEau0TxlU4/Ys=,iv:+Bd14IlOTsP6WPAQH++Oq7q0gFcWc6Z+PH/gx+D2Oto=,tag:7bZ19dlkN3w3+Iuq31qexA==,type:str]
    SUPERTONIC_BASE_URL: ENC[AES256_GCM,data:O5GUHiwjLAgrKxL6gJQSFNy5fqohxLo=,iv:hcoJsNEuIvdT1HseMJFuwUl4MQNu8uvL+8HnmyjTwyk=,tag:WiHFVeHdSvlZOBNYB3CNcA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR0VIdlJkSk9yZVB4bXBi
            UWxpNVM1bFpPWkFjbTF5TnZORE8vQS91NkRBClViZHhEbmdtVnJWVGxUem5XRk1P
            ZXdlTkIyUFc1NzV1N0FPRFp1aVJySGcKLS0tIEcxa0gxTFgvYU85eG9TWWk4ZVRu
            WnVyeG1hSEVRQVJ6Tzkwck55ZUZJYW8K2pijo6Gxroj6Y93ydzfo19rhn2wqvehN
            y4CayiWTugur7WNIEYxG+cx06afhBXBbQbqWPMvEOjkUGteSftKGmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZnZhVFdHSVVic0lJQW5L
            T2tIRFlCTk82MWUvdVBIUzBSSTQzeFppV2dvCjdIOG5wYWEvTkYvOFlGZU5Fbzg4
            dW9JY3hlNFJjanVWL1J6YVJ0V2hOaEEKLS0tIHpjMGVsVUZSQW1tK3llRUdZa3h0
            WVZvQ29Ja3hScHYxZExpb0pnajhVMDgKd/vaY8tp3mClsoWAObNpbEKgGLnmP/U+
            pEJryGME6oQaMU3DG/+jlxNhyDFQB5Dudw7pXQV26bkqsjyi1k21kw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV09qY2JLeHB1QmpodW80
            dmZyZTJlc3FoK2Y5SGVHMjczeGJJaVNseUU4CnhUU1JhR1V6UFVPQzd5WjhSN3pi
            VUY2cmdMZ0svemlqNWdFd0lCNmt5N3MKLS0tIEJSNFJlYjBTczVCY3BqMVpRK1RT
            a1k2d0cvWnEyR2F3UGd3ekVhdzhOL1kKH7zTGVytay5vAH4y+IVlc8sLgdhkKmH5
            r/iJ3sIbXdSK8zV+citBeN2uf2+0n0Ad5FMhL4h3bcv/xyI1F2K/Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T16:03:06Z"
    mac: ENC[AES256_GCM,data:CDeZBFenoC5XoupL4iwkAyP4aYYO03v+5B5msdcEMTTCtYbqT8j9QkFxwXNSI6rnx7np5eGDKhfTUh0TMvGPgcCQeDSa5TluH6+2inkTy76M698ui7R+A+VJsPeSV/LfAWkUshaCAsjNBuAl6a8e9NpthfPDTAm4JqKpuNxpAcg=,iv:hpwUawLo8yk2rugX0i5AeZehs1SU1isoac0i3EOb3GE=,tag:nck6cwEWviHAvNfEaQZolQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
