apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 1e52ad2d1e211db20f7dac38f0a07c31d18203ab
    name: poise-config
    namespace: apps
stringData:
    JOBS_PASSWORD: ENC[AES256_GCM,data:AZSQ3n01aCqY1+goVmPtZOJP/zq3CYz3gIB20LDQ,iv:xexvwQ6BT3IROd06MzdDiaidc2MqQ1MMew7zWq/KAZE=,tag:ykkC/ZUCkWKJ0yMSU9xN+Q==,type:str]
    JOBS_USER: ENC[AES256_GCM,data:l65J/xU3cLKU,iv:YePHxt3HpvyknDcp251H6riYgXqck3vCgcY17slW7WU=,tag:C9tY+YmwMCWBwL/AZmaDxw==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:kZI90QNiGe/Km+GbByQT4i2OsG6qwm/7Cddbt3N6qWbxJDY0i0kuSve3D4eEMlVib8HU31W2yw79,iv:M+SAbHlpIoPiz8d3g80AgDcM/9XM0mZw9q+e6xgDNmY=,tag:oj8czBzuJhN4eLc5HercTw==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:u4xl6qLyo7V8RxRFuhvTdAIrpg0MiVTlAaTcQjCtCrFDzVcXBC4Qrw==,iv:nigw0alxgTa9AoFs/uL6ed4pfnEc4Nv5ISQNmowwB34=,tag:KMrBAFMyuyPQtpK2eX5h4w==,type:str]
    POISE_DATABASE_HOST: ENC[AES256_GCM,data:fIqZ7VnT4iujuammULvoOX5rkedjyV7tcptWbASo+yWlJhbZ36kS6dk=,iv:+BF50ODUfNH7lRLbnqTd7HBYQTjpVLeuq2yjmLgrk1c=,tag:J1ZD4Y1yoZvCuve5Yyss+w==,type:str]
    POISE_DATABASE_NAME: ENC[AES256_GCM,data:eSzmg+Lk0taApJr0QplNbA==,iv:QB8amEHSGsqgyiGQsVZhe6VnoJHAR3lCjQHj/vXn9Ns=,tag:oSctfTLdkwvW7hf11lqWtg==,type:str]
    POISE_DATABASE_PASSWORD: ENC[AES256_GCM,data:I0SevofXkx8wglzqNhF3t6PnjQ==,iv:juZr9UbUe+E4MYsTqA7kUzH1yQRq4+EuC3VD8Jtr0Kc=,tag:DQ3Eta2pnfXsSdAFYEit2Q==,type:str]
    POISE_DATABASE_PORT: ENC[AES256_GCM,data:DnK1jQ==,iv:me9SkStB3r6FD+8Zq88upT13/kDbsINGTKzJDJMknxU=,tag:bTlLBJSy4x2c90JmftqGwA==,type:str]
    POISE_DATABASE_USER: ENC[AES256_GCM,data:AY3hVawUNyU=,iv:uU+8Qt5ckaq4hNGosnXRtr0e6bJxpH5C0YbRTcmdSoE=,tag:fZD+4sJqdWt6200aCw/BIw==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:Leh4QVI=,iv:8uYcdjD8toARHaWHbu+/pwnG9Fn0zSz28ar4FwwrhI8=,tag:/fy/QMUMc0wnEN6Wjx6c1g==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:iQ/30WLjjjGqxKs8nRuUOPIn4YPV1BPn4Ia6eaZqJG4nOM/TbZx8X4ZvMoG4aXZ/pV6oWlZAgsdeX8UleSUrSI0=,iv:js2zUEjmKblbqgyy+6ghlP9Xd5dF3ea/rupxH5QN8HI=,tag:bgwyFNCi2MevzfkfjXBHCw==,type:str]
    S3_REGION: ENC[AES256_GCM,data:OyFhqhE6So7t,iv:UwWNFnu4DCVH0CDM66LYG3ntnXiRiiiTamXLWhxn4MI=,tag:6V/FDqeYFt6ryD8vI7yX2g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaktSOXllNzU5NTlMVGlx
            djR4N0VQU0ZrVit1NEFvWFE4WHpjeGlwMmxzCmJKYkxYTUI3Z1VTMmtHWGdKem1X
            NnZwd1p1bEtiN0VNZWNuVFd3RVl2M3MKLS0tIE91d0pVbXZkdGo1VmxhcWh3MXlo
            Q29NczhRbjhRRDYrZlh3K1ZUUCsxWmMKA/my/EP0CndPBGbFrpUlM2OAH/QZFQDj
            SnA7HnzuL3xSPBZbZob14c5+iSQq22caVXAv8DnzIek7tKS0UvJfJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YnJPYzZWcG5zQ2U2Njhy
            NEZnaExZbE81ZEg2MW05Yk53anhKZDl0bEVrCmx0dmJnallIVFpRakthbmRMdFVu
            ZmJDcHBjR3o2cGszMExKSktHUU9EVUkKLS0tIDNmS2d5U290ajViM1Z5Qkl0V253
            ZDdhZStJb3FpQUt4SytBU2Npd0tTL0UKHzmHQ2wHKWNbsjIKOoiPgqYlLu4Rkfp3
            j1Lgh+ITLkWBVLDDuju6po4DEv9xB0U8Nd1DRIFmBVwT1vxxqXZpHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDREUrUGxqL25FZmkvN3I1
            K3FKWTBSaEFGZDdSVENJU0hFZCtMT0QzK3o4CkVKRGgyQ3VHclV6SHZ3anRFR2lH
            VC9qR0luQTlFZUs4MC91ZmY1Mzh6bWMKLS0tIFlsdFE3ODgzMlZkdkpUY1pvbW1Q
            OXlIWEM0Z1F3UnJqOXN4VUhXd0cxSjAKS0sJZ8xvHhjUS6YnLwUGMG3lkIt4Q2Nt
            Ay3fMhOXIORg9GcxWBbae04dK657Svbj7D/spttpTBRQj7mshX7HAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T19:20:09Z"
    mac: ENC[AES256_GCM,data:lWdpUHp8MaY0PKrlG5Fx+TtO3Z0Jvk6HJgvcScprGB+imh0f8wD4IXs2z6vrZZ/aWB7QoAwJwDYYkHWsBC9nREAff3P4Pdp5lwiIcQXlZj/Tr4JmBxVh7Hzx//NUhIqZErEdPKu+OcvU8Xv95FdBfjmFo85LSJkecuVM2yY6s04=,iv:rN1UhuDmmOcvw5bKCBSd161IScHmus1b6VYVU7my7cc=,tag:XqXnJI/khaJwXCW5WYyqrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
