apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 3145a91a28cb3b5333423c26f8833b714876594a
    name: readeck-env
    namespace: apps
stringData:
    READECK_DATABASE_SOURCE: ENC[AES256_GCM,data:XhARu6LDfrp1A2iPUuNufQcGAwtI1wXShUVyK/yq7kKlo48MbHLrrSYRHgnBSdFbnMbq5d2yOrmY5y5bkk5LzQLwfrOSwpfdE4GfPgjLLyZGsMuDR/xrTWDa0X/z1BFY27DOdzGDunX+Fr5R8ek=,iv:xWpQ4jO/wDOzaHd9miiflQYuUnsfXEAHJaHoZYvue+c=,tag:GUAwpUNBfH3yGDX3eNvnbg==,type:str]
    READECK_SECRET_KEY: ENC[AES256_GCM,data:1t7QLJ5w2+V4L8RXUb2s+HweuOogSb5fPMZcMz8NHK+rEFZiAUY3UblH25N/ZOk=,iv:ks2P6NJdabCMAeUItYz/hTjxrcn5YAWKgQl/TCCmMyY=,tag:6ORNJLDOTuVW0dcvKHZoXw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdFc0Z0NNUmFjYk04NkdQ
            bHROYVV5cEEyYU5QSkxHTjRSNHVmc2VpUmlvCnFTdmNsVTNiT0xZTk1Kd3NpdDUw
            eVEyR2ZWbGZlU2FLMHBjdDF1MFRxVVUKLS0tIDg0NGRzcE1NYkYzUmZ1aEpOQkFr
            b2NlQ0NvbWFDWlY2TE9RYXpRbldRVTgKSPu6aWvlK91eVxtyHkbaEBc7cHhEMNke
            1yoOSThyftN+o4Pr8KEuOWUYN0tRi9Jh1Rt8MXnSBj4DSvKnIi56dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRjk5UUJZMm0yM2RxaXpU
            b25mTHR2dGY4NXRuTFNzcmF2MmRVcUxuYnlnCmdpRnFLVzJmZmdIZjlSQURQOUY5
            bUNCdnZVQkxwSTlHOUVoSWRVTVN3N28KLS0tIGZ6VkNGNFlzbHQzcGp2UGJmTE9T
            NHpkcnpCRlBESU0vOThWMGZlSWJPSm8KdHXXQZCPsbQ7P82v+6nll6tsqjPgBKP+
            HmxRt3aAraCl6UmteCzEyOvKDpPcPW8s/KxRzekj7wN+v05WWj8YMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOXF5SDlDM2FUS003TmVs
            Uy9VWUlmSjF2eXljMGFwWHQwMS9VZGxvM0F3ClFVTHdOVWJ4M0N0cWtqRnZhZWF0
            djE0a3U5eDdhUWIzbWlYTzIvM1Fkc0UKLS0tIEd5ZzlFa1dQNjA0R1VsWlZ4NDFQ
            cXozMXVEYlRXZm15TG9Xc0tFNmF0MDgK6Vfw3PiySk1VsQ7NX8b0tfsG0P9CO4Sk
            Mk0SISQZs+4VMKXnskOOIFb/F4ELh5h1HFr6oHVZPoAfUW/5rSCT5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T19:33:23Z"
    mac: ENC[AES256_GCM,data:m4zj1ZLJNQaMtTFnQZZOVoIfldwn9pFqXarMedz2bV/q1uL0X1dG9VDs7MLibQI5hf5aBjrK7kBcVB8EQVRoiB1iPnpKmNEHiWy2g8Ex4GqNvG/El9hyfiA+tE6Vl4zdJSnxba0Rc5hOAs1GrusdQk+z2Dm80yhU0nc+mGfZPg0=,iv:vz+brOqBCx8Wb9UXu38ycF4QRU38Cumlch9Gc8itPZE=,tag:CYk1Yn3Z+rQjcaH3vNt6ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
