apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: redis-auth
    namespace: apps
stringData:
    redis-password: ENC[AES256_GCM,data:DBuAvJOshHlToUYG2WEM+Nmq6bC117USWhDHfO+S0i121ry6YNxsSdEjlnWs0jrcKYXP2Co1,iv:eS4UtbXqC47buHtL8tObaFzwKghA56emD7BCQ4iD7ts=,tag:hiV11CyOu6/UxgoBLI3ODA==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z0sxb0xKekFvNk12dFBD
            YVhDTzVVekpKMFA3UG9DVTZFUCtYbW5YbmswCmtNWW92N3hWOTc2OE12d1Zta1li
            elEzRDJQQXptTnltcnUyV0wvQ1p2Z0EKLS0tICsrVGNjUWRJcGoxbVBtVzRGelZP
            dDk3U0ZrTG0wM2JwNHA0R3N6eXkvMjQKJa4abkL3qDWBaYZ2fefVSQDcRIEcVe2e
            eZHgXDQCQHMuiB0l1p+wCXILROfp3hgeJZk0016Y/XsettA3hhqOwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZnQwN2ZjUkt2NlJnaXZs
            OUZYOVE5NG1wTDZxdFFxUGhSazFqZzVoaUFvClJNdXJmTk45LzNycndJZWk2aUZl
            c053Q0pDRFV5OUEyQndPSnMyRStFdlEKLS0tIGVua0RBYXVjSDdoMm96NXViNEtn
            ZTlJQW4xRnNoZjRoNktMS3AyVTByTk0KTs3JlnztSEy8iPSYW3TdVKTf4T9mwt0l
            +Y7P7yzAN4rtI1cUUbX6e+1t/46Clfb5M8IG9CLntnvvhmB/kl2BIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTllaUmJOSzlobUhQTCta
            b3ZQYUQzNGs3Rm9wcm9mZ012Ti9RMmljaWxnCm56YnNUQmMzU3d2dktyejFpR0dD
            QzRiQkN6TWtkT01wUWROTUkyQm1nbE0KLS0tIGFIUjdzeUFqdENDYWY3ZXdEMFlV
            bmRkKy95U29ibUt0ZmFUL3hlSUpyVWMK2fRLuPxmDwFqVplBT0vRRSaDrlk8oFOZ
            M3CvhgzH03uIsmNBpTKH5LIlEV8z2YXcxJ9riicVNGyAResOPv2fWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T01:15:55Z"
    mac: ENC[AES256_GCM,data:/0YwGyRz2V1lQajilHnWPWk4p7PR9hjVumikSqUxBrcOOq/Xg2dvyDSm1+QoHg0FiNxmD5AihEPZD8Fv/eYDPnRbXJfm00PWOefMcy1G8pSaghis/Ljv8g/NRy61ZE113uW+CA948889YaewsFQwDA5jbZag+fOm+0bOWRjo7GU=,iv:qGfTEy/J3lxzHBOIhScRVmIq5iXiZ+Ak7ODxhZk9v48=,tag:xpIjM2eF2m0MJTY83vL2kA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
