apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: redis-auth
    namespace: apps
stringData:
    redis-password: ENC[AES256_GCM,data:UDJzMnvQqt8MFozjuFAO2dTCdouLk8FS,iv:nHyMR3ts9nKTjhO+bYIU7inOtzbr6uCklrTFVn2zQFM=,tag:IGCnRy7XjHM6FKT4RXHpGw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWUFTMWN2TXdSRmlTOEta
            S1JvUGRFQUpnYjg4Zm50aHUxRXhQTjltOWlBCkNXSXBMd3Y4T1FZWk5xZVFXeG5p
            T3BhK0dPT1R5WlJwb1IzMGUwS3RJU0UKLS0tIDF0c2RtTWdud1VGbWt3YUV4ejRw
            dytvQm5vSEU2RWlJcGNkbjMwYjdZV2MK1tnhtWn2cQ9AJIvu8t1tNqWSmn9mx6Vf
            2WM7Ht2CjvhiAoay8xE1aEeMyrnXZBXwcuA7UIOON6FqIdeSXhrgmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscTczaHhCbGlhWENsYlVl
            ZC8rR0g5RTFURDQyU3ZQZngzajRGVTVzb1FjCkxiME4rckdwcUZMRVp5NnBOZDJZ
            N0V0U2JudDcwNkNvc1BzT2dKRXd3N1EKLS0tIHRjb3FXOW11ZDZpOWNOQ25HWGxC
            TFVtM1N2MmtVS2RnSm1WbXUxL2lERjgKqhXL617zuK8UV7KN+p1Edo83jjGPkZ05
            RG4sNqnXasT97Y7InAKzrwud8rarOr9OxScBUxRww7VLSUvjQIPY4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dWM1alhibHlPaTlQQXFo
            cUZOUlQ4QzgvYjM4bGN6SzNLaGFSazUzNkNVClZURkhmbE1CMXplTmpBOUVPaWdH
            YVhLRlpzWXNLaVRnekkvN0xsOCtQOG8KLS0tIEY1bmJDajFtVDAycDBhbW10NERu
            SFBGdlE0UTZNVlBMZzd5MkoxVXVrZVkKxBz0DXYWtQy/NjGSRMQyrcaKcEGXg4zl
            C6/ZYFLum0cdWGbabbBjdQ8Z8H0cVNJX8qEntbaVl4GKENk+Y263rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:00Z"
    mac: ENC[AES256_GCM,data:+qJJAViWKt5Ny16sLzd7qJkqJJAcVl8g1JA3cG9L6j9iCgKHyK09sFsSLmvLBeUUil98bimqVe287wMpNHIMODYNn3k8ZcdQLpqAaii3P9VRNxZtm4axHOPrZDEN8zEeFDwY8O58gU14Et/8VNOyibmubg1yTN5cIlec7CqpGXc=,iv:q6yV81sLuKZEsVNSoJ/hpaJE4Bo5N1Zwm/dSEwQsI10=,tag:W2jqSltgxhDJkDOeL8OZAw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
