apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: redis-auth
    namespace: apps
stringData:
    redis-password: ENC[AES256_GCM,data:dwGUQJnYx1RoPsMAz17z5O62stzE0LVK,iv:tQ4ZxIQYcPYVR0zUBtGYqBkCg246kHRI9AzzDJljXJE=,tag:3s6i7yNaJBQykm6qKZCwZg==,type:str]
type: Opaque
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia1U4eWZXeUZiRkk4NmxL
            NzFsK2tjOEVrWE9BR2VCZlR4cUtxcGFINlNJCkkwOHFNWURramsxRTNpQ1g4dGZS
            VWJmMVQ4aXliVjdBcy9IVE9sd2VxTEUKLS0tIE5iNVBZMmRzMUgraW1Dc2tVSitw
            TE1tYzF2K05hZzd2UTdTVDN1WVFlckUKSZGdGHj3IqDIwAHxtbipev5DpquXphht
            R54TKczhUnhG5KF1jDGY3nvOP7fPmaJlpPnrVenbTv0HKMpHblHncg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzN2RtelkzblRKc2JrSUZ1
            R1I3czBOSHZIMGsxc0ZZNkNNS2htL3A4R1hBCkIrc3RseVViWkRYRGJ0UFlBcmdQ
            M1pOc1lhaVFOTWNEK2NWRUFUZHNyK00KLS0tIGtCb1JlYjhkbTNpdVA0T2xXNkFa
            V3JSZy9MT1orTmJOUXFUeXYvRFpIczgKKI5IQLiXx81g712bcgdxPJio1/ZGMx8T
            Fb07xFng6Cpj+wP8TgsxfshU0M+C7WWmC/ytuKwswzO8hBfxInSEUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRmZSbGhhQ21ZVmVtMEJz
            Y1VDRWZhN3RSR29MWjdLL1Q5VUkxc2xJNGtzCk8rNUMxaFcveWJwb0s3UmFwWFZL
            UVptN3JTNTduY0JBd2dMZmtVemVVdVEKLS0tIGhvelZUaXJhcTFsU1hNZmJOZ085
            bTF6YUt2Y0YzTjlxamlyYUZvUFR6U3MK5SftuMMnoN3Ao3KtxhnxOCiLMSY8lPu+
            v/xrqGIGJT19jqGxXehq3eAKuCiDENG+u9EY5afTJlLtY0cCPt/SgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:56Z"
    mac: ENC[AES256_GCM,data:YQrIZl7232xVxSTfjLymqY7Cp2eGkUuovgAShKZJJtKWKJneD7VnuxsQaFw18jxRWz64KScMZL9OC6aJBsnn0VxmorLQ7UCtH8XxcT4DXeiTuYxLP4eH2ltnrMfCqLeWQzWOR4agLUzFwsnken+RUNkmgMd02I8DjWLlRTINxA0=,iv:bl8Teh++YHqwn3gxCEj/nklvtbWxm871IKp87sNdFtg=,tag:f5Ig6NETsEtvaGrdeXJm4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
