apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: s3-user
    namespace: apps
spec:
    clusterNamespace: rook-ceph
    keys:
        - accessKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: s3-credentials
          secretKeyRef:
            key: AWS_SECRET_ACCESS_KEY
            name: s3-credentials
    store: ceph-objectstore
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ME9UNWcrVm9tRFNJanZw
            SGFxdkppRXVSazZDTEJ4UHFKOWVnNjF6SVJvCm16NUxQZkhJQUZFQS91ZTBSSkpJ
            M3pkbDJkaGJTQ3FSWkczYmRGRThaWU0KLS0tIC9VTnlwaTVOdzF2a3hrMldwNnJ0
            d2JKMktQVW1QQTJzRngxTXpiVUNiVUUK5G3IgPnZOt09cU6xzKyhffugzscmLsnh
            tJkdNJjn+zBjOk6ZX49Shw4rxPxpQWz5nmh7SV/pZwrNhjrq0NQBSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScUdpK3ZQVG5XRXgvQ3N6
            bEhoWWtYNWRIN0U3UnM5Z0VNVmJXMUhaa204CkZWMmI2UElXRHZ5RWMxNjBHZHlH
            UXU3eHc0Y3orZzlzMDdXWEVUWmMwOEUKLS0tIHVKZUg0WXdBZm1meGR4RTFydnlY
            MGtuTVVnKy9vU2c3QW9TcDk5cFh4eUUKxZ9/MMeE9is1OZwXdglEU12I8cZP6hw7
            dWkLImpJzL0Dj9UJKhWFin3Z6SbKOqXzQnN3gFerOdEAO7idWv6oiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZU40NGhoZjJSQld1MEFj
            amZES2llSTBXWkVtZmlkcjFmdTlzWVZtdFFrCkg2RGFLdmkrbE44N0JnM2IwWXJS
            ck1lU3N6Tk1ENVhHS1dZSGoxVVN1U1kKLS0tIHNzcHV1UThDSGVBNlVwL0xQejI4
            Y1doU0FJdjhHZEFGM2JZMWZ0cDFPTjQKt68YbJq3suNx5/6SFtPbipUSwyiLGf59
            sTGnBO80nsjQB1PzKU6W9mqIZ8BxEr6Q1kfGiFmn0CZg4DP8S6ZJoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:25:00Z"
    mac: ENC[AES256_GCM,data:H9NnkpaOKuMbeksXj/nN0h8Vxt2lE6QVVMkNcmi5hMdtlNydVgPhpmXKf4wHyKNaSYIPGtetlHNpSkd761DpeyEjuSFImr1m/7BrqjEmXxFMccXMisRqCESkricToYgzLvRHNPAh6jS6uAmzFmOuIG0o+Gghm26YacOn3Vwf08Q=,iv:Ehh0nQgJf2wOakJFG4adAVMe4DEBTOKOVO577AAXFKI=,tag:fndH3r6KdcsFaLKHSxTsTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: s3-credentials
    namespace: apps
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:sK7BLuKAWLLKuQuVn70I9EzBgdJn0f6R,iv:p+ixRjtXyqdPcwm1NekDtrMofHWLm2870rNlbfkYYdE=,tag:8y80jdTUm6ts9630NvbcbQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:hWXWP64DBT2zCxgqwa8NhtAQ8T7fiCMlTk5NDBt2DCtGfLrcDM1pY86aOOg=,iv:ltZL73AXgsyJkCL/D7Ev31KjG+q/MwLueSotSIY+fuo=,tag:vHzymTtNVamfQTiE2PSx/g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ME9UNWcrVm9tRFNJanZw
            SGFxdkppRXVSazZDTEJ4UHFKOWVnNjF6SVJvCm16NUxQZkhJQUZFQS91ZTBSSkpJ
            M3pkbDJkaGJTQ3FSWkczYmRGRThaWU0KLS0tIC9VTnlwaTVOdzF2a3hrMldwNnJ0
            d2JKMktQVW1QQTJzRngxTXpiVUNiVUUK5G3IgPnZOt09cU6xzKyhffugzscmLsnh
            tJkdNJjn+zBjOk6ZX49Shw4rxPxpQWz5nmh7SV/pZwrNhjrq0NQBSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScUdpK3ZQVG5XRXgvQ3N6
            bEhoWWtYNWRIN0U3UnM5Z0VNVmJXMUhaa204CkZWMmI2UElXRHZ5RWMxNjBHZHlH
            UXU3eHc0Y3orZzlzMDdXWEVUWmMwOEUKLS0tIHVKZUg0WXdBZm1meGR4RTFydnlY
            MGtuTVVnKy9vU2c3QW9TcDk5cFh4eUUKxZ9/MMeE9is1OZwXdglEU12I8cZP6hw7
            dWkLImpJzL0Dj9UJKhWFin3Z6SbKOqXzQnN3gFerOdEAO7idWv6oiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZU40NGhoZjJSQld1MEFj
            amZES2llSTBXWkVtZmlkcjFmdTlzWVZtdFFrCkg2RGFLdmkrbE44N0JnM2IwWXJS
            ck1lU3N6Tk1ENVhHS1dZSGoxVVN1U1kKLS0tIHNzcHV1UThDSGVBNlVwL0xQejI4
            Y1doU0FJdjhHZEFGM2JZMWZ0cDFPTjQKt68YbJq3suNx5/6SFtPbipUSwyiLGf59
            sTGnBO80nsjQB1PzKU6W9mqIZ8BxEr6Q1kfGiFmn0CZg4DP8S6ZJoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T16:25:00Z"
    mac: ENC[AES256_GCM,data:H9NnkpaOKuMbeksXj/nN0h8Vxt2lE6QVVMkNcmi5hMdtlNydVgPhpmXKf4wHyKNaSYIPGtetlHNpSkd761DpeyEjuSFImr1m/7BrqjEmXxFMccXMisRqCESkricToYgzLvRHNPAh6jS6uAmzFmOuIG0o+Gghm26YacOn3Vwf08Q=,iv:Ehh0nQgJf2wOakJFG4adAVMe4DEBTOKOVO577AAXFKI=,tag:fndH3r6KdcsFaLKHSxTsTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
