apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: s3-user
    namespace: apps
spec:
    clusterNamespace: rook-ceph
    keys:
        - accessKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: s3-credentials
          secretKeyRef:
            key: AWS_SECRET_ACCESS_KEY
            name: s3-credentials
    store: ceph-objectstore
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OVV6Unp3Yjl2eXI5NTg4
            bGFGUkZIRGpjYlM4dGxydTU1TVN0RjNVOGxnCnBMdDRuc2x4dUtWU1J1RG5xd1pl
            NUJqa01peVVCbnpVR3VvdkloK0g3MWMKLS0tIERDL0gwWXNJSWRUZ3ZJQW5nekRK
            WTZCQkM0ckdZTnFsSjgwS3hBZTNYWVUKppJpADogKNk42+Be6TOKENA46K0XUBm/
            gJh05dq5HpDOOr9mxtixlFyXJEZrwL8Ged3opBCQq6pEuD+yBgRUGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aElPUFMzZkV0NVEvT3BD
            c0lXbGNSajRZVmRDOG54bE0vdmZwSkNmWlY4ClNNWG1JbmxRcy9CUFFPSVpRelpo
            eExyckcxY0Z0eUZlVVlkcWRMditHRW8KLS0tIGVka0NzektlU0dtdldLZ1pKYzBB
            eUNMd1ptclIxRXhJNU1WeGZmM094TncKtcwdE4ax+XSjgzY1kaH7yH5gI06zKkYt
            29PYBQYvvAu5FJi+5wPjHQmc2qFmlo6/+JvT2g46Nx56pyAcJFbv2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QUtoRHdEU3hMYXJtR0Vm
            ZHJNV1JOZmE5aTFlT1RqNWNLeEJFL1JCS1MwCllqb1hwd2RqNlpZSEZHYkdiMFBH
            K21RdjJnayt0czJTK240T2ZWZ3lmOGMKLS0tIEE2RXhkZWxxM3luRjlaKzZEM0lM
            MFpQZFI5RnNJN3Rvc1prVU1uRDBzRnMKhnKRIYmnVRDLyJIcFyT+1c2i1Zsd08EB
            lOO5yWL5CkHqfei0sQJldH4ZBJnRVniRb1aZ+44Tf4wrWjo2IkA05w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:33Z"
    mac: ENC[AES256_GCM,data:MgjjbFBKbJCTy3eFbdbgAol3TxMr3S3KvztLYJSnTfFAuGlqe2XBN33S9PK/ia0k5IaQ5hkVgBYLCKIFB5ttzoswJLIr5AHDbEPjAbgHv7zN/7beHaa3GSvBph1rH732yZl5Tej13w7WcwBUY1ZiNLGdI0eu0PXUeZdiiQi8wgk=,iv:oaQ8kigN8mPbvxd3Xwmm7kj81okedoDYbTyB1vQFf0Y=,tag:5df1Fi8RlbZiNhc3cwtzSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: s3-credentials
    namespace: apps
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:blGp1UoyFH7IyMKpSfuunKtRiEwpJcUu,iv:IwJKfgc9S9vXyQJBE/xOrrkYlksdWetNZkLT1rKg+0M=,tag:ybP96SxQRrm79TxvmeLRtg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ew6rLgVnqgN1o9buvNhAc6lSH1b3q/eR4Wp8RICzvBoFna1NoeuULxN9O4o=,iv:ImVZ6BzXicTFdyrWNvOFQdMxx6E9bzwb3QltIexXSVc=,tag:4XwTOuT5DwX0PaiLjjtdsw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OVV6Unp3Yjl2eXI5NTg4
            bGFGUkZIRGpjYlM4dGxydTU1TVN0RjNVOGxnCnBMdDRuc2x4dUtWU1J1RG5xd1pl
            NUJqa01peVVCbnpVR3VvdkloK0g3MWMKLS0tIERDL0gwWXNJSWRUZ3ZJQW5nekRK
            WTZCQkM0ckdZTnFsSjgwS3hBZTNYWVUKppJpADogKNk42+Be6TOKENA46K0XUBm/
            gJh05dq5HpDOOr9mxtixlFyXJEZrwL8Ged3opBCQq6pEuD+yBgRUGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aElPUFMzZkV0NVEvT3BD
            c0lXbGNSajRZVmRDOG54bE0vdmZwSkNmWlY4ClNNWG1JbmxRcy9CUFFPSVpRelpo
            eExyckcxY0Z0eUZlVVlkcWRMditHRW8KLS0tIGVka0NzektlU0dtdldLZ1pKYzBB
            eUNMd1ptclIxRXhJNU1WeGZmM094TncKtcwdE4ax+XSjgzY1kaH7yH5gI06zKkYt
            29PYBQYvvAu5FJi+5wPjHQmc2qFmlo6/+JvT2g46Nx56pyAcJFbv2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QUtoRHdEU3hMYXJtR0Vm
            ZHJNV1JOZmE5aTFlT1RqNWNLeEJFL1JCS1MwCllqb1hwd2RqNlpZSEZHYkdiMFBH
            K21RdjJnayt0czJTK240T2ZWZ3lmOGMKLS0tIEE2RXhkZWxxM3luRjlaKzZEM0lM
            MFpQZFI5RnNJN3Rvc1prVU1uRDBzRnMKhnKRIYmnVRDLyJIcFyT+1c2i1Zsd08EB
            lOO5yWL5CkHqfei0sQJldH4ZBJnRVniRb1aZ+44Tf4wrWjo2IkA05w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:33Z"
    mac: ENC[AES256_GCM,data:MgjjbFBKbJCTy3eFbdbgAol3TxMr3S3KvztLYJSnTfFAuGlqe2XBN33S9PK/ia0k5IaQ5hkVgBYLCKIFB5ttzoswJLIr5AHDbEPjAbgHv7zN/7beHaa3GSvBph1rH732yZl5Tej13w7WcwBUY1ZiNLGdI0eu0PXUeZdiiQi8wgk=,iv:oaQ8kigN8mPbvxd3Xwmm7kj81okedoDYbTyB1vQFf0Y=,tag:5df1Fi8RlbZiNhc3cwtzSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
