apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: s3-user
    namespace: apps
spec:
    clusterNamespace: rook-ceph
    keys:
        - accessKeyRef:
            key: AWS_ACCESS_KEY_ID
            name: s3-credentials
          secretKeyRef:
            key: AWS_SECRET_ACCESS_KEY
            name: s3-credentials
    store: ceph-objectstore
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbFVERVhPNkhJUlE5QXZS
            NkpjdWJGcDdIaEFCS3RsZWpxRnNDRUhuTGxjCmlBbFlQa2R2Mmwyay9Lc2xzcDlL
            V1hzb0wwOWZTNzlzaDQ1VHZpSmNnNDAKLS0tIFhYMUpoNkV3cHlDSW5vZnhQSEJV
            ckxpd2pQMndWL3IyQTFtMnRtRWFVWFEKozaHOD9VjjeFMrAEWuijtXD8g9/UuYSo
            mJ2W0n6OjJe9T6+x1Ozx5NX9XBL8u8wsYQHS7NNxlUbreQ1UchYowg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UUFOMGtXVlJMSFArR0sv
            TUJXMUVac2VndHdRQWw0TVIxNndKN3RseVVRCnFBbWF2bXNKVjdFcHlIY29nSFNw
            M1RQMDZsalFxTE9rKzdtZDRyTU9XbFEKLS0tIFZjVFIwSUhOTlNMY3NHZ0lOVWVR
            TENUd2l5NDkybnE2WjV5RmlhWmg4SU0KBcKjT1JHUwphfTJrWS0G7KMfh/bigTDP
            6+a90zDILRp3vgFNlEw1JAKk/HnT3iAvffHO+Jg6ubRpN2OEt7UTIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa2JENitZWEIrbUMwWWdL
            dFFKb1lETDZhSW9rUUxoVEZjR1FNRlh1bWk0Cm5qVWRmbUpIYW1RTW9GdHJWZG9v
            SzJJNjFxM1ZoK0pybEtuS3JzTTZhYjAKLS0tIHUvVGRMM0lIWno1SVNCOTU0dEdv
            bmhUdzRha0dSS2hPYTh5bFI2RWQ5QWcKen4sOmK7mQMpgsRY17/EmACSYuvQhZeU
            GS+64lFqWBHNrSUnjtPahLcg7kMdo3Mrc3QgYTvazigmDD+jMHFxFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:00Z"
    mac: ENC[AES256_GCM,data:7zDJB4QT9bpsNzfSWRKtB/wL1CwoiIN0VW0ik9Zu70oMDEHb4G1XJFFJt/DXN1rQVhAnPHwX9T030dQkYLf+i1AD26iK7I5Bo52uL/VkmJOgvy6ARXND5ZFyQ4lU8Q2sY8N2pmCO+W1ivQSz3Gq55hmGy9DGMTC8Y2Ds4Hqa1q4=,iv:bL4X9Q6+ivjTbfmQHIsSSRoWEmdlD3g9BSralsnKoBs=,tag:wIU6gVOhmZrE7BQbvBbRGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: s3-credentials
    namespace: apps
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cNEICBQBTnaOHrb914rRTmF70WqxCb8N,iv:SFULncWQ5ZDPnMAS7y8F1HkjsBoycyrFKeLhbVpERcE=,tag:838g/cv7bjPbHfwYBrw3Kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6EriLBih9eOYUVUsihZu5W3IFr2ztcr/Ko3F/zVVnL7InH4b8gZFkObg9hE=,iv:nRPPZcbKPoinh+aK5UavOaZlSyxC/cHf4XYbngR6RHU=,tag:duYId0mCol/eVkfBtwoGTg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbFVERVhPNkhJUlE5QXZS
            NkpjdWJGcDdIaEFCS3RsZWpxRnNDRUhuTGxjCmlBbFlQa2R2Mmwyay9Lc2xzcDlL
            V1hzb0wwOWZTNzlzaDQ1VHZpSmNnNDAKLS0tIFhYMUpoNkV3cHlDSW5vZnhQSEJV
            ckxpd2pQMndWL3IyQTFtMnRtRWFVWFEKozaHOD9VjjeFMrAEWuijtXD8g9/UuYSo
            mJ2W0n6OjJe9T6+x1Ozx5NX9XBL8u8wsYQHS7NNxlUbreQ1UchYowg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UUFOMGtXVlJMSFArR0sv
            TUJXMUVac2VndHdRQWw0TVIxNndKN3RseVVRCnFBbWF2bXNKVjdFcHlIY29nSFNw
            M1RQMDZsalFxTE9rKzdtZDRyTU9XbFEKLS0tIFZjVFIwSUhOTlNMY3NHZ0lOVWVR
            TENUd2l5NDkybnE2WjV5RmlhWmg4SU0KBcKjT1JHUwphfTJrWS0G7KMfh/bigTDP
            6+a90zDILRp3vgFNlEw1JAKk/HnT3iAvffHO+Jg6ubRpN2OEt7UTIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa2JENitZWEIrbUMwWWdL
            dFFKb1lETDZhSW9rUUxoVEZjR1FNRlh1bWk0Cm5qVWRmbUpIYW1RTW9GdHJWZG9v
            SzJJNjFxM1ZoK0pybEtuS3JzTTZhYjAKLS0tIHUvVGRMM0lIWno1SVNCOTU0dEdv
            bmhUdzRha0dSS2hPYTh5bFI2RWQ5QWcKen4sOmK7mQMpgsRY17/EmACSYuvQhZeU
            GS+64lFqWBHNrSUnjtPahLcg7kMdo3Mrc3QgYTvazigmDD+jMHFxFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:00Z"
    mac: ENC[AES256_GCM,data:7zDJB4QT9bpsNzfSWRKtB/wL1CwoiIN0VW0ik9Zu70oMDEHb4G1XJFFJt/DXN1rQVhAnPHwX9T030dQkYLf+i1AD26iK7I5Bo52uL/VkmJOgvy6ARXND5ZFyQ4lU8Q2sY8N2pmCO+W1ivQSz3Gq55hmGy9DGMTC8Y2Ds4Hqa1q4=,iv:bL4X9Q6+ivjTbfmQHIsSSRoWEmdlD3g9BSralsnKoBs=,tag:wIU6gVOhmZrE7BQbvBbRGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
