apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: sandbox-nix-ssh
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV01ObGRZL3Y4V2JTeVgy
        WVpJVktsdkJ1Nm1JeDJwaWRqeCt0RVBEdjJNCmFoUzdiQi83UEZ5aEs4T1pSb1ZU
        SjlFVkFEazFxb1BlcU1Pd3BHZmtIaUkKLS0tIElXRk1FRlVqTFpaOU8rUElkLzht
        a240ZXVySlltclBZSjRzeEpHRTVaWUUKRKa35WLuLU9/U5Q1ojY7olAqe96beUNa
        FdyvwjdVJv8hXFlehuMoUbTbdoSIIap0fw++mc6hCyB8YJzRbYM6UA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNElla0doN0R1cTJaOU9D
        cGRJYzhSd3IwZTdTRkVKUlh5N0R2a0dDemprCmQwVkYzNmk4SXZ6aUc4ei9RUkZ4
        cG9aeXZ3NktLSVNNU3d4cVlEbTk2RDgKLS0tIFVseVZWSXpjWjg1eFRxQ25IOHBS
        SnM4TGFwem5BTUVlc3JTYzBDL2dTT0kKYAu0sUordSQB8aJFGKWOBMkyJmr+PPFO
        1iHEBI5aj+g+zL/RdV/PhT7ySh6fe4OgUqcxbEQ9jL9GvNB/apZvaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dDh0NHVTcnhUbFRkTFlF
        ZVR1Vks5cklid2tVaFlsRUFaOFY3MmYvc0JZCmVIcG9EVU9Ec3BNVWVhbE8wUlVK
        MEpmYXFNTERNT2lrM2ZIREJZL1pmZjQKLS0tIEJLYjM3M3hBZVdzMHVPRVhtQm05
        amNsc1hWU0lEeTZpR0RuY3dCMXdJWW8KDQfAt+EPYqUsuSfZ6rUkGIOFrzubp4ma
        LICdsbflkimZ2UjZTkTtD2Phy/4CK0ab6Xg9LAEda83Il20Gg1nY6Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:55Z"
  mac: ENC[AES256_GCM,data:xQbT38EcFK4r4ptP1zyyPJV/TLx4EQIzS9ocqh78tr179fG1vpcguT2vi5ISqTpEzlh2lN/8af6GLo6Ud9nS8sfFGsYWuWkSggGIsjV9J8fd+Rh31ZKG5DhTO3/c4RHp6ZwE+DS9KtnGYC5pA5c9cP+V9OTbca6hrfeTJh8KRus=,iv:EK1CGPnO5sBk72c0rZ9OwOXJoK7g9Ba/3AsH2NLVfW0=,tag:awdRcMZAq5FYnihnvl1LcA==,type:str]
  version: 3.10.2
stringData:
  authorized_keys: ENC[AES256_GCM,data:gPXM2cH3E5Pq3qCuf546Isk2gNC1cmeN7uhPY7J8syvCsuxHVzABVr+GIXnEVx3JkMwhHMOXGMKyvkPuKPG88W8Q,iv:9UWdjuw2KAjvWVlyADFnzkIwhB2tRzsK7jWabL4yWPM=,tag:fATBIR9V5ApxiQBMAvaOBA==,type:str]
