apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sandbox-nix-ssh
    namespace: apps
stringData:
    authorized_keys: ENC[AES256_GCM,data:GZX2cdmeK0qOW2zV/NvRJhDnXrD56Uml+lmDRVpM/H0hS7cSeB7wx/a4xWv9Zjp+5j/kGg2gZ314wsPeoW/tLaXj,iv:aNy4hTE5dEN2ggrgW/UGvVGlPsNoJdOh9e7/COEXuc4=,tag:78PHMSBN6rBuRzhg5/aTEA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxKzFVRDk3Q3lZcDVmZUJs
            TDRGR0IvRkFWblpRdWJMVGd0R2hyRHlsNUR3Cmg5SWY4TGFXVklQbGZMQllSOVFo
            WXd6enRqZzgwbjNMUDJWcmxWUWVzSDAKLS0tICttenBQZE1sWDNxUTd0Kyt5WGpv
            Q0hUNHJ0bnNUYjFGN09PWk1TSVdOdEkKN/kA5q+g60B7J+TsdniOwVkXNcFQRgLx
            PXHcBX5vpzCKRxHGPno1S/R6wj4vnnsPaGqTleoCyRdAqxicftaPOg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYVNvVjZ2KzJERTFqU04w
            VDdVSFgvN0VYZ3d3dS82S01JZTBNYkEzTEMwCmQrSzdVMHEvMHZlTGJPQ0ZXaWFu
            RTlwc21XWkxXWnVwRXlIeEUwNVh5MTgKLS0tIHBVRjRaZDJPZThkUUtFbCtXTitq
            bnhMSnpvYktjMWl5QTVTU2hmbWNnSGcKfNCV0vQui70Klx8PxhgADIsDecnTsD2m
            x/BYM7QC01YHjROw9fCgQUw8MSclzjbjsgrB6ZJi8hY0v7Ni17WpDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYjA5RmFIajM2NjE4dWZQ
            b1dJVlhkMTRxcFlTUm9ZSHo2elZWczkvOWdNCmhhZDczQ1k1T3hKK2dkL082SDMz
            ellCWldpaUNMUnZNbW5XSEtsb3diSW8KLS0tIEFONDM0WE93cnYwa0RCVVlXQ0tx
            N2pqSEdiRU54ZmVkQ1dVVlZOeVB0OEUKijES0qzse8Qx+g2DV3sTuuDio1aOrQlG
            W8DIoGizifYxxSiQpPqlzHIJiNc9JslxYMP63HDKbVcYXVxkYSzxFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T19:58:01Z"
    mac: ENC[AES256_GCM,data:Ujf0XcrIo8avsiw0/6HcvsXNabqFkQZfUpTL4Bk+0efEDygqbvxK5qMNGMO3VByVK1d4c/egBgN/FmshBfJcW/q1lxldGSZK7t7LXmMti51SS6E5eKgY7+AXYH/o91MvMKXQBZ9LE6Lu/zkHDAZoBzqxAAhZb7FdXqiIZ//mPjc=,iv:KNe0QuSazV8q6Cwaod6EYM3hYq4UG9Q6FGHhWkDng8M=,tag:/OPnokmCgcugI5ekz5gLOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
