apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:l0aqWnQz2wcqg9yrapLHgWirxG1hMK/NbaOOdVkgos+6DmGnZc6dFG4cFiK0veS/1Ny8JAxHDsuzYOk0zMXNU5IbJLEGTQExS03/97zYMaOeysWSVmNmY1MtFNm5bwZ9hOGF/FwmYJICGPmUXPzUJvoUBctChUEwAMh0tnK+XeAiFfNMubTOoRJgF+ISYfpcztg0T12IA8L4dko4kJcVfBQq3bj2UdJOSDuj2XHcYpiHPgMYPTJN0FbbKV3Rh4CjyyU2PEB9mpQAOO6/zmpQuklUEvNerOX13O3E73PJK1tQ/5bMAvaxvJzkV+ZNrIdRhcxcTq6YHRxukulaaAkNi7okZnLDJ9g5qmsftTWoqd2z11XHiOLPnNae4Lx5L+w=,iv:bvUcxxRGUtxEK1BNr4mpVNjCNltx5YEwPSEcHiK7zsU=,tag:lXxIzBArE2FkZWiolU/biQ==,type:str]
    settings.yml: ENC[AES256_GCM,data:OgAus8eZKjRc3Z1qtX+bUmxp4i2n99S31yK9xfTw+gewXit2tpu/EMsRmH0MCqLkI72sjUQKGW7ZzPMVBJUjEEa3YsFJFXxjyT88gHxJRL/RJpRUiRRfGBmltEecfB//Nag2B9c/wLiY+FgOOyhPzF8iITu3B/PBpgpqBSzeK+l3Ipov4XkH6zsNNAk6OSu76E/t3iyD5ZgnRflfyHVKywNNdchyt5/Me/MGAADKgTf0fG5C/RTALKWtm1mRYhsVTVXa8ygPPAw8nqVjU9rk1o+DZXhaVG3TEOgxKrkBWe08Wy4LQo/miSxjIFL7IdMiueZ8PkySNpUk2PHmD4MBBizqFc3X+IBi+B5BHBGIDi1g/hgnwjfeVMxMK4WeIZPhRc8iMwU6CDq5+qQayP06JwkYtGMGp/RvdoM4u/2kpZvhW3DwEucj7gG4f3z68VeIlbmWm7LLYoEfy+85B7GlE07kjmj1d7za2j/90ed98e2TbNd9rEu3yvN3VbtSEf1c5A9322DnKkzYoRvthnoL153NYnygekHbj2xmn/q1n7UX18X88KQBm2Vk/3wsIdTFytsRpJdNLaAMO4WUsk60BkEiTR3Ux0zXJzRUdxmC2iauk6dFtWwAgx+Gg+y6yDVnqTJCh/M8vCuZJ5PDhEtHkSv6am47MYJGzNdch3ZL4QeILPVcci03YUUl5n86yKftvI/AidLpmis1vymM,iv:rdnqheGqVD0RoW6DMv91GD+lTJqTHnUKxerHpHnONhA=,tag:RI2fLZSvXpIv2YrzeHcHOQ==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvalk3alFvMElSVEZzZ25n
            a3l1Um1IMjRzcFg4L0hhdHZCdjdSdU5MRHc4Cjh2b0R4N202emdlMlhsUWVtQ0t4
            b284aURKdEluOEdzWEJtdzhzQzJoblkKLS0tIGliRVNEeDB2VkFIb2lWL3BpRm9G
            K3BFNmZWVEhxWGZPU0JQYzRnSGVJM2sK84T1KPqM0mnxik/OTs6LtcLX//xFC8xH
            l9C6Ioj0DmrjuURp2OZ6JEOH4M+nmORWBYVxoUls0Bsl+0hakVzc4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VDZIaTJvU1FSbVNaQ3JE
            WnFCNm5IM3Urb0hXNU56VTlHbUh4RkZqTDBRClVCajFuRzNleW5EL2d1amZ2SzNR
            TnR2L3FQUE1lVnltajRGbDRFaUFYSVkKLS0tIEVjekZIMitwb0tNL3FFYXVzV2oz
            WTcycU1UekpLSEMzZ01wQmZZQUpnN1kKz8laUwb+l6wSjPAVgJbE/Ex8LgzqcS3a
            RpMoDnBuf65jYzzMbgSnirbRpophBaFLpdtXzlbQAgujmuqN7m2pvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNFU4eU1hS0gxUWZrNU9F
            UUY5SGw5a1RScDVRdCthOE5HaUJ3KzdSdUhnCnBQMGpNWGNwVEFmMmVOOHBucTdm
            cU1PSkp6blhsTlAvVDJ6UGtxUFlza0EKLS0tIFErYm15SmxzeE5iZzY1Z21YM08w
            c2ZocXV6NXBvNGw0RjlqV1grVkdDcFkK/XiceEZrMHaEq1Y5LmVKbvYYZoucJo0T
            D6eafakC9Yn2y+3LP6UoYUGl9Ci6ywcAj9+fHzRMBUvG78QqZguNzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:01Z"
    mac: ENC[AES256_GCM,data:chpucw3qomGQXZWE5H5VpVVy4ZX9Ad60WPsLzFaBdYXBvNGLUqUewNLKgl9KVKjH9+yGSr9zpRxW7+9+aSb/vs+5gXxza5FYwvKSqvtFhHMqjcLlA0Tafy4+o20IWfn0uOo88OovFmtvmugDNEiIxZB1RjaDOgNr+Cv+8Ql4TGY=,iv:Kxx8f/aH2+ChfaMu3pZbsQMMUwC5RYNmku5hlCOvtfs=,tag:+M7KbnbuhatdiK3EjGEswA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:yf5fm6QPn5/UCNib4zctpouMZVKc,iv:WMg8kvyKhsZQ1AL/4xp+nhE/nK9hsDsd1pgXdnD6wpY=,tag:EEydBa9agVVB0wHvwHZIiQ==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:SUWXKXONdFnIz+gZwTdNmbpMmW8SCmJXM4hJAmDghSivQYWXkM50s5xNj+2+SGpmExKj7GkoeKLxqilT80V+iQ==,iv:2rXHA2PLx+ectRqaGZ2LzBuwPKYvibSJTDIP2pFcppU=,tag:UVw+JK8ByHvjM4JJV7tqPg==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:GVvTa85U7Dr/HGoYdDVHH+5JNML0RM2BoBGNNoYmuqE2U1/RJVHkqxetv9STFSOBrUeM9QruzcNMrA==,iv:3EzDSQoQEwGVC1jMp05xCqM4Dvnig/gLjmSzuWTgq2Y=,tag:8A6CsIjvPhC+79b7Slc5wQ==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvalk3alFvMElSVEZzZ25n
            a3l1Um1IMjRzcFg4L0hhdHZCdjdSdU5MRHc4Cjh2b0R4N202emdlMlhsUWVtQ0t4
            b284aURKdEluOEdzWEJtdzhzQzJoblkKLS0tIGliRVNEeDB2VkFIb2lWL3BpRm9G
            K3BFNmZWVEhxWGZPU0JQYzRnSGVJM2sK84T1KPqM0mnxik/OTs6LtcLX//xFC8xH
            l9C6Ioj0DmrjuURp2OZ6JEOH4M+nmORWBYVxoUls0Bsl+0hakVzc4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VDZIaTJvU1FSbVNaQ3JE
            WnFCNm5IM3Urb0hXNU56VTlHbUh4RkZqTDBRClVCajFuRzNleW5EL2d1amZ2SzNR
            TnR2L3FQUE1lVnltajRGbDRFaUFYSVkKLS0tIEVjekZIMitwb0tNL3FFYXVzV2oz
            WTcycU1UekpLSEMzZ01wQmZZQUpnN1kKz8laUwb+l6wSjPAVgJbE/Ex8LgzqcS3a
            RpMoDnBuf65jYzzMbgSnirbRpophBaFLpdtXzlbQAgujmuqN7m2pvA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNFU4eU1hS0gxUWZrNU9F
            UUY5SGw5a1RScDVRdCthOE5HaUJ3KzdSdUhnCnBQMGpNWGNwVEFmMmVOOHBucTdm
            cU1PSkp6blhsTlAvVDJ6UGtxUFlza0EKLS0tIFErYm15SmxzeE5iZzY1Z21YM08w
            c2ZocXV6NXBvNGw0RjlqV1grVkdDcFkK/XiceEZrMHaEq1Y5LmVKbvYYZoucJo0T
            D6eafakC9Yn2y+3LP6UoYUGl9Ci6ywcAj9+fHzRMBUvG78QqZguNzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-19T01:01:01Z"
    mac: ENC[AES256_GCM,data:chpucw3qomGQXZWE5H5VpVVy4ZX9Ad60WPsLzFaBdYXBvNGLUqUewNLKgl9KVKjH9+yGSr9zpRxW7+9+aSb/vs+5gXxza5FYwvKSqvtFhHMqjcLlA0Tafy4+o20IWfn0uOo88OovFmtvmugDNEiIxZB1RjaDOgNr+Cv+8Ql4TGY=,iv:Kxx8f/aH2+ChfaMu3pZbsQMMUwC5RYNmku5hlCOvtfs=,tag:+M7KbnbuhatdiK3EjGEswA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
