apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:wJPpjFsyl6zugS2R9hd/QsFVL6azlrV9XuZHnjxoVyWLYJuwjbYwhYIRIiAptiYJFaP+rtkCwgoaPdoHTi+J3me9F6RXMT4Bo6jERY91tZYAk2ZFiRt7G22LA8BjCssvZcPZa49C1wTXqVJRq55a+XiURu95cUjZ484U+TsF3fJUCPEXs2/QhK34UldV7Paky53TTcon3bafWo6pXFWmfG7W2HoqW2IFbdmcNaMTvwA4wYBLP57Ii0KU6lBX3ttoeGPjdGamfC1/klDjO4UV2mMECCWYB5dkLU2xPwJTlQaNeZAcV0qzxvDxY6IQSjlHSkf/wVEWgnlFUdFTqGOHDeSYPAlykM/eQQkfAG8xstllHdPAaoJRFjRnqz36owk=,iv:R5TLAGafWhwN38vFSk53RgEkkwHQU+zT88hZ99wOJxs=,tag:6gsSzaYF+AnjxKjtj0gHLA==,type:str]
    settings.yml: ENC[AES256_GCM,data:qfXqmsTMps92FcVwKT0O2RTGqyDDOPFFwUzbC/u030UDTW4R3gZ9zz/rsv0pCPt5+jgVJd1iPatNvStZt/tXKqGoe+F0CTjKIKehO/+vX3KHEJEUWsOPqVwW7R47FX/Q/ig0r1AogKWLUfXOcmclMGlT91X0Ybl5kryuy7kbg5tnVNW/HPa0VOjOg3RV286WhSjab3eXQ45SDNeFSGh+qy0jwCsPND6twZGfxbzDFrh9ShQ5pR0/fE6REzV3pA6x1s1+3iVIuKOAKrqMt8NMSaAiwwPfk3v//J0cF8578kb/SkYrD9NfOrsiHgRm0m2xGHqZkmfad0iSOs+vluGi/YKp5w+ix3Evld+q8qsg/x+KOIAwlcwGsJMyrIQzwbFlRV5BCAPPa6eyz+wpokegDfA15ySuxYnZlyDnfF2s6fZnafCMRHw72NpBvdNPWSAW7xkH0xf9UTIbIbHujjB+QKrILxAVYymHyg7xPyFn6CQQrzZdWAuMJYj8rwVH5oiHuc9QzGHIv6YEkUq22TxEGKFFnkQkdXnmMtw67R1bW1oP/kpYR6SVDvQ3sJmG/NzDywQanNcM7s+jNWLc7BYEpwGnWNjdAXNfBjb4BRlPjGNSJNu5ZnrMOZ4E/XPA0ObuZuuixBxg9bMVGmi+HGDim6hY7ALNvCA0+iRiAiSzWPCCkAAR5fxrbp0RUMXmwfoYMzGNxfZP4SoaBIklPnW1TnKO/JA2d6hl44io6VHQ0tnz8LCtx7xNvOPM1XTP87rQn4h2Tq/cWV6FTw1kQn7hRXUR0k/DxldTYSYmjL1PbXXWYDumMqP2kQoaQ6P3UnLMEFqN20QMBqdeaxr2tjfEh2BtcUFwOxGUlUFmXJ3Qw03ICP3Iev/U1DGh72lvsTG2adn2Q8jG7qezq9GFrSF3bsUEAdLFRkDDgf3nVoFJ/fSqe2yR/oxrGetKnapx//I12zHj8b5jdvo2n9Fu58LhQrP1xneag/AQfhzQUocBGU8l7h5l61hczOkMQh5RV3hIHg9pL4gg2cnaRlzCbLZEo44KLi9ViTpqG+feDsPZ53K2Y2ui12aDW3V0A9rLwuM8qerE1rMnQRBr2iNGbI3uNG9WJN+XjHsL395aNz+Qh0SSOb7hvVLXDYocT7medzrz3qcVed0veclcfpj/Cxi2DpJfVKHMQEvVDm0KurmIu0uLqPhtlRfWSQzpr/Umo7GlsUs4H2LZyA2Zm69X6q0KJJSGDoVn1EOJgUtbalACEsi65nWJSfyIFNxqWhNDCToPAm9/U1+1cy3fjwYxKP2VIhd7tNpJS+YAl5S/o9uU5wVvPkRuMJlqpWsh/69LCIQqWfgjZ0oZ/SZU9LsOaoKnoEkeGgCyKUVEvXb3Eju0t+pH2png4rOLppFvmaBayrIM2L4GaC6IxLzQPMPzh4a6uij2xTZdONyu5eRygN9/rzgnqArM7H6r36rutYtTvsfXL73/o8xeZlHxs1NwEZbEK4O+ry92ITBPniKmJs9nvJ3mjrFYT652wti8CQtXUgjfUqiz40jwfX5kh0EhBfkQcxEb3dC0eR2WHcJ3VYO69xr9uPx9FD5T/ftkAMv2hL6cV3lEaXJGGMbe6QUcO70A4Aqb/ePhlvewCE3Av2UDJoZGoBmQOW5g0PAx03zznaSdztbCxlAbUpVhh6bGamCCd1+n539P96pneCVA96kPVOgVFV0BEOrCu7boab2w9eTpu9QjmOILFx5KIEbB/p1l+5dOhNk7cPWrKLF/QDSvRMacdS9peDWewUU6RfOALMjZB4z7j5OXh3dHUj76VbOgKtNV1EHJbFWiRMaoNZBfPTYWkC+f0AYu75YIWdOAd2LwR2hPYXptd0Txpwbw2VK/ToG3hZ+CFFPDikIMPeRmgNAxsvR3+y3/Q7xARkl1R1U4mclKArDV+WvR94t0fus+TVQq6RU3m110AO9s2fdY0ZdMyU2czviPByU9O/vjm5IW1Q+l3bekcdjrxSl+/IjxPSqjcQKGaqMn22G6guHqXpU0wxWqd59pgusZKzUmmnsMmxfUubBrQkVj+R97S91c66dGaI5oYTxyakDFN7YXkY5u1oMWhmiHNg3O4ZWShRNYAtBQtt7e7fRSrLNjrgsJAyOgFdnAW3ezhl7oXy1OEIy3IYMpBtT8GXHD0m1zefcXikSNoRvQaZApvkcVPWy6zJqBMueBTFgEe0+QmdZEIyG671X0xKk6Jb/f+fJA4r7buK2soe4qbKOhMWCQk6MNd7UOpY+t4UzCCdvV0UiUrJcQxLaytLhrux/5QzaA42mCj2qAa6dIsbG3ENlZUXaXqhuC+hUVVD0DAnN0wXk0We52QcX2vxaFWaKdvIQB3xq8MZSG5QW46/msQrL+gVxRabkY2NYuB3DgALF5UKjUU/FnA34mgq0jfAeO5Sdit58jkMWl9wMn5GciHhbZqXER8ugyFmEmF8NH4FUoghIdTPgMRXVY7P8JbFtFZJX9h9hjnj3slUdpnaaEKeFQeVKuF91IrZCOb6UCP6DCEj/kPFzmZj5yn5x+nWVIZbY+lpSSFQB84r5IsN7OxcCmDHsJb41Rcqn0ptuRhQnrzNMLgpnTB+9q3JFngZDhprYqIW17MTgq5UvpQbkWZPlBvS62uIlSKtDDf3gsL7E78+bL6uDXP6uedDNSZoNjWQCMLgRCQJAZhSivRyKSeXWaAv6axEQgocgfS5t2dqMF/ZL/g9zmMhDbrBeS6iM7wDHPG4yGX3QdvFUNzOPk06ZyWNqFA6SAbnJ3kun5PpDOqmv14vArkNYd3KBRF5lzolNppy3JB4LRZ3JGva6r/7HT+8pOI/HfTwmpzyowPoQeaknPOc1O8yoi7fsT5ociZ74HYAxJGQIhePv+bDIWGJrAPY29ab3wy7S2Ta23aT+uL/9mz73/cM5qa8Utnl1gu0epWgAzStNhT44apvXJKf1WfVFOvvyffolhS51mTzR22qfy3HE73Kkih6yQwexq4hOz2T+OXA6/9oZhgjK2LKdb67G4iXKADpQAcSXN0hhAomTLQVxAJi8nwnvWxXuCS8z+5FBKq8rJkoaeyUZk0Ggybw4iziSMLMTdec1jscO2LE/igszgv185nes52S50ydki/sX0tkE7mNjz5MS9HlFf+Ro5KIbZCLfqM40GJnJArKPhAAvm77stR0vez1uytsZeQIRi9dTzilwFwofCnHySzgnVtMmUNfODMOh7z9c7OpI2Imdo7KgGdKOshKYKHJiy4G9Q7DJ4rUaBr04eUG7cnWU9akSsWv6Gm9m40UgUED6srHOgEPbQA55+C/fS157ET+u9NySMeIKFD+3/2fI9t6ay0t8OumgX/iFJ1/G8EaXdFe2OqeK4wWGocDjb3BIO6JOysIjY8D89WcIReSrSAwH9nQU2Yw6cFPUK83s5YlZmfq6u/S3WVL/rxn8nRJAlz9rccFWABKcUQzuEY61X/Rqjy/2dZB9RlgmZ1CaVtgRNPYK0peGK0rNqd/fiLOO1fVGeRx6rK+HKty/Ogn0/I6HrtV+DOiJg8wLmjFiG1LlcomKE5X0zAfegahuFCr1zUJEMggrTIaLn296lKljmxokppM64gY0c9Tyyg5RiOYtosW5efIJU7B7psDG7fte26EoeKsof4jw=,iv:NtuIRm6jiptsw2VIXRXgpoLz4WYOToLhgUSCEf/piY0=,tag:30Zz7wuvqIHevFZ664vw7g==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArandMR3Vnazh3N0Q3VDA2
            Nmp1VUJybUJuV1lRY0IyREdEZXp5RjZsbEJ3CnNIa1Bnemd0UHZ5L0F0RkRGQmpv
            TkZqRmF0OGpYZVhacUg0U0VDWjJYLzAKLS0tIFo1N1lNWVl1dzZXWEpYdnV5SkJW
            dDlXeFY1Y3lQdHEyeU4wUnJ4cHhPNjgKKEDarwb2PV/NXaGH6jf53Hxf+Vfd4/H0
            ZfE/AsaoIr/dtrB2LWHqffVhyoHzGaDshSUbdpMBaz2ahOrkgHlc8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNnN5c29MZm5hbjRXMW91
            T3hWU21kL0VKaTZiWHk1RUpxMElPSGs1bkhjCmpFb3NmNHNkT082ZDhiWTRwQXVY
            eHVtUHl0NVJpa3g5RmFpTVJpbk9saVkKLS0tIHgxd3k2aXhXeWpqVUNjWUJKSHpB
            WW9nVFpFWTB6clJ6cmpUcGRsa3ZLVWMKoC0uQDV6nbc7Lajf8nzecx5/GicOs7yt
            5g9sYIM3eu7P9d70Svbn3SBfmpLSA5Je5NscPDw/cOqQe1HpXPd7Fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTFl2ZUZCSk1ua1hFeEE0
            WHBJc0lvZDdQMlU4UUs3SFFYRWZZUUxwNVRBCnlGQ3k2U2VsT3o3VlBVOEoxd0Z2
            U2xMWC9Iek9hYS9EdVFkUVZqWEd1Z2sKLS0tIHBHMFN3aHdQdTZtWlZFVU9Qa0RU
            NzB6NU53TTc5cVRYTVNzMFdyKzBtenMK/ZMR0nDGP3617M2ds8rXfyCI7G01QWyJ
            TMmLXKMLlqE626fHyAzwjpPl9iMvIM9HMQ7eUSIl7CG9FFT3t8fbnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T18:50:57Z"
    mac: ENC[AES256_GCM,data:N/behQIi/hYL1ndSe8DqiColOcMRxron7PhLLnZ0g0j85u7CSF4A4Gd98ou1H73I0ouY9miWKZYAAE8hrbqpo3JoxUlVRFuLuWgeNbzwjUmX/QsS8c9Vum6D5DBnegBv804HWvT+zHqj74U2WOH1JZSzePeZlljh4C0Pg3SDNVs=,iv:F283kwD/hm33Te8T4Xu0vWBVcL6HtmdhIkZWnSUfX+w=,tag:eqILVuF9GaFtNoPf0YbsBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:FEc2LEpG9rYFydRnll7J61ZlL/y8,iv:nQhPIPM2xmMC/pDwSIuumKOzK4XOS8GX7u/cQF1YgQM=,tag:a7On0QEzWkJKKeo0zT0LoA==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:FbaW+3Vdcr6XuPZht9S0vuOroj2qsOEAAyINFAokGsineqKESv4Jc+ghLKw4loHgLXMk51e/OlNo/PWN0nV8SQ==,iv:a5xMNoRZCgYU1uzrFeLG78Ii8PvTNf7nHER8aCMLyV8=,tag:eIk5fgddtiXbPPRVnm+LYg==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:pGorjNxe2bWGjF4svXAGwQRYy9i0D+ZMqrFAlapR6qQzEIZaXyN8MM1wkJ5J47Quu+f6ibXrV46hXA==,iv:4FMOpsamqpun/eDYJBgIeHgBuGI/L7OReTvridHS6pA=,tag:LrDGLtWezJfB2yld+7wDTA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArandMR3Vnazh3N0Q3VDA2
            Nmp1VUJybUJuV1lRY0IyREdEZXp5RjZsbEJ3CnNIa1Bnemd0UHZ5L0F0RkRGQmpv
            TkZqRmF0OGpYZVhacUg0U0VDWjJYLzAKLS0tIFo1N1lNWVl1dzZXWEpYdnV5SkJW
            dDlXeFY1Y3lQdHEyeU4wUnJ4cHhPNjgKKEDarwb2PV/NXaGH6jf53Hxf+Vfd4/H0
            ZfE/AsaoIr/dtrB2LWHqffVhyoHzGaDshSUbdpMBaz2ahOrkgHlc8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNnN5c29MZm5hbjRXMW91
            T3hWU21kL0VKaTZiWHk1RUpxMElPSGs1bkhjCmpFb3NmNHNkT082ZDhiWTRwQXVY
            eHVtUHl0NVJpa3g5RmFpTVJpbk9saVkKLS0tIHgxd3k2aXhXeWpqVUNjWUJKSHpB
            WW9nVFpFWTB6clJ6cmpUcGRsa3ZLVWMKoC0uQDV6nbc7Lajf8nzecx5/GicOs7yt
            5g9sYIM3eu7P9d70Svbn3SBfmpLSA5Je5NscPDw/cOqQe1HpXPd7Fg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTFl2ZUZCSk1ua1hFeEE0
            WHBJc0lvZDdQMlU4UUs3SFFYRWZZUUxwNVRBCnlGQ3k2U2VsT3o3VlBVOEoxd0Z2
            U2xMWC9Iek9hYS9EdVFkUVZqWEd1Z2sKLS0tIHBHMFN3aHdQdTZtWlZFVU9Qa0RU
            NzB6NU53TTc5cVRYTVNzMFdyKzBtenMK/ZMR0nDGP3617M2ds8rXfyCI7G01QWyJ
            TMmLXKMLlqE626fHyAzwjpPl9iMvIM9HMQ7eUSIl7CG9FFT3t8fbnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-27T18:50:57Z"
    mac: ENC[AES256_GCM,data:N/behQIi/hYL1ndSe8DqiColOcMRxron7PhLLnZ0g0j85u7CSF4A4Gd98ou1H73I0ouY9miWKZYAAE8hrbqpo3JoxUlVRFuLuWgeNbzwjUmX/QsS8c9Vum6D5DBnegBv804HWvT+zHqj74U2WOH1JZSzePeZlljh4C0Pg3SDNVs=,iv:F283kwD/hm33Te8T4Xu0vWBVcL6HtmdhIkZWnSUfX+w=,tag:eqILVuF9GaFtNoPf0YbsBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
