apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: searxng
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: searxng-1.1.0
  name: searxng
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: searxng
      app.kubernetes.io/name: searxng
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: searxng
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: searxng
        app.kubernetes.io/version: 1.1.0
        helm.sh/chart: searxng-1.1.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - lab-pi-bk
      containers:
        - env:
            - name: SEARXNG_PORT
              value: '8080'
          envFrom:
            - secretRef:
                name: searxng-secret
          image: ghcr.io/searxng/searxng:2026.6.20-fd42d4fda
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: searxng
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - mountPath: /etc/searxng/settings.yml
              name: settings
              readOnly: true
              subPath: settings.yml
            - mountPath: /etc/searxng/limiter.toml
              name: settings
              readOnly: true
              subPath: limiter.toml
      imagePullSecrets: []
      tolerations:
        - effect: NoSchedule
          key: pi-only
          operator: Equal
          value: 'true'
      volumes:
        - configMap:
            items:
              - key: settings.yml
                path: settings.yml
              - key: limiter.toml
                path: limiter.toml
            name: searxng-config
          name: settings
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: searxng
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: searxng-1.1.0
  name: searxng
  namespace: apps
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/name: searxng
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubenix/k8s-version: '1.32'
    kubenix/project-name: ze-homelab
  labels:
    app.kubernetes.io/instance: searxng
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: searxng
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: searxng-1.1.0
  name: searxng
  namespace: apps
spec:
  ingressClassName: cilium
  rules:
    - host: searxng.josevictor.me
      http:
        paths:
          - backend:
              service:
                name: searxng
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - searxng.josevictor.me
      secretName: wildcard-tls
