apiVersion: v1
data:
    limiter.toml: ENC[AES256_GCM,data:ZHs1WoEQ6+pNlGcZIVrPTTd5OOnaVdocl+SmMNASc9c8OXzgow1xeRkI8XRzOapkxCoQN64zFWyVspSkZI3BWwos63cx6Az+o9p6xUQVPLRRGikQQ6cRpWYq6CUm/cxOupeAqziOOfKjxLZHsKTYZ5NEPbWTrc9Qq+J3luPVfX9rC/nf9sjXdy17MGqf8kn6SQ1eroJAXLF2si4VygIsL4rT/b1f4YxLLUSRMCDCFI/z4Se6I8Ts2sQrDcpwYpbDj6LlGTWvsTGR4JKAShjxpyWrnGummjIdYQOsvB5htWOPgMlMXf3HVuzwF47v/IR73BeyOZy1YxR5XDQXAN7E7YbDnEYcbxhWQMyAVfUFYhGo15pHfmWRn9CDe83lJAo=,iv:2l6r5bIA5qXva4IQHs6FHeVW6lJ5bX4xKraMw4+pWcM=,tag:uyuoWUMUv3NXqziM5MSbEQ==,type:str]
    settings.yml: ENC[AES256_GCM,data:IKlxMimOM6MLh89j9BfSaCqXdsjWAU/BDQ07fewA8GgwCW9VpRDGcb8U5zlTAsLXw3h/hTUOd6NG0pfA/CXxi0b/qsfqulqaGmzu/kxUhmeYU4zvfIkUnpWft/YH3hS4iWhar3f6HxZMuay3kl6vJ1mRyiag9UR9crbMMaYA5quSujUE2Etz0p+FXd1om0Uy4C5YMJqkNS4KvhAKhv0OolSNAKSyGEbj/ujTXIcMH4pAJbMxjr+dUFsGIpxs2C5ciqdGMKmFvNtS3XC0/+a2YcXbr0g2qxL//7QX07JZOOI5bJNmF/1E94dg6wbzWArdTPVF+eNVaD7wl2JTAW5nD7jckPwsJ+nw02ycr9192kzqZriKsN/go5I5C30LM5288JXgIYTSNcZ+Ne+KWay859F3IQPeFB92IcyhUvVvgMz24Kg8YaOPokvcfV/zgE+u6xPhy0a7Ci/4vb1jqKumUtaVrK8USpVB/x1KF7jOOVMcDzBwxpFBx6ijU0JCGML7BaKl189KZIT3SxObyyVuWVjX5o6nsx0IKnQ0O9ArxkXiZRwQijhS+AuRP+PWnT6bvAb+ZMgnQqjrB9S+WETZEL4FA39OInkrnMu6TXFGJCCf0dWnbF0m38Z9goIR0nxErZzaHoceLMbCH/044lA9wgPRz7Rm8DDMDYBMXZfGQjyJVJI4ek7DhibYk1BeI3dKA9BmapATwftalJ3v,iv:zVLBJsSOhSo6YAakrBUdYADquGW8n0yuHSdOWQLF5WU=,tag:/fivwJnkOrUsnAP+gSDJ3w==,type:str]
kind: ConfigMap
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-config
    namespace: apps
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb1JIazFHSk1veW51anBN
            cWc5NVZBUG5zeXpBSExMdkwwcldvcElUdHdnCnh3dkVpN0ZRY0ZUclczajF4aEls
            dHhWb3hpdHY5ajZsaFBLN3pzYjJ1a0UKLS0tIFhWeWpRVXlVV2lQa1JYSHF2bTR6
            ODkveWpoUEJIVnpVdnNydnRlRGQrVlUKv5+aXRBnzYZT+LszT6zGaFPSQay/ge4F
            /hvFD/aGLJNfGlk2RkSkqeRcDPsTmXhdjOtVKkn+b1GAf57aJJAwPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUFuWU1pUU12MzFBTjgw
            bGRML3p4NlN5dlVibmowT2F2OGhJSGo1RVQ0CmpLZWx2Zk1pbHl2cHNCa2VRRFlY
            dkNqR2hscG9SeFBxbkQ1cEFHS2Q0bFEKLS0tIDhRRysrL1JNTHFkdmdOQkEwVFRx
            M1NHb01IRnhtdlRON1lJMU1hSm1SeG8Ki5BKmxaUH40YpOLj63q5p3csDt24zbSu
            3pXn8FdQD5cHBw+XitYMTtXAiOWFYKjN1PPjEnrNe4hGt9hy0UK2EQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N1IwVTBDTmlvLzlkTnBm
            UlE1SlhQZ0d3RWZkejJ1eThhYUh2NkNUQXhFClZIOHlscFFXanZLNzVWUkcxUFBo
            WFN1SkpXMUxXbjN2THk0WHNwZXZEeDgKLS0tIFlFOVY3dElkNW9oWCtKOHVlaDkx
            NGtwb2JwcWIwWkxuTVU0b3dGSUh0VGsKI+Supv+Vnve6JElub9mJqPnc59QhuhDh
            lBQzXBir6maXUbrVewxOgqG/2m3p4Dz1HMTIwgrZGP3xZwuCmTiHzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T14:14:10Z"
    mac: ENC[AES256_GCM,data:vDrg0zxtaOR5yPT8YSD1ICf2jrfO54AwM7JD7pZ2LyaXwa5xcj/r0TFQOhdWi7Z91eldwkMh3VSoC8sakTuuZtnIlp79UWpF2qML6XAcfzCyesUaiI2yFmtk8IxyuQzW9A1phhjiQwuhZcSaWkfJddf3MnNiShk/+4iyJO0u/2w=,iv:GekrhG5JfgCa1FN1f4jw/4YgBH4uD15hcaQP/bMeZqw=,tag:Gn6RC/NK5t94s8/PN0BgRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: searxng-secret
    namespace: apps
stringData:
    SEARXNG_HOSTNAME: ENC[AES256_GCM,data:tjbyWbcnEPj6YmPVL6Z53qeaCG4i,iv:WD3QcKQIqWlS0ShCirV6F076+vxew402RBAXhCNTc68=,tag:Yz5vTcL/Ku4x2EgNTcuHYg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:/hkNvQKOomWB3tw0AAdTZzjOPgwUiEQR3mOulCOFU1dJk3WDvJPb8OPzXCQyu3dEoI16lDd3C0RXHN7kZ4Q6ww==,iv:ver0moXdUV8g/dZhuQlyrUZV8Mu4Cy1OUxBWVoFsHs4=,tag:zZjko5anS5dPQ1uGx1u67Q==,type:str]
    TAVILY_API_KEY: ENC[AES256_GCM,data:dXM52ZGHGP+XbGtBakYa10XZzO7BgpmrXPu1pR/fcCfBECOxmw4ryq0f215ZnbcnYcMEraUr+uEWJQ==,iv:A48XMcgF6VRiAoOJh1Lc9xpTZ19Xhx7uzS7p9dS3rec=,tag:xYc6yo/zyGu3W73RgyTWbA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJb1JIazFHSk1veW51anBN
            cWc5NVZBUG5zeXpBSExMdkwwcldvcElUdHdnCnh3dkVpN0ZRY0ZUclczajF4aEls
            dHhWb3hpdHY5ajZsaFBLN3pzYjJ1a0UKLS0tIFhWeWpRVXlVV2lQa1JYSHF2bTR6
            ODkveWpoUEJIVnpVdnNydnRlRGQrVlUKv5+aXRBnzYZT+LszT6zGaFPSQay/ge4F
            /hvFD/aGLJNfGlk2RkSkqeRcDPsTmXhdjOtVKkn+b1GAf57aJJAwPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TUFuWU1pUU12MzFBTjgw
            bGRML3p4NlN5dlVibmowT2F2OGhJSGo1RVQ0CmpLZWx2Zk1pbHl2cHNCa2VRRFlY
            dkNqR2hscG9SeFBxbkQ1cEFHS2Q0bFEKLS0tIDhRRysrL1JNTHFkdmdOQkEwVFRx
            M1NHb01IRnhtdlRON1lJMU1hSm1SeG8Ki5BKmxaUH40YpOLj63q5p3csDt24zbSu
            3pXn8FdQD5cHBw+XitYMTtXAiOWFYKjN1PPjEnrNe4hGt9hy0UK2EQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N1IwVTBDTmlvLzlkTnBm
            UlE1SlhQZ0d3RWZkejJ1eThhYUh2NkNUQXhFClZIOHlscFFXanZLNzVWUkcxUFBo
            WFN1SkpXMUxXbjN2THk0WHNwZXZEeDgKLS0tIFlFOVY3dElkNW9oWCtKOHVlaDkx
            NGtwb2JwcWIwWkxuTVU0b3dGSUh0VGsKI+Supv+Vnve6JElub9mJqPnc59QhuhDh
            lBQzXBir6maXUbrVewxOgqG/2m3p4Dz1HMTIwgrZGP3xZwuCmTiHzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T14:14:10Z"
    mac: ENC[AES256_GCM,data:vDrg0zxtaOR5yPT8YSD1ICf2jrfO54AwM7JD7pZ2LyaXwa5xcj/r0TFQOhdWi7Z91eldwkMh3VSoC8sakTuuZtnIlp79UWpF2qML6XAcfzCyesUaiI2yFmtk8IxyuQzW9A1phhjiQwuhZcSaWkfJddf3MnNiShk/+4iyJO0u/2w=,iv:GekrhG5JfgCa1FN1f4jw/4YgBH4uD15hcaQP/bMeZqw=,tag:Gn6RC/NK5t94s8/PN0BgRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
