apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sftpgo-config
    namespace: apps
stringData:
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:iI7vYSidJcyXeDw6ZhxQpvYlu8Ti3O9t6Z3uMpFB5S8x00NO1TX1xvVQwbYr,iv:y/fRVrBh7SHMnle0b+vpFiW6q0repEZnWtoIZYj5Dho=,tag:8kW06q+ZE5wwE3SYvwk2Jg==,type:str]
    SFTPGO_ADMIN_USERNAME: ENC[AES256_GCM,data:Vpy5MIw=,iv:fOrLUMWWuHaMr01IvuQkjI5SZEehcgTAdZ9HVJzqG7c=,tag:3jP1FKId5bpHBLnmR3Tz5Q==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID: ENC[AES256_GCM,data:Edwj+ycz,iv:wertdL4CEWY0YE19PwJ88fkX9c56msRdoJyON/SF70I=,tag:YfY+8e3iuhI9Mscw6T+q1Q==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:CbEroTwUGTImx3U2LFE1A8sS6gBq5HVuZEjByU1QN1SsR18TlB6Cc/thaUvYAa7OfggukKMn,iv:6zZbNAOKbIFQ3VxMNOxtcP5csgJmHitmdL2IU4qYpJE=,tag:9oOQmCWc1B95VvAATTe7tA==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL: ENC[AES256_GCM,data:D/49opCzmohwgWJdfjpPSh08xh1OTME9mpmBu/7tMkvffntP+w/ZoUEVgXvh,iv:NRtWWCozgyK/7NA5C09+zqYh+rfy4wV7WvVURe5rIc0=,tag:8cNZZBI3QcMYHjqeX4hHyQ==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL: ENC[AES256_GCM,data:t5AZr4oNtm+E+L3dZmTjELgkN3xbfjt7lo6l9g==,iv:fVP7zMLwJgKzWthXXt/wFU/coCjCLiEPT+kwO4g1dg4=,tag:1DzHMpedbMtmPJswROWvRw==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__SCOPES: ENC[AES256_GCM,data:5Xq6YQXOSaeADjwlVDv97pX4LEA=,iv:TfdrhRzCrWfNnoXFBngZRzZ3cEXgVuJH+++zhGaVpk4=,tag:bBbHx46E+hjcdnssTyTApA==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD: ENC[AES256_GCM,data:tkkwLUDAH/Da28nh923got9u,iv:AtLDjU8BvuZza1sgaKckc779CJJUhRuX6Hj1g6c4TTA=,tag:iKTl7p3Txh5e7SxPIwJfqg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWWdlNFkzRUcrNUpPeWRs
            R0NoUHpDeU5ubHR1Z1VQd2ZXdENIQktoT25zCkNoMk1tQlR4R0xtblF1WjZEU2dC
            ckdZYWlqU3BuaGluaDcxYWVoc1dCZ0kKLS0tIHo3V1ZSUlJ6QmNZZGd4VmRnc05E
            dlpKNmtlRDVKd29uc0hYREFYSjdKTXcKtQOuGnyQoZp5njErolxo4AzEkxwUlvy6
            7zqU2j8tr8eSnYsfDYaL9wAgwJQ1H0hKMQl/FR+Y1p3SGPLzNmAxgw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVFdDSDBPSjRIc0xXakdV
            Sk1IdmhiQk45RnMrOHpoUVU0cDc4N0xCNld3Ck1ONG00RGF4aFQxNXVxd1VxZTQ0
            N3ltOHRSMmIwcjVPRW4vUUsxcms3VVUKLS0tIEZwcHlGYTFYQURZZEYyeVBZMmN0
            SWRhWmNPU0dsdkJCb2d0YWp3QmdXRzgK6RNv/0XoOh+BNJMueZTC2LaAjso1RsHo
            b3d5ZbH1NtqMRSfXRSmKSn+lr0jHdH3buoi1J9Akg5Jpuby6hi9IFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbFdOdmNSUk5MZ0JXSFZ3
            WkNpWEYxK2tSd0hVSSs0QzR1aFlXOG5YbDBJCmZRUjZwL2ZYdmpqdVI1Q2EwYjUx
            WnVSVmxmMTFUWCtqZjZNWW1HZ3RlZUEKLS0tIE9JT3VKb0t3ZjY1emsrMVV4SGdn
            SzR3V2V4WnhMWkVXVUx4YUE1Y2pkTVkK4GuuXgtqC9Vnicht7Ph/+yuFqTjWPclv
            ahI3zPgLHoD8Hu1niApvKfMywsAnBFZH/qVis1l/pfhWyPBxygpUDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T19:34:47Z"
    mac: ENC[AES256_GCM,data:iSaOSwtQs1jq61F7ROp6DncRewf+JJ5H+img7rOCwwWfp8gyZUz66qAx2U/SAX2AW2OrJ03lDFRNDjytjVSfNJckl+F/FEqfjYBOCgA8mNG2e0q7EIzVHn8xPRb2nwguXq/4bfvEB1CSFSxEqln/q3oEVpm8BeglspnsIrPvKZA=,iv:soAtQtIcOjGMXFKNIv0lS+wZ7T5HgUn74tgi7PW5a0g=,tag:+EsqMP446TovkrMlJ8IIKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
