apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sftpgo-config
    namespace: apps
stringData:
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:o73uByUmekLlGD699B5NCPCLbpcW4O2hZz3fjIqaOu5pg9FrEKtJnpz/XV0W,iv:lmrFF7p1Bz52L3oC552BwUcCE6PRfQ5zpF047JiVUUg=,tag:+lXQh4+6v5RaocjA4epB4g==,type:str]
    SFTPGO_ADMIN_USERNAME: ENC[AES256_GCM,data:l8rxVkk=,iv:i6XKXatnhIDfEZmaSwOHe0JKZtF8dnPqpMv19suKigs=,tag:H/2KzSx+GCmBKROze8dESw==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZDJFWVJJdmczTm1oM1oy
            YUNtc09RMlpFMVdXcUc1amY0bkp5cDBiblFvCjBZbzF3NHZkZmJkSU45QjhGVmZu
            Sk9HQXdJYWRKR2U1Y2xDZmR5S051eTgKLS0tIHptaEdSQlVuN2s5UHA5dGNsZytm
            YkN0VXlsd01WbkoxMTQ3L2tPc0x0eDgKXnReNG64P0HhX34UVoWtfrMpU9kCkbfJ
            44Nxa5hnQUvW6dXIc4tQ+Ii//QzNXjqN0aCxX8PLHyBq08raQF18Jg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZG1YQ25UNTRLVUNCNDNx
            VytLMUpsL1hjdnArUDdyOFEyMjlQdThrTEdrCnI3VmZ1a2tPQ08vYjkyZll0Y0Fi
            RTlQYmNmWHhHQStmWGdMb3k3cDNCYmcKLS0tIFNZbzJ0anY1bGYxc0JEUUZ6d214
            UmZUMlRySW04S2FPOWJmOVFGU2N6TTQKQ2g9LmOtatKjX5JuX8ABFNzcMvwbUtP3
            ylrZoETGH1k14eA0wi8TvrP29Gydq+ionnUIA+ASkaHm6jJ/qiXhng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSm9BdVFFZS9CRVd1b3FH
            MndSN0lHaVVJelFad2pvOVRpa2VLL2c3c0NzCkdFcnFyMy9Jck1qY21NdGxsN0ZC
            SmNzWFY5L0MvS1h3c0tDZFJYYlNmZ1kKLS0tIFRxZDZyOFNORW9ac2xaYUY1OFE2
            alIyU1hFL09zNk11V2hCVEdKMmkxT28KW5Oti/bagaNToT6vXs25IbvyWg8/nu/+
            gWgplSAKa321n4hm+yBeekCVK/bjl0qYES/JZADHHD32D0z26uMjMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:33Z"
    mac: ENC[AES256_GCM,data:TI6seASN//GLQO1lCYinelIK8YK6o/oq6UQstwTXVS/z7ku+a5ciUFWPaDbi1AfCedcPo+j+hG8z6C0LD5cBP7P5kQuOIIyOOrCSoZ5qMUmBLMtNWV2FUdzdOYCj0q/QarniqmjXIOKZ81Q3IqcrGJG5AHu/IQkQyEYJrO7cF5k=,iv:z/PMK6Sw7csPRZwdQ3ajIp95EUfjgBSBGvUOKwQWmUM=,tag:rAQ9NPEXUp8DdI3QAcU17Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
