apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: sftpgo-config
    namespace: apps
stringData:
    SFTPGO_ADMIN_PASSWORD: ENC[AES256_GCM,data:xeNLMmr+wltqjDNkZNo7b8F6aUk9TRj8FtHXi+w84LVzfZY0oVS0ZSFh7Yir,iv:1+XA2VHUmp1d/WxaJ0vcMeajI39pEZRNDRCvrm1rIgc=,tag:PtMPHwIStvTpFJDhtZNy+g==,type:str]
    SFTPGO_ADMIN_USERNAME: ENC[AES256_GCM,data:vNPKwas=,iv:2rMTPAMkfnjI6dYZc9TuR/aD4XerwLdXJfPVjxf7IOQ=,tag:LW5VEU8EYZ6bq6Nc2jiIcA==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID: ENC[AES256_GCM,data:UcrfXbNz,iv:gdJY6Odo9FgQ6lKquhPubXA11ZKY5etr4irPKAY+p5U=,tag:Z6erl+WL5Mh5oiLMGyA/mw==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET: ENC[AES256_GCM,data:rtN8oBL3wJNmslUmLNg5o8rLm0UUydnfoWpD8FwpDdLZV+r2NSdybFZ2XgjNgCcjcBsOnRvF,iv:p5F/rk42uCjGY0v32eBF1XDKJ7xsD7WdkjYoeybx/P4=,tag:j29B4RkNaf4MNZurkknwhA==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL: ENC[AES256_GCM,data:/E02yctZgwi+8I56fcan/YN5/UxGIv1qLFX4HX+C9UDdtL/Euo02G3cJxwwP,iv:0OY225snDURdRO7ASDalUodEMNCZI+3A0KFM2hNdtFE=,tag:NcAV7fcsEGRL52RG6TAa0Q==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL: ENC[AES256_GCM,data:7i4v6W18MDyRrFxmJFRsOfFPXzYnRVOYfOTxDw==,iv:Wee6H7HLmxxuB7Lhvtnqokup9IxRPGjUSSIduL6cf7A=,tag:/9zNppd/pEDcGbZKL+Xi5A==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__SCOPES: ENC[AES256_GCM,data:idwc/8FCqVqyJYfCQk16Gwfott8=,iv:bAZdLkPmmuSfzAQ48/nae+1yPEkCeYnekOjx9piuCCE=,tag:XqzlfEnJs1FXXJALrVLGIA==,type:str]
    SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD: ENC[AES256_GCM,data:jrmDoWx6z5yLcAS7iDHq5/QX,iv:yYCFz12n5IEB9EBF1HnSBf1nOwdGhNwkYMLm3i2z9QI=,tag:Q+gfLPqaELnYkkF8s8RCFg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SGlQMlEvbEVNSUdiZGpm
            TDFGQnUyUVNLMm1CSmxaN1hxWGhlaE5RZjFRCnRqT2V2UnlxcWtNOUhYbm1scUJ4
            QUxVWmVDdWo0WEZQckRMQm8vMHZNa00KLS0tIEtvQ2ZqeVlVTzVDU2tTc0FKbUxP
            bG5QTklzZ1IyTTc3RDNlSFBpZXBvaEUKQ3kefAQlZTStxbfwNK4ydBqiN14AdZLg
            Skx6c0/yKYS2Ayh+RxQMcus6hpcLQVHwfWaDaxgv4+H6EdwhhbKUPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaVV6MmtNUUVzaHAxa3Mw
            MkgrTEVEWEdRZDI3TytEOFNjRzZDbnZ0VVU0Cm54cXJwSHFPalVReFJlUUxNY2gv
            cjN5cHNwNGV1ZTNtQmZFMWNtNUoxL0kKLS0tIG1LSG9HTmdzMndqMmVCeHRMdGZ5
            MkhzWk1oc3FkZVJvUnJ1bm1KaTdzNGcKkuu/rt2cTNvUGosI3+FtzXm0/Ax+Hdr9
            tTrUXG0ns0PlfX1xqkfjrrKxbBEv/olNmkNjkV8WELNZx7S1FkHEkQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSk8rakNlSEZ6cVVYRVU5
            TWQ1L0NpUmgydWcxTlJxWm55VXVTZ3R1cERFCmhlV29wcGJtUHp2OGZpK3VSanps
            RzZtOXByNW9IbXFsN3VtemZWUWFOVkUKLS0tIHZVZ3gzdjNwVjlQSVluRmFZbmc4
            a0ZtaFVPR0MzcWwrbnNlN2JXS2d6ODAKFTcRmR/wITYRsPVika/F8ELGN6eIKL/6
            5Tz62f26lUZzq5ysWP9C7WLI0Y2n4bHkcpF3qbQ4NC+X5v67T8aqgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:56Z"
    mac: ENC[AES256_GCM,data:UgLWtd5uJy8Ra0JvqA6slTnFaRtRcFeGNHnMR2jXalPIYXVHfA18xeJnNsrgcY7VuIGVqZi3lD5mKSGeq/Cfg5F44snYE6mrQb92rx3bnHC2bKeNDdbjNrJUWDPRb47MRkG8wbBeI9DXhMC1pGaq4hWPEN38Hxo0n2cJynY9EL4=,iv:Vb6nkCuISyBACU37Dpu9gEZVOzZk43ghnttJNsqvbNE=,tag:4wHKvWgKDei0PPJyuBiAZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
