apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: b5313f02c4dd3a585173d94af68a1601aa034e3e
    name: tuwunel-config
    namespace: apps
stringData:
    tuwunel.toml: ENC[AES256_GCM,data:e2u6UkAztcUcaFIj5PqOH3RjkdLrdYLJvMSDmosZ57kyxj/Ym5G/+1bSzdCOuyPl+62UA/nGEQm+irmaEIGsjvFfYp/NxQ9/UGVmKfEIiiBqnfP/gWfYZTgLpHcMy4I51mA2wFU92gz/UHOD81a/ZkYHphwOgujaoVOu8lkop62l3sg57AKlGhH6K/CSB6ZYJuo4BmQ+PBPPkh91UTSbaPQK11Np0nEMO0DMYKfXsv5dFAnVX5ChAScFnSroZJxduu9HEmW8ZmlCZhLv+3vZ/HTEE4vX+3zQRFczrXx5s5WqgwrL2mwSAk1QjIyVxeVBR2cENPXcErQBEf6eoi75rpryUtyVkNbpcLcAKDcK+vW8yW1ts/p9PPVJTAER10jFDss9n3P0an9sK5QF/3PY2lJnJXzFgCzm661EpU68SJ1yqSCbdNSVftsIY06rOwwkH5ehB3hsob/J+DRR2AiiM7Q+c83Ctdtr06XhkkGewHKY5VRc031S4+B4yovorqV40XVb4pftG9u9297QDriVIrx3O1V8NApQ1LSWQgeE95ugh+yR47X9YhZ98plz0RXl3n3+Ac46N+NCCKFV4AdIiJH0BPwTVzKl0KDi9u+cwMSCpc9NirVU/ttY7vQK0ZgVkax8ypq1vJ13MGXeS6CxbiK3dUABnt87mY4PDJdQug3naJXFNTX64rOP7G3wO5lYNuD8WtTh3m9PvzLZwZ65TWOzGJapKS5hLQtMw/iZTRBQ7QwP1VLkC8bCW6KeAM889ahcKe6so+Vt67IqZfPnqHY2DL5w2iBwOWplFM0GJXCqmK4RpICM4fui74Ps5Q3tagTEOBdFOakGan9q8xqpNI1GO3qDp0Ktb6UNyfqntlRaY9xvsehk1DKqM2s61QE7M13ihi1ISgLweZBzpylls6aF5k5hqfgzwLl5Djy+SnMUOP9AbswWYUGHYqSzln8FlkWxJGPhCq/9bEsXRlRsaR2Km0f4c02HzZc1GU3BerelnR6kaaZGwiJMM+vmnELClKVsmOp6azFQRqqesLHbN/+3kI4lpQaXLNC0CUz2dIPdJVa6lgWB8rh0X5Iiq+Y0jNflDdpb9Fq/3JYNxv8LMR0/EV7VGJRXHqmF5Zb2H/EzIUgxlp/N/oRCa4dygFbkU34vCyElAJmvqZVE1pqUQ/K4WY+oMOxIT1EwpA==,iv:OtvOhzMtDfOVtps5YgN9F2OH6kEu1mFS8QK3zuIcSoQ=,tag:7BhnjEG0H16h6lrnJ2dz3g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ2pDSWZ1c0NLQ1Q1SWZz
            ZGxRU2Q4UkZ0UDhpWTdYU1ZCZXY1QTcyMlR3ClRrRXFyazVST1lWS3pFVHFEUzhJ
            WVl4OUNZQlltNmlja2l0OTlSR3JsSU0KLS0tIGtmSjUwMEd4a1NtblFJVGkrZXRv
            ZFUwa1k2VnR3VG45T0YrUHZqZ0hGZm8KvhSY5MGFO/YwTWi3pKnnotlDIMr0rzxD
            Q/nQ0GF3DH4ItDK2YcJX1DiBgNyuaBDNVHiFDgtJS0HScNaZf8exLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4azFlTmxHam5EN0MySEpH
            UHRVQ3ZRY2prZ0tqNStnclAvU2ZUc2NiWHpRCjJ5TE5DbVBEM0pDUWxzSVF2T1BY
            QlNacSs3aFlLTzVFaFo4dFJsQ3I0QWcKLS0tIGRDeVVyTW1FNUVEVWlwbGlBL3pK
            d043RDZvU20rRklXbzFxWlFzUXRwWTQK8SsLPQkqXg+Xn4eBbpwoXiAWhcvJ86Ko
            4qhRn8fQhJr9iCQ4BbG3VXX1dENL9ndLC8M+tqDiqN/fB/I1nGSRUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlJVMG9ha2JWRjdYUmtG
            N2xSYVgrTmdSSkFzYnZQZ25DYStjUVFYQnhvClpiNkN0QTJOdlJsMHR2ZHlMditv
            OThMS1lobjZ6Qm11WEVmUU01RXlkdEUKLS0tIFkzdjhZeU40WHhwQ2VZNXR6ckZY
            YmkvekZMQVZvcWczYWV2UGRYdHcrL0EK5TLrwXDx+3U826Bwn/EPVboP+XkOSkJO
            oJNn/A4N1Q7RxP79xZjZlSwlZeviKWj+KHxFMufNkR44aTemCRjfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T13:38:14Z"
    mac: ENC[AES256_GCM,data:Y4xwziNC42U7Rf72k8Smqz3UG9SJ/WfZxNHT+wm6Zz8bd0ptvjKBIMy/6u6RRpy3BoHqnXIpbenhab4/MFHGxyWcclDW1HeJ0R/zVcxkNwg7oGw4Qsa0sqTul5DOjQ5CcM7Pb61LCnQH4jrJV3wVnB6qRAs7ZpLRjkhID5FbYuo=,iv:ZypYAaEGnfnnLIhQeMINVnSlv2DpVAsUzDp8zmsxt4Q=,tag:79FJaTKT1Y0Hrin+IyZxBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: b5313f02c4dd3a585173d94af68a1601aa034e3e
    name: tuwunel-env
    namespace: apps
stringData:
    TUWUNEL_EMERGENCY_PASSWORD: ENC[AES256_GCM,data:tDCQuUAfNfl+R9jpnzJIAj4m9QTLsz8bYoOx5LW7vhFw5+uzzwKIbqQA,iv:vTuijXvk2kY+H6ELz+K5OoiJteSvZ4AA2+mtmCKMCdk=,tag:BlRfw7P5qz81ecSwhguCTw==,type:str]
    registration_token: ENC[AES256_GCM,data:Xk0uZWbiwwkomC/KDD+eXtMhIoDgpseLwR8sXoNGNN/bEECOGRJXRdA=,iv:44Pl26imnDgZq1DjNOd5aoAEQjs3+SP8AAaFk4LFAhE=,tag:SAC5Ib4WJICuKFME2e0I4g==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ2pDSWZ1c0NLQ1Q1SWZz
            ZGxRU2Q4UkZ0UDhpWTdYU1ZCZXY1QTcyMlR3ClRrRXFyazVST1lWS3pFVHFEUzhJ
            WVl4OUNZQlltNmlja2l0OTlSR3JsSU0KLS0tIGtmSjUwMEd4a1NtblFJVGkrZXRv
            ZFUwa1k2VnR3VG45T0YrUHZqZ0hGZm8KvhSY5MGFO/YwTWi3pKnnotlDIMr0rzxD
            Q/nQ0GF3DH4ItDK2YcJX1DiBgNyuaBDNVHiFDgtJS0HScNaZf8exLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4azFlTmxHam5EN0MySEpH
            UHRVQ3ZRY2prZ0tqNStnclAvU2ZUc2NiWHpRCjJ5TE5DbVBEM0pDUWxzSVF2T1BY
            QlNacSs3aFlLTzVFaFo4dFJsQ3I0QWcKLS0tIGRDeVVyTW1FNUVEVWlwbGlBL3pK
            d043RDZvU20rRklXbzFxWlFzUXRwWTQK8SsLPQkqXg+Xn4eBbpwoXiAWhcvJ86Ko
            4qhRn8fQhJr9iCQ4BbG3VXX1dENL9ndLC8M+tqDiqN/fB/I1nGSRUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlJVMG9ha2JWRjdYUmtG
            N2xSYVgrTmdSSkFzYnZQZ25DYStjUVFYQnhvClpiNkN0QTJOdlJsMHR2ZHlMditv
            OThMS1lobjZ6Qm11WEVmUU01RXlkdEUKLS0tIFkzdjhZeU40WHhwQ2VZNXR6ckZY
            YmkvekZMQVZvcWczYWV2UGRYdHcrL0EK5TLrwXDx+3U826Bwn/EPVboP+XkOSkJO
            oJNn/A4N1Q7RxP79xZjZlSwlZeviKWj+KHxFMufNkR44aTemCRjfug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T13:38:14Z"
    mac: ENC[AES256_GCM,data:Y4xwziNC42U7Rf72k8Smqz3UG9SJ/WfZxNHT+wm6Zz8bd0ptvjKBIMy/6u6RRpy3BoHqnXIpbenhab4/MFHGxyWcclDW1HeJ0R/zVcxkNwg7oGw4Qsa0sqTul5DOjQ5CcM7Pb61LCnQH4jrJV3wVnB6qRAs7ZpLRjkhID5FbYuo=,iv:ZypYAaEGnfnnLIhQeMINVnSlv2DpVAsUzDp8zmsxt4Q=,tag:79FJaTKT1Y0Hrin+IyZxBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
