apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: tuwunel-config
    namespace: apps
stringData:
    tuwunel.toml: ENC[AES256_GCM,data:Jlx8SRJnW2OFAt6ZFcbgxaRAojRjq+RpkInYzBfhUZy3g5h3PYFlhi1vXX+Es2/SOm2g1SLc+vzGc+UGUM4PuIETE16M4vZPPa+TYaaXZTdR6ezyXmvxlEADJp8qLD6XWsQhdYvCM3qOjOTc64JHJZQaGO9/P0O0VeYtse8wQwCtH/o82dEkU8FrEcJZIsWk4UCYxL5YSb5H8F+tjqV3/wzZ4v9+fqeqY3DMuuuoPvuZuumnalNIEK6zY5mHN9OPck7XuTxc6voSSZ6tyEIPYjW0L+uFBPRV18M2n5Rm30LTPL66o+PkRJBpIEYkIPVWciR7k1U0oPOnb4AsY3zRxqek0YVDSSnwScdm+CciSKlqGXvvJg/sqTSOygFI6wOyeYfw/k/al5HiGZ3oXwe06gRznjayCh7E9NQjDiX0VGLJdBL/eU9639nzBHn6P0vyNCSH1XLEN/mqAiD6XfXo/i+Gbfx4g6CiiuCkekUIDk1Rp9bd+MlWrS1c0a5MeDeQPWs4GZVc+Oc0LUbp5vTqANZSFcqX05h5gr4HBylZqjvTCnT3zfhmJlo8W6VdC5E7cMaKkmNzTggLurlpmx1Z4uSQtYZufK8MmyyDcku3JSOFi0RrIgMqXDkUJJWE2ZgZPW6pi5p7BMIWhDkrM74XrN5fVlmt31GHoKP9OVIWLdRI9P2IqEMmT7AnZ/ly0NO6MBGgDlsyJz6CSEPa0ZVpQ8SHi9T7gYfguEE63NFSwb+6ci4RReBa+xWCjcyxHsPdBluL1koCgfQxnpJ7nOLbhCLKwFkFR7nHQsnEA0P7B2LuqbZApXPo/LPEn2dFjt5Q/oZ/R0ic6BVe7AeN4iDJJ8C6I8UOP1g8B6gCF/k=,iv:E48vUgzVCm1H3A9CQU75MARLi2C0wmBQa5nkzhQr9QE=,tag:sukotcaB8ev9igfra/VV/w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT2htR0NFZ3dBYXFqdjZT
            bXA4ZHZpVGVlWS8vMDRObGxSdGhsM1I4ZEhBCnI4RDlzZldPeVMyN3ppTXlqVTlM
            MnRpOFdxQzI3N3ViVEhkUDhreTdYYmMKLS0tIG9mL3lDVHl3Q21mOHd4djVId2lK
            TXNiemYweldOYTlqS1o1Q00yQUFlRm8KoiWn2ELFMa7aRLiCJPrNZWIP1CHcMOkO
            wCxqr4lEnd/ZtQQa7xPxWYgLj3hVS6FWPI8xeY0s3dLWaO9aYCAEiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSFYvd2ZCbS9HSjNlYXhL
            WGYxYVN4RGY3NkV3TXhpYU4xSE9lVzdtZ3cwCjdsQjI0RnZoZGZPbFVZYWg1Uk83
            aGEyUWRNVElXQXlGWmdibUhFRGZmRzAKLS0tIDhTNXMwR1dUeHYzQ1RzeHlFaTUy
            QzNoR0dhdUJ4S0wybkpKQzFKZ0pLNFkKi7haQLcUkGyNC0E/x/qn+E/7PN/Vtwgh
            kC6nxnqnx77lWkymKrorxFHMjwgawnDRpNOk/wTC4U81pvl8lJJa9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUm0wOVJRRUtjanpoWnJU
            TU9kN3U5SjhkOVVaSmV1TXUvbmdWUDNWa3pzCkE1elRpa1FVN2dHTkpFY1VDa2VV
            VTRoNjFIM3ROcG9jYzhDdTU5ZnF2VVUKLS0tIGdybEJSYmFOUUQxeXZWejhsN2s2
            MDk0Q2pqOHNiTU1EcnMyOFRqQ2xNeFUKbhpltneewa5mlpCmG5yiWd1Oi9D7jAC1
            ZSjAtYKN5WwamPhaS7w3dRCHX942g0d8P/THJobrWtt9Au/GzTaFew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:56Z"
    mac: ENC[AES256_GCM,data:8CqG8RYemEY/Dgws6HgfR5pNxPHDNouv0/R0mer1rp2XtW3r2CaFGAjgZICiU655IZR3T90MHv0ugefk6mYMwm1Hghw7y4n2wdeRzUbv9J3gafFzfivPGzYEmd/UjQJbIafmJX1np9e2D0Pbz11m1/vqmlYAcIjDT/o4Q1UcI4k=,iv:0N9HuRgnWS6SRaGS+ASfvQcLNLAmklb8pkTd9IrjYjI=,tag:XV+NO9Ft+5ehcbaeRkEDrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: tuwunel-env
    namespace: apps
stringData:
    TUWUNEL_EMERGENCY_PASSWORD: ENC[AES256_GCM,data:GoNiVf55dPDRg3NT0lXraqewRchlVXCYESUNxgZoHT8N6K1xPxitHWEm,iv:9WNcOp3cr7sgzklbBuX3zxc0o83hqPywShPRsfCvLNE=,tag:cqChLCfa9rkufQGCN2xhFQ==,type:str]
    registration_token: ENC[AES256_GCM,data:ro3Gp4tNtO3dTSIKMMs1wxKMVgBjKqpLFGpzSSwRFJlfJ6+3dPfLgQE=,iv:QRAlMxKlRu6QnA/BB6nTdvS/nvuAJzMA2oHc+t5oALE=,tag:DAuYYjhaN57ZovNrvYifhg==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzT2htR0NFZ3dBYXFqdjZT
            bXA4ZHZpVGVlWS8vMDRObGxSdGhsM1I4ZEhBCnI4RDlzZldPeVMyN3ppTXlqVTlM
            MnRpOFdxQzI3N3ViVEhkUDhreTdYYmMKLS0tIG9mL3lDVHl3Q21mOHd4djVId2lK
            TXNiemYweldOYTlqS1o1Q00yQUFlRm8KoiWn2ELFMa7aRLiCJPrNZWIP1CHcMOkO
            wCxqr4lEnd/ZtQQa7xPxWYgLj3hVS6FWPI8xeY0s3dLWaO9aYCAEiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSFYvd2ZCbS9HSjNlYXhL
            WGYxYVN4RGY3NkV3TXhpYU4xSE9lVzdtZ3cwCjdsQjI0RnZoZGZPbFVZYWg1Uk83
            aGEyUWRNVElXQXlGWmdibUhFRGZmRzAKLS0tIDhTNXMwR1dUeHYzQ1RzeHlFaTUy
            QzNoR0dhdUJ4S0wybkpKQzFKZ0pLNFkKi7haQLcUkGyNC0E/x/qn+E/7PN/Vtwgh
            kC6nxnqnx77lWkymKrorxFHMjwgawnDRpNOk/wTC4U81pvl8lJJa9A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUm0wOVJRRUtjanpoWnJU
            TU9kN3U5SjhkOVVaSmV1TXUvbmdWUDNWa3pzCkE1elRpa1FVN2dHTkpFY1VDa2VV
            VTRoNjFIM3ROcG9jYzhDdTU5ZnF2VVUKLS0tIGdybEJSYmFOUUQxeXZWejhsN2s2
            MDk0Q2pqOHNiTU1EcnMyOFRqQ2xNeFUKbhpltneewa5mlpCmG5yiWd1Oi9D7jAC1
            ZSjAtYKN5WwamPhaS7w3dRCHX942g0d8P/THJobrWtt9Au/GzTaFew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-25T20:04:56Z"
    mac: ENC[AES256_GCM,data:8CqG8RYemEY/Dgws6HgfR5pNxPHDNouv0/R0mer1rp2XtW3r2CaFGAjgZICiU655IZR3T90MHv0ugefk6mYMwm1Hghw7y4n2wdeRzUbv9J3gafFzfivPGzYEmd/UjQJbIafmJX1np9e2D0Pbz11m1/vqmlYAcIjDT/o4Q1UcI4k=,iv:0N9HuRgnWS6SRaGS+ASfvQcLNLAmklb8pkTd9IrjYjI=,tag:XV+NO9Ft+5ehcbaeRkEDrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
