apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubenix/k8s-version: "1.32"
    kubenix/project-name: ze-homelab
  name: valoris-config
  namespace: apps
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkelczYU9DV1FnTUV1aDVC
        USsyYXZvc1hoQVVNLzhyZkJQeDVvSVM0b2xZCmFJSTJ5NEQxWFh3VVFqN1NIUW1v
        aktkdE1DSzBZcmN5cTFIWHBxb2lCcTAKLS0tIE9JNzE0bVFYMzlSU25qalB4VUFr
        NHVqVzFWNkdYTXlNc0tBZDBZQ1NOMVEKhaOjTjMafHikoYzmOYgqcNY2Y35ipowi
        euWinQfkU/C8qpzi4VwVo7xxu0OqoQdO2xjRnImZwfi9CAXFTbj1iA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNURlM0dmYUlhVjcyaFdJ
        OWtDNWQ5TDR2WWtscmI3cE9nektsdzBYMlZNCjlmTGhNSU1ER2h6R011REQzTyt5
        TW1uYmFUK3pvN3NYeHpPSDRQd1JOQVkKLS0tIDkvSHo1dVIyUWt4TzdTVXhyNlRZ
        TlI3UHB1K2ZPM0x2eWJLMnM4QUFzK2cKYoo5w+guKjof3A2q0oriL5FgRdKxw5dj
        69poLIoCKxq2wl3rvE3leDg/fQ9tbp5vkrkA570jATzr4xwEEL52cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQUU0RWhSend4K0tybUNB
        aG1OZnJEdDgxVk1JSlBDSFVObVlUQnF3YkZRCk16Y2xPS1ljQXh0NkZRb2VLMXhC
        a0g0NUo1Y2MwTVhYZVJzTThQNk9BUUEKLS0tIGc3UGwyVUVYcVhBZVBteUtRK3g1
        cURMM0lyUGdWMDJPd2g3RHpWZElBRHcK2L3mHUh9O0hUhf0SOi7vIQQ0CK+9w5TU
        V1sVz40N5XOLcDEp6RS4/Mt6ErVVWnpTxzkn2NC40PRNL8LUxBwTNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-26T01:15:56Z"
  mac: ENC[AES256_GCM,data:m4Ps1gGtCZ2uIZO0E5knsXZTJmIVL37zKF2PE6ewkurAIwNuzSW79zb1BArCeE22j46AO7VCmtR+PQ99/ffRodS3KIc6oL3yr6btCrVhJDgWwjy/YxiGhfBMkibZnK/oBxAcusLzKabT6Mg1ackLVs++1XxD70WJ/+RYy+KuBZU=,iv:MdYJzVotNvr0/TUMT8KFRYz73LfGGIJp30W7HQBI+pM=,tag:NjnCG2/IbUI5wHjDPSP5sw==,type:str]
  version: 3.10.2
stringData:
  IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:uLh1qPdD1CuW24PaEPAgNAC0BtJZzBXAWLzu6uxL,iv:dgMMIRLTG+0Ofv95cp4zfv+2TgkGyBlwYi63pbXyN4U=,tag:Vbh4nAGjrPYivA42MwB/Cw==,type:str]
  IMGPROXY_KEY: ENC[AES256_GCM,data:uD8kxQGv4u7uaUt/9PCNcs2yyFrOvJoTaaYMFqCp4+jfiSscISUEaEKAzbZpaFG9N8Z5KA==,iv:dugvZ6cGlzMNxWgzmJBgmRBLd3dlyWRZFKrcOwUHg2E=,tag:MUNuIGmL5/sb9OHkJkMenw==,type:str]
  IMGPROXY_SALT: ENC[AES256_GCM,data:rcaNw/J3ojl3hvb7s5dlM0pqxqWhQR2jM8wrNoLMUhDyqdS8Hl1QZqaFULBHRDjtLWY3wrk=,iv:UMrJjCZjDOkZmkP32avXUVQNtkRMw2q6GgN9qrRLNFA=,tag:z8rKDZY8reux/pOodapn7w==,type:str]
  LLM_API_KEY: ENC[AES256_GCM,data:+5DDQcaV4fbsUQTDzNbMW8Z6Nu11EqwYvbdheScOZ3CarujUvPu3qseFCO0yAP94O4lYuI1gmh9p,iv:120k0NaWGAnraEQ8c57ny6nCyx1jKFAEZneo9WlmMXo=,tag:ubNGPwAYckX+xEtVwKYL5Q==,type:str]
  LLM_BASE_URL: ENC[AES256_GCM,data:5yT3z+JYpKEB9xF4D/Ytv7qeeFhQPukU+0pnQypWN8/GTolhSDlMEaTN4LTVoNb1iRv7YPjJS/I8wPSdAyWNve8=,iv:ak1NKTzJwB+9GCl5Crdlni9lIxcYcUWkDFGXX6rO3bM=,tag:03YwqVZxxCv7L2uiwYoKpA==,type:str]
  LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:vyLf5XIad74kbSVOTWSxlHHgcUlQdUHD5y0EhfWO0xYyWOKECQ4/iDc9BiTmpKlzoF2QLHhnM/40,iv:Z2zZoS1MrLP7Z9p7mIWgdtm2ZJH6Ce3jYuxHyjbO0c4=,tag:MDCxt6W4EDBGMJl4Y4A0JA==,type:str]
  LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:tLDxzLtKQQIGTMh3M206tDQFdQoNDOeK8mH7yBnHMVLHP50Lq2U2ioluB6OvLXuhAb3U5t2vsFFjhBUqaPQibkk=,iv:hoDDd1180Ovd/XWU5nznoaCvSjZyB81wODJOx9bmXtI=,tag:uvgK8JW+p7LXpTiMTfYxjg==,type:str]
  LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:Dufz+Psa,iv:dPJa0b7oIMYJO88bU8pw/du3n5bHH8JZkBkQpmiZAEg=,tag:pnK27b/UGO8yN2FiYaMLIQ==,type:str]
  LLM_MAX_RETRIES: ENC[AES256_GCM,data:Fg==,iv:Xdi8+xXpb9OrnG/omdVAztVK+iXp3N3idFJGvn5zSxU=,tag:3KDjmh9BuHO+ZL5mu03igg==,type:str]
  LLM_MODEL: ENC[AES256_GCM,data:k2nEHjTT,iv:zA2Fvyu9wTvzTDHDayvpM/nMW782IK5o2iIdpidgDzU=,tag:c6Iu0FXLwWjT/12k1ifdVg==,type:str]
  LLM_PROVIDER: ENC[AES256_GCM,data:vc5sff+7Uln7,iv:biJUHDMC++Co4MqsOI2nnh0xRI9+aI4IUXMap5BZU3g=,tag:GSUBibzFEqwKVX8pWZhk6Q==,type:str]
  LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:rllh,iv:S88Inqe6dmX6K4p82ivazlvRpwLWPbu+IhB8TSrGX3Q=,tag:467Uh2+q1CElMGonCTOtdQ==,type:str]
  LOG_LEVEL: ENC[AES256_GCM,data:ZCW3flk=,iv:r6CPgWPPX5Vc4DurJP/AzsXMS6IdQLHU0finL/NZJAU=,tag:BgHS22Yr1GWKu2aCaNpX8A==,type:str]
  RAILS_ENV: ENC[AES256_GCM,data:KGT87nFvstJfPw==,iv:yYD8UKhkc3mzBL1hnVXF2fzJha13aX8ejzmxqE11u/s=,tag:MZPFQQ7/y/Txw42zE2Z1kA==,type:str]
  RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:88GOzg==,iv:61q/IsRx/yQyPlnZt4hDxBN318SM2HmNNmPEKijpcE8=,tag:6c0ygcODZcVa7Wz3SPSM/A==,type:str]
  S3_BUCKET: ENC[AES256_GCM,data:MTDyRzqGkI1kQA==,iv:qNLX5q78b+iEqAyu3biMyNCmsjmtusPHz5JMf+SD940=,tag:rrH2KuwuwCgf5ZodFzmsWQ==,type:str]
  S3_ENDPOINT: ENC[AES256_GCM,data:qSlFp4XgrKiEE3r/jXZ3xAlF7yZ73nvsxbC8WkVpDGKNzFe6X4zgW8u7ksfkUGdC8OaflPzutAmH8TODWA7k+f0=,iv:i8SOHtaDiWVvIkbxPE+H24u7AJQHKKhv/H9IHMoAv6Q=,tag:b9yuugX0nHUgeTqyB2azsQ==,type:str]
  S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:PsLU1LKJhnmJmPClTIJ4fsNQiJzUhMtMCwGZsd026IG8,iv:VPgnDH8W4VcCHNTVEh3LA9Tn1Ckzhzkd7hnoIs+d3mY=,tag:4qovfxnvCIHs1JL3pEd1qg==,type:str]
  SECRET_KEY_BASE: ENC[AES256_GCM,data:t9i3NQtZxcQsG4lK7mc4fPbjUDpNv0ThjdrSl/PGm1u52TSh0D0ywlicoz5onmrtz3kin/CYhLbxEt/2DR89,iv:iGmzXsSeWswXU1rqYSyuzjJ8RFQbwgm/fWg6bXoBbjw=,tag:5UXfPzoKJr2QS6mkvyfkGw==,type:str]
  VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:DydGiLKh52s4x4EEa2gcpA==,iv:QxmV9uzmereevHuAz8d5GRr9tz52TxqNKSyAjUfB55s=,tag:ZZsetCzvDgpU7crmmt5Z0w==,type:str]
  VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:7roVqpIzFJQ2CxiMahnYI/3+2MJw6ESlTIYwNT/RHjl2JoOaEV18TWC+tjv+w7t6ggtnOaXh0Xe9VTQdeLQV/0Y=,iv:x9VITxiTZN8qUZ4xAXNS9FanfNzCFH5PCSwR7W5isLU=,tag:LSP0WYaPwkAj3khHSRBKlw==,type:str]
  VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:gJdHVUC1RK5EWYMyHMIjlcly6Eeqnc/PsUujKTTFcNKhRrMt1jDm9rhLcJGNfKTSXhxS1PZ+dvTX4MV8dCkMdQ==,iv:/95F0pVSflUlFz4FLi7lzjtZcok9qaefPhH/Fqr3IWg=,tag:2rjNwUHxfgDGZJC7TDpnLg==,type:str]
  VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:pKbO9QpubgzRv1WfUI6qO4uzcIPqxNQ6BwYfPTuFpJYEYUYkG01jq6alyvLOCU9AKTgu5pw6fl+r1sNRux3nYQ==,iv:NsWWSES6sCK+7hNLplEigERkl0FXBCeFWiS7J5U+JqU=,tag:MW5FbVg/XMO7maXAFTnVcA==,type:str]
  VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:f0RxVSXxZrPhovb0VqAaEi7brzki1gWZgkJlPPIcASeIo2C6DS+mPki6tRy6idxnNQHM5DalOHtHr3A5kyUpROVPJbQ=,iv:uy0qN7/E+GEZFfTbRKnI/psKTz8rRwj3kwFcYFV/mJQ=,tag:e+Ul44wb+H0jAYht8/sScw==,type:str]
  VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:CFdMYv/RutEuXiSCHqtSIrxZEGAKeSBR+oUwmzw0CYU9DX+ZGwisO4r/SoA19+LqwipbBzXAKeCdtkMtnymSBQK0pK4=,iv:DhFC752hJuXQCs+GQvzOGsHj8vcqSzlElPSWgZ7oCgA=,tag:xzfqz8nTuhJ1oXQigsp9pg==,type:str]
