apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: ff5e1ac5dabcaaa60e3f3172ebdf861e5c89e2b0
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:xloAH4f057dVndOuVEQDlX2P4TS+yfU0EAv5tBjL,iv:VCYqDYuFU2hdlcDzg/vFlA1E16iWctEOgzoI7zmTjm0=,tag:W/O0RZy1IWz4nfvfE9ifxw==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:7LfhrECIr7IjZ7o4J6WHdpeiMhLONIThqWW6XOMvO4m95/0y/BvmEWxHe/M2wpNPERHrsT8MFucJ92cnGJPltxEknTSkgWoRwBBsSzi62CCUlCKau8A8Ig==,iv:P3AexVrC1OEK5QFTlRSXl/kSdy3E71+3m9g0ek2VHRs=,tag:kQnxfEYrgZ/8afBUllwrqg==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:epxl1ma8qan0UjT7sm4SlUqzDjNYR4lu+CltPjmNAHuUiEUeE3RPMYydXlZlcwn2HoY7KViiiq55OA/f6RdSlnlH0rRRGzZjNXyemAsGPR+0KPiz7iPPOw==,iv:dyHS66Q8DPw0eSwGsRwLk2+DAOBJzp2BaxdvmHTGoP4=,tag:LXluU2IqzGdF7OwE2dzgiQ==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:91cK+j0GS7wjnIoKbbUoT0Q21eNLZ6sXTHzJraS+T6pFok+kqcSschp9HZAbMVfVQSxtaaP3z3xJ,iv:twWAlFBVyw7a/dwMOtVqwm+QNB58kvp/7b5sbTAgysE=,tag:4c8v/pYhXhpBJDqDpbLUog==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:Z7U1Vd5bgerakpfDM0mfkO5gfIJ7V52a7xhfVYUN5eE4EByRXWkuG8d1LUXedx4my2lcu/rYk5vhfixl,iv:0gQdjfnApPHm8cGo015ZDEcqKtrXji51Nzpb3HMtduI=,tag:6EfmWRKvCFqV+sm+ZEMcIg==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:o1lceLJBzeCEMd0toX8E0nzUE2D188E0NKeHsWPMQZVZWro6jAyLq23muvYg5WW9cXy1neFT72OW,iv:j/TcBEp9PtSLQRrzl5OADYyjMXkzD9Q81mtAH+lwOnw=,tag:r9wLwT5O0P3BC15UT2NXTQ==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:CJ74EB25kIEDpzCwiExSTagwowKPQLQp9cne+OSH/02y7JNC3xhpqJymfwFyGxuzJi8Y0/QJnPxWIEf0,iv:nkOv4ub4Hxu0kwd00H3gOibvM+4ATc1hydJhww8u/4A=,tag:IhhTBLg2whmr7h34/QjsLw==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:MHuKnSn5,iv:Huq3FGEmVqcJbETm4DonOZM/kj9gxs5kgbSGnXCNJmg=,tag:5hEc5VvFmFQc53Xzjkz71A==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:kw==,iv:yjpvWjyBLM43NNX7uBNHLMTlInMC2SXRVRjqJqxBrr0=,tag:Yyq49v4rq7/sj3L4UW2TEg==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:MYWlhU50,iv:Cfq7ZToeLTsyfnLxs67yhmneqNESSPRiOyiwLnh8QrU=,tag:8XhbJPGu0pPs9JeglPH8Wg==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:roqVgCI=,iv:e91iz0JnVamMUYrJstLj8bSvZ0QGGnAAvgyLBwQ/PwA=,tag:D0p7UmTzei2qAObep3Aq/g==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:D/IT,iv:fmJogNRn5cBvNG4hiNJGVkS3nA0Dxx4ZEu6s9LXu6bM=,tag:mEDeCSBhaiYILqXIWcj8Ng==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:s1fj5Ic=,iv:XFfrsrNLTcD9SecGr9aVkAP+FeHskHO4rcLF/SWczlg=,tag:yE3mNryD1PB36tH1GB3gqw==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:z90+2PZ8iLDV6Q==,iv:vh/uU5IsMYUjuiALqGnaWol2h6C/2aoYPIJn+PdttTM=,tag:xsyIeFo6miz40IuHgcueEw==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:qT0DXQ==,iv:NVS/3I+G94obW8V0Omcb9s+kVZp3wsN0qzjj0X0cZ64=,tag:95A2Gi+ZEU0X71WxemTZaA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:ImcpyO7bY/M1LA==,iv:x0pTLgiflEm6+IBGY4Idqg9t3GomWoenSx87ozQCIAk=,tag:x+8wR7wbxT1a/W3h9n3JDw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:QkwIqvmfFEG0tfLAXON8I578JQGPsVwmbkuMeMUEwjBtVm/AbIa5yCxLsxdhkqy8Td2aEQODMNKQ+ztPx/7MCwc=,iv:vbOgKGW4xzQfj9dnzI8JtK5u3Fsem9BgXtKcicxOWk4=,tag:mdQlcaa980dg4jIQ0tbVwQ==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:2BeC6yi75bKZPkxBFInWWPMl/Tzr4Bv2YAFI2MsfBp8p,iv:MXkUhSXafbmCqQVDsIaVxdt2Mif+odbjCQmIq2RchL8=,tag:gdRPtF5nmZfxaac3G7ni6Q==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:ev6crNyh97+MqO4bE0XAy5gBoOrC4rl1nlZAjde1eHVHvU/d6RLZJu5rt2DNA4KpXwVOPLKxNvxg9aG/5wbid0W4bedlK8HiJ/HCONX7qu8iz+3sP2orHBSSVv+v5sqmx54QqXhGnt/92zSFJYYfR6uh2uBrztMMrFjxUkwhik4=,iv:5As+86bmn5Hb9XZ5Mf1Xxt9VemteDcmqcYyarW2zfTs=,tag:PMJBzXoEa3/L52w08x7oQA==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:3Y6LWiOPCeydpEfT9CJqQDv6vXMXbjgFdGGUNts4LGxgOrAdvT/eqeI=,iv:OSpKWgKrkNX20Xt7o8544hdvscHN2RwUpnq5YESqafE=,tag:ERp9LOYfppv1Kt8kkzVtNA==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:tfNLidfWAJwC6ZlXWjVcvA3zag==,iv:0rTf8Ypu3iK9RUmITJhwAiNb4geeuQotP1EWOH/dg/A=,tag:0TeiJrSu6olCuJjkWLIpRw==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:UIkIQUJkJzGtNcQnoIKe6tPej4ZNr5DCzVcJIxj8H9ie0toSO6ryYGY=,iv:YNKWEdA2EWBLrahCbl/BfkXrQuoSOLy5trG64e20YmI=,tag:pyMpcLWGrmtN3Ng2ay3dhw==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:wzGNiTadUout5YiAvdrxPi6B,iv:FPX9/VbtHmagdjAWatKtS4q5lBn1I2alKU6Ho+h55w0=,tag:kdMs46QsyVxdUppzb2/u+A==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:Y83XiqfHdi+oUGB5qvWnGlXHb2r5CD4t9TMtUzbBGkwf63gI5iuvLCM=,iv:PqsjQ607/ASyJmdQpAWdB86xAw5vWI2GGYlKsJBWb14=,tag:mxja5OUh1hdQyxsoc9XDQw==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:RmD449g+MOF0vZuig15H7Kr9,iv:xXSPV4/0RexG1e2e3fS2G5dUPYQgkW6eTZgjQoGCVh0=,tag:YNgxQ/943kNsGXy+uha+rA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Z3hSNTNxWTYrWGVNdGd3
            Uy9DZDBBMHNEdUlkbS9yVGdWRGh1WnNoeTF3ClNKTzB0ZzR1bnVjUFo3V3lsQms0
            NXA4WkYwL0xqeU5UVjZqcFRKWEV4dXcKLS0tIFVYK0J3RWJJOG1mbjBQQ28xTjBP
            S1pGNzdJVFM2WGlaVEh0dnNvcTZXUWsKZ8+nETfeYx1dtzWWcYUsO5YkYiU0fVk3
            kSotWnVg5bQqHOax8MFAt0hVwcYfabIOO3bl3Ohhb6OoS0Zcrpym/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRUFacnB4RmVoNTB2cnd3
            cUMzc2JpUWp6cW44S3N4VjdONis2Y2tjblFNClkraVJicUdoZUZqUnFOL0MvdFRm
            aldaN294TW8xb25sTy9LTkRhTk14VHMKLS0tIEFNL0wzZytDMVZKMTlZbzVCMndD
            aFNyNlBLdFRsWGRwVHAyQkJnMjNxT1UKP/wp0jUpkEEDKQF3Ekuqt78exx+1Hv2Z
            1GoaVvZoZouQivHiTiNpWhv7/HEMuxYpi4bYpTjN8C0o+gsV5pWvdQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZmEwTi9xbS8vdmREazZi
            WVZ3UjVISGIvdHpMY2xScXMrMzUrTjFVM2hjCmRBWXF5QmF5Ni9aWmIzaXVENHYw
            aHF0N0NmL0kxa1B0aXgyQm43Z1ZmZE0KLS0tIEhIdThjc0ZaTUY3RmN3NitmNVlx
            cW5YRGd3T3UxU1NUckNSQ2xNcGpzNlUKE+HYqd0WHafCnG6dCzoNpvtXQ/BiXay1
            55g68v+DR/NbOXh3Rekzsv1KvwFLow9KQASpSYW3EBh2NyIF0hfflg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T19:20:09Z"
    mac: ENC[AES256_GCM,data:PlIl9SElkHhJGroOLIa+kaqCsRv7doGdjHIY7GoQAjL2lcud1PILhrG6AKfWrjxlRi8DPp5JQchFv7+v4l5xzLN45d7CLpcVjK1EztpgdkMC82NOH4oHb7gq9mUcHAfDogE7W4lpk2ZaKpb5ar0hQpLezUf9byS+7FwBbjEJA2g=,iv:2dLu2ADyvx4OiN+Sd62eFA05pH9v8u16eBPnN7jf8dI=,tag:Rlr8HYhwLT3CkQqPz6wjSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
