apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    name: valoris-config
    namespace: apps
stringData:
    IMGPROXY_ENDPOINT: ENC[AES256_GCM,data:x/r1dDTFftA+0W1DOZoaWSvDt1CXD7li2d3pDy+M,iv:xbklHlTkYoUPuVFSTJIDPODp6J0xf2ut1nzIMi5rlbk=,tag:oc30qrZP157REpVSh1tOyg==,type:str]
    IMGPROXY_KEY: ENC[AES256_GCM,data:4QlSrBKv8kfVkXbDact0De+RWEOMaIvB5PUIHebgKvQ0iUX286kCCjAkIC8LVI0CXixgmuKtNeNuxpphKn4qoTXyEpkxQQKHwojYOU9Yrt1kTQOFpEaqdw==,iv:tH0VkQktGzvSmLDX/h4nCjEGnjPmCRf1C+oHsb3m49s=,tag:BkLIPpNjIq2/jTc21ePIIg==,type:str]
    IMGPROXY_SALT: ENC[AES256_GCM,data:DZl3mqON/oUdoCULz9rKumJeX3dGvsviNMyxEVZlHNrgsi3GoIeegC5da/m3QpxuSEsU68dk5AMRaaiT414AuREeaUqVcVY7/7/SWD4wJs3j36bktp8doA==,iv:MbNI3eMvW9h4UX21ehI53gBCMiKXFLn+PKjWt5l61W4=,tag:MT3Mv/nOHeMef2PDVxBqaA==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:I/NbluQ0EFh6jbq6mhB75nVs5jkaFMhSYq0lsXI/+ScdICSICLJStYVctzvIEiuLVDxz6pkAqaNa3kpmtB7IbzzaMhCiOqJb0g==,iv:3OKi+gKsQGzEpcmY/bgUHCuDWWGVjQYeHHgbZT7GV1M=,tag:5UpwmMQVNF00XP3dM5Mt+w==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:gVPz9Wd/YpWryUI9Us/I2ST6tkpjicj35GGKKD0Q/7LNc/DbCTNaASC9VBec,iv:beBTpTu1JyTSo8w0jsJBIOAZxSd0YZt0y6zI1cmeLKs=,tag:1pTw2Bvhfm7Hsv3FyN6CCg==,type:str]
    LLM_FALLBACK_API_KEY: ENC[AES256_GCM,data:S0+zHvcgyktlIbBx2BDDPYYD+PEotwqRaUD4izKEjhRLn2yWSA8HnGOzT0i4c0nRvk8Pz7GxXzxlOWTcA2mrxDvC719ANdZEmA==,iv:yOi6Mg+VPf6OJgj0ztmAC4zqglz15MYOtWudfHnov2A=,tag:p0LxPAaX5sZ9qbHmK6ecBQ==,type:str]
    LLM_FALLBACK_BASE_URL: ENC[AES256_GCM,data:segLOBk+N/SLdFWKbN9jhLoBoGCW4h8CQY8YNxK4nU2mIRwr6qmJYICYoin7,iv:DQwCr6GiwLfw5EMwukOH08jOQE7j1qO5a7y8VGTemdE=,tag:WWobAquj9d9i88Ss+Aeyyg==,type:str]
    LLM_FALLBACK_MODEL: ENC[AES256_GCM,data:cLsJT/u9wPd8SML/PSiBoUWFfUXbVMVYxTPHFJ1Fc0lf,iv:GzpRzgm2J48SpDbuhThnOgBXJyWf7v4FRjmdAnfgY0M=,tag:xgLaM+FKHNO4rsT/7tasog==,type:str]
    LLM_MAX_RETRIES: ENC[AES256_GCM,data:Qw==,iv:VorkVHTd5sT2safKZ1v0hQv0qJw6mybmdeQ03RyMrIQ=,tag:3H0X69PZM1VSI5EQWDpmKg==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:OUW5g1wrYdjz4b9MkVwaJLscDx66VqomqhK/bzJIoVYD9vTFR3A=,iv:3bV8s5cjnyzAR6V2hJz69XIwvNvOTeh6yaP4r2uXyX4=,tag:WR6Jp7U+mfc87j4bGqGeDw==,type:str]
    LLM_PROVIDER: ENC[AES256_GCM,data:UpKpDe+0QxAFvw==,iv:riwdj/B5zc2l9C0DIo+DVV3hgHiCeQ5X6c/0U0HW11Q=,tag:0tfoNcMNME+fQA411ysJ/A==,type:str]
    LLM_TIMEOUT_SECONDS: ENC[AES256_GCM,data:fPON,iv:gT+2VDv8gTqQ74ahhqxSE+OLeKZnJZXqYCJz/4u3sSA=,tag:S5JkZOLX5J4s5IQcJQHr5w==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:dQAl3ec=,iv:iT6V1wCGGB4feGNEV0vee9QiLlIkygRQjO8tjpFL7u4=,tag:icRnWosYC6KKfYuebNN4NA==,type:str]
    RAILS_ENV: ENC[AES256_GCM,data:8rX+pJrx4ORiyw==,iv:sxacsIv5BBZfSMgF5bIb0dnGWNo4HRgIM3x9vb6ZY/w=,tag:3qKTzXvcmu0nV5pqU5Zgog==,type:str]
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:wVkngA==,iv:YFVWy3GVuYgkUvCzeNe6Mzy/Xi4cvObLo46rxDPW9nQ=,tag:tRYDrJre4wMzRyZ62XBeWA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:24AYC7KSZDtgeA==,iv:bGS4PTVgVqMPNuI/kjfxn8otE1CAWoVsMYYGvNKwK3c=,tag:AK8XsfOSjjtAQZIOx4gyjQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:k8qryLpT2OB4dX2g47aB6YXMN6Igl+LLGn1dWJkd/ZC26lvOJAfcho2etjTOHmjuvgNi5iJZpZhz7PAEUNng7F4=,iv:bFF4l7jNS7LY7PlJaI1/pvtMZlcgezGRRZQldCRO9Po=,tag:yjbzl0D+5hU2+l53rMrZdw==,type:str]
    S3_PUBLIC_ENDPOINT: ENC[AES256_GCM,data:WtY0u63TDpsZGEZscJwlvipxcMbNm6VR7E4KoH0VmZt9,iv:I8ymMJs+sGKt+mVA1WROuKtDpl1Z/pWOQkvg7ZLD9YM=,tag:gDz7KC9nTtoGBGSi0BoqQQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:b+rIdUVZvKDX6Lrz+dU9WSvmVNx62eKLJcNSDOnc5T0sxmRgt5Tcbu7+6LMO2N9yXjMJXbVLHHctSIIYKfMsvb1Ae4LyqyZdJCKMt1ZOVz4eik1l9pdvqkuUm0zfA8tRfeb7qKP3QOpg7P4DvDUzy6Sha6R6VDEk+j1cLScYLZs=,iv:K1I/9342bysrPPgu+FC6MGhdwkrrJu4hM5WvNuWh0Cw=,tag:LEYJGi7m7QEiu2CH8qKzFQ==,type:str]
    VALORIS_DATABASE_HOST: ENC[AES256_GCM,data:vn+QitEHr2Hk6XPqOkleig==,iv:6XgZGLvKCj+qQc11YvXulOa1BHgf/2X614j8kvdgD2I=,tag:ThsInMYBsWki1AJOOXv0Tg==,type:str]
    VALORIS_DATABASE_PASSWORD: ENC[AES256_GCM,data:ZjjhizTMFpDRpcpXqy3f+mCdWg==,iv:UEfMJLiXjU0VGwz5qu1Nk4tCRnTKgmo9hiipOrGsguM=,tag:cx5pFtmfuyNkGa9Zdw3Oxw==,type:str]
    VALORIS_JOBS_UI_PASSWORD: ENC[AES256_GCM,data:KRge0v383YH+6MJSgt7Osed8aevPFzifFkzQZuDDg2/c75iWGoAML2c=,iv:ftnkLZKYatRfoZr9anki4jXBy31Ad9V5OHn3CYHA81c=,tag:rGIE5F7ZSNviurfhC/qGfw==,type:str]
    VALORIS_JOBS_UI_USERNAME: ENC[AES256_GCM,data:QYMz/HY3kOJa3nk2TTDcbtjH,iv:hVLmjGPzdIFia9RrdmO4UqazKKQJpY+ERwuNvTBeHFc=,tag:dUiMSJtzdssbwseJnp2uKg==,type:str]
    VALORIS_RES_BROWSER_PASSWORD: ENC[AES256_GCM,data:V6Ew6mzDjr8/kkYVHRFF3DpKPpmAdb39MzDSm5MXtxGzLBROBV5NS/M=,iv:AYXQJMn02y+Ng87a66mocfszRBGPpZG8xSdRE9epjbk=,tag:qOzqB8b1je27nLBO9s5HjQ==,type:str]
    VALORIS_RES_BROWSER_USERNAME: ENC[AES256_GCM,data:NzJ1PRrDTA0WUNkOdPRtXJ/f,iv:MsF4X4Y+Au0uzH+aBcpFYrqn4P8e90ad0OqYyaApuwE=,tag:01dTxxCO7QAm4WNBe3OS0A==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWWEvaFVIU2ZScjBaUlVu
            MVJxUTlFREIxYlNNVWpQQVRUakRzWW8zSDFFClBHQXlVM0RPM0tnTjlaZlFRMTB1
            VUZJT2ZJVERGVGN4MldVZ054czNDQjQKLS0tIForS0dQZFVnaDNWWXIyTmpmRTh2
            eHVlV3ptQUxEeEhrZkd6NW9PeHFUdncK27k+veKNDqve4K/UA7LweXH1ogB8sArz
            Z5CRwQs9b/TC+GPMshev0bjRsvoyJGtlL2JJnoS1+m1+t5/3nykpsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L2wvVWlaNGJRSTJzMEE3
            OWhiTFB4UmNwbWJGRk9GeGllTUdBNllLY2lBCnpLbkwyTWV3d2ZOMUdnaGJXRG1D
            djZsQmgwNVZEK1lSTnFhNVp2UXVFeTQKLS0tIEtqdXB1WlR4a1FkUWFYb3VxaWxa
            YjNidnBlQWRWR3pXYzNnd3NPM2Z6SWsKzMxHrgkyrVIXu9xZuHWWgzZR64yrhhTF
            BzMaJnTRk+bCNxcrjI5CorJGwTUnFwtnPFaWz41BRdtdinYcWX23sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZOXFtdU1KWDNFS29XVzhT
            YWVmcTY4NHlQL1paVVNkNVVlQ1drUEZqYkZNCkREZWhOYUYvOTFnOThORTNMWFM3
            RXlrS1JUeUVVeG1JYnBGK1p3cGVWeVUKLS0tIEpqdkpZTTNqVmxPTGo5Y1dNV3lh
            RUJGUW9NWjA4Nm9ybWpIUzAvK2J2MDAKmaBZFAea719c213EfO5rYCJmRvhOYKRT
            80GQBbFhipq/XGzLsY+lQLJ2t+GlRiawLBaje3SIQPzTFK94U7IroA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T10:49:34Z"
    mac: ENC[AES256_GCM,data:JRZ6x4TaJCVKvgn/FZUdlcBmyvIDReapAPkWtJtcxCSNRQSpVN1b1gOwkVbb5c6FlVwniIymmZW0NeFP0r8H8C0O4xg3Uv/wp3BW+irR5lXMHF4kkSDkEWzPFinobXGc2X+O/vc5xQ3x5r4PGtCGN6grEGjHqeo5t6ue+PpLXvA=,iv:Vsx36chkz/mbVoEyQml7LAI/Y0d5itX9aJypXAfWGnY=,tag:HP6BbHbA5FxPKrXI1W1L4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
