apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: fa2c0506e90f93402c314123a4895641e2ca8a57
    name: velox-config
    namespace: apps
stringData:
    ALIBABA_TOKEN_PLAN_API_KEY: ENC[AES256_GCM,data:o8BP4sZuBOthngySHTRiSIqDogtTrnHFUoq5mFGNdQVXTa9VBSMu0ZZyDNz67aHeq1wbohBNiMU6pf2ySJGYB25IrIp6W08riBzyNC64lYFEP/HwSCWFzkiMjmgRYU+Z58BkhaxCcn6YpyGzu0ilHa0n,iv:iUcpBNoJu53tZizVbwpKM16P+wUEzglLjXvmTHyuNQA=,tag:UKEryALgGpy3cQjXeh0aLw==,type:str]
    ANTIGRAVITY_CLIENT_SECRET: ENC[AES256_GCM,data:wHO+eCsINhauw380NmNsliz5LAletKwoEFYbWEKX3V7k8q8=,iv:A9lU4EV/8XGekLU+JUONqjz+vs5m0o5/g+QQLRpirs8=,tag:9Z5Ib5Hzkrqs3iU1w++Haw==,type:str]
    BAZAARLINK_API_KEY: ENC[AES256_GCM,data:oEB3eIz5DPLERElQWW+DUG1VCm0EnTwh0xp2y9MNmmjJAHWkMzqqj4TJ3nxrFYGFhwusOaY5,iv:XtpzSu24ae9lLnvRiZrhQdA9zmJ8hA7aALGBfVVVhtM=,tag:w286UooazPfmK55wPSxPXA==,type:str]
    CEREBRAS_API_KEY: ENC[AES256_GCM,data:HDjLgUfmLLoqmKYsa2QaojhJwdj8LHjiiCPdt+/LTnoS+qkuH6o8875I95HI0kWJamSVkw==,iv:HIMAt+w6shpKoAcLk+o/2XGma9AH++yL/91E8QFRKF8=,tag:llcNp1qTbIs6u44Dqy8IWA==,type:str]
    GLM_API_KEY: ENC[AES256_GCM,data:Obh30tmhP6vtDVSm3cLsQJb8nti/i/SfO4r10SyJGkhH8VnocwZ6dajlUYDN8eIxFg==,iv:qaTf708f+R0/RhWfjzyAB2Z3XpdWBa4255jWoM5SUq0=,tag:7X51gJj18xbQEmdu3QYm/Q==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:j7pWAAw6m9BH3DdxlCBIRepXkUkSuQXqnwjoJ5bBpIEx9CVSllG6XzraNRaZ4kVeoGPfnu9Eas30Pb6irv9uqnDSxJjiGQaK,iv:u3p/PSLuInxDdja701X0BggaGz6Rvy8CkOOvxhs0b8A=,tag:ch3P3sYANseF99ileu6tbQ==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:NuhW2DzrBQOLCrgsqYia8CXsuaF/sx+Bb4XAtBk2PXc=,iv:ytXaeDF0xtNPuprSkLLMVswYDqJeEQHp7JeUDnBLPoI=,tag:5wQqaqhb/YPfgeEJzxCwUw==,type:str]
    NANOGPT_API_KEY: ENC[AES256_GCM,data:hxov8staMyqil1V7+I3gG3PpmTGoR1/4hwfsz3chgZ2WgNOH8tnm+tuXNLA=,iv:ufIY+R6XDDVA4aQ8KXk2rn4lKBmx5TcuAaKVPY0DF+k=,tag:ryMpl7ViNXp8045WN+BfVg==,type:str]
    NEURALWATT_API_KEY: ENC[AES256_GCM,data:wmsHrDT1zsZiSz/OZ4zX+KkqxXQ2qCvNIrr9Z8doSOWGKmrezKaD0Iuy9yjVhFsMZCqRNK3HnxU8bWqgCLHL+TXKow==,iv:QI0eZmu+yRbGs1zSDy+ZfZBTpidX3RYyFCB8mICZOFE=,tag:8JXZ7EcZnR2fmuNztuaimA==,type:str]
    NVIDIA_API_KEY: ENC[AES256_GCM,data:490TrKAXB8n/Lb+yj7wEkcxHERuQGb4SM82Y6G3wbXVNt7mc+rWutamjzNFvSdB+PQEMwv2CjRDllAbSKsjq+CKIiIB2vg==,iv:mPgCKZUnXk99wiNcLgEFqkDc3xRYjjg5JpVHSo9SZvs=,tag:71HVcwfhzkaTUd2Mj7B/Hw==,type:str]
    OPENCODE_GO_API_KEY: ENC[AES256_GCM,data:BBZA/Y5TdrT+EjtyTH8IKe1dsUj++eydAc5pSNSF11jlaiz2y/A/DakNCYg3uS1JGQvzuIEkOZxpZrMMSCmb9S2Ktg==,iv:U7CR0zY7OQ9NlS6REDOCH5HnIGGGtuAKG1xPhZqcwrQ=,tag:y4vuUH3o8OGXFj6fGQeWqg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:XFbRUzhMlDLzyJ8S2HWug5i8vKEZl/ozL+EocihDiVRlL1PXFa5gPyQZGyTF50q6f0M8zNxJgLF+tS/Ewx3pPuIV5ZBKEhI8sQ==,iv:yWHRMcP+LAsxTqF1qyPWPGSIqgwSYox8rKsSnGGESyU=,tag:5R0q0455xX2HPuerfsaUHg==,type:str]
    PUTER_API_KEY: ENC[AES256_GCM,data:XR4RjB+gD1Wu8fugML6/g7XDMJuvVfte1OyblzfjGK1vIUZ6DOi9ejNHkJXcdjXVuu9ib5VoI9U93HG1fbwb4vhSa/Nni/jeDoPAAyybsv3+RopZrsMz36Fln1+SF9094peSiO30bJXVz/KhNl0pyQBlVf5M6eTWJxj5FEA7lFftkZQpcd+2p/6V40s30sTQ8cGm7001nZDM6KpdkVqANDa6u0/q4i4hx3k2ZwQvcbMyiZ/BQwS55Ag6iXjkFzbP5TzhreN+SGSQQQs2K/9yc/miDc1JgV1THzeLhUhaD0p9ruZwFJXpfhuIXNNH2wp1aR4reZi1U9pD7AHJCebpnpo3PxmHO4jDyS8xspAekHsGv0zMTS5rww+fddC7YUxI824py73wHRKTCR+2GbeuVZ0lxr+KcQlAk3U+6iX6Gqb4u2cqtMfCX7i9Mibj7cXsBYNBfeofWSoXsBfnjRv8NjlWaQY2Lr3rA+54,iv:mkS2vgThF+0Qu61WJ+s3yCOClZkzBLv9PEB68s+ysz4=,tag:hYTpqntPp0sAmBIvgAj1Xg==,type:str]
    VELOX_API_KEYS: ENC[AES256_GCM,data:Ji4dFrouy1IvmZ9fN5/zsU9iyToPmmuFdSMykSdCpPsdl4l9l9Xl6gNLX4HVFmk6RvbSov2KBlE0,iv:RyItsQIAj/B5RO5ISiyiHDRGSpP7PtlHxNT8DoUuAH0=,tag:wtm5ozOCkCQgS34VjNOj2Q==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:gHlWNE/UIdNRJjcOyjnqpH2TTKcaBieMriQ+uvPobwhRcxx9laXGq/iR4pUGDA==,iv:rT/fmFvbWNIYer0Ye9Qyfg8NNjojAI1Z2cwdaaYOFDk=,tag:itVLW4EubOG0JwdKMjxMBw==,type:str]
    XIAOMI_MIMO_API_KEY: ENC[AES256_GCM,data:g0xw3scr9RYZdcUNO3QRTSHJ4TNFkCMPapsOfpWA8Rfzinw7/j7rRwwEkuvULUkKDV/a,iv:2hfeCznG0zRHtFrOpzsPZBNVYGJP1zTS6Zy5ZfCIO0c=,tag:HOwEiK+Pog7GSF/ZomDWoQ==,type:str]
    YOLOAUTO_API_KEY: ENC[AES256_GCM,data:5qj9LjAf1d7gWyleCO1TFyKAwJ1REU3s7nu1Y4XbBt8UMxuF11xaCuGENwCLqfeu,iv:DW13PrNGg75k2R58aE9hXUF4C7PXROkgcfU3A9xYJ3s=,tag:YOrms9TiYmQTPaS9AioR5w==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSGYxZ1lOTlhZbnF0QlVj
            RXVxb1phWEVNRk1PWnlTVEp0NzArM2tSNWxFCkhoSW9UZlpkWHJZVkZkeERObHdi
            U0MyV0lHaE1mbzZRN1g5VEZNMXl2MjAKLS0tIEdxMDMvWjE1RGtOalUwVHVjaUFW
            RFRxcWl3RVF6b0VPNnE0cjNhSkgreUEKEBZRYwVS7wmE5VtIKuRCr0aK0NigWnan
            rBAbiGPjgHWAd8ZD9OvX1wTSMTJGrvlAbXc7t4wQ96d3uHUDljFL9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZjNsM0RobE9yUEZkb0tq
            Mld5Z2p5c1RXdytxZVU0SS9EV01xbXVrWlVJCnV2b1dacmQvaGlaK3cySUxSS1hp
            bmtaTDdtc2RDb0NxaGo4WXVLTnB2ZHMKLS0tIHZXRzQ3OVVNZGRFQlJrZXZla0o4
            REd1WkxxbWJiTEM0bDl4aWdTNkpQZVUKGefZE+8bpMkNCm0bjsT+jfwVRsu27Aya
            Ou1+utllbQV4X/3U1XmUr9WenkQDxZIRbOEJnEkhak5Idox4gI6URQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bnM5OUdlZitUQkxxSlpP
            YmRsZFlTU2JSRVhkZEN2SUpCd3pEcElLaEVzCjdCMHROZFRRdkhRUFhCMFlwMkV4
            NmJkZmRPRzhvMUZBN21pRkhHR1hiejQKLS0tIHNINUVKODl5dFdPalBCRzFhSXlI
            ZmlkbndaVUxSYU1jbEhnNWxCYmNtN2MKkdvf6ZEac6qFYHNJyRoP/eRZh40MOU3A
            NuZA7/3PQC35u1c/M481fJeYE0TjuMi4whJMttCd078pdE51+WIViA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T16:04:27Z"
    mac: ENC[AES256_GCM,data:g5VcFeNYgYspfoc/rsIRTn5Ex0F7GLDf4XqZhzMYYOvt0rqv+nbgzd14nskpAmeR9TeGWDoj/H4FuFtp6Z9N2qAs1WKKtIHLK+fR0cOw3clQUxprun+fSZTRkxRHCWVCTPAYHWlBWdih+da2YU0mm375Yv/0H40phBeirhclZpc=,iv:lijGnjFVBI3WWNVTsOJcIMqWLEVrFft2I35Q+SusW7E=,tag:9RN5RpuyLI19eXjJbsYcxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
