apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubenix/k8s-version: "1.32"
        kubenix/project-name: ze-homelab
    labels:
        kubenix/hash: 2a34ff655cf45249f3fdfa58e0d738886de71695
    name: velox-config
    namespace: apps
stringData:
    ALIBABA_TOKEN_PLAN_API_KEY: ENC[AES256_GCM,data:ae/IpBlLv9+k2up6HesxufucYucImZBQVxIHfvAPbj0tvF5eIEf0kub3Wa65rE6+HDjapYNBljwCHOUF0gULM+zZ/Crl1bYboERSAsabCaLEee5ftBLtiIGbZW0rLYam8B66QjiZ4WyOcYwefae1N0G+,iv:42eWcZiTAgrwQ5itLXRQfLUehyI8j83NQwTBUYuVnXs=,tag:FCAydIUJNoEkaJZFBuDSUg==,type:str]
    ANTIGRAVITY_CLIENT_SECRET: ENC[AES256_GCM,data:CaRZKGdncbS2M8jjsRH3e8I7DsFTtsLA4K2c1gYgU+jVO6Y=,iv:4xpGY/m6T7dwK8TCvQ4eUC0MWoBOMu2RVm7sjR52Il4=,tag:KGSEi5C+hZxdWMaVhW59NQ==,type:str]
    BAZAARLINK_API_KEY: ENC[AES256_GCM,data:PjPC7Vs+vc6AofbyyNRSDqPYVdN7lUv9uH/FfECI1BtKJw4dJCCn6cdbNKrEg8XkWH1mbbD1,iv:GCNFkeBNTFHLx4WwcPa4olhnX4MjG89R5bySuJk26wM=,tag:hBIlps4Uo69ZifNhPdq6MA==,type:str]
    CEREBRAS_API_KEY: ENC[AES256_GCM,data:uGEK27XRU1v/NOlVPF4OtmVI0ovHRv9s3Vrt7aIExz7WYD3uML8lV99OhEmrYPrdzWsWEw==,iv:JaVXABpXjHQvKU8G8Auh2D4pggbQjuwZbL8CAQYcY8A=,tag:VtGFgsYOtuBj6/E7CBD7Vw==,type:str]
    EXA_API_KEY: ENC[AES256_GCM,data:yi74ZzWXfpVQI9BzPTKX/NxjZ5sC1eFYnqEHtBM38Va4PqSW,iv:KrB5o29Sh4NzrKLyHVpGzmt9fjDvwMvb9U/mav8C+u4=,tag:UfeQ/xeLBRS71CjL9WcPVQ==,type:str]
    FIRECRAWL_API_KEY: ENC[AES256_GCM,data:RnKU1fc83SwnfR0GsYJs2/2WhvIAiHkjqMjofhTBHwmnvp0=,iv:S0LZnTHYui1rltN4Nk2+tSrU4a+tBnSk3pe3y4lwYS4=,tag:4upPr4rh26U5FQl8FIl8eA==,type:str]
    GLM_API_KEY: ENC[AES256_GCM,data:dWc9tp+KH4DEtJLaZZhWlibbrOO+1qetXKOQ3imfwFZqNyfW+cEiGKn7gdztyshE0w==,iv:xgtaxnvXQBcXV0mTke2njc7MA0OP+nUlBIjJIl+vYyY=,tag:JHjZvf6jFm79LVHhiFi9tQ==,type:str]
    JINA_API_KEY: ENC[AES256_GCM,data:obktkjV3UmAgBpjDlgxE56FbismqXVLoiOL9pLID8/TKwTgXH98u5/HJF3V6lvr9SSlVQS/pEPklKEL4fYc+97k=,iv:D2bQP06+/Uqd0GNJMrnRpwibDCtQWiDEBSgYXtfq1eM=,tag:fNY5qGJ0cR9W4/Tx6gn55g==,type:str]
    KIMI_API_KEY: ENC[AES256_GCM,data:llQadmoxDwZEQ/pxgxsOtOvv3Fw46avS/GEThxD667v7sxXkWI5nzIU7BMLCPo/jWjUxoGkgIQE3OY7RKHt78yIvar8Q+AvU,iv:sqOyo1wiqCSlTWjvu3RunYNu5OBFHnq79acYUFSZ250=,tag:a7RYLrybsMMuLQ8puokSrg==,type:str]
    MISTRAL_API_KEY: ENC[AES256_GCM,data:tncJI6Ievo98HrOh2aGHZgi7+K+kE9cAK762+NrvByQ=,iv:d0dF0S2Pi1/Os3nXeRZ3L490tTQrtv25Ked+OKZnDwk=,tag:8U3WZvErryk5cd4VWD1+GQ==,type:str]
    NANOGPT_API_KEY: ENC[AES256_GCM,data:9Ii/1cFfnVsFCllKBXQX6Du98X+LecQkDNb7QJEDCrO285mUHPIVEOZwj8A=,iv:Z4MI6Kl/vh+m/hmw6agd4ciDokjcMQT0RMPjVSzcIcc=,tag:g+kTsn2PrPjHgIWN73vdLA==,type:str]
    NEURALWATT_API_KEY: ENC[AES256_GCM,data:T5G3cngZFrjXXfRiFtyyfKPpsxeMqsd327qqegVzVlDvjvCfzn9ZADkO9XXzLpeWgG+1wqPW/zSxXQHZPiDhiHj2lg==,iv:8UfkxCWFihAH34w3gogOcGwpDf+doGV5v7tNgl0HKbI=,tag:v8G8f24I6pspS7/s+G0mmw==,type:str]
    NVIDIA_API_KEY: ENC[AES256_GCM,data:6FBU6BgOFK5d+BbTKTABci2vFKtOQTtSlJ/R3NctEK3/20+sgMTnMWLp6Vc0l+fn47xqruHimwnwlTn+50wlpkE6l94cFQ==,iv:EBNnqZ/gqIFq1owJkLutcgYT//so8l6xBEFnVt1QrDs=,tag:j2dMsKHmTs6kuB0badM3pg==,type:str]
    OPENCODE_GO_API_KEY: ENC[AES256_GCM,data:JZHO8/2vx14TEIsLCWDwxz90+rwgKK7hE6m0LFH4jdYed1d4bEPssBccsehcL0jn/72nKL5PNHyxOhQdnHCnx8WgKA==,iv:3VQJUIvF0vK6bwSIDcMu8TAWRfHmDaM9OVrfKF8GxzI=,tag:fTZkQVe4MdK4wYF618dMmw==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:saJcr8sW6BAO2TwIe5JmwAP0HNhbZrrCROrhC4pNwL64rqGU9nZ20fsoavkcENoJrVRs024TEghIvZgBT+TlhOxKMmLGtGUzgA==,iv:xKrQEfqI1CgJdkdKMNUPvg47/fDZAQ+6MVeTDtCcmUE=,tag:LHdniw7d5A5VQh/307obDg==,type:str]
    PGS_GROVE_API_KEY: ENC[AES256_GCM,data:GZ27Z35t136tG1977sJXKHCPasib8PZElLZTtHS9YgUwjnvI4eABMED0LXlD60u04rq+Kg8k3zo709IyUS1I3AC47vcDCfrDgCs=,iv:lemi868QExfShqreSNRpKaiak+RbkFXTItIbiyZ7YsM=,tag:jDbcp0QR4ZTTI/xo/QZoxg==,type:str]
    PUTER_API_KEY: ENC[AES256_GCM,data:nsy7A5yO9Ub2wdOrWNd2M3vSCNPNDWtJuvIq9P08M5QsUFPtngb0g0lY8lAeDNW80oXB0e2v+3JI0aC7qGtTmtO4WjGOWwPhdgd6XgMfl/YU3zCHXI5WbPglT74kPpmgkPn49HZqonrumRzSOhB9svDEdj48Sdo/xejqvZGGFnhEXIsNQHShf8htSqW/GLxA7dGPwVY0U0yv0WEW/7rGlr1xZpWXIc5gnWyBplTDvqFgpmNdhpROsg8qNBC6eX7oiqkKsQhyamKHD6ZNN+ugmY3ft+c7AWYwLpxvPDBUDVgGvTkhnJlt/xkqvppXja2mYENyf9YUrhdcPtF+B1lcex7EJWdu2ZW+ZQ9ftNkMAuwXPDco0hwyQZs1Zk/6ZsZrvxGYZR1Kb3ML5RdnTSEmAeyD8gl6zeYewdTJh188W8SEs6Ck+YjDRRVzqLYJ2iSYPKJGF/zOu1Yr2gwYWls3TTJNQhGyBres9E4/,iv:zXSbwjeTYOnS5uSxcxAq+JICif3CmzMZj2CrXX0Q1eM=,tag:O1VFO2W4soJpOhtBa4YcMg==,type:str]
    SPEECHIFY_API_KEY: ENC[AES256_GCM,data:MyYR2TDKgG36hu4CzLoAhoOKUbPh9sihC7gRBDsnifMqEDUPjbBsfm6p19KN/A==,iv:3hKcq3rddKbDa9N6SSPtA0GwwsQ3yYj2Eoed2RpGW0Y=,tag:/MpJ3Z7tD34eCD8hm9l1BQ==,type:str]
    VELOX_API_KEYS: ENC[AES256_GCM,data:5ZYRSQ4+LrwjyJfR7vcPQoLAr7IE6rFv7czStw6/B4dwL59qyo+rWgsMY7cwh9OJf/ggmcbIdM96,iv:TL8SjPdd/+VJTXcR1gvcPXG9M5IvIwaThPTeiOOFPlo=,tag:5lTDtusQR1neMh7YRrFRHg==,type:str]
    VOYAGE_API_KEY: ENC[AES256_GCM,data:fuu6dlrJV/njx5f4bPidxXZRq2IgSPuL8ASCWuLvMsl+FLz0D1ie3qXeIPaFCA==,iv:g/VWX+MKqdzSMPRaW5aIqCw7ag2EroYWyL6w7L31Tfg=,tag:hDBkIbAdJRVCfur+n6YxDg==,type:str]
    XIAOMI_MIMO_API_KEY: ENC[AES256_GCM,data:TG7e9P0tv6CMMpolnw15WTLUIEC3WCAccDlzXPHi6fEFqaqV5jpRCVPZdMc0jjZlTljg,iv:i4hUeYPSunMBkpi66ZlY5kwkWLfpbvP4pjoWJmTVfB4=,tag:BPsDa/OKXYriKDKSX+yyzQ==,type:str]
    YOLOAUTO_API_KEY: ENC[AES256_GCM,data:NvXqblpMd6JoSvJIoVo9ppRESXtE7IAw8esV8c+gNhJFjRXIY05KtY0NkYF90g49,iv:YS+YP/2C7ki/QSEJi1sLUneBt6Ttb/zMehMKW5lfqlo=,tag:13O5l0XHGrlIfjfbSlOQjA==,type:str]
sops:
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvaC9QaUNJTHE0L3oycjJs
            ZVBlUHpZMmNvZXJHdTVTZi9UbDNONlVyNW5vCmJUazNCNnVLb0ZRUGd1SXc3N21j
            RmdhSk5pVE5YVkdHb1lCQzkyWDhyQ2sKLS0tIEdEcm5qb3ZrLzBHOXBISitmK3JD
            MWYwbUJENjh0MW5GTnJrRE1lYndiTlEKIfBUF8EReSMuafc8xzn1BU64SLYW6pXK
            m5qihOpiGS6titgozG7S8ORSptQifpHe9eMa1R5BSMsMDSSw5emWHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZEwzNkEweG1xWWhZTTkx
            cXpQQkc5cE8vc2h2ckkvNE1NM2tONThuWWdvCktGZCs3WG53N1FaNXRmUHIyK0U5
            QWNtME5HMDJiU0hkMkpFa2p1bUJTR0kKLS0tIEovdlkyd3JhVUpCQjFKZGRRTDE2
            cG4xNVhxc1I1eEpSNi9IWUQ3clFzN28K9h3DAcEgrU8dS4o7s8BVps+4WrfXkDnl
            9llOEH66SkEM/QS5uOHVJjvxkuSbkR/oWHlL4PttRdGAhIAuRr8ODA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaU9KcjFjTHpESXhHN1FT
            N2c3T21hcHYyVUJvaVJMRG1OUVg3aVpEQ25VCm9pd21mSTRYOWdsbmJPM1VSb09J
            Qjk3dmdBdWYvZkZxeVVObHYyNXl4N2cKLS0tIDFvT29HcmxaQk91NTdKT0tqakdS
            cGJTTmJsSy9WVTJCWnRLRGxPMjhmNkEKlK4zyMzAPfJlJZEsZycN2uZYgZRkUWm6
            ZfTsp1nvDci2HChCVRNbbLWpF8vIIgV6VI6ftGlB1X/cv1adGeBEkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-03T15:18:18Z"
    mac: ENC[AES256_GCM,data:SSU/v2QAekIv6fTm5qIviuC4o9U3CXMRbDBcupiVVwGUnYFbvaAGU48GvPvWVT3lRfjhYLYjnY6xepV6gRq2VEZmHrRClliwn+kMEgU6qvz6jzPvOLD05wDgrwFoRfz/dVXVY9IhHGWzJxHHNSuM3KTm7idwaqtyixf3X8TcrRU=,iv:6QvUNBE/2d5PCkSXlYFoSr4f48lm0RwPIHiBAa3+TTw=,tag:H5RixldZAwIP1MwZFlaqvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
