apiVersion: ENC[AES256_GCM,data:zco=,iv:lwKfoAJKF/YvRVjs0fZoSzvMg5fxf6uXOYy+K5EsD2o=,tag:GZuLMLLviOoOAUSxJkMyDg==,type:str]
kind: ENC[AES256_GCM,data:jhbc7Fnv,iv:nWEiFFMlJ1TniDXfoeAxYEVcl69iA175b6Dzlo7ZoDA=,tag:g7QE73xWDSY3TjaYXkHD7Q==,type:str]
type: ENC[AES256_GCM,data:X8/ffFwR,iv:mrmUBBNqYOD3WvIlNyjRXWMJHWkNf/pI0rE5fITC8tU=,tag:XSjYbx89LwDqWxNGW3HVrA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bB/E8aXXmZk0sx57PNvFDpOr,iv:pLhlfOnApGhh6jEIJnojzrCvglxdZCjFQ3FkicZE8HM=,tag:WzmxJAFzkb2s162b4p2lkw==,type:str]
    namespace: ENC[AES256_GCM,data:IafL5Xk0ALdalg==,iv:k8YZvAWo4jwVjxCPdN31MTd+O1ToqcD4xUAhvSOzliw=,tag:B3IBqkASAX9znfz8cQbjDg==,type:str]
data:
    VPN_TYPE: ENC[AES256_GCM,data:Wy0Sl0BLTew7,iv:8oBzEepZuGyRm818xtdWIyCZiFVZ5ITGt0hYSyBpKiY=,tag:E+wDEwc/UIciZh49UZc+/Q==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:wwHjwBEQcA==,iv:R/kKzPot7gT3J7BcQO7uh5cwQUkSwetAcpXGYMD3bwI=,tag:vtO4QIjANESOYsb+3LF6yw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:9CAYrSkdPqbktVDsi9Xy0a49+IegZ3MhOblG0gZ9bVFPlQNxS7codkZUl50=,iv:vJrZccNilMal33fh1jiI7VQRtAdYWYSawu3m4ObO29w=,tag:kuOEkKxhX2fjg9fCFf2tkA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:SU9043DKgD1RAHs=,iv:bP8g52hPf0tFHF1UlWvn37DblaQqHCYAHECXHXeZSaE=,tag:8L6DbnXvfBE07bYrYfxbfA==,type:str]
    QBT_USERNAME: ENC[AES256_GCM,data:g56EihZ0+4TY/w==,iv:qxiCixtBO+Zsjkk6KF5atd873sldK3fzgWLf2u8TTNg=,tag:aZ23QXwznaaXGiZaL2afZg==,type:str]
    QBT_PASSWORD: ENC[AES256_GCM,data:mzhZLcwGK/y5NA==,iv:Ua5irpNw1de7fULGqx7+VPXi2fIhddNb34VdLGgiHnw=,tag:Ww2TcrjNyKrnUY06H2s3bA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlliVlJ0WTl6eG4yWFNH
            UUtITnlNTG9PRlpHMEsxeGQrZnExdVlYRGhJClVqYlJuVzJ3VjVvOG5ZQUdrYXVm
            ZEdjTE5Ma1JjN3VNSVlIUk5JVkpPQ2MKLS0tIFA5VkJhT0ZNcFFUUW9UTklEWVhW
            ZUJxVG9haXIwa2REMFdOcURnRzhobDAKtsDRGI7Tk6upKFimU5Dks+EThkD8vNEU
            7wDV0x7MpC8EGlppHramTu2sKFpzC5NEx4INAvauTkUAI6m9RDIEQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-04T19:07:16Z"
    mac: ENC[AES256_GCM,data:aJKQPkrgPTKORRRY8aJqfqEstN6gY6oO+kjDiTlEtVNJg4LbV6r1M8TE/l7SA+xzwCOidpmfQIvd6GjfNIsCWY8Ju5CpGB4lQSdis2k+yVQYFXTHXEXoEMPVtVG0NMxqkJfN9rX52CErRF5mrc0++8M00QQPie46FdYb5eK7dYc=,iv:uaUp+FTyoiAhBL/azNuvmNuFNmz1JumFadtLox+CnqA=,tag:L+89MVmSN+xhvZiYMGil8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
