releases:
  - name: metallb
    namespace: "{{ .Values.namespaces.metallb }}"
    chart: metallb/metallb
    version: {{ .Values.versions.metallb }}
    hooks:
      - events: ["prepare"]
        showlogs: true
        command: "sh"
        args: ["-c", "sops -d metallb-memberlist-secret.enc.yaml | kubectl apply -n {{ .Values.namespaces.metallb }} -f -"]
      - events: ["cleanup"]
        showlogs: true
        command: "sh"
        args:
          - "-c"
          - |
            echo "
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: default-pool
              namespace: {{ .Values.namespaces.metallb }}
            spec:
              addresses:
              - {{ .Values.load_balancer.addresses.range }}
            ---
            apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: default
              namespace: {{ .Values.namespaces.metallb }}
            spec:
              ipAddressPools:
              - default-pool
            " | kubectl apply -n {{ .Values.namespaces.metallb }} -f -
