apiVersion: ENC[AES256_GCM,data:kSA=,iv:lQmUhe0nP7XxpqyTn/17GetvDD+BBPyNMXwn1f4jB+I=,tag:jdIZ/p816BHVWsfNycSWXw==,type:str]
kind: ENC[AES256_GCM,data:ILFOzbyJ,iv:b4LV6NsGQQ7b5QwzgPcIXMolckJVZnVrqF/1NT22QRU=,tag:9vL2B6dT1Rl7FZcn0+jMLQ==,type:str]
type: ENC[AES256_GCM,data:PcZG8KVZ,iv:u1qiy6rSqzEWX8Nsx1LM35GJqARy3kArIthkOtM6Sts=,tag:AGenyCCyYwGWZk0j3z/wvw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XOHJYl7BaYVQmfxMMQcgiYKz,iv:3sWuIUl7z/xxsvcoM0gqr07/8ztdf8p1yTnUeFUQuXs=,tag:9N0YG4ffdjRr+QWk2DIYig==,type:str]
    namespace: ENC[AES256_GCM,data:APW0qn5C+jAG1hhT+8k=,iv:BTP8uqb74et41iBdrN8Z8RxbnkoNjzdlzPzhiTQE04M=,tag:uqchxWs6V3Sd8SzTotezcA==,type:str]
data:
    secretkey: ENC[AES256_GCM,data:J90tXZaWIhaEdOAdz3UwEsqEfcl2JxjsipY1lQmXSvnsBj/gbvQIJNxCN3FC3zqGwJ9xcAV0WlfYAk8Jn2LLONNpMjg3Q521TqM9mCeIVLTPN9h6+zIRCwGE9IfsMZ7VAuPy14yGSdCyYTxmldfSqomCs1fOoJ2rF+f2BZWj8V5TjmdJYQr7ysUEk6441JdIU8gL1TxJB/lHAVe7/OiqtVvBJDH9Xqh1T1hHO9En5LjMerI7czZtAcb+/81yP+lIm6aP+JFTFINGkHsHgzjoaxxi3uqhFH2mO1bcgNIRUrOWLWWoeW3HFQ==,iv:x3qeZBdW/6iah9O794KWUVX2V7mieUC4rJr72Eje1+M=,tag:ppMNaRzstOeoFOrzaF7U2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQzRrQk1GcUlCb3MwSU4x
            bmRSNk5IeXhFeXJTNmtWUVIxRW9xbUhBR1dFCkxXSkQ0dUllN3pOa3Ztakp1eE9t
            TnlsdE1yZGZVb2tsM0hNOFVvU09hejQKLS0tIEhOak1icmRPOFk1WEZkcEdhOGZG
            T3lKQXJ1UCtIc0hVZnFuTzZwaVZsVXcKYyMgm8zOtN9IK6XWh/G8Bn/z1IHRE6hU
            ZnyjiCFfqWf/CfMUJNkiyWXkH0BhEQjqiNGso9rXXNVXy3y9S5kNRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-04T19:26:56Z"
    mac: ENC[AES256_GCM,data:B1O8v2rDrNcESp4vCBQbxOoxJ5RLaaFd2lIVy3mQ5bzk8DUIJy5yCkPD8qNmVdL5REzbl9mtMkKndkT98G5d4iZeNvEyPRqlbAN8Ownh7pa3kyYhJxxZWyT9ueGC9/9cfklh5RvoLA/miRttpzEZNLmDzaQkD56UI5cgqC0rqIs=,iv:xLOA+3PsX1EyPCDWT3KTgY7Ei6Evwaka3mf3JUNmuHY=,tag:tAqwCdHyJP8GHEeJ+cabLg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
