{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}"
  {{- if .Values.app.labels }}
  labels: {{ toYaml .Values.app.labels | nindent 4 }}
  {{- end }}
spec:
  ports:
  {{ range .Values.externalService.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
  {{- end }}

---

apiVersion: v1
kind: Endpoints
metadata:
  name: "{{ .Values.app.name }}"
  {{- if .Values.app.labels }}
  labels: {{ toYaml .Values.app.labels | nindent 4 }}
  {{- end }}
subsets:
  - addresses:
      - ip: "{{ .Values.externalService.externalName }}"
    ports:
    {{ range .Values.externalService.ports }}
      - name: {{ .name }}
        port: {{ .port }}
        protocol: {{ .protocol | default "TCP" }}
    {{- end }}
{{- end }}
