---
environments:
  homeserver:
    kubeContext: homeserver
    values:
      - environments/homeserver/values.yaml
      - environments/homeserver/common.yaml
      - environments/homeserver/versions.yaml
    secrets:
      - environments/homeserver/secrets.enc.yaml
