repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    namespace: "{{ .Values.namespaces.cert_manager }}"
    chart: jetstack/cert-manager
    version: v1.17.1
    values:
      - global:
          leaderElection:
            namespace: cert-manager
        installCRDs: true
        prometheus:
          enabled: false
