releases:
  - name: cert-manager
    namespace: "{{ .Values.namespaces.cert_manager }}"
    chart: jetstack/cert-manager
    version: {{ .Values.versions.cert_manager }}
    values:
      - global:
          leaderElection:
            namespace: cert-manager
        installCRDs: true
        prometheus:
          enabled: false
  - name: cert-manager-issuer
    namespace: "{{ .Values.namespaces.cert_manager }}"
    chart: ../../../charts/cert-manager-issuer
    version: {{ .Values.versions.cert_manager_issuer }}
    needs:
      - cert-manager
    values:
      - ingress:
          namespace: "{{ .Values.namespaces.ingress }}"
      - domain: "{{ .Values.secret.domain }}"
      - cloudflare:
          email: "{{ .Values.secret.cloudflare_email }}"
          api_token: "{{ .Values.secret.cloudflare_api_token }}"
