kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
  labels:
    app.kubernetes.io/managed-by: Helm
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: external-storage-pv
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: "{{ .Values.storages.local.capacity }}"
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "{{ .Values.storages.local.path }}"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "{{ .Values.nodeSelector.hostname }}"
