releases:
  - name: namespaces
    chart: kustomize
    kustomize:
      path: ./namespace
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["apply", "-k", "."]
  - name: storage
    needs:
      - namespaces
    chart: kustomize
    kustomize:
      path: ./storage
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["apply", "-k", "."]
  - name: cloudflared
    chart: kustomize
    kustomize:
      path: ./cloudflared
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["apply", "-k", "."]
