apiVersion: ENC[AES256_GCM,data:ROI=,iv:+tzvp+2vOpxFqC4p8iwZPpUqznoXudbYnXSFJ32RLCs=,tag:qYmyLXnk6pHoWsz+asdkLw==,type:str]
kind: ENC[AES256_GCM,data:smGdhk/z,iv:w1RsO1NJYX+Yu0ETioeijo7v3n4+4ZjjFe9yKu8wAkA=,tag:Zw1H6Dsx6uX98nBN1ZAMDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:cf6LSdotfGTOhU1hukw0cWzD4VYlpdsV9Yw=,iv:lGsMOQry3Z7qar962BvS/7M9Rm4IhfNBWtR5+lXoU4I=,tag:eC3Sqh5MD7W8UE+9DSvVJg==,type:str]
    namespace: ENC[AES256_GCM,data:X/lxig==,iv:RHKqn95gXpHZdMgQljRFeBRPpVARNaekH8alhZioBz0=,tag:5n5lwaxzgRfvuWyJyqCojg==,type:str]
type: ENC[AES256_GCM,data:cW6XQKPI,iv:lCLJiRqMgRSaaRybxzZxBBy4Hycbz/83wEWuortVG14=,tag:19k91iIS96G55mooHm/S9A==,type:str]
data:
    .htpasswd: ENC[AES256_GCM,data:fQ8FfQ4GY3pjWk/DtGK0bidGtZa0AKXzejdWffcvuho8nPyTP976YTnZ76hLZf59WQMn7rXYSBxPdp+J,iv:w5hhUCHWYqnkcTTSQDnnS+DV90Uh6tyvFiwvjaZwflE=,tag:++ZsSdpwzxuaEOR6y4h0ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYzJONEFwOVREcWZFdHhD
            SzF1NzN4cVZ0bXZLbDVyUWhveUovYktha25ZCnhFaG43S3B4dGJyNFZkZFo0QkF1
            d3VFRkNJY2Z2bk5GVkdkZ3RNbEkvK2cKLS0tIFhZV1F1WE9JbFhKc2UveTQzUVo3
            bTB2SWcrcHlvVU1QdHR3ZS9henhVblEKQRafS4NiBrXr/62m1WM1K1xD6rhv5qFh
            dKzLhtm+LZBz/tSFwmZGRRRj27sfZEJHHB6Kuvkxp+TI0zJ64MpVRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16yrhmz8fytj7j9ns80zl40zjcdfd3pdxh48ld7ys7veea774udtqfn9jyx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5am1rNkJmZ2hXY01Jb3Va
            NGZZQmowbDcxWlQweklhbitGUlBlQ25TSHdNCkw2ODQ2VmFDVmI5OERwSnVwaHYr
            S0x6c0xYYUp5ZFNWK3kybmMvQi96NjAKLS0tIEx5SkFhdWZBRThqcVhYc2NRSk5r
            dXplWVRmWXlLRVFzbUU0QkR6ME9FYXMKedFVBfgVRrYZOBmFZHE7tA/3V1cC5XMq
            08wHKvxoGVOsbiyQJ5QZsAHJJ+8ngX3TvWeDq9WXYxkKL8N8AQAggQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jx9qu5p0ycvymrl2gykd9z3w8x8n67jxnatxs49j7qzspjr6asqqf8u35h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQ3o1T2t0YW5vaHI0N240
            U2UxU1grMnc4Y0p6NFhSTTRITVdsQlFtZHpzCkJQekVkOTdJVWI1Yi8xZVhGbGlN
            MHRnQjhzYlZxZHc4Z2FFYkloUmRyZGsKLS0tIE5nSGUybXBDaGlmNlNIUEtGSHMx
            aWlIMUhMYnA3TXFMaEJOWnN0OVVRSm8KcML15oZeuIG5ZdvGmQXJ4E2eiM54FtrD
            FZPW7ENYbPLZuRPnTG+JYQKhdr2qcLWypQlGvw/Z9MHZnBV430PMOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1myzhwq67gu5zrfk8fvs0p7mh5fk67d20ltwqf9325ya83lm06ytsyax3j2
    lastmodified: "2026-05-17T15:34:01Z"
    mac: ENC[AES256_GCM,data:xa74ffBVJLkW7pHzFNZdLc+MxUhRfuFA/RtO4wqE9JVJFBCmSN5m4birVL545lxX2caHZZFYjBW9/aEdFlQ/O3Ik6s2acORT8ocvJl22ERZ9d7lVSlg2L39QBsOn23dFfHxKsoYI3t5fziT6FEl5M4KO8TPlJQ03tHN8kiGNDF0=,iv:vbwxfzMbcnTE5A/dWzgkMrqvYgOpmf4iYTjeiyXpZxo=,tag:Uy9QJVDnTBh/cCTDsQcVXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
